"""Week 3 — Data Preparation and Pipelines  ·  slide spec (bilingual).

Aligned with the official course documents (52015CC3BV):
CU(3) · Module 1 (Week 1-4) · KT5/KT6 · Lab 2 (Dataset / DataLoader / Data Card).
"""

SPEC = {
    "week": 3,
    "slides": [
        # ---------------------------------------------------------- cover ----
        {"type": "cover",
         "kicker": {"zh": "52015CC3BV · 本科 · 来华项目", "en": "52015CC3BV · UNDERGRADUATE · INTERNATIONAL"},
         "title": {"zh": "数据准备与管道构建", "en": "Data Preparation and Pipelines"},
         "title_sub": {"zh": "Data Preparation and Pipelines",
                       "en": "Raw data -> cleaning -> splits -> Dataset -> DataLoader -> batches"},
         "subtitle": {"zh": "Week 3 · 数据获取与清洗 · 训练/验证/测试划分 · 数据泄漏 · Dataset 与 DataLoader · 增强与类别不平衡",
                      "en": "Week 3 · Acquisition & cleaning · train/val/test splits · data leakage · Dataset & DataLoader · augmentation & class imbalance"},
         "chips": [
             ({"zh": "模块一 · W1–4", "en": "Module 1 · W1-4"}, 1.0),
             ({"zh": "180 min · 授课 + 实验 + 小测", "en": "180 min · Lecture + Lab + Quiz"}, 1.5),
             ({"zh": "PyTorch · Dataset · DataLoader · torchvision", "en": "PyTorch · Dataset · DataLoader · torchvision"}, 1.8),
             ({"zh": "留学生班 · 英文授课", "en": "International Students"}, 1.0),
         ]},

        # ------------------------------------------------------- contents ----
        {"type": "contents",
         "right": {"zh": "模块一 · Week 3", "en": "Module 1 · Week 3"},
         "count": {"zh": "5 部分", "en": "5 Parts"},
         "count_label": {"zh": "本周结构", "en": "Part"},
         "tagline": {"zh": "先把「数据决定上限」说清楚，\n再把六步管道变成可运行的代码。\nData sets the ceiling; the pipeline gets you there.",
                     "en": "First accept that data sets the ceiling, then turn the six-step pipeline into runnable code."},
         "timing": {"zh": "理论约 90 min · Lab 80 min · 小测与小结 10 min",
                    "en": "Theory ~90 min · Lab 80 min · Quiz & Summary 10 min"},
         "parts": [
             {"title": {"zh": "数据决定上限", "en": "Data Sets the Ceiling"},
              "title_en": "Data Sets the Ceiling",
              "desc": {"zh": "总纲 · 六步管道 · 以数据为中心",
                       "en": "Thesis · the six-step pipeline · data-centric thinking"}},
             {"title": {"zh": "数据获取与清洗", "en": "Acquisition & Cleaning"},
              "title_en": "Acquisition & Cleaning",
              "desc": {"zh": "缺失/异常/重复/标签噪声 · AI 辅助探索与核对",
                       "en": "Missing, outliers, duplicates, label noise · AI-assisted exploration"}},
             {"title": {"zh": "划分与数据泄漏", "en": "Splitting & Data Leakage"},
              "title_en": "Splitting & Leakage",
              "desc": {"zh": "70/15/15 · 随机/分层/时间/分组 · 泄漏识别与规避",
                       "en": "70/15/15 · random/stratified/time/group · detecting leakage"}},
             {"title": {"zh": "Dataset 与 DataLoader", "en": "Dataset & DataLoader"},
              "title_en": "Dataset & DataLoader",
              "desc": {"zh": "两个契约 · 批处理与打乱 · 数据增强 · 类别不平衡",
                       "en": "Two contracts · batching & shuffling · augmentation · imbalance"}},
             {"title": {"zh": "Lab · 实验 2 数据管道与数据卡片", "en": "Lab · Pipeline & Data Card"},
              "title_en": "Hands-On Lab",
              "desc": {"zh": "探索 → 划分 → Dataset/DataLoader → 增强 → 数据卡片",
                       "en": "Explore -> split -> Dataset/DataLoader -> augment -> Data Card"}},
         ]},

        # ------------------------------------------------- Part 01 (p3-6) ---
        {"type": "section", "num": "01",
         "title": {"zh": "数据决定上限", "en": "Data Sets the Ceiling"},
         "title_en": {"zh": "Data Sets the Ceiling", "en": "Data Sets the Ceiling"},
         "lead": {"zh": "模型再强，也无法凭空造出数据里没有的信息。\n这一部分先立下本周的总纲：数据决定上限，模型只是逼近上限。",
                  "en": "However strong a model is, it cannot invent information the data does not contain.\nThis part sets the thesis of the week: data sets the ceiling, models only approach it."},
         "pillars": [
             {"title": {"zh": "上限", "en": "The Ceiling"},
              "sub": {"zh": "信息量与标注质量决定误差下界", "en": "Information and label quality bound the error"}},
             {"title": {"zh": "逼近", "en": "Approach It"},
              "sub": {"zh": "换模型只是逼近得更紧", "en": "A better model only approaches it more closely"}},
             {"title": {"zh": "可信", "en": "Trustworthy"},
              "sub": {"zh": "划分与泄漏决定数字真假", "en": "Splits and leakage decide if the number is real"}},
         ]},

        {"type": "cards", "cols": 3, "h": 5.8, "top": 3.6,
         "title": {"zh": "一句话总纲：数据决定上限，模型逼近上限", "en": "One Thesis: Data Sets the Ceiling, Models Approach It"},
         "right": {"zh": "模块一 · Week 3", "en": "Module 1 · Week 3"},
         "subtitle": {"zh": "工程经验：项目卡住时，先回头看数据——多数情况下瓶颈在数据，而不在模型结构。",
                      "en": "Field experience: when a project stalls, look back at the data first - most of the time the bottleneck is data, not architecture."},
         "cards": [
             {"title": {"zh": "① 数据决定上限", "en": "1 · Data Sets the Ceiling"},
              "title_en": "the ceiling",
              "body": [{"zh": "数据覆盖了多少情况、标注有多准，决定了误差能低到哪里", "en": "Coverage and label quality bound how low the error can go"},
                       {"zh": "上限低，换任何模型都救不回来", "en": "A low ceiling cannot be rescued by any model"}]},
             {"title": {"zh": "② 模型只是逼近", "en": "2 · Models Only Approach"},
              "title_en": "the approach",
              "body": [{"zh": "换模型、调超参，是在逼近同一个上限", "en": "Swapping models and tuning hyper-parameters approaches the same ceiling"},
                       {"zh": "所以：先修数据，再换模型", "en": "So: fix the data first, then change the model"}]},
             {"title": {"zh": "③ 评估决定你是否知道", "en": "3 · Evaluation Tells You Whether You Know"},
              "title_en": "the measurement",
              "body": [{"zh": "划分错了、泄漏了，你看到的指标就是假的", "en": "A wrong split or a leak makes the number you see fake"},
                       {"zh": "本周后两个目标都服务于「看见真实水平」", "en": "The rest of the week serves one goal: seeing the true level"}]},
         ]},

        {"type": "flow", "y": 6.3, "h": 4.7,
         "title": {"zh": "数据管道六步：从原始数据到批次", "en": "The Six-Step Data Pipeline: Raw Data to Batches"},
         "right": {"zh": "模块一 · Week 3", "en": "Module 1 · Week 3"},
         "steps": [
             {"title": {"zh": "原始数据", "en": "Raw Data"},
              "title_en": "Raw",
              "desc": {"zh": "多来源、多格式、\n尚未定义好坏", "en": "Many sources and formats,\nnot yet good or bad"}},
             {"title": {"zh": "清洗", "en": "Clean"},
              "title_en": "Clean",
              "desc": {"zh": "缺失、异常、重复、\n标签噪声", "en": "Missing values, outliers,\nduplicates, label noise"}},
             {"title": {"zh": "划分", "en": "Split"},
              "title_en": "Split",
              "desc": {"zh": "train/val/test，\n固定种子，策略有据", "en": "train/val/test, fixed seed,\nstrategy justified"}},
             {"title": {"zh": "Dataset", "en": "Dataset"},
              "title_en": "Dataset",
              "desc": {"zh": "__len__ 与 __getitem__，\n样本级访问", "en": "__len__ and __getitem__,\nsample-level access"}},
             {"title": {"zh": "DataLoader", "en": "DataLoader"},
              "title_en": "Loader",
              "desc": {"zh": "批处理、打乱、\n并行加载", "en": "Batching, shuffling,\nparallel loading"}},
             {"title": {"zh": "批次", "en": "Batches"},
              "title_en": "Batches",
              "desc": {"zh": "训练循环真正\n看到的东西", "en": "What the training loop\nactually sees"}},
         ],
         "note": {"zh": "顺序不可交换：划分必须发生在任何「会学习」的步骤之前——标准化、填补、特征选择、增强都算。这是本周最重要的一句话。",
                  "en": "The order is not negotiable: splitting must happen before any step that learns - scaling, imputation, feature selection and augmentation all count. This is the single most important sentence of the week."}},

        {"type": "compare", "top": 3.25, "h": 9.6,
         "title": {"zh": "以模型为中心 vs 以数据为中心", "en": "Model-Centric vs Data-Centric"},
         "right": {"zh": "模块一 · Week 3", "en": "Module 1 · Week 3"},
         "columns": [
             {"title": {"zh": "以模型为中心", "en": "Model-Centric"}, "accent": "6B7280",
              "bg": "F5F7FA",
              "items": [
                  {"zh": "数据随手处理，直接喂给模型", "en": "Data is processed ad hoc, then fed to a model"},
                  {"zh": "主要手段是换模型、调超参", "en": "The main moves are swapping models and tuning"},
                  {"zh": "提升越来越小，且无法解释", "en": "Gains shrink and cannot be explained"},
                  {"zh": "指标无法复现，也说不清为什么", "en": "Metrics are not reproducible and the cause is unknown"}]},
             {"title": {"zh": "以数据为中心", "en": "Data-Centric"}, "accent": "1E4FA8",
              "bg": "F0F5FC",
              "items": [
                  {"zh": "先诊断质量，明确来源与合规", "en": "Diagnose quality first; settle provenance and compliance"},
                  {"zh": "划分有依据、有种子、可复现", "en": "Splits are justified, seeded and reproducible"},
                  {"zh": "同一个模型，指标更稳更高", "en": "The same model gives steadier, higher metrics"},
                  {"zh": "错误能归因到具体的数据问题", "en": "Errors can be traced to a concrete data problem"}]},
         ],
         "note": {"zh": "两条路线不是对立的：先做数据，再谈模型。顺序反过来，你连「模型到底好不好」都判断不了。",
                  "en": "The two are not rivals - do the data first, then the model. In the opposite order you cannot even judge whether the model is good."}},

        # ------------------------------------------------- Part 02 (p7-11) --
        {"type": "section", "num": "02",
         "title": {"zh": "数据获取与清洗", "en": "Data Acquisition & Cleaning"},
         "title_en": {"zh": "Acquisition & Cleaning", "en": "Acquisition & Cleaning"},
         "lead": {"zh": "清洗不是「把数据弄得好看」，而是把已知的问题变成可核查的记录。\n这一部分讲四类常见问题，以及如何用 AI 生成探索代码又不被它带偏。",
                  "en": "Cleaning is not making data look nice - it is turning known problems into an auditable record.\nThis part covers four common problems, and how to use AI for exploration without being misled."},
         "pillars": [
             {"title": {"zh": "来源合规", "en": "Provenance"},
              "sub": {"zh": "授权与隐私是底线", "en": "Licence and privacy come first"}},
             {"title": {"zh": "质量诊断", "en": "Diagnosis"},
              "sub": {"zh": "先量化，再决定动作", "en": "Quantify before you act"}},
             {"title": {"zh": "清洗留痕", "en": "Traces"},
              "sub": {"zh": "处理前后要能对照", "en": "Before/after must be comparable"}},
         ]},

        {"type": "cards", "cols": 2, "h": 5.0, "top": 3.6,
         "title": {"zh": "四类常见数据问题", "en": "Four Common Data Problems"},
         "right": {"zh": "模块一 · Week 3", "en": "Module 1 · Week 3"},
         "subtitle": {"zh": "发现问题只是第一步：每个处理动作都要写清判据，并留下处理前后的对照。",
                      "en": "Spotting a problem is only step one: every action needs an explicit criterion and a before/after comparison."},
         "cards": [
             {"title": {"zh": "缺失值", "en": "Missing Values"}, "title_en": "missing",
              "body": [{"zh": "先看缺失率排行，再看缺失是否与标签相关", "en": "Rank the missing rates, then check whether missingness relates to the label"},
                       {"zh": "填补统计量（中位数/众数）只能来自训练集", "en": "Imputation statistics (median/mode) may come from the training set only"}]},
             {"title": {"zh": "异常值", "en": "Outliers"}, "title_en": "outliers",
              "body": [{"zh": "用 1/99 分位或 IQR 判定，而不是「看起来奇怪」", "en": "Judge by the 1/99 percentiles or IQR, not by \"looks weird\""},
                       {"zh": "可以截断、变换，也可以保留并加标记", "en": "You may clip or transform them, or keep them with a flag"}]},
             {"title": {"zh": "重复与不一致", "en": "Duplicates & Inconsistency"}, "title_en": "duplicates",
              "body": [{"zh": "主键去重、单位统一、类别编码统一", "en": "De-duplicate on keys; unify units and category codes"},
                       {"zh": "重复样本跨集合 = 直接的数据泄漏", "en": "A duplicate across splits is direct data leakage"}]},
             {"title": {"zh": "标签噪声", "en": "Label Noise"}, "title_en": "labels",
              "body": [{"zh": "交叉核对、标注一致性检查、抽样人工复核", "en": "Cross-check, measure annotator agreement, spot-check by hand"},
                       {"zh": "噪声比例高时，再多的数据也救不回来", "en": "With a high noise rate, more data will not help"}]},
         ]},

        {"type": "table", "top": 3.2, "h": 6.5,
         "title": {"zh": "清洗动作与判据对照表", "en": "Cleaning Actions and Their Criteria"},
         "right": {"zh": "模块一 · Week 3", "en": "Module 1 · Week 3"},
         "cols": [{"zh": "问题", "en": "Problem"},
                  {"zh": "怎么发现", "en": "How You Detect It"},
                  {"zh": "处理动作", "en": "Action"},
                  {"zh": "风险与注意事项", "en": "Risk / Caveat"}],
         "widths": [4.2, 6.2, 8.4, 10.6],
         "bold_first": True,
         "rows": [
             [{"zh": "缺失值", "en": "Missing"},
              {"zh": "df.isna().mean() 排序；缺失与标签的交叉统计", "en": "df.isna().mean() ranked; missingness vs label"},
              {"zh": "删除、中位数/众数填补、模型填补", "en": "Drop, median/mode imputation, model-based imputation"},
              {"zh": "填补统计量若用了全量数据，就是泄漏", "en": "Imputing with full-data statistics is leakage"}],
             [{"zh": "异常值", "en": "Outliers"},
              {"zh": "分位数、箱线图、IQR 规则", "en": "Percentiles, box plots, the IQR rule"},
              {"zh": "截断、对数变换，或保留并加标记", "en": "Clip, log-transform, or keep them with a flag"},
              {"zh": "异常值可能正是你要预测的目标，别默认删掉", "en": "The outlier may be exactly what you must predict - do not delete by default"}],
             [{"zh": "重复与不一致", "en": "Duplicates"},
              {"zh": "主键计数、单位/编码取值集合检查", "en": "Key counts; checks on unit and code value sets"},
              {"zh": "去重、统一单位与类别编码", "en": "De-duplicate; unify units and category codes"},
              {"zh": "同一实体跨训练与测试 = 泄漏", "en": "One entity across train and test means leakage"}],
             [{"zh": "标签噪声", "en": "Label Noise"},
              {"zh": "一致性告警、模型高置信错例、人工抽样", "en": "Agreement checks, high-confidence errors, manual sampling"},
              {"zh": "重标、剔除，或使用鲁棒损失", "en": "Re-label, remove, or use a robust loss"},
              {"zh": "先量化噪声比例，再决定是否清洗", "en": "Quantify the noise rate before deciding to clean"}],
         ],
         "note": {"zh": "表格里最后列才是重点：动作谁都会做，知道「这个动作会把什么搞坏」才是工程能力。",
                  "en": "The last column is the real lesson: anyone can perform the action - knowing what it breaks is engineering."}},

        {"type": "code", "top": 3.5, "h": 11.3,
         "title": {"zh": "AI 辅助数据探索：生成代码，自己核对结论", "en": "AI-Assisted Exploration: Generate the Code, Verify the Claims"},
         "right": {"zh": "模块一 · Week 3", "en": "Module 1 · Week 3"},
         "blocks": [
             {"title": {"zh": "① 让 AI 生成探索代码", "en": "1 · Let AI draft the exploration"},
              "size": 10.5,
              "code": {"zh": [
                  "import pandas as pd",
                  "",
                  "df = pd.read_csv(\"data/raw/defects.csv\")",
                  "",
                  "print(\"shape:\", df.shape)",
                  "print(df[\"label\"].value_counts())",
                  "print(df[\"label\"].value_counts(",
                  "    normalize=True).round(3))",
                  "",
                  "print(df.isna().mean().sort_values(",
                  "    ascending=False).head(5))",
                  "",
                  "print(df.describe().T[[\"mean\", \"std\",",
                  "                       \"min\", \"max\"]].round(2))",
                  "",
                  "# AI 常在这里给出「看似合理」的结论：",
                  "# 「类别分布均衡，可以直接训练。」",
              ],
              "en": [
                  "import pandas as pd",
                  "",
                  "df = pd.read_csv(\"data/raw/defects.csv\")",
                  "",
                  "print(\"shape:\", df.shape)",
                  "print(df[\"label\"].value_counts())",
                  "print(df[\"label\"].value_counts(",
                  "    normalize=True).round(3))",
                  "",
                  "print(df.isna().mean().sort_values(",
                  "    ascending=False).head(5))",
                  "",
                  "print(df.describe().T[[\"mean\", \"std\",",
                  "                       \"min\", \"max\"]].round(2))",
                  "",
                  "# This is where AI makes plausible claims:",
                  "# \"classes are balanced, you can train as is.\"",
              ]}},
             {"title": {"zh": "② 用断言与图复核每一条结论", "en": "2 · Verify each claim with asserts and plots"},
              "size": 10.5,
              "code": {"zh": [
                  "# AI：「各类别分布均衡，可直接训练。」",
                  "share = df[\"label\"].value_counts(normalize=True)",
                  "assert share.min() > 0.20, \"最小类别占比过低\"",
                  "",
                  "# AI：「没有缺失值。」",
                  "assert df.isna().sum().sum() == 0, \"有缺失值\"",
                  "",
                  "# AI：「特征与标签强相关，模型会很准。」",
                  "# -> 画图 + 独立复算相关系数，不许只看文字",
                  "df.groupby(\"label\")[\"size\"].mean().plot(",
                  "    kind=\"bar\")",
                  "",
                  "# 每条结论都要能被一行断言或一张图复现；",
                  "# 校验失败 -> 记入 AI_USE.md，写明修正结论。",
              ],
              "en": [
                  "# AI: \"classes are balanced, train as is.\"",
                  "share = df[\"label\"].value_counts(normalize=True)",
                  "assert share.min() > 0.20, \"minority too low\"",
                  "",
                  "# AI: \"there are no missing values.\"",
                  "assert df.isna().sum().sum() == 0, \"missing\"",
                  "",
                  "# AI: \"features correlate strongly with the label.\"",
                  "# -> plot it and recompute the correlation yourself",
                  "df.groupby(\"label\")[\"size\"].mean().plot(",
                  "    kind=\"bar\")",
                  "",
                  "# Every claim must be reproducible by one assert or",
                  "# one plot; log failures in AI_USE.md with the fix.",
              ]}},
         ],
         "note": {"zh": "关键要求：AI 给的统计结论与你的可视化方向不一致时，以你自己跑出来的为准，并把这次分歧写进协同记录。",
                  "en": "The key rule: when an AI statistic disagrees with your own plot, trust what you ran - and write the disagreement into your AI-use log."}},

        {"type": "cards", "cols": 3, "h": 6.4, "top": 3.65,
         "title": {"zh": "AI 赋能：结论必须被核对", "en": "AI Empowerment: Claims Must Be Checked"},
         "right": {"zh": "模块一 · Week 3", "en": "Module 1 · Week 3"},
         "subtitle": {"zh": "AI 可以帮你写代码，但不能替你判断：数字与可视化必须互相印证。",
                      "en": "AI can write the code but cannot make the judgement: numbers and plots must confirm each other."},
         "cards": [
             {"title": {"zh": "AI 常犯的「看似合理」错误", "en": "Plausible-but-Wrong AI Claims"},
              "title_en": "the risk", "bg": "FEF2F2", "accent": "B91C1C",
              "body": [{"zh": "不平衡数据下用 accuracy 下结论", "en": "Concluding from accuracy on imbalanced data"},
                       {"zh": "把「缺失率为 0」当成「数据干净」", "en": "Treating a zero missing rate as clean data"},
                       {"zh": "编造并不存在的列名与文件路径", "en": "Inventing column names and file paths"},
                       {"zh": "把样本数说成特征数", "en": "Reading the sample count as the feature count"}]},
             {"title": {"zh": "你要做的核对动作", "en": "What You Must Do"},
              "title_en": "the check", "bg": "ECFDF5", "accent": "059669",
              "body": [{"zh": "每条统计结论配一行断言或一张图", "en": "Pair every claim with one assert or one plot"},
                       {"zh": "用 pandas 独立复算关键数字", "en": "Recompute the key numbers independently in pandas"},
                       {"zh": "结论与可视化不一致时，以自己跑的为准", "en": "When they disagree, trust what you ran"},
                       {"zh": "不平衡时改用 per-class 指标再下结论", "en": "On imbalanced data, switch to per-class metrics"}]},
             {"title": {"zh": "必须留下的痕迹", "en": "The Trace You Must Leave"},
              "title_en": "the trace",
              "body": [{"zh": "AI_USE.md：提问、AI 原话、你发现的问题", "en": "AI_USE.md: the prompt, the AI answer, the problem you found"},
                       {"zh": "写明你改了哪一行、为什么改", "en": "State which line you changed and why"},
                       {"zh": "计入形成性考核的评价项", "en": "Counts toward the formative assessment items"}]},
         ]},

        # ------------------------------------------------- Part 03 (p12-16) -
        {"type": "section", "num": "03",
         "title": {"zh": "划分与数据泄漏", "en": "Splitting & Data Leakage"},
         "title_en": {"zh": "Splitting & Data Leakage", "en": "Splitting & Data Leakage"},
         "lead": {"zh": "划分是本周最重要的一步：它决定了你后面看到的所有数字是否可信。\n这一部分先讲比例与策略，再讲泄漏的四种常见形态。",
                  "en": "Splitting is the most important step of the week: it decides whether every number you see later is trustworthy.\nThis part covers ratios and strategies first, then the four common shapes of leakage."},
         "pillars": [
             {"title": {"zh": "比例", "en": "Ratios"},
              "sub": {"zh": "70/15/15 与它的变形", "en": "70/15/15 and its variants"}},
             {"title": {"zh": "策略", "en": "Strategy"},
              "sub": {"zh": "随机 · 分层 · 时间 · 分组", "en": "Random · stratified · time · group"}},
             {"title": {"zh": "泄漏", "en": "Leakage"},
              "sub": {"zh": "识别与规避", "en": "Detect and avoid"}},
         ]},

        {"type": "splitbar", "y": 5.6, "h": 3.1,
         "title": {"zh": "训练 / 验证 / 测试：各自只做一件事", "en": "Train / Validation / Test: One Job Each"},
         "right": {"zh": "模块一 · Week 3", "en": "Module 1 · Week 3"},
         "segments": [
             {"value": 70, "color": "1E4FA8", "pct": "70%",
              "title": {"zh": "训练集", "en": "Train"},
              "desc": {"zh": "拟合参数与统计量。标准化、填补、特征选择、数据增强都只在这里做。",
                       "en": "Fits parameters and statistics. Scaling, imputation, feature selection and augmentation happen here only."}},
             {"value": 15, "color": "3D7BD9", "pct": "15%",
              "title": {"zh": "验证集", "en": "Validation"},
              "desc": {"zh": "用来选模型与调超参。它会被反复看，所以不能当最终成绩。",
                       "en": "Used to choose models and tune hyper-parameters. It is looked at repeatedly, so it is not the final score."}},
             {"value": 15, "color": "059669", "pct": "15%",
              "title": {"zh": "测试集", "en": "Test"},
              "desc": {"zh": "只在最后报告一次。一旦参与调参，它就已经变成了验证集。",
                       "en": "Reported once, at the very end. Once it informs tuning, it has become a validation set."}},
         ],
         "note": {"zh": "两条常见变形：数据量小（不足 1 万条）时用 5 折交叉验证代替固定验证集；类别不平衡时优先分层划分，保证每个集合的类别比例接近总体。",
                  "en": "Two common variants: with small data (under 10k) use 5-fold cross-validation instead of a fixed validation set; with class imbalance prefer stratified splitting so each split keeps the overall class ratio."}},

        {"type": "cards", "cols": 2, "h": 5.0, "top": 3.6,
         "title": {"zh": "四种划分策略：按数据性质选", "en": "Four Splitting Strategies: Choose by Data Nature"},
         "right": {"zh": "模块一 · Week 3", "en": "Module 1 · Week 3"},
         "subtitle": {"zh": "没有万能划分：先问「样本是否独立、是否有时序、是否同一实体」，再选策略。",
                      "en": "No universal split: ask whether samples are independent, whether there is a time order, whether one entity repeats - then choose."},
         "cards": [
             {"title": {"zh": "随机划分", "en": "Random Split"}, "title_en": "i.i.d. data",
              "body": [{"zh": "适用：样本相互独立、无时序、无重复实体", "en": "Use when samples are independent, with no time order and no repeated entity"},
                       {"zh": "用 torch.Generator 固定种子，保证可复现", "en": "Fix the seed with torch.Generator so the split is reproducible"}]},
             {"title": {"zh": "分层划分", "en": "Stratified Split"}, "title_en": "imbalanced data",
              "body": [{"zh": "适用：类别不平衡，尤其少数类样本很少", "en": "Use when classes are imbalanced, especially with few minority samples"},
                       {"zh": "保证每个集合的类别比例接近总体", "en": "Keeps each split's class ratio close to the overall ratio"}]},
             {"title": {"zh": "时间划分", "en": "Time-Based Split"}, "title_en": "time series",
              "body": [{"zh": "适用：时序、流式、有明显先后关系的数据", "en": "Use for time series, streams, or data with a real order"},
                       {"zh": "用过去训练、用未来测试；随机打乱会「看到未来」", "en": "Train on the past, test on the future; shuffling lets the model see the future"}]},
             {"title": {"zh": "分组划分", "en": "Group Split"}, "title_en": "repeated entities",
              "body": [{"zh": "适用：同一用户/设备/病人有多条记录", "en": "Use when one user, device or patient has many records"},
                       {"zh": "同一实体只能出现在一个集合里，否则就是泄漏", "en": "One entity may live in exactly one split, otherwise it leaks"}]},
         ]},

        {"type": "code", "top": 3.45, "h": 10.9,
         "title": {"zh": "数据泄漏：一个错误示范与一个正确示范", "en": "Data Leakage: One Wrong Way, One Right Way"},
         "right": {"zh": "模块一 · Week 3", "en": "Module 1 · Week 3"},
         "blocks": [
             {"title": {"zh": "错误：测试集被当成训练集", "en": "Wrong: test set used as training data"},
              "size": 10,
              "code": {"zh": [
                  "import torch.nn as nn",
                  "from torch.utils.data import DataLoader, random_split",
                  "from torch.utils.data import ConcatDataset",
                  "",
                  "# 划分之后又把测试集并回训练集",
                  "train_ds, test_ds = random_split(ds, [0.8, 0.2])",
                  "leaked = ConcatDataset([train_ds, test_ds])  # 泄漏",
                  "",
                  "loader = DataLoader(leaked, batch_size=32,",
                  "                    shuffle=True)",
                  "model = nn.Linear(n_feat, n_class)",
                  "opt = torch.optim.Adam(model.parameters(), lr=1e-3)",
                  "for _ in range(20):",
                  "    for xb, yb in loader:",
                  "        loss = nn.functional.cross_entropy(",
                  "            model(xb), yb)",
                  "        opt.zero_grad(); loss.backward(); opt.step()",
                  "",
                  "# test_ds 已被训练见过，等于自己批改自己",
                  "print(eval_acc(model, test_ds))  # 0.99 虚高",
              ],
              "en": [
                  "import torch.nn as nn",
                  "from torch.utils.data import DataLoader, random_split",
                  "from torch.utils.data import ConcatDataset",
                  "",
                  "# after splitting, the test set is merged back in",
                  "train_ds, test_ds = random_split(ds, [0.8, 0.2])",
                  "leaked = ConcatDataset([train_ds, test_ds])  # leak",
                  "",
                  "loader = DataLoader(leaked, batch_size=32,",
                  "                    shuffle=True)",
                  "model = nn.Linear(n_feat, n_class)",
                  "opt = torch.optim.Adam(model.parameters(), lr=1e-3)",
                  "for _ in range(20):",
                  "    for xb, yb in loader:",
                  "        loss = nn.functional.cross_entropy(",
                  "            model(xb), yb)",
                  "        opt.zero_grad(); loss.backward(); opt.step()",
                  "",
                  "# test_ds was seen in training: marking your own exam",
                  "print(eval_acc(model, test_ds))  # 0.99 fake",
              ]}},
             {"title": {"zh": "正确：先划分，只在训练集上拟合", "en": "Right: split first, fit on train only"},
              "size": 10,
              "code": {"zh": [
                  "import torch",
                  "from torch.utils.data import DataLoader, random_split",
                  "",
                  "# 先划分，并且种子固定",
                  "g = torch.Generator().manual_seed(42)",
                  "train_ds, val_ds, test_ds = random_split(",
                  "    ds, [0.70, 0.15, 0.15], generator=g)",
                  "",
                  "# 标准化统计量只来自训练集",
                  "tr = X[train_ds.indices]",
                  "mu, sd = tr.mean(0), tr.std(0).clamp_min(1e-8)",
                  "X_norm = (X - mu) / sd",
                  "",
                  "train_loader = DataLoader(train_ds, batch_size=32,",
                  "                          shuffle=True)",
                  "val_loader   = DataLoader(val_ds, batch_size=64)",
                  "test_loader  = DataLoader(test_ds, batch_size=64)",
                  "# 测试集只报告一次，绝不参与调参",
              ],
              "en": [
                  "import torch",
                  "from torch.utils.data import DataLoader, random_split",
                  "",
                  "# split first, with a fixed seed",
                  "g = torch.Generator().manual_seed(42)",
                  "train_ds, val_ds, test_ds = random_split(",
                  "    ds, [0.70, 0.15, 0.15], generator=g)",
                  "",
                  "# scaling statistics come from the training set only",
                  "tr = X[train_ds.indices]",
                  "mu, sd = tr.mean(0), tr.std(0).clamp_min(1e-8)",
                  "X_norm = (X - mu) / sd",
                  "",
                  "train_loader = DataLoader(train_ds, batch_size=32,",
                  "                          shuffle=True)",
                  "val_loader   = DataLoader(val_ds, batch_size=64)",
                  "test_loader  = DataLoader(test_ds, batch_size=64)",
                  "# test set is reported once, never used for tuning",
              ]}},
         ],
         "note": {"zh": "真实翻车案例：某团队把含测试样本的数据喂进训练，线下准确率 0.99，上线后跌到 0.78——虚高的部分不是模型学到了规律，而是它见过了考题。判断泄漏只需一句话：这个信息在推理时拿得到吗？拿不到，就不该出现在训练里。",
                  "en": "A real incident: a team trained on data that included the test samples, reported 0.99 offline and dropped to 0.78 in production. The inflation was not learning - the model had seen the exam. One test for leakage: could you obtain this information at inference time? If not, it must not appear in training."}},

        {"type": "checklist", "top": 3.55, "h": 2.15,
         "title": {"zh": "数据泄漏自查清单", "en": "Data-Leakage Self-Check"},
         "right": {"zh": "模块一 · Week 3", "en": "Module 1 · Week 3"},
         "items": [
             {"badge": {"zh": "必查", "en": "CHECK"}, "accent": "1E4FA8",
              "title": {"zh": "划分发生在所有「会学习」的步骤之前", "en": "Splitting precedes every step that learns"},
              "desc": {"zh": "标准化、填补、特征选择、增强都要在划分之后，且只作用于训练集。",
                       "en": "Scaling, imputation, feature selection and augmentation come after the split and touch the training set only."}},
             {"badge": {"zh": "必查", "en": "CHECK"}, "accent": "1E4FA8",
              "title": {"zh": "统计量只来自训练集", "en": "Statistics come from the training set only"},
              "desc": {"zh": "均值、方差、分位数、词表都只能由 train 计算，再应用到 val 与 test。",
                       "en": "Means, variances, quantiles and vocabularies are computed on train, then applied to val and test."}},
             {"badge": {"zh": "必查", "en": "CHECK"}, "accent": "1E4FA8",
              "title": {"zh": "同一实体不跨集合", "en": "One entity never spans splits"},
              "desc": {"zh": "同一用户、设备、病人、文档的多条记录必须待在同一个集合里（分组划分）。",
                       "en": "All records of one user, device, patient or document stay in one split (group split)."}},
             {"badge": {"zh": "必查", "en": "CHECK"}, "accent": "1E4FA8",
              "title": {"zh": "时序数据使用时间划分", "en": "Time-series data uses a time-based split"},
              "desc": {"zh": "用过去预测未来；随机打乱会让模型在训练时就「看到未来」。",
                       "en": "Predict the future from the past; shuffling lets the model see the future during training."}},
             {"badge": {"zh": "必查", "en": "CHECK"}, "accent": "1E4FA8",
              "title": {"zh": "测试集没有被反复使用", "en": "The test set is not reused"},
              "desc": {"zh": "一旦用测试集挑模型或调参，它就已经变成验证集，成绩不再可信。",
                       "en": "Once the test set selects models or hyper-parameters it is a validation set, and the score is no longer trustworthy."}},
         ]},

        # ------------------------------------------------- Part 04 (p17-23) -
        {"type": "section", "num": "04",
         "title": {"zh": "Dataset 与 DataLoader", "en": "Dataset & DataLoader"},
         "title_en": {"zh": "Dataset & DataLoader", "en": "Dataset & DataLoader"},
         "lead": {"zh": "划分之后，数据要以「样本可索引」的形式交给训练循环。\nPyTorch 用两个抽象完成这件事，这一部分把它们讲到你能自己写出来。",
                  "en": "After splitting, the data must reach the training loop as indexable samples.\nPyTorch does this with two abstractions - this part takes you to the point of writing them yourself."},
         "pillars": [
             {"title": {"zh": "契约", "en": "Contract"},
              "sub": {"zh": "__len__ 与 __getitem__", "en": "__len__ and __getitem__"}},
             {"title": {"zh": "批处理", "en": "Batching"},
              "sub": {"zh": "batch · shuffle · workers", "en": "batch · shuffle · workers"}},
             {"title": {"zh": "增强", "en": "Augmentation"},
              "sub": {"zh": "只作用于训练集", "en": "Training set only"}},
         ]},

        {"type": "cards", "cols": 3, "h": 5.0, "top": 3.6,
         "title": {"zh": "Dataset 与 DataLoader：六条要点", "en": "Dataset and DataLoader: Six Points"},
         "right": {"zh": "模块一 · Week 3", "en": "Module 1 · Week 3"},
         "subtitle": {"zh": "Dataset 定义「一条样本是什么」，DataLoader 定义「批次怎么来」。",
                      "en": "A Dataset defines what one sample is; a DataLoader defines how batches are formed."},
         "cards": [
             {"title": {"zh": "Dataset 的契约", "en": "The Dataset Contract"}, "title_en": "two methods",
              "body": [{"zh": "子类必须实现 __len__ 与 __getitem__", "en": "A subclass must implement __len__ and __getitem__"},
                       {"zh": "__getitem__ 返回一条样本 (x, y)", "en": "__getitem__ returns one sample (x, y)"}]},
             {"title": {"zh": "DataLoader 做四件事", "en": "What DataLoader Does"}, "title_en": "four jobs",
              "body": [{"zh": "批处理、打乱、并行加载、collate 拼批次", "en": "Batching, shuffling, parallel loading, collating"},
                       {"zh": "它是可迭代对象，不是数据本身", "en": "It is an iterable, not the data itself"}]},
             {"title": {"zh": "batch_size 怎么选", "en": "Choosing batch_size"}, "title_en": "batch",
              "body": [{"zh": "太小：梯度噪声大、训练慢", "en": "Too small: noisy gradients, slow training"},
                       {"zh": "太大：显存紧张、泛化可能变差；32/64 起步", "en": "Too large: memory pressure and worse generalisation; start at 32/64"}]},
             {"title": {"zh": "shuffle 的规则", "en": "The shuffle Rule"}, "title_en": "shuffle",
              "body": [{"zh": "训练集 True，验证/测试 False", "en": "True for train; False for validation and test"},
                       {"zh": "顺序不影响指标，但便于对齐与排查", "en": "Order does not change metrics but helps debugging"}]},
             {"title": {"zh": "num_workers 与加载瓶颈", "en": "num_workers and the I/O Bottleneck"}, "title_en": "workers",
              "body": [{"zh": "加载成为瓶颈时设为 2–4 个子进程", "en": "Set 2-4 worker processes when loading is the bottleneck"},
                       {"zh": "设太大反而拖慢；Notebook 下先试 0", "en": "Too many can slow it down; try 0 first in notebooks"}]},
             {"title": {"zh": "随机性要可控", "en": "Keep Randomness Controlled"}, "title_en": "seeds",
              "body": [{"zh": "用 torch.Generator 固定划分与 shuffle", "en": "Fix splits and shuffling with torch.Generator"},
                       {"zh": "多 worker 时用 worker_init_fn 固定各自种子", "en": "With workers, fix per-worker seeds via worker_init_fn"}]},
         ]},

        {"type": "code", "top": 3.45, "h": 11.6,
         "title": {"zh": "自定义 Dataset：只需要两个方法", "en": "A Custom Dataset: Two Methods Are Enough"},
         "right": {"zh": "模块一 · Week 3", "en": "Module 1 · Week 3"},
         "blocks": [
             {"title": {"zh": "dataset.py", "en": "dataset.py"},
              "size": 11.5,
              "code": {"zh": [
                  "import torch",
                  "from torch.utils.data import Dataset",
                  "",
                  "class DefectDataset(Dataset):",
                  "    \"\"\"DataFrame -> PyTorch 数据集：只需两个方法。\"\"\"",
                  "",
                  "    def __init__(self, df, transform=None):",
                  "        self.y = torch.tensor(df[\"label\"].values,",
                  "                             dtype=torch.long)",
                  "        self.x = torch.tensor(df.drop(",
                  "            columns=[\"label\"]).values.astype(\"float32\"))",
                  "        self.transform = transform  # 增强只在训练集传入",
                  "",
                  "    def __len__(self):",
                  "        return len(self.y)          # 批次数靠它算",
                  "",
                  "    def __getitem__(self, i):",
                  "        x = self.x[i]               # 一次只返回一条",
                  "        if self.transform is not None:",
                  "            x = self.transform(x)",
                  "        return x, self.y[i]         # (特征, 标签)",
                  "",
                  "ds = DefectDataset(df)",
                  "print(len(ds), ds[0][0].shape)",
              ],
              "en": [
                  "import torch",
                  "from torch.utils.data import Dataset",
                  "",
                  "class DefectDataset(Dataset):",
                  "    \"\"\"DataFrame -> PyTorch dataset: two methods only.\"\"\"",
                  "",
                  "    def __init__(self, df, transform=None):",
                  "        self.y = torch.tensor(df[\"label\"].values,",
                  "                             dtype=torch.long)",
                  "        self.x = torch.tensor(df.drop(",
                  "            columns=[\"label\"]).values.astype(\"float32\"))",
                  "        self.transform = transform  # train split only",
                  "",
                  "    def __len__(self):",
                  "        return len(self.y)          # used for batch count",
                  "",
                  "    def __getitem__(self, i):",
                  "        x = self.x[i]               # one sample at a time",
                  "        if self.transform is not None:",
                  "            x = self.transform(x)",
                  "        return x, self.y[i]         # (features, label)",
                  "",
                  "ds = DefectDataset(df)",
                  "print(len(ds), ds[0][0].shape)",
              ]}},
         ],
         "note": {"zh": "两条纪律：__getitem__ 里不要做「跨样本」的统计（那是泄漏的温床）；transform 只在训练集传入，验证与测试必须与线上推理保持一致。",
                  "en": "Two disciplines: never compute cross-sample statistics inside __getitem__ (a breeding ground for leakage), and pass transform to the training split only - validation and test must match inference."}},

        {"type": "code", "top": 3.45, "h": 11.6,
         "title": {"zh": "DataLoader 与固定种子的划分", "en": "DataLoader and a Seeded Split"},
         "right": {"zh": "模块一 · Week 3", "en": "Module 1 · Week 3"},
         "blocks": [
             {"title": {"zh": "dataloader.py", "en": "dataloader.py"},
              "size": 11.5,
              "code": {"zh": [
                  "import torch",
                  "from torch.utils.data import DataLoader, Subset",
                  "",
                  "# 固定种子的划分：可复现，且不污染全局随机状态",
                  "g = torch.Generator().manual_seed(42)",
                  "perm = torch.randperm(len(ds), generator=g)",
                  "",
                  "i1, i2 = int(0.70 * len(ds)), int(0.85 * len(ds))",
                  "train_ds = Subset(ds, perm[:i1])",
                  "val_ds   = Subset(ds, perm[i1:i2])",
                  "test_ds  = Subset(ds, perm[i2:])",
                  "",
                  "train_loader = DataLoader(train_ds, batch_size=32,",
                  "                          shuffle=True, num_workers=4)",
                  "val_loader   = DataLoader(val_ds, batch_size=64,",
                  "                          shuffle=False)",
                  "test_loader  = DataLoader(test_ds, batch_size=64)",
                  "",
                  "xb, yb = next(iter(train_loader))",
                  "print(xb.shape, yb.shape, len(train_loader))",
                  "# shuffle 只开在训练集；val/test 保持顺序即可",
              ],
              "en": [
                  "import torch",
                  "from torch.utils.data import DataLoader, Subset",
                  "",
                  "# a seeded split: reproducible, no global RNG side effects",
                  "g = torch.Generator().manual_seed(42)",
                  "perm = torch.randperm(len(ds), generator=g)",
                  "",
                  "i1, i2 = int(0.70 * len(ds)), int(0.85 * len(ds))",
                  "train_ds = Subset(ds, perm[:i1])",
                  "val_ds   = Subset(ds, perm[i1:i2])",
                  "test_ds  = Subset(ds, perm[i2:])",
                  "",
                  "train_loader = DataLoader(train_ds, batch_size=32,",
                  "                          shuffle=True, num_workers=4)",
                  "val_loader   = DataLoader(val_ds, batch_size=64,",
                  "                          shuffle=False)",
                  "test_loader  = DataLoader(test_ds, batch_size=64)",
                  "",
                  "xb, yb = next(iter(train_loader))",
                  "print(xb.shape, yb.shape, len(train_loader))",
                  "# shuffle on the training set only; val/test stay ordered",
              ]}},
         ],
         "note": {"zh": "运行前先确认 xb 的形状与 dtype：形状不对，多半是 __getitem__ 返回了整列而不是单条样本——这是实验 2 里最常见的报错。",
                  "en": "Check the shape and dtype of xb before anything else: a wrong shape usually means __getitem__ returned a whole column instead of one sample - the most common error in Lab 2."}},

        {"type": "table", "top": 3.2, "h": 9.0,
         "title": {"zh": "DataLoader 关键参数与常见坑", "en": "Key DataLoader Arguments and Their Pitfalls"},
         "right": {"zh": "模块一 · Week 3", "en": "Module 1 · Week 3"},
         "cols": [{"zh": "参数", "en": "Argument"},
                  {"zh": "作用", "en": "What It Does"},
                  {"zh": "建议初值", "en": "Start With"},
                  {"zh": "常见坑", "en": "Common Pitfall"}],
         "widths": [4.0, 5.6, 5.4, 14.4],
         "bold_first": True,
         "rows": [
             [{"zh": "batch_size", "en": "batch_size"},
              {"zh": "每个批次的样本数", "en": "Samples per batch"},
              {"zh": "32 / 64", "en": "32 / 64"},
              {"zh": "太大显存爆且泛化变差；太小梯度噪声大、训练变慢", "en": "Too large runs out of memory and generalises worse; too small is noisy and slow"}],
             [{"zh": "shuffle", "en": "shuffle"},
              {"zh": "每轮是否打乱顺序", "en": "Whether to reshuffle each epoch"},
              {"zh": "训练集 True", "en": "True for train"},
              {"zh": "验证/测试开 True 会让排查困难；与 sampler 互斥", "en": "True on val/test makes debugging harder; mutually exclusive with sampler"}],
             [{"zh": "num_workers", "en": "num_workers"},
              {"zh": "并行加载的子进程数", "en": "Worker processes for loading"},
              {"zh": "2 – 4", "en": "2 - 4"},
              {"zh": "设太大会拖慢；Notebook 与 Windows 下多进程容易报错", "en": "Too many slows it down; multiprocessing often breaks in notebooks and on Windows"}],
             [{"zh": "drop_last", "en": "drop_last"},
              {"zh": "丢弃不足一批的尾批", "en": "Drop the final short batch"},
              {"zh": "训练集 True", "en": "True for train"},
              {"zh": "不丢时尾批可能只剩 1 个样本，BatchNorm 会直接报错", "en": "Leave it False and a batch of size 1 can crash BatchNorm"}],
             [{"zh": "collate_fn", "en": "collate_fn"},
              {"zh": "自定义批次拼装方式", "en": "Custom batch assembly"},
              {"zh": "变长序列时自定义", "en": "Custom for variable-length sequences"},
              {"zh": "默认要求同形状，NLP 任务里会直接报错", "en": "The default requires equal shapes and fails in NLP tasks"}],
             [{"zh": "generator", "en": "generator"},
              {"zh": "固定 shuffle 的随机性", "en": "Fixes the randomness of shuffling"},
              {"zh": "torch.Generator", "en": "torch.Generator"},
              {"zh": "不设时，两次运行的批次顺序不同，结果无法逐位对齐", "en": "Without it, batch order differs between runs and results cannot be matched bit-for-bit"}],
         ],
         "note": {"zh": "参数没有「最佳值」，只有「与你的数据、显存和指标口径匹配的值」。实验报告里必须给出取值与理由。",
                  "en": "There is no best value - only a value that matches your data, memory and metric. The lab report must state each value and the reason."}},

        {"type": "cards", "cols": 3, "h": 5.0, "top": 3.6,
         "title": {"zh": "数据增强与类别不平衡", "en": "Augmentation and Class Imbalance"},
         "right": {"zh": "模块一 · Week 3", "en": "Module 1 · Week 3"},
         "subtitle": {"zh": "两条边界：增强只作用于训练集；任何采样都要报告处理前后的类别分布。",
                      "en": "Two boundaries: augmentation touches the training set only, and every sampling step reports the before/after class distribution."},
         "cards": [
             {"title": {"zh": "数据增强：训练集专用", "en": "Augmentation: Training Only"}, "title_en": "augment",
              "body": [{"zh": "图像：翻转、裁剪、颜色抖动、随机擦除", "en": "Images: flip, crop, colour jitter, random erasing"},
                       {"zh": "表格：加噪声、插值、特征扰动", "en": "Tabular: noise, interpolation, feature perturbation"}]},
             {"title": {"zh": "不平衡之一：重采样", "en": "Imbalance 1: Resampling"}, "title_en": "resample",
              "body": [{"zh": "WeightedRandomSampler 给少数类更高权重", "en": "WeightedRandomSampler gives the minority class more weight"},
                       {"zh": "过采样少数类，或欠采样多数类", "en": "Oversample the minority, or undersample the majority"}]},
             {"title": {"zh": "不平衡之二：代价敏感", "en": "Imbalance 2: Cost-Sensitive Loss"}, "title_en": "loss",
              "body": [{"zh": "CrossEntropyLoss(weight=1/counts)", "en": "CrossEntropyLoss(weight=1/counts)"},
                       {"zh": "不改数据，改的是「犯错的代价」", "en": "The data is untouched; the price of an error changes"}]},
             {"title": {"zh": "不平衡下的指标", "en": "Metrics Under Imbalance"}, "title_en": "metrics",
              "body": [{"zh": "类别只占 4% 时，accuracy 可以到 0.96 却毫无用处", "en": "A 4% class lets accuracy reach 0.96 while being useless"},
                       {"zh": "改用 per-class recall、F1 或 AUPRC", "en": "Switch to per-class recall, F1 or AUPRC"}]},
             {"title": {"zh": "增强的边界", "en": "Limits of Augmentation"}, "title_en": "limits",
              "body": [{"zh": "验证/测试一律不增强，否则指标不可比", "en": "Never augment val/test, or metrics are not comparable"},
                       {"zh": "增强不能改变标签语义，否则是造噪声", "en": "Augmentation must not change label semantics"}]},
             {"title": {"zh": "采样带来的新偏差", "en": "Bias Introduced by Sampling"}, "title_en": "bias",
              "body": [{"zh": "有放回重采样会放大少数类的噪声与重复样本", "en": "Sampling with replacement amplifies minority noise and duplicates"},
                       {"zh": "必须报告采样前后的分布对照", "en": "Always report the distribution before and after sampling"}]},
         ]},

        {"type": "code", "top": 3.45, "h": 11.6,
         "title": {"zh": "类别不平衡：重采样与代价敏感损失", "en": "Class Imbalance: Resampling and Cost-Sensitive Loss"},
         "right": {"zh": "模块一 · Week 3", "en": "Module 1 · Week 3"},
         "blocks": [
             {"title": {"zh": "imbalance.py", "en": "imbalance.py"},
              "size": 11.5,
              "code": {"zh": [
                  "import torch",
                  "from torch.utils.data import DataLoader",
                  "from torch.utils.data import WeightedRandomSampler",
                  "",
                  "# 按样本权重重采样，让每个批次接近均衡",
                  "y_tr = torch.tensor([ds[i][1]",
                  "                     for i in train_ds.indices])",
                  "counts = torch.bincount(y_tr)      # 每类样本数",
                  "w = (1.0 / counts.float())[y_tr]   # 少数类权重更大",
                  "",
                  "sampler = WeightedRandomSampler(",
                  "    weights=w, num_samples=len(w),",
                  "    replacement=True)              # 有放回重采样",
                  "train_loader = DataLoader(train_ds, batch_size=32,",
                  "                         sampler=sampler)",
                  "# 注意：sampler 与 shuffle=True 互斥",
                  "",
                  "# 另一种做法：不改数据，改损失",
                  "# criterion = nn.CrossEntropyLoss(weight=1/counts)",
                  "# 增强只加训练集；验证/测试与线上推理保持一致",
              ],
              "en": [
                  "import torch",
                  "from torch.utils.data import DataLoader",
                  "from torch.utils.data import WeightedRandomSampler",
                  "",
                  "# resample by sample weight so each batch is balanced",
                  "y_tr = torch.tensor([ds[i][1]",
                  "                     for i in train_ds.indices])",
                  "counts = torch.bincount(y_tr)      # samples per class",
                  "w = (1.0 / counts.float())[y_tr]   # rarer, bigger weight",
                  "",
                  "sampler = WeightedRandomSampler(",
                  "    weights=w, num_samples=len(w),",
                  "    replacement=True)              # with replacement",
                  "train_loader = DataLoader(train_ds, batch_size=32,",
                  "                         sampler=sampler)",
                  "# note: sampler and shuffle=True are exclusive",
                  "",
                  "# alternative: keep the data, change the loss",
                  "# criterion = nn.CrossEntropyLoss(weight=1/counts)",
                  "# augment train only; val/test must match inference",
              ]}},
         ],
         "note": {"zh": "处理完一定要回看指标：如果少数类的 recall 上去了但多数类掉得很厉害，说明你在用整体性能换少数类，这个取舍必须写进报告。",
                  "en": "Always re-measure after treating imbalance: if minority recall rises while the majority class collapses, you traded overall performance for the minority - state that trade-off in the report."}},

        # -------------------------------------------------- Part 05 (p24-27) -
        {"type": "section", "num": "05",
         "title": {"zh": "Lab · 实验 2：数据管道与数据卡片", "en": "Lab · Experiment 2: Pipeline & Data Card"},
         "title_en": {"zh": "Dataset, DataLoader & Data Card", "en": "Dataset, DataLoader & Data Card"},
         "lead": {"zh": "80 分钟，把本周的六步管道真正跑通：\n先按「是否需要统计量」给清洗动作分组，再实现自定义 Dataset 与 DataLoader，完成探索、划分、增强与不平衡统计，产出数据卡片。",
                  "en": "In 80 minutes you make the six-step pipeline actually run:\nsort the cleaning steps by whether they need a statistic, then implement a custom Dataset and DataLoader, complete exploration, splitting, augmentation and imbalance statistics, and produce a Data Card."},
         "pillars": [
             {"title": {"zh": "探索", "en": "Explore"},
              "sub": {"zh": "质量诊断与可视化", "en": "Diagnose quality and plot it"}},
             {"title": {"zh": "划分", "en": "Split"},
              "sub": {"zh": "固定种子 + 说明依据", "en": "Fixed seed + justification"}},
             {"title": {"zh": "管道", "en": "Pipeline"},
              "sub": {"zh": "自定义 Dataset 与 DataLoader", "en": "Custom Dataset and DataLoader"}},
             {"title": {"zh": "交付", "en": "Deliver"},
              "sub": {"zh": "数据卡片 Data Card", "en": "The Data Card"}},
         ]},

        {"type": "cards", "cols": 3, "h": 4.7, "top": 3.6,
         "title": {"zh": "实验 2 的七件事", "en": "The Seven Tasks of Experiment 2"},
         "right": {"zh": "模块一 · Week 3", "en": "Module 1 · Week 3"},
         "subtitle": {"zh": "AI 可以帮你写探索代码，但每一条统计结论都必须由你自己核对。",
                      "en": "AI may draft the exploration code, but every statistical claim must be checked by you."},
         "cards": [
             {"title": {"zh": "A · 探索与质量诊断", "en": "A · Explore and diagnose"}, "title_en": "task A",
              "body": [{"zh": "分布、缺失、异常、重复各写清判据", "en": "Give explicit criteria for distribution, missing, outliers, duplicates"},
                       {"zh": "每条结论配一张图或一行断言", "en": "Pair every claim with a plot or an assert"}]},
             {"title": {"zh": "B · 清洗原始表（无需统计量）", "en": "B · Clean the raw table (no statistics)"}, "title_en": "task B",
              "body": [{"zh": "去重、单位换算、编码统一，各写清数值判据", "en": "State a numeric criterion for de-duplication, unit conversion and code unification"},
                       {"zh": "预测删除数必须等于实际删除数（812 = 812）", "en": "The predicted removal count must equal the actual one (812 = 812)"}]},
             {"title": {"zh": "C · 先划分，再只用训练集算统计量", "en": "C · Split, then training-only statistics"}, "title_en": "task C",
              "body": [{"zh": "用固定种子划分，并说明为什么选随机/分层/时间/分组", "en": "Split with a fixed seed and justify random / stratified / time / group"},
                       {"zh": "报告每个集合的样本量与类别比例", "en": "Report the size and class ratio of every split"}]},
             {"title": {"zh": "D · 自定义 Dataset", "en": "D · Custom Dataset"}, "title_en": "task D",
              "body": [{"zh": "实现 __len__ 与 __getitem__，返回 (x, y)", "en": "Implement __len__ and __getitem__ returning (x, y)"},
                       {"zh": "验证 ds[0] 的形状与 dtype 正确", "en": "Verify the shape and dtype of ds[0]"}]},
             {"title": {"zh": "E · DataLoader 与增强", "en": "E · DataLoader and augmentation"}, "title_en": "task E",
              "body": [{"zh": "设置 batch_size、shuffle、num_workers 并说明理由", "en": "Set batch_size, shuffle and num_workers with reasons"},
                       {"zh": "增强只加在训练集，并给出对照", "en": "Apply augmentation to train only, with a comparison"}]},
             {"title": {"zh": "F · 不平衡统计与处理", "en": "F · Imbalance statistics"}, "title_en": "task F",
              "body": [{"zh": "统计各类占比，选重采样或代价敏感损失", "en": "Measure class shares, then pick resampling or a cost-sensitive loss"},
                       {"zh": "给出处理前后的类别分布对照", "en": "Show the class distribution before and after"}]},
             {"title": {"zh": "G · 尊重数据与隐私", "en": "G · Respect for Data and Privacy"}, "title_en": "task G",
              "body": [{"zh": "只使用来源合规、获得授权的数据", "en": "Use only data with a lawful, authorised source"},
                       {"zh": "个人信息先去标识化，不上传到公网工具", "en": "De-identify personal data; never upload it to public tools"}]},
         ]},

        {"type": "code", "top": 3.3, "h": 12.2,
         "title": {"zh": "实验 2 交付物：数据卡片（Data Card）", "en": "Lab 2 Deliverable: The Data Card"},
         "right": {"zh": "模块一 · Week 3", "en": "Module 1 · Week 3"},
         "blocks": [
             {"title": {"zh": "data_card.md", "en": "data_card.md"},
              "size": 11,
              "code": {"zh": [
                  "# Data Card · 数据卡片 · defects-v1",
                  "",
                  "## 1. 来源与合规",
                  "- 来源：<内部产线导出> · 许可：内部授权 · 采集：2026-09",
                  "- 已去标识化：删除工号与设备序列号；未上传公网工具",
                  "",
                  "## 2. 规模与结构",
                  "- 11,668 行（原始 12,480，按主键去重删除 812）· 特征数 10 · 标签 5 类",
                  "- 划分 train 70% / val 15% / test 15%",
                  "  （seed=42，分层划分，理由是类别不平衡）",
                  "",
                  "## 3. 质量与已知问题",
                  "- 缺失：age 3.2%（少数类 25% vs 其他 2.3%）-> 用训练集中位数填补",
                  "- 单位混用：935 条华氏记录 -> 换算为摄氏（不是删掉）",
                  "- 编码不一致：material_code 10 种写法 -> 归一为 5 个编码",
                  "- 异常：35 条传感器卡死值 -> 截断到训练集 1/99 分位",
                  "- 重复：按 batch_id + 时间戳去重，删除 812 条",
                  "",
                  "## 4. 增强与不平衡",
                  "- 类别 3 仅占 4.1% -> WeightedRandomSampler",
                  "- 训练集：高斯噪声；验证/测试：不增强",
                  "",
                  "## 5. 偏差与使用边界",
                  "- 样本集中来自单一产线，结论不可外推到其他工厂",
              ],
              "en": [
                  "# Data Card - defects-v1",
                  "",
                  "## 1. Provenance and compliance",
                  "- Source: <internal line export> · internal licence · 2026-09",
                  "- De-identified: employee and device IDs removed; not uploaded",
                  "",
                  "## 2. Scale and structure",
                  "- 11,668 unique rows (12,480 raw, 812 duplicates removed) · 10 features · 5 classes",
                  "- Split train 70% / val 15% / test 15%",
                  "  (seed=42, stratified - because the classes are imbalanced)",
                  "",
                  "## 3. Quality and known issues",
                  "- Missing: age 3.2% (25% in the rare class vs 2.3% elsewhere) -> training median",
                  "- Unit mixed: 935 Fahrenheit readings -> converted to Celsius, not deleted",
                  "- Codes: material_code in 10 spellings -> normalised to 5 and encoded",
                  "- Outliers: 35 stuck-sensor readings -> clipped to the training 1st/99th pct",
                  "- Duplicates: de-duplicated on batch_id + timestamp, 812 gone",
                  "",
                  "## 4. Augmentation and imbalance",
                  "- Class 3 is only 4.1% -> WeightedRandomSampler",
                  "- Train: Gaussian noise; val/test: none",
                  "",
                  "## 5. Bias and limits of use",
                  "- Samples come from a single line; do not extrapolate",
              ]}},
         ],
         "note": {"zh": "数据卡片是本周的交付核心：它把「我怎么处理数据」变成别人可以核查的文字。缺少「偏差与使用边界」一节的数据卡片，视为未完成。",
                  "en": "The Data Card is the deliverable at the heart of this week: it turns \"how I handled the data\" into text someone else can audit. A Data Card without the bias-and-limits section counts as incomplete."}},

        {"type": "checklist", "top": 3.55, "h": 2.15,
         "title": {"zh": "实验 2 提交清单", "en": "Experiment 2 Submission Checklist"},
         "right": {"zh": "模块一 · Week 3", "en": "Module 1 · Week 3"},
         "items": [
             {"badge": {"zh": "必交", "en": "MUST"}, "accent": "1E4FA8",
              "title": {"zh": "可运行的数据管道代码", "en": "Runnable pipeline code"},
              "desc": {"zh": "data_pipeline.py 含自定义 Dataset 与 DataLoader，能在干净环境里端到端跑通。",
                       "en": "data_pipeline.py with a custom Dataset and DataLoader, running end to end on a clean checkout."}},
             {"badge": {"zh": "必交", "en": "MUST"}, "accent": "1E4FA8",
              "title": {"zh": "划分策略与依据", "en": "Split strategy and its justification"},
              "desc": {"zh": "写明选随机/分层/时间/分组的原因、种子取值，以及每个集合的规模与类别比例。",
                       "en": "State the chosen strategy, the seed, and the size and class ratio of each split."}},
             {"badge": {"zh": "必交", "en": "MUST"}, "accent": "1E4FA8",
              "title": {"zh": "数据卡片 Data Card", "en": "The Data Card"},
              "desc": {"zh": "含来源与合规、规模与结构、质量与已知问题、增强与不平衡、偏差与使用边界。",
                       "en": "Covering provenance, scale, quality, augmentation and imbalance, and bias and limits of use."}},
             {"badge": {"zh": "必交", "en": "MUST"}, "accent": "1E4FA8",
              "title": {"zh": "增强与不平衡的前后对照", "en": "Before/after evidence for augmentation and imbalance"},
              "desc": {"zh": "给出处理前后的类别分布与关键指标，说明这个取舍的代价。",
                       "en": "Give the class distribution and key metrics before and after, and state the trade-off."}},
             {"badge": {"zh": "必交", "en": "MUST"}, "accent": "1E4FA8",
              "title": {"zh": "AI 协同记录", "en": "AI collaboration log"},
              "desc": {"zh": "记录 AI 给出的统计结论、你核对后的结果，以及那条被证伪的结论。",
                       "en": "Record the AI's statistical claims, your verification, and the claim that turned out wrong."}},
         ]},

        # ------------------------------------------------------ quiz (p28) --
        {"type": "quiz", "cols": 2,
         "title": {"zh": "随堂小测", "en": "Quick Check"},
         "right": {"zh": "模块一 · Week 3", "en": "Module 1 · Week 3"},
         "questions": [
             {"tag": {"zh": "泄漏", "en": "Leakage"},
              "q": {"zh": "用测试集参与训练后得到的 0.99 准确率，能作为最终指标吗？",
                    "en": "After the test set took part in training, accuracy reads 0.99. Can it be the final metric?"},
              "options": [{"zh": "能，数字更高说明模型更好", "en": "Yes - a higher number means a better model"},
                          {"zh": "不能，测试集已被模型见过，必须换真正未见过的数据评估", "en": "No - the model has seen it; you need data it has never seen"},
                          {"zh": "能，只要再跑一次验证集就行", "en": "Yes, as long as you also run the validation set"},
                          {"zh": "取决于测试集的大小", "en": "It depends on the size of the test set"}]},
             {"tag": {"zh": "划分", "en": "Splitting"},
              "q": {"zh": "带时间顺序的数据应该怎么划分？",
                    "en": "How should data with a time order be split?"},
              "options": [{"zh": "随机打乱后按比例切分", "en": "Shuffle randomly, then cut by ratio"},
                          {"zh": "时间划分：用过去训练、用未来测试", "en": "Time-based: train on the past, test on the future"},
                          {"zh": "只分训练集和测试集，不分验证集", "en": "Only train and test, with no validation set"},
                          {"zh": "按类别分层划分", "en": "Stratified by class"}]},
             {"tag": {"zh": "Dataset", "en": "Dataset"},
              "q": {"zh": "自定义 Dataset 必须实现哪两个方法？",
                    "en": "Which two methods must a custom Dataset implement?"},
              "options": [{"zh": "__init__ 与 fit", "en": "__init__ and fit"},
                          {"zh": "__len__ 与 __getitem__", "en": "__len__ and __getitem__"},
                          {"zh": "forward 与 backward", "en": "forward and backward"},
                          {"zh": "load 与 save", "en": "load and save"}]},
             {"tag": {"zh": "不平衡", "en": "Imbalance"},
              "q": {"zh": "某个类别只占 4%，第一步应该做什么？",
                    "en": "One class is only 4% of the data. What comes first?"},
              "options": [{"zh": "直接训练，用 accuracy 评估", "en": "Train as is and evaluate with accuracy"},
                          {"zh": "先统计各类占比，再选重采样或代价敏感损失并改用 per-class 指标", "en": "Measure the class shares, then choose resampling or a cost-sensitive loss and per-class metrics"},
                          {"zh": "直接删掉这个少数类", "en": "Delete the minority class"},
                          {"zh": "把整个数据集复制一份", "en": "Duplicate the whole dataset"}]},
         ]},

        # --------------------------------------------------- summary (p29) --
        {"type": "summary",
         "title": {"zh": "本周小结", "en": "Week 3 Summary"},
         "right": {"zh": "模块一 · Week 3", "en": "Module 1 · Week 3"},
         "points": [
             {"zh": "数据决定上限，模型逼近上限：效果不好时，先诊断数据，再考虑换模型。",
              "en": "Data sets the ceiling and models approach it: when results are poor, diagnose the data before changing the model."},
             {"zh": "清洗是把已知问题变成可核查记录：缺失、异常、重复、标签噪声各有判据、动作与风险。",
              "en": "Cleaning turns known problems into an auditable record: each of missing, outliers, duplicates and label noise has a criterion, an action and a risk."},
             {"zh": "划分必须发生在所有「会学习」的步骤之前：标准化、填补、特征选择的统计量只来自训练集。",
              "en": "Splitting precedes every step that learns: the statistics behind scaling, imputation and feature selection come from the training set only."},
             {"zh": "数据泄漏 = 训练时看到了推理时拿不到的信息：四种形态是测试集混入、重复样本跨集、时序随机划分、测试集被反复调参。",
              "en": "Leakage means training on information unavailable at inference: test data merged in, duplicates across splits, random splits on time series, and a test set reused for tuning."},
             {"zh": "Dataset 定义一条样本是什么，DataLoader 定义批次怎么来；增强只加训练集，不平衡用 sampler 或代价敏感损失。",
              "en": "A Dataset defines one sample, a DataLoader defines the batches; augmentation applies to train only, and imbalance is handled by a sampler or a cost-sensitive loss."},
         ],
         "todo_title": {"zh": "课后待办", "en": "After Class"},
         "todos": [
             {"title": {"zh": "提交数据管道代码与数据卡片", "en": "Submit the pipeline code and the Data Card"},
              "desc": {"zh": "data_pipeline.py 能端到端运行；数据卡片说明划分策略、增强策略的选择依据与潜在偏差。",
                       "en": "data_pipeline.py must run end to end; the Data Card states the reasoning behind the split and augmentation choices, plus the remaining bias."}},
             {"title": {"zh": "预习 W4：从张量到 nn.Module", "en": "Preview W4: from tensors to nn.Module"},
              "desc": {"zh": "把本周的 DataLoader 接进一个最小训练脚本，先跑通一个 epoch，并记录训练与验证损失。",
                       "en": "Plug this week's DataLoader into a minimal training script, run one epoch, and log the training and validation loss."}},
         ]},

        # --------------------------------------------------- closing (p30) --
        {"type": "closing",
         "quote": {"zh": "「模型的上限，在你划分数据的那一刻\n就已经写好了。」",
                   "en": "\"The ceiling of your model is written\nat the moment you split the data.\""},
         "quote_sub": {"zh": "本周交付：一条可复现的数据管道 + 一张说清偏差的数据卡片。",
                       "en": "This week you deliver: a reproducible data pipeline + a Data Card that states its own bias."},
         "thanks": {"zh": "谢谢大家", "en": "Thank you"},
         "next_label": {"zh": "下周预告", "en": "Next week"},
         "next": {"zh": "W4 · 从张量到 nn.Module：用本周的 Dataset 与 DataLoader 训练第一个真正的模型，并读懂训练/验证曲线。",
                  "en": "W4 · From tensors to nn.Module: train your first real model on this week's Dataset and DataLoader, and learn to read the training/validation curves."}},
    ],
}
