"""Week 5 — Training Loop, Loss and Optimizer  ·  slide spec (bilingual).

Aligned with the official course documents (52015CC3BV):
CU(5) · Module 2 "Core Deep Learning" (Week 5-8), the first week of that module.
KT9/KT10: loss functions, optimizers, learning-rate policy, the five-step
training loop, batch size vs. VRAM, training logs and visualisation.
"""

MOD = {"zh": "模块二 · Week 5", "en": "Module 2 · Week 5"}

SPEC = {
    "week": 5,
    "slides": [
        # ---------------------------------------------------------- cover ----
        {"type": "cover",
         "kicker": {"zh": "52015CC3BV · 本科 · 来华项目",
                    "en": "52015CC3BV · UNDERGRADUATE · INTERNATIONAL"},
         "title": {"zh": "训练循环、损失函数与优化器",
                   "en": "Training Loop, Loss and Optimizer"},
         "title_sub": {"zh": "Training Loop, Loss and Optimizer",
                       "en": "What we optimise, how we walk, how big the step"},
         "subtitle": {"zh": "Week 5 · 损失函数选择 · 优化器差异 · 学习率 · 训练循环五步法 · 日志与可视化",
                      "en": "Week 5 · Choosing a loss · Optimizers compared · Learning rate · The five-step loop · Logging & plots"},
         "chips": [
             ({"zh": "模块二 · W5–8", "en": "Module 2 · W5-8"}, 1.0),
             ({"zh": "180 min · 授课 + 实验 + 小测", "en": "180 min · Lecture + Lab + Quiz"}, 1.5),
             ({"zh": "PyTorch · 优化器 · 学习率 · 训练日志", "en": "PyTorch · optimizers · learning rate · logs"}, 1.8),
             ({"zh": "留学生班 · 英文授课", "en": "International Students"}, 1.0),
         ]},

        # ------------------------------------------------------- contents ----
        {"type": "contents",
         "right": MOD,
         "count": {"zh": "5 部分", "en": "5 Parts"},
         "count_label": {"zh": "本周结构", "en": "Part"},
         "tagline": {"zh": "损失函数决定模型在优化什么，\n优化器决定它怎么走，\n学习率决定它一步走多大。",
                     "en": "The loss names what you optimise, the optimizer decides how you walk, the learning rate decides how big a step you take."},
         "timing": {"zh": "理论约 90 min · Lab 约 75 min · 小测与小结 15 min",
                    "en": "Theory ~90 min · Lab ~75 min · Quiz & Summary 15 min"},
         "parts": [
             {"title": {"zh": "损失函数：我们在优化什么", "en": "The Loss: What We Optimise"},
              "title_en": {"zh": "Loss", "en": "Loss"},
              "desc": {"zh": "任务类型决定损失 · 三种常用损失 · 一个常见坑",
                       "en": "Task type decides the loss · three common losses · one classic pitfall"}},
             {"title": {"zh": "优化器：参数怎么更新", "en": "Optimizers: How We Update"},
              "title_en": {"zh": "Optimizer", "en": "Optimizer"},
              "desc": {"zh": "SGD · Momentum · Adam · 三者的差别与代价",
                       "en": "SGD · momentum · Adam · what differs and what it costs"}},
             {"title": {"zh": "学习率：最重要的超参数", "en": "Learning Rate: The First Hyper-parameter"},
              "title_en": {"zh": "Learning rate", "en": "Learning rate"},
              "desc": {"zh": "过大 / 过小的症状 · 衰减策略 · 损失曲线诊断",
                       "en": "Symptoms of too large / too small · schedules · reading the loss curve"}},
             {"title": {"zh": "训练循环五步法", "en": "The Five-Step Training Loop"},
              "title_en": {"zh": "Training loop", "en": "Training loop"},
              "desc": {"zh": "清零 → 前向 → 计算损失 → 反向 → 更新 · 日志与批大小",
                       "en": "Zero → forward → loss → backward → step · logs and batch size"}},
             {"title": {"zh": "Lab · 实验 4 优化器 × 学习率", "en": "Lab · Optimizers × Learning Rates"},
              "title_en": {"zh": "Hands-On Lab", "en": "Hands-On Lab"},
              "desc": {"zh": "3 种优化器 × 3 组学习率 · 损失/准确率曲线 · 最优组合与理由",
                       "en": "3 optimizers x 3 learning rates · loss/accuracy curves · the best combo and why"}},
         ]},

        # ------------------------------------------------- Part 01 (p3-7) ---
        {"type": "section", "num": "01",
         "title": {"zh": "损失函数：我们在优化什么", "en": "The Loss: What We Optimise"},
         "title_en": {"zh": "Loss", "en": "Loss"},
         "lead": {"zh": "训练不是「让模型变好」这么模糊，而是「把某个数字变小」。\n损失函数就是你选择的那个数字——选错了，模型会把力气用在你不在乎的地方。",
                  "en": "Training is not vaguely \"making the model better\" — it is driving one number down.\nThe loss function is that number; choose it wrongly and the model spends its effort where you do not care."},
         "pillars": [
             {"title": {"zh": "任务定损失", "en": "Task Decides"},
              "sub": {"zh": "分类 / 二分类 / 回归", "en": "Multi-class / binary / regression"}},
             {"title": {"zh": "激活已内置", "en": "Activation Inside"},
              "sub": {"zh": "别再手动 softmax", "en": "Do not softmax by hand"}},
             {"title": {"zh": "数值要稳", "en": "Numerically Stable"},
              "sub": {"zh": "logits 版本更安全", "en": "The logits version is safer"}},
         ]},

        {"type": "cards", "cols": 3, "h": 6.4, "top": 3.6,
         "title": {"zh": "三类任务，三种损失", "en": "Three Task Types, Three Losses"},
         "right": MOD,
         "cards": [
             {"title": {"zh": "多分类", "en": "Multi-class"},
              "title_en": "nn.CrossEntropyLoss",
              "accent": "1E4FA8", "bg": "F0F5FC",
              "body": [
                  {"zh": "输入 (N, C) 原始 logits", "en": "Takes raw logits of shape (N, C)"},
                  {"zh": "标签是类别下标（long）", "en": "Labels are class indices (long)"},
                  {"zh": "softmax 已内置，别再手动做", "en": "softmax is built in — do not repeat it"},
                  {"zh": "例：10 类图像分类", "en": "e.g. 10-class image classification"}]},
             {"title": {"zh": "二分类 / 多标签", "en": "Binary / Multi-label"},
              "title_en": "nn.BCEWithLogitsLoss",
              "accent": "D97706", "bg": "FFFBEB",
              "body": [
                  {"zh": "输入 logits，形状 (N,) 或 (N, 1)", "en": "Takes logits, shape (N,) or (N, 1)"},
                  {"zh": "标签必须是 float（0.0 / 1.0）", "en": "Targets must be float (0.0 / 1.0)"},
                  {"zh": "sigmoid 已内置", "en": "sigmoid is built in"},
                  {"zh": "多标签时各类独立判断", "en": "For multi-label each class is independent"}]},
             {"title": {"zh": "回归", "en": "Regression"},
              "title_en": "nn.MSELoss",
              "accent": "059669", "bg": "ECFDF5",
              "body": [
                  {"zh": "预测连续数值：房价、温度", "en": "Predicts a continuous value: price, temperature"},
                  {"zh": "不用任何激活函数", "en": "No activation function at all"},
                  {"zh": "对大误差惩罚很重", "en": "Punishes large errors heavily"},
                  {"zh": "有离群点改 L1 / SmoothL1", "en": "With outliers use L1 / SmoothL1"}]},
         ]},

        {"type": "table",
         "title": {"zh": "常用损失函数对照表", "en": "Common Loss Functions at a Glance"},
         "right": MOD,
         "cols": [{"zh": "任务", "en": "Task"},
                  {"zh": "损失函数", "en": "Loss"},
                  {"zh": "输入是什么", "en": "Input"},
                  {"zh": "输出层", "en": "Output layer"},
                  {"zh": "注意", "en": "Watch out"}],
         "widths": [4.8, 6.6, 6.4, 5.6, 6.0],
         "h": 9.6, "bold_first": True,
         "rows": [
             [{"zh": "多分类", "en": "Multi-class"},
              {"zh": "CrossEntropyLoss", "en": "CrossEntropyLoss"},
              {"zh": "原始 logits (N, C)", "en": "Raw logits (N, C)"},
              {"zh": "无（内含 softmax）", "en": "None (softmax inside)"},
              {"zh": "再手动 softmax 就是做两次", "en": "A manual softmax means doing it twice"}],
             [{"zh": "二分类", "en": "Binary"},
              {"zh": "BCEWithLogitsLoss", "en": "BCEWithLogitsLoss"},
              {"zh": "原始 logits (N, 1)", "en": "Raw logits (N, 1)"},
              {"zh": "无（内含 sigmoid）", "en": "None (sigmoid inside)"},
              {"zh": "标签必须转成 float", "en": "Targets must be float"}],
             [{"zh": "多标签", "en": "Multi-label"},
              {"zh": "BCEWithLogitsLoss", "en": "BCEWithLogitsLoss"},
              {"zh": "原始 logits (N, C)", "en": "Raw logits (N, C)"},
              {"zh": "无", "en": "None"},
              {"zh": "各类独立，可同时为正", "en": "Classes independent, can co-occur"}],
             [{"zh": "回归", "en": "Regression"},
              {"zh": "MSELoss", "en": "MSELoss"},
              {"zh": "连续预测值", "en": "Continuous predictions"},
              {"zh": "无", "en": "None"},
              {"zh": "对离群点极敏感", "en": "Very sensitive to outliers"}],
             [{"zh": "不平衡分类", "en": "Imbalanced"},
              {"zh": "CrossEntropyLoss(weight=)", "en": "CrossEntropyLoss(weight=)"},
              {"zh": "logits + 类别权重", "en": "Logits + class weights"},
              {"zh": "无", "en": "None"},
              {"zh": "权重按类频率倒数设", "en": "Set weights as inverse class frequency"}],
         ],
         "note": {"zh": "一句话记法：分类用交叉熵、回归用均方误差；带 Logits 字样的损失已经把激活函数包在里面了，这就是为什么不要自己再加一层。",
                  "en": "One line to remember it: cross-entropy for classification, mean squared error for regression; any loss with \"WithLogits\" in its name already contains the activation — which is why you must not add another."}},

        {"type": "code", "top": 3.55, "h": 11.2,
         "title": {"zh": "三种损失的写法", "en": "The Three Losses in Code"},
         "right": MOD,
         "blocks": [
             {"title": {"zh": "选择损失", "en": "Choosing the loss"},
              "code": {"zh": [
                  "import torch, torch.nn as nn",
                  "",
                  "# 1) 多分类：softmax 已在损失内部",
                  "criterion = nn.CrossEntropyLoss()",
                  "",
                  "# 2) 二分类 / 多标签：sigmoid 已在内部",
                  "criterion = nn.BCEWithLogitsLoss()",
                  "",
                  "# 3) 回归：不用任何激活",
                  "criterion = nn.MSELoss()",
                  "",
                  "# 铁律：永远传原始 logits",
              ],
              "en": [
                  "import torch, torch.nn as nn",
                  "",
                  "# 1) multi-class: softmax is INSIDE",
                  "criterion = nn.CrossEntropyLoss()",
                  "",
                  "# 2) binary / multi-label: sigmoid INSIDE",
                  "criterion = nn.BCEWithLogitsLoss()",
                  "",
                  "# 3) regression: no activation at all",
                  "criterion = nn.MSELoss()",
                  "",
                  "# rule: always feed raw logits",
              ]}},
             {"title": {"zh": "常见坑：softmax 做了两次", "en": "Pitfall: softmax done twice"},
              "code": {"zh": [
                  "# 常见坑：softmax 被做了两次",
                  "logits = model(x)            # 原始 logits",
                  "probs = torch.softmax(logits, 1)",
                  "loss = nn.CrossEntropyLoss()(probs, y)",
                  "",
                  "# 概率被再次归一化并压扁，",
                  "# 梯度变小，损失下降缓慢、",
                  "# 准确率上不去。",
                  "# 正确做法：直接传 logits",
                  "loss = nn.CrossEntropyLoss()(logits, y)",
              ],
              "en": [
                  "# PITFALL: softmax applied twice",
                  "logits = model(x)            # raw logits",
                  "probs = torch.softmax(logits, 1)",
                  "loss = nn.CrossEntropyLoss()(probs, y)",
                  "",
                  "# probs get re-normalised and squeezed,",
                  "# gradients shrink, the loss falls slowly",
                  "# and accuracy stalls.",
                  "# FIX: pass the logits directly",
                  "loss = nn.CrossEntropyLoss()(logits, y)",
              ]}},
         ],
         "note": {"zh": "左边是「怎么选」，右边是「怎么错」。两次 softmax 不会报错，只会让你的准确率莫名其妙地低——这类静默错误比崩溃更难查。",
                  "en": "The left panel is how to choose; the right is how to get it wrong. A double softmax raises no error — it just leaves your accuracy inexplicably low, and silent bugs are harder to find than crashes."}},

        {"type": "compare",
         "title": {"zh": "正确用法 vs 常见坑", "en": "Correct Usage vs Common Pitfalls"},
         "right": MOD,
         "columns": [
             {"title": {"zh": "正确用法", "en": "Correct Usage"}, "accent": "059669",
              "bg": "ECFDF5",
              "items": [
                  {"zh": "损失函数吃原始 logits，不吃概率", "en": "Feed the loss raw logits, not probabilities"},
                  {"zh": "激活函数交给损失内部处理", "en": "Let the loss handle the activation internally"},
                  {"zh": "二分类用 BCEWithLogitsLoss", "en": "Binary tasks use BCEWithLogitsLoss"},
                  {"zh": "标签类型：交叉熵用 long，BCE 用 float", "en": "Labels: long for cross-entropy, float for BCE"},
                  {"zh": "不平衡时用 weight= 传类别权重", "en": "Under imbalance pass class weights via weight="}]},
             {"title": {"zh": "常见坑", "en": "Common Pitfalls"}, "accent": "B91C1C",
              "bg": "FEF2F2",
              "items": [
                  {"zh": "先 softmax 再喂交叉熵 = 做了两次", "en": "Softmax then cross-entropy = done twice"},
                  {"zh": "用 BCEWithLogitsLoss 时又手动 sigmoid", "en": "Adding a manual sigmoid before BCEWithLogitsLoss"},
                  {"zh": "标签忘了转 long / float，直接报错", "en": "Forgetting the long / float cast, which errors out"},
                  {"zh": "把 MSELoss 用在分类任务上", "en": "Using MSELoss for a classification task"},
                  {"zh": "损失一路下降但准确率不动（正是坑 1）", "en": "Loss falls but accuracy is stuck (usually pitfall 1)"}]},
         ],
         "note": {"zh": "记住这条判据：损失在下降、指标却不动，第一反应就去看损失函数前面的那一行有没有多做一次激活。",
                  "en": "Keep this diagnostic: if the loss falls but the metric does not move, first look at the line just above the loss call for a redundant activation."}},

        # -------------------------------------------------- Part 02 (p8-12) --
        {"type": "section", "num": "02",
         "title": {"zh": "优化器：参数怎么更新", "en": "Optimizers: How We Update"},
         "title_en": {"zh": "Optimizer", "en": "Optimizer"},
         "lead": {"zh": "损失函数告诉你「错了多少」，优化器决定「往哪走、走多远」。\n同一套模型、同一份数据，换一个优化器，收敛速度可以差一个数量级。",
                  "en": "The loss tells you how wrong you are; the optimizer decides which way and how far to move.\nSame model, same data — change the optimizer and convergence can differ by an order of magnitude."},
         "pillars": [
             {"title": {"zh": "SGD", "en": "SGD"},
              "sub": {"zh": "只看当前这一步的梯度", "en": "Only the current gradient"}},
             {"title": {"zh": "Momentum", "en": "Momentum"},
              "sub": {"zh": "累积历史方向形成惯性", "en": "Accumulates direction into inertia"}},
             {"title": {"zh": "Adam", "en": "Adam"},
              "sub": {"zh": "每个参数一个自适应步长", "en": "One adaptive step size per parameter"}},
         ]},

        {"type": "cards", "cols": 3, "h": 7.2, "top": 3.6,
         "title": {"zh": "三种优化器：三代思路", "en": "Three Optimizers: Three Generations of Ideas"},
         "right": MOD,
         "cards": [
             {"title": {"zh": "SGD 随机梯度下降", "en": "SGD"},
              "title_en": "one batch, one step",
              "accent": "6B7280", "bg": "F5F7FA",
              "body": [
                  {"zh": "直接用当前批次的梯度更新", "en": "Updates straight from the batch gradient"},
                  {"zh": "只多了学习率一个超参数", "en": "Only one hyper-parameter: the learning rate"},
                  {"zh": "对学习率极敏感，1e-1 就会炸", "en": "Extremely lr-sensitive; 1e-1 blows up"},
                  {"zh": "泛化常略好，但调参成本高", "en": "Generalises well, but costly to tune"}]},
             {"title": {"zh": "SGD + Momentum", "en": "SGD + Momentum"},
              "title_en": "add inertia",
              "accent": "D97706", "bg": "FFFBEB",
              "body": [
                  {"zh": "把历史梯度按动量累加", "en": "Accumulates past gradients with momentum"},
                  {"zh": "沿一致的下降方向越走越快", "en": "Speeds up along a consistent descent direction"},
                  {"zh": "能穿过小的鞍点与噪声", "en": "Can pass through small saddle points and noise"},
                  {"zh": "惯例：momentum = 0.9", "en": "Convention: momentum = 0.9"}]},
             {"title": {"zh": "Adam 自适应矩估计", "en": "Adam"},
              "title_en": "adaptive per-parameter",
              "accent": "059669", "bg": "ECFDF5",
              "body": [
                  {"zh": "同时估计梯度的一阶与二阶矩", "en": "Estimates first and second moments"},
                  {"zh": "每个参数有各自的步长", "en": "Every parameter gets its own step size"},
                  {"zh": "对学习率更宽容，1e-3 通常可跑", "en": "More forgiving: 1e-3 usually works"},
                  {"zh": "代价：多存两份状态，更吃显存", "en": "Cost: two extra state buffers, more VRAM"}]},
         ]},

        {"type": "table",
         "title": {"zh": "优化器对照表", "en": "Optimizer Comparison Table"},
         "right": MOD,
         "cols": [{"zh": "优化器", "en": "Optimizer"},
                  {"zh": "更新规则（直觉）", "en": "Update rule (intuition)"},
                  {"zh": "主要超参数", "en": "Key hyper-parameters"},
                  {"zh": "收敛速度", "en": "Convergence"},
                  {"zh": "典型场景", "en": "Typical use"}],
         "widths": [5.0, 8.4, 5.8, 4.2, 6.0],
         "h": 8.4, "bold_first": True,
         "rows": [
             [{"zh": "SGD", "en": "SGD"},
              {"zh": "沿当前梯度方向走一步", "en": "One step along the current gradient"},
              {"zh": "lr", "en": "lr"},
              {"zh": "慢", "en": "Slow"},
              {"zh": "需要精细调参的经典基线", "en": "A classic baseline when you can afford tuning"}],
             [{"zh": "SGD + Momentum", "en": "SGD + Momentum"},
              {"zh": "累积过去梯度，形成惯性", "en": "Accumulate past gradients into inertia"},
              {"zh": "lr, momentum=0.9", "en": "lr, momentum=0.9"},
              {"zh": "中", "en": "Medium"},
              {"zh": "计算机视觉的常用默认", "en": "A common default in computer vision"}],
             [{"zh": "Adam", "en": "Adam"},
              {"zh": "每参数自适应步长 + 动量", "en": "Adaptive per-parameter step + momentum"},
              {"zh": "lr, betas, eps", "en": "lr, betas, eps"},
              {"zh": "快", "en": "Fast"},
              {"zh": "默认首选、快速原型、稀疏梯度", "en": "First choice, fast prototyping, sparse gradients"}],
             [{"zh": "AdamW", "en": "AdamW"},
              {"zh": "同 Adam，但权重衰减解耦", "en": "Adam with decoupled weight decay"},
              {"zh": "lr, weight_decay", "en": "lr, weight_decay"},
              {"zh": "快", "en": "Fast"},
              {"zh": "Transformer 类模型的标配", "en": "Standard for Transformer-style models"}],
         ],
         "note": {"zh": "注意第二列的措辞——「沿当前梯度走一步」和「每参数自适应步长」，这个差别就是后面 3×3 实验中收敛速度差异的根源。",
                  "en": "Note the wording of column two: \"one step along the current gradient\" versus \"adaptive per-parameter step\" — that difference is exactly the source of the convergence gap in the upcoming 3x3 experiment."}},

        {"type": "code", "top": 3.55, "h": 11.2,
         "title": {"zh": "构造三种优化器并做对照", "en": "Building the Three Optimizers, Side by Side"},
         "right": MOD,
         "blocks": [
             {"title": {"zh": "同一套权重，三种优化器", "en": "Same weights, three optimizers"},
              "code": {"zh": [
                  "import torch",
                  "from torch import nn",
                  "",
                  "model = nn.Sequential(",
                  "    nn.Linear(784, 128),",
                  "    nn.ReLU(),",
                  "    nn.Linear(128, 10))",
                  "",
                  "params = model.parameters()",
                  "opt_sgd = torch.optim.SGD(params, lr=1e-1)",
                  "opt_mom = torch.optim.SGD(params, lr=1e-1,",
                  "                          momentum=0.9)",
                  "opt_adam = torch.optim.Adam(params, lr=1e-3)",
              ],
              "en": [
                  "import torch",
                  "from torch import nn",
                  "",
                  "model = nn.Sequential(",
                  "    nn.Linear(784, 128),",
                  "    nn.ReLU(),",
                  "    nn.Linear(128, 10))",
                  "",
                  "params = model.parameters()",
                  "opt_sgd = torch.optim.SGD(params, lr=1e-1)",
                  "opt_mom = torch.optim.SGD(params, lr=1e-1,",
                  "                          momentum=0.9)",
                  "opt_adam = torch.optim.Adam(params, lr=1e-3)",
              ]}},
             {"title": {"zh": "学习率扫描 1e-1 / 1e-3 / 1e-5", "en": "Sweeping lr = 1e-1 / 1e-3 / 1e-5"},
              "code": {"zh": [
                  "# 学习率扫描：1e-1 / 1e-3 / 1e-5",
                  "for lr in [1e-1, 1e-3, 1e-5]:",
                  "    net = build_model()      # 重新初始化权重",
                  "    opt = make_opt(\"adam\", net, lr)",
                  "    hist = train(net, opt, epochs=10)",
                  "    log.append({\"optim\": \"adam\",",
                  "                \"lr\": lr,",
                  "                \"val_loss\": min(hist[\"val_loss\"])})",
                  "",
                  "# 1e-1 ：损失爆炸 / 震荡",
                  "# 1e-3 ：平稳收敛 —— 从这里开始",
                  "# 1e-5 ：同样的 epoch 还远未收敛",
              ],
              "en": [
                  "# sweep the learning rate: 1e-1 / 1e-3 / 1e-5",
                  "for lr in [1e-1, 1e-3, 1e-5]:",
                  "    net = build_model()      # fresh weights",
                  "    opt = make_opt(\"adam\", net, lr)",
                  "    hist = train(net, opt, epochs=10)",
                  "    log.append({\"optim\": \"adam\",",
                  "                \"lr\": lr,",
                  "                \"val_loss\": min(hist[\"val_loss\"])})",
                  "",
                  "# 1e-1 : loss explodes / oscillates",
                  "# 1e-3 : converges smoothly - start here",
                  "# 1e-5 : still far from converged",
              ]}},
         ],
         "note": {"zh": "对照实验的纪律：每次运行都要重新初始化权重，否则第 2 组吃的是第 1 组已经训练过的权重，比较结果无效。",
                  "en": "Discipline for a controlled experiment: rebuild the model every run, or run 2 inherits weights already trained by run 1 and the comparison is void."}},

        {"type": "compare",
         "title": {"zh": "SGD 与 Adam：两种性格", "en": "SGD and Adam: Two Personalities"},
         "right": MOD,
         "columns": [
             {"title": {"zh": "SGD + Momentum", "en": "SGD + Momentum"}, "accent": "1E4FA8",
              "bg": "F0F5FC",
              "items": [
                  {"zh": "每步只用一个批次的梯度", "en": "Each step uses only one batch of gradients"},
                  {"zh": "动量让方向更稳、更快", "en": "Momentum makes the direction steadier and faster"},
                  {"zh": "对学习率极其敏感，1e-1 直接爆炸", "en": "Very lr-sensitive; 1e-1 simply explodes"},
                  {"zh": "最终泛化常略好，但需要调参功夫", "en": "Usually generalises a little better, at a tuning cost"},
                  {"zh": "计算机视觉里的经典默认", "en": "The classic default in computer vision"}]},
             {"title": {"zh": "Adam", "en": "Adam"}, "accent": "059669",
              "bg": "ECFDF5",
              "items": [
                  {"zh": "每个参数一个自适应步长", "en": "Every parameter gets an adaptive step size"},
                  {"zh": "对学习率更宽容，1e-3 通常能跑", "en": "More forgiving; 1e-3 usually runs"},
                  {"zh": "前期收敛快，适合快速拿到基线", "en": "Converges fast early — good for a quick baseline"},
                  {"zh": "多存两份状态，显存占用更高", "en": "Two extra state buffers, so more VRAM"},
                  {"zh": "Transformer 类模型的首选", "en": "First choice for Transformer-style models"}]},
         ],
         "note": {"zh": "选择策略：先用 Adam(lr=1e-3) 拿到一个能跑通的基线，再用 SGD+momentum 精调。但「哪个更好」这个结论，必须来自你自己跑出来的对照实验，而不是这一页。",
                  "en": "Strategy: get a working baseline with Adam(lr=1e-3) first, then refine with SGD+momentum. But the verdict on which is better must come from your own experiment, not from this slide."}},

        # -------------------------------------------------- Part 03 (p13-15) -
        {"type": "section", "num": "03",
         "title": {"zh": "学习率：最重要的超参数", "en": "Learning Rate: The First Hyper-parameter"},
         "title_en": {"zh": "Learning rate", "en": "Learning rate"},
         "lead": {"zh": "学习率决定每一步走多远。它大到一定程度会让损失爆炸，小到一定程度会让训练看起来「没在学」。\n看到异常损失，第一个要查的就是它。",
                  "en": "The learning rate is how far each step goes. Too large and the loss explodes; too small and training looks like it is learning nothing.\nWhen a loss looks wrong, this is the first thing to inspect."},
         "pillars": [
             {"title": {"zh": "过大", "en": "Too Large"},
              "sub": {"zh": "震荡、爆炸、出现 nan", "en": "Oscillation, explosion, nan"}},
             {"title": {"zh": "过小", "en": "Too Small"},
              "sub": {"zh": "损失几乎不动", "en": "The loss barely moves"}},
             {"title": {"zh": "先查它", "en": "Check It First"},
              "sub": {"zh": "异常损失的第一嫌疑", "en": "Prime suspect for a broken loss"}},
         ]},

        {"type": "cards", "cols": 3, "h": 6.4, "top": 3.6,
         "title": {"zh": "学习率：症状与策略", "en": "Learning Rate: Symptoms and Schedules"},
         "right": MOD,
         "cards": [
             {"title": {"zh": "过大：跳过了谷底", "en": "Too Large: Overshooting"},
              "title_en": "lr=1e-1",
              "accent": "B91C1C", "bg": "FEF2F2",
              "body": [
                  {"zh": "损失上下震荡，根本不下降", "en": "The loss oscillates and never descends"},
                  {"zh": "很快出现 nan 或 inf", "en": "nan or inf appears quickly"},
                  {"zh": "处置：先把学习率除以 10", "en": "Fix: divide the learning rate by 10"},
                  {"zh": "现象：准确率停在随机水平", "en": "Symptom: accuracy stays at chance level"}]},
             {"title": {"zh": "过小：在原地磨", "en": "Too Small: Crawling"},
              "title_en": "lr=1e-5",
              "accent": "D97706", "bg": "FFFBEB",
              "body": [
                  {"zh": "10 个 epoch 损失变化不到 0.05", "en": "Loss moves less than 0.05 in 10 epochs"},
                  {"zh": "看起来在训练，其实几乎没动", "en": "It looks like training but is barely moving"},
                  {"zh": "处置：升 10 倍再试一次", "en": "Fix: try 10x larger once"},
                  {"zh": "别用「加 epoch」掩盖它", "en": "Do not mask it by adding epochs"}]},
             {"title": {"zh": "策略：三段式", "en": "Schedule: Three Phases"},
              "title_en": "warmup + decay",
              "accent": "059669", "bg": "ECFDF5",
              "body": [
                  {"zh": "Warmup：前几个 epoch 从小到大", "en": "Warmup: ramp up over the first epochs"},
                  {"zh": "中期：StepLR 每 N 轮衰减一次", "en": "Middle: StepLR decays every N epochs"},
                  {"zh": "后期：CosineAnnealing 平滑退火", "en": "Late: CosineAnnealing anneals smoothly"},
                  {"zh": "PyTorch 里用 lr_scheduler 实现", "en": "Implemented with lr_scheduler in PyTorch"}]},
         ]},

        {"type": "chart", "w": 19.0, "h": 11.8,
         "title": {"zh": "学习率诊断：同一模型、同一数据，只改 lr",
                   "en": "Diagnosing lr: Same Model, Same Data, Only lr Changes"},
         "right": MOD,
         "categories": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
         "x_label": {"zh": "训练轮次 Epoch →", "en": "Epoch →"},
         "y_label": {"zh": "训练损失 Train loss", "en": "Train loss"},
         "y_max": 2.8,
         "series": [
             {"name": {"zh": "lr = 1e-1（过大）", "en": "lr = 1e-1 (too large)"},
              "color": "B91C1C", "emphasis": True,
              "values": [2.30, 2.58, 2.09, 2.64, 2.04, 2.71, 2.16, 2.56, 2.22, 2.67]},
             {"name": {"zh": "lr = 1e-3（合适）", "en": "lr = 1e-3 (about right)"},
              "color": "059669",
              "values": [2.30, 1.62, 1.05, 0.72, 0.51, 0.38, 0.30, 0.25, 0.22, 0.20]},
             {"name": {"zh": "lr = 1e-5（过小）", "en": "lr = 1e-5 (too small)"},
              "color": "6B7280",
              "values": [2.30, 2.28, 2.26, 2.24, 2.22, 2.20, 2.18, 2.16, 2.14, 2.12]},
         ],
         "notes": [
             {"zh": "红线上下震荡、始终不降 → 学习率过大",
              "en": "The red line oscillates and never descends → lr too large"},
             {"zh": "灰线几乎水平 → 学习率过小（不是模型不行）",
              "en": "The grey line is almost flat → lr too small (not a weak model)"},
             {"zh": "绿线单调平稳下降 → 这才是可以继续加 epoch 的状态",
              "en": "The green line falls steadily → this is the state where more epochs help"},
             {"zh": "实验 4 要求你亲手跑出这三条线，而不是照抄",
              "en": "Lab 4 requires you to produce these three curves yourself, not copy them"}],
        },

        # -------------------------------------------------- Part 04 (p16-20) -
        {"type": "section", "num": "04",
         "title": {"zh": "训练循环五步法", "en": "The Five-Step Training Loop"},
         "title_en": {"zh": "Training loop", "en": "Training loop"},
         "lead": {"zh": "再复杂的训练脚本，内核都是这五步。把它背下来，你就能读懂任何一份 PyTorch 代码。\n这一部分的目标不是「看懂」，而是「默写出来」。",
                  "en": "However complex a training script looks, its core is these five steps. Memorise them and you can read any PyTorch code.\nThe goal here is not to recognise it, but to reproduce it from memory."},
         "pillars": [
             {"title": {"zh": "顺序不能错", "en": "Order Matters"},
              "sub": {"zh": "尤其是第 1 步", "en": "Especially step 1"}},
             {"title": {"zh": "先默写再对照", "en": "Write, Then Check"},
              "sub": {"zh": "先合上讲义写一遍", "en": "Close the slides and write it first"}},
             {"title": {"zh": "留下日志", "en": "Leave a Log"},
              "sub": {"zh": "每个 epoch 一行", "en": "One row per epoch"}},
         ]},

        {"type": "flow", "y": 5.6, "h": 6.4,
         "title": {"zh": "训练循环五步法", "en": "The Five Steps of a Training Loop"},
         "right": MOD,
         "steps": [
             {"title": {"zh": "清零梯度", "en": "Zero Grads"},
              "title_en": "zero_grad()",
              "accent": "6B7280",
              "desc": {"zh": "清掉上一批的旧梯度，\n否则会累加",
                       "en": "Clear the previous batch's\ngradients or they accumulate"}},
             {"title": {"zh": "前向传播", "en": "Forward"},
              "title_en": "logits = model(x)",
              "accent": "1E4FA8",
              "desc": {"zh": "把本批数据喂进模型，\n得到预测",
                       "en": "Feed the batch through\nthe model to get predictions"}},
             {"title": {"zh": "计算损失", "en": "Loss"},
              "title_en": "criterion(logits, y)",
              "accent": "3D7BD9",
              "desc": {"zh": "用选定的损失函数\n给预测打分",
                       "en": "Score the prediction with\nthe chosen loss function"}},
             {"title": {"zh": "反向传播", "en": "Backward"},
              "title_en": "loss.backward()",
              "accent": "D97706",
              "desc": {"zh": "求每个参数对损失的\n梯度",
                       "en": "Compute the gradient of the loss\nfor every parameter"}},
             {"title": {"zh": "更新参数", "en": "Step"},
              "title_en": "optimizer.step()",
              "accent": "059669",
              "desc": {"zh": "优化器按梯度\n走一步",
                       "en": "The optimizer takes\none step along the gradient"}},
         ],
         "note": {"zh": "课堂做法：先合上讲义，把五步默写在自己的本子上，写清每一步的括号与顺序，再对照这一页。第 1 步最常被漏掉——漏掉它，梯度会跨批次累加，损失曲线会变得毫无规律。",
                  "en": "In class: close the slides, write the five steps from memory with their exact calls and order, then compare with this page. Step 1 is the one people drop — drop it and gradients accumulate across batches, making the loss curve look random."}},

        {"type": "code", "top": 3.55, "h": 11.2,
         "title": {"zh": "完整训练循环与训练日志", "en": "A Complete Training Loop and Its Log"},
         "right": MOD,
         "blocks": [
             {"title": {"zh": "五步法：完整循环", "en": "The five steps, complete loop"},
              "code": {"zh": [
                  "for epoch in range(epochs):",
                  "    model.train()",
                  "    for x, y in train_loader:",
                  "        opt.zero_grad()       # 1 清零旧梯度",
                  "        logits = model(x)     # 2 前向传播",
                  "        loss = crit(logits, y)  # 3 计算损失",
                  "        loss.backward()       # 4 反向传播",
                  "        opt.step()            # 5 更新参数",
                  "",
                  "# 五步的顺序不可交换：",
                  "# 1 必须在 4 之前，否则梯度跨批次累加。",
              ],
              "en": [
                  "for epoch in range(epochs):",
                  "    model.train()",
                  "    for x, y in train_loader:",
                  "        opt.zero_grad()       # 1 clear old grads",
                  "        logits = model(x)     # 2 forward pass",
                  "        loss = crit(logits, y)  # 3 compute loss",
                  "        loss.backward()       # 4 backpropagate",
                  "        opt.step()            # 5 update weights",
                  "",
                  "# The order is not interchangeable:",
                  "# 1 must precede 4 or grads accumulate.",
              ]}},
             {"title": {"zh": "训练日志：每轮一行", "en": "Logging: one row per epoch"},
              "code": {"zh": [
                  "history = []",
                  "for epoch in range(epochs):",
                  "    tr = train_epoch(model, loader, opt, crit)",
                  "    va, acc = evaluate(model, val_loader, crit)",
                  "    history.append({          # 每个 epoch 一行",
                  "        \"epoch\": epoch,",
                  "        \"train_loss\": round(tr, 4),",
                  "        \"val_loss\": round(va, 4),",
                  "        \"val_acc\": round(acc, 4)})",
                  "    print(history[-1])",
                  "",
                  "# 训练损失降、验证损失升 -> 过拟合",
                  "# 两条都平着不动 -> 学习率太小",
              ],
              "en": [
                  "history = []",
                  "for epoch in range(epochs):",
                  "    tr = train_epoch(model, loader, opt, crit)",
                  "    va, acc = evaluate(model, val_loader, crit)",
                  "    history.append({          # one row per epoch",
                  "        \"epoch\": epoch,",
                  "        \"train_loss\": round(tr, 4),",
                  "        \"val_loss\": round(va, 4),",
                  "        \"val_acc\": round(acc, 4)})",
                  "    print(history[-1])",
                  "",
                  "# train loss down, val loss up -> overfitting",
                  "# both flat -> learning rate too small",
              ]}},
         ],
         "note": {"zh": "日志不是形式主义：没有 train/val 两条曲线，你就无法判断是过拟合、学习率太小，还是数据有问题——只能靠猜。",
                  "en": "A log is not bureaucracy: without both train and val curves you cannot tell overfitting from a too-small learning rate from a data problem — you can only guess."}},

        {"type": "table",
         "title": {"zh": "批大小与显存的关系", "en": "Batch Size and VRAM"},
         "right": MOD,
         "cols": [{"zh": "批大小", "en": "Batch size"},
                  {"zh": "显存占用", "en": "VRAM"},
                  {"zh": "梯度稳定性", "en": "Gradient stability"},
                  {"zh": "常见取舍", "en": "Trade-off"}],
         "widths": [5.4, 6.2, 8.6, 9.2],
         "h": 8.0, "bold_first": True,
         "rows": [
             [{"zh": "8 – 32", "en": "8 - 32"},
              {"zh": "低", "en": "Low"},
              {"zh": "噪声大，偶尔有益于泛化", "en": "Noisy; occasionally helps generalisation"},
              {"zh": "显存小或数据集小；需更小的学习率", "en": "Small VRAM or small data; needs a smaller lr"}],
             [{"zh": "64 – 256", "en": "64 - 256"},
              {"zh": "中", "en": "Medium"},
              {"zh": "较稳定", "en": "Reasonably stable"},
              {"zh": "最常用的默认区间，先从这里开始", "en": "The usual default range — start here"}],
             [{"zh": "512 以上", "en": "512+"},
              {"zh": "高", "en": "High"},
              {"zh": "很稳定，但泛化可能变差", "en": "Very stable, but can generalise worse"},
              {"zh": "需配合更大学习率与 warmup", "en": "Needs a larger lr and warmup"}],
             [{"zh": "1（单样本）", "en": "1 (per-sample)"},
              {"zh": "最低，但速度极慢", "en": "Lowest, but extremely slow"},
              {"zh": "噪声极大", "en": "Extremely noisy"},
              {"zh": "仅用于教学演示或显存极限", "en": "Only for teaching demos or extreme memory limits"}],
         ],
         "note": {"zh": "一条经验公式：显存 ≈ 批大小 × 单样本开销 + 模型参数 + 优化器状态（Adam 的优化器状态约为参数量的 2 倍，这就是 Adam 比 SGD 更吃显存的原因）。批大小翻倍时，学习率通常也同步放大。",
                  "en": "A useful estimate: VRAM ≈ batch size x per-sample cost + parameters + optimizer state (Adam's state is roughly twice the parameter count, which is why it costs more than SGD). When you double the batch size, you usually scale the learning rate up with it."}},

        # -------------------------------------------------- Part 05 (p21-27) -
        {"type": "section", "num": "05",
         "title": {"zh": "Lab · 实验 4 优化器 × 学习率", "en": "Lab · Optimizers × Learning Rates"},
         "title_en": {"zh": "Hands-on: a 3 x 3 controlled experiment",
                     "en": "Hands-on: a 3 x 3 controlled experiment"},
         "lead": {"zh": "75 分钟，亲手做一次真正的对照实验：3 种优化器 × 3 组学习率 = 9 次运行，\n然后回答一个必须用数据支撑的问题——哪一个组合最好，为什么。",
                  "en": "75 minutes for a real controlled experiment: 3 optimizers x 3 learning rates = 9 runs,\nthen answer a question that must be backed by data — which combination wins, and why."},
         "pillars": [
             {"title": {"zh": "9 次运行", "en": "9 Runs"},
              "sub": {"zh": "一次只改一个变量", "en": "One variable at a time"}},
             {"title": {"zh": "画出曲线", "en": "Plot It"},
              "sub": {"zh": "损失 + 准确率", "en": "Loss + accuracy"}},
             {"title": {"zh": "给出理由", "en": "Justify It"},
              "sub": {"zh": "最优组合必须有论证", "en": "The winner needs an argument"}},
         ]},

        {"type": "cards", "cols": 2, "h": 6.6, "top": 3.6,
         "title": {"zh": "实验 4 的四个任务", "en": "The Four Tasks of Lab 4"},
         "right": MOD,
         "cards": [
             {"title": {"zh": "A · 3 × 3 网格实验", "en": "A · The 3 x 3 grid"},
              "title_en": "9 runs, one variable at a time",
              "body": [
                  {"zh": "3 种优化器：SGD / SGD+momentum / Adam",
                   "en": "3 optimizers: SGD / SGD+momentum / Adam"},
                  {"zh": "3 组学习率：1e-1 / 1e-3 / 1e-5",
                   "en": "3 learning rates: 1e-1 / 1e-3 / 1e-5"},
                  {"zh": "同一网络、同一划分、同一随机种子",
                   "en": "Same network, same split, same seed"},
                  {"zh": "每次重新初始化权重，记录 train/val 指标",
                   "en": "Rebuild the model each run; log train/val metrics"}]},
             {"title": {"zh": "B · 绘制损失与准确率曲线", "en": "B · Plot the curves"},
              "title_en": "loss and accuracy, every run",
              "body": [
                  {"zh": "每个组合一条曲线，图例标注优化器与 lr",
                   "en": "One curve per combo, legend names optimizer and lr"},
                  {"zh": "损失曲线看收敛速度与稳定性",
                   "en": "The loss curve shows speed and stability"},
                  {"zh": "准确率曲线看最终质量与是否震荡",
                   "en": "The accuracy curve shows final quality and jitter"},
                  {"zh": "至少画一张 3 条曲线同坐标系的对比图",
                   "en": "Plot at least one chart with 3 curves on shared axes"}]},
             {"title": {"zh": "C · 给出最优组合并论证", "en": "C · Name the winner and argue it"},
              "title_en": "data, not preference",
              "body": [
                  {"zh": "明确写出最优组合（优化器 + 学习率）",
                   "en": "State the best combo (optimizer + learning rate)"},
                  {"zh": "用验证指标支撑：最低损失、最高准确率",
                   "en": "Back it with val metrics: lowest loss, highest accuracy"},
                  {"zh": "解释它为什么胜出：自适应步长？动量？步长刚好？",
                   "en": "Explain why it wins: adaptive step? momentum? the right size?"},
                  {"zh": "指出失败组合及其直接现象（爆炸 / 不动）",
                   "en": "Name the failing combos and their symptom (explode / crawl)"}]},
             {"title": {"zh": "D · 记录一次不收敛的排查", "en": "D · One debugging log"},
              "title_en": "hypothesis → test → conclusion",
              "body": [
                  {"zh": "选一个失败组合，按「先查学习率」的顺序排查",
                   "en": "Pick a failing combo and start by checking the lr"},
                  {"zh": "再查数据（标签、归一化、划分）与代码（五步顺序）",
                   "en": "Then data (labels, scaling, split) and code (step order)"},
                  {"zh": "记录每一步的假设、验证方式与结论",
                   "en": "Record each hypothesis, how you tested it, the conclusion"},
                  {"zh": "交付：脚本 + 对照表 + 曲线图 + 排查记录",
                   "en": "Deliver: script + table + curves + debugging log"}]},
         ]},

        {"type": "chart", "w": 19.0, "h": 12.0,
         "title": {"zh": "3 种优化器 × 3 组学习率：验证损失曲线示意图",
                   "en": "3 Optimizers x 3 Learning Rates: Illustrative Val-loss Curves"},
         "right": MOD,
         "categories": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
         "x_label": {"zh": "训练轮次 Epoch →", "en": "Epoch →"},
         "y_label": {"zh": "验证损失 Val loss", "en": "Val loss"},
         "y_max": 2.8,
         "series": [
             {"name": {"zh": "SGD · lr=1e-1（发散）", "en": "SGD · lr=1e-1 (diverges)"},
              "color": "B91C1C",
              "values": [2.30, 2.48, 2.36, 2.55, 2.30, 2.60, 2.34, 2.52, 2.31, 2.58]},
             {"name": {"zh": "SGD · lr=1e-3（过慢）", "en": "SGD · lr=1e-3 (too slow)"},
              "color": "6B7280",
              "values": [2.30, 2.21, 2.12, 2.03, 1.94, 1.86, 1.78, 1.70, 1.63, 1.56]},
             {"name": {"zh": "Momentum · lr=1e-3（良好）", "en": "Momentum · lr=1e-3 (good)"},
              "color": "D97706",
              "values": [2.30, 1.70, 1.15, 0.80, 0.58, 0.44, 0.35, 0.29, 0.25, 0.22]},
             {"name": {"zh": "Adam · lr=1e-3（最优）", "en": "Adam · lr=1e-3 (best)"},
              "color": "059669", "emphasis": True,
              "values": [2.30, 1.35, 0.78, 0.48, 0.33, 0.24, 0.19, 0.16, 0.14, 0.13]},
         ],
         "notes": [
             {"zh": "1e-1 下无论哪个优化器都不收敛 → 学习率是主导变量",
              "en": "At 1e-1 no optimizer converges → the lr dominates everything else"},
             {"zh": "同样 lr=1e-3，Adam 明显快于 SGD → 自适应步长的作用",
              "en": "At the same lr=1e-3 Adam is clearly faster than SGD → adaptive steps at work"},
             {"zh": "Momentum 位于两者之间 → 动量只加速，不改变步长尺度",
              "en": "Momentum sits between them → inertia accelerates, it does not rescale"},
             {"zh": "图中数值仅作示意；以你自己跑出的 9 组实测为准",
              "en": "These numbers are illustrative only; your own 9 runs are the evidence"}],
        },

        {"type": "table",
         "title": {"zh": "超参数对照表（9 组，学生填写）", "en": "Hyper-parameter Comparison Table (9 runs, to be filled in)"},
         "right": MOD,
         "cols": [{"zh": "组合", "en": "#"},
                  {"zh": "优化器", "en": "Optimizer"},
                  {"zh": "学习率", "en": "lr"},
                  {"zh": "最低验证损失", "en": "Min val loss"},
                  {"zh": "最高验证准确率", "en": "Max val acc"},
                  {"zh": "是否收敛", "en": "Converged?"}],
         "widths": [3.2, 5.8, 3.6, 5.4, 5.2, 6.2],
         "h": 11.0, "bold_first": True,
         "body_size": 10.5, "head_size": 11.5,
         "rows": [
             [{"zh": "1", "en": "1"}, {"zh": "SGD", "en": "SGD"}, {"zh": "1e-1", "en": "1e-1"},
              {"zh": "2.31（发散）", "en": "2.31 (diverged)"}, {"zh": "0.10", "en": "0.10"},
              {"zh": "否", "en": "No"}],
             [{"zh": "2", "en": "2"}, {"zh": "SGD", "en": "SGD"}, {"zh": "1e-3", "en": "1e-3"},
              {"zh": "1.56", "en": "1.56"}, {"zh": "0.62", "en": "0.62"},
              {"zh": "太慢", "en": "Too slow"}],
             [{"zh": "3", "en": "3"}, {"zh": "SGD", "en": "SGD"}, {"zh": "1e-5", "en": "1e-5"},
              {"zh": "2.28", "en": "2.28"}, {"zh": "0.11", "en": "0.11"},
              {"zh": "否", "en": "No"}],
             [{"zh": "4", "en": "4"}, {"zh": "Momentum", "en": "Momentum"}, {"zh": "1e-1", "en": "1e-1"},
              {"zh": "2.44（震荡）", "en": "2.44 (oscillates)"}, {"zh": "0.10", "en": "0.10"},
              {"zh": "否", "en": "No"}],
             [{"zh": "5", "en": "5"}, {"zh": "Momentum", "en": "Momentum"}, {"zh": "1e-3", "en": "1e-3"},
              {"zh": "0.22", "en": "0.22"}, {"zh": "0.94", "en": "0.94"},
              {"zh": "是", "en": "Yes"}],
             [{"zh": "6", "en": "6"}, {"zh": "Momentum", "en": "Momentum"}, {"zh": "1e-5", "en": "1e-5"},
              {"zh": "2.19", "en": "2.19"}, {"zh": "0.24", "en": "0.24"},
              {"zh": "太慢", "en": "Too slow"}],
             [{"zh": "7", "en": "7"}, {"zh": "Adam", "en": "Adam"}, {"zh": "1e-1", "en": "1e-1"},
              {"zh": "2.51（爆炸）", "en": "2.51 (exploded)"}, {"zh": "0.10", "en": "0.10"},
              {"zh": "否", "en": "No"}],
             [{"zh": "8", "en": "8"}, {"zh": "Adam", "en": "Adam"}, {"zh": "1e-3", "en": "1e-3"},
              {"zh": "0.13", "en": "0.13"}, {"zh": "0.97", "en": "0.97"},
              {"zh": "是（最优）", "en": "Yes (best)"}],
             [{"zh": "9", "en": "9"}, {"zh": "Adam", "en": "Adam"}, {"zh": "1e-5", "en": "1e-5"},
              {"zh": "1.98", "en": "1.98"}, {"zh": "0.45", "en": "0.45"},
              {"zh": "太慢", "en": "Too slow"}],
         ],
         "note": {"zh": "表里的数值是示意，你的任务是用自己跑出来的 9 组数据替换它。表填完，最优组合与理由自然就浮出来了——这就是「调参不是碰运气」的意思。",
                  "en": "The numbers here are illustrative; your job is to replace them with the nine runs you measured. Once the table is complete the winner and its justification fall out of it — that is what \"tuning is not luck\" means."}},

        {"type": "code", "top": 3.55, "h": 11.2,
         "title": {"zh": "实验脚本骨架与不收敛排查", "en": "Lab Script Skeleton and a Debug Helper"},
         "right": MOD,
         "blocks": [
             {"title": {"zh": "3 × 3 网格，结果落表", "en": "The 3 x 3 grid, results to a table"},
              "code": {"zh": [
                  "results = []                 # 每次运行一行",
                  "for name in [\"sgd\", \"momentum\", \"adam\"]:",
                  "    for lr in [1e-1, 1e-3, 1e-5]:",
                  "        net = build_model()",
                  "        opt = make_opt(name, net, lr)",
                  "        hist = train(net, opt, epochs=10)",
                  "        results.append({\"optimizer\": name,",
                  "                        \"lr\": lr,",
                  "                        \"val_loss\": min(hist[\"vl\"]),",
                  "                        \"val_acc\": max(hist[\"va\"])})",
                  "",
                  "plot_curves(results)         # 损失 / 准确率曲线",
                  "write_table(results)         # 3x3 对照表",
                  "# 然后：写出最优组合并解释它为什么胜出",
              ],
              "en": [
                  "results = []                 # one row per run",
                  "for name in [\"sgd\", \"momentum\", \"adam\"]:",
                  "    for lr in [1e-1, 1e-3, 1e-5]:",
                  "        net = build_model()",
                  "        opt = make_opt(name, net, lr)",
                  "        hist = train(net, opt, epochs=10)",
                  "        results.append({\"optimizer\": name,",
                  "                        \"lr\": lr,",
                  "                        \"val_loss\": min(hist[\"vl\"]),",
                  "                        \"val_acc\": max(hist[\"va\"])})",
                  "",
                  "plot_curves(results)         # loss / acc curves",
                  "write_table(results)         # the 3x3 table",
                  "# then: state the best combo AND why it wins",
              ]}},
             {"title": {"zh": "不收敛时的排查顺序", "en": "Debug order when the loss will not fall"},
              "size": 10,
              "code": {"zh": [
                  "def diagnose(hist):",
                  "    first, last = hist[0], hist[-1]",
                  "    if math.isnan(last[\"train_loss\"]):",
                  "        return \"损失是 nan -> 学习率太大\"",
                  "    if last[\"train_loss\"] > first[\"train_loss\"]:",
                  "        return \"损失在升 -> 降低学习率\"",
                  "    if abs(last[\"train_loss\"]",
                  "           - first[\"train_loss\"]) < 0.05:",
                  "        return \"几乎不动 -> 学习率太小\"",
                  "    return \"正在下降 -> 再看验证曲线\"",
              ],
              "en": [
                  "def diagnose(hist):",
                  "    first, last = hist[0], hist[-1]",
                  "    if math.isnan(last[\"train_loss\"]):",
                  "        return \"nan -> learning rate too large\"",
                  "    if last[\"train_loss\"] > first[\"train_loss\"]:",
                  "        return \"rising -> lower the learning rate\"",
                  "    if abs(last[\"train_loss\"]",
                  "           - first[\"train_loss\"]) < 0.05:",
                  "        return \"flat -> learning rate too small\"",
                  "    return \"falling -> now check the val curve\"",
              ]}},
         ],
         "note": {"zh": "左侧脚本的正确性标准：同一份代码可以跑出 9 组结果，且每组只改动优化器与学习率两个变量。右侧的顺序就是「训练不收敛」排查记录里应该写的顺序：先查学习率，再查数据，最后查代码。",
                  "en": "The left script is correct when the same code produces all nine results while only the optimizer and the learning rate change. The right-hand order is exactly what your \"training does not converge\" log should record: learning rate first, then data, then code."}},

        {"type": "cards", "cols": 3, "h": 6.6, "top": 3.6,
         "title": {"zh": "AI 赋能 · 课程思政 · 排查提示", "en": "AI Assistance · Professional Rigour · Debugging Hints"},
         "right": MOD,
         "cards": [
             {"title": {"zh": "AI 赋能：让 AI 提方案", "en": "AI Assistance"},
              "title_en": "propose, then verify",
              "accent": "1E4FA8", "bg": "F0F5FC",
              "body": [
                  {"zh": "让 AI 给出 3 组优化器与学习率组合",
                   "en": "Ask AI: 3 optimizer x lr combos"},
                  {"zh": "逐组用自己的对照实验验证",
                   "en": "Verify each one with your own run"},
                  {"zh": "记下 AI 哪些说法缺乏依据",
                   "en": "Log where the AI had no basis"}]},
             {"title": {"zh": "课程思政：精益求精", "en": "Professional Rigour"},
              "title_en": "rigour, not luck",
              "accent": "059669", "bg": "ECFDF5",
              "body": [
                  {"zh": "调参是实验设计，不是碰运气",
                   "en": "Tuning is experimental design, not luck"},
                  {"zh": "一次只改一个变量",
                   "en": "Change one variable at a time"},
                  {"zh": "异常先查学习率，再查数据与代码",
                   "en": "Odd results: lr, then data, then code"}]},
             {"title": {"zh": "排查提示", "en": "Debugging Hints"},
              "title_en": "check in this order",
              "accent": "D97706", "bg": "FFFBEB",
              "body": [
                  {"zh": "损失为 nan / inf：学习率太大，先除以 10",
                   "en": "nan / inf -> lr too large, divide by 10"},
                  {"zh": "损失几乎不动：学习率太小或层被冻结",
                   "en": "Barely moving -> lr too small"},
                  {"zh": "损失降但准确率不动：多做了一次激活",
                   "en": "Accuracy stalls -> an extra activation"}]},
         ]},

        {"type": "checklist", "top": 3.55, "h": 2.15,
         "title": {"zh": "实验 4 提交清单", "en": "Lab 4 Submission Checklist"},
         "right": MOD,
         "items": [
             {"badge": {"zh": "必交", "en": "MUST"}, "accent": "1E4FA8",
              "title": {"zh": "训练脚本（含可复现命令）", "en": "Training script with a reproducible command"},
              "desc": {"zh": "同一份脚本可以跑出全部 9 组结果；README 里给出可直接粘贴的运行命令。",
                       "en": "One script produces all nine runs, and the README gives a command you can paste and run."}},
             {"badge": {"zh": "必交", "en": "MUST"}, "accent": "1E4FA8",
              "title": {"zh": "3 × 3 超参数对照表", "en": "The 3 x 3 hyper-parameter table"},
              "desc": {"zh": "9 组各一行：优化器、学习率、最低验证损失、最高验证准确率、是否收敛。",
                       "en": "Nine rows: optimizer, lr, minimum val loss, maximum val accuracy, converged or not."}},
             {"badge": {"zh": "必交", "en": "MUST"}, "accent": "1E4FA8",
              "title": {"zh": "损失 / 准确率曲线图", "en": "Loss / accuracy curves"},
              "desc": {"zh": "至少一张 3 条以上曲线同坐标系的对比图，图例写清优化器与学习率。",
                       "en": "At least one chart with three or more curves on shared axes, labelled with optimizer and lr."}},
             {"badge": {"zh": "必交", "en": "MUST"}, "accent": "1E4FA8",
              "title": {"zh": "一次「训练不收敛」的排查记录", "en": "One \"does not converge\" debugging log"},
              "desc": {"zh": "写明现象、假设、验证方式与结论；顺序是先查学习率，再查数据与代码。",
                       "en": "Symptom, hypothesis, how you tested it, conclusion — lr first, then data, then code."}},
             {"badge": {"zh": "加分", "en": "BONUS"}, "accent": "059669",
              "title": {"zh": "AI 协同记录（写清 AI 错在哪）", "en": "AI collaboration trace (stating where AI was wrong)"},
              "desc": {"zh": "记录 AI 给出的一条超参数建议，以及你的对照实验证明它是否成立。",
                       "en": "Record one hyper-parameter suggestion from AI and the controlled run that confirmed or refuted it."}},
         ]},

        # ------------------------------------------------------ quiz (p27) --
        {"type": "quiz", "cols": 2,
         "title": {"zh": "随堂小测", "en": "Quick Check"},
         "right": MOD,
         "questions": [
             {"tag": {"zh": "损失", "en": "Loss"},
              "q": {"zh": "10 类图像分类任务，应该用哪个损失函数？",
                    "en": "A 10-class image classification task: which loss?"},
              "options": [{"zh": "A. nn.MSELoss", "en": "A. nn.MSELoss"},
                          {"zh": "B. nn.CrossEntropyLoss（内含 softmax）", "en": "B. nn.CrossEntropyLoss (softmax inside)"},
                          {"zh": "C. nn.BCEWithLogitsLoss", "en": "C. nn.BCEWithLogitsLoss"}]},
             {"tag": {"zh": "常见坑", "en": "Pitfall"},
              "q": {"zh": "先 torch.softmax(logits) 再喂 CrossEntropyLoss，会发生什么？",
                    "en": "Softmax the logits, then feed CrossEntropyLoss. What happens?"},
              "options": [{"zh": "A. 完全没有影响", "en": "A. No effect at all"},
                          {"zh": "B. 等于做了两次 softmax，概率被压扁、梯度变小", "en": "B. Softmax twice: probabilities squeezed, gradients shrink"},
                          {"zh": "C. 程序立刻报错", "en": "C. It raises an error immediately"}]},
             {"tag": {"zh": "优化器", "en": "Optimizer"},
              "q": {"zh": "下面哪个说法是正确的？", "en": "Which statement is correct?"},
              "options": [{"zh": "A. Adam 不需要设置学习率", "en": "A. Adam needs no learning rate"},
                          {"zh": "B. Momentum 累积历史梯度方向，形成惯性", "en": "B. Momentum accumulates past gradients into inertia"},
                          {"zh": "C. SGD 一定比 Adam 收敛快", "en": "C. SGD always converges faster than Adam"}]},
             {"tag": {"zh": "学习率", "en": "Learning rate"},
              "q": {"zh": "训练损失在第一轮就变成 nan，第一步应该查什么？",
                    "en": "The loss becomes nan in epoch 1. What do you check first?"},
              "options": [{"zh": "A. 换一个更深的模型", "en": "A. Switch to a deeper model"},
                          {"zh": "B. 学习率是不是太大", "en": "B. Whether the learning rate is too large"},
                          {"zh": "C. 增加训练轮次", "en": "C. Add more epochs"}]},
             {"tag": {"zh": "五步法", "en": "Five steps"},
              "q": {"zh": "训练循环五步的正确顺序是？", "en": "What is the correct order of the five steps?"},
              "options": [{"zh": "A. 前向 → 清零 → 损失 → 反向 → 更新", "en": "A. forward → zero → loss → backward → step"},
                          {"zh": "B. 清零 → 前向 → 损失 → 反向 → 更新", "en": "B. zero → forward → loss → backward → step"},
                          {"zh": "C. 清零 → 损失 → 前向 → 更新 → 反向", "en": "C. zero → loss → forward → step → backward"}]},
             {"tag": {"zh": "批大小", "en": "Batch size"},
              "q": {"zh": "把批大小从 64 增加到 512，通常需要同时做什么？",
                    "en": "Raising the batch size from 64 to 512 usually requires what?"},
              "options": [{"zh": "A. 同步放大学习率，并注意显存是否够", "en": "A. Scale the learning rate up and check that VRAM fits"},
                          {"zh": "B. 同步缩小学习率", "en": "B. Scale the learning rate down"},
                          {"zh": "C. 与学习率无关，只影响速度", "en": "C. Unrelated to the lr; it only affects speed"}]},
         ]},

        # --------------------------------------------------- summary (p28) --
        {"type": "summary",
         "title": {"zh": "本周小结", "en": "Week 5 Summary"},
         "right": MOD,
         "points": [
             {"zh": "损失函数按任务选：多分类 CrossEntropyLoss、二分类 BCEWithLogitsLoss、回归 MSELoss；带 Logits 字样的损失已内含激活，不要再手动加一层。",
              "en": "Pick the loss by task: CrossEntropyLoss for multi-class, BCEWithLogitsLoss for binary, MSELoss for regression; a \"WithLogits\" loss already contains the activation, so do not add another."},
             {"zh": "优化器决定怎么走：SGD 只看当前梯度、Momentum 累积惯性、Adam 每参数自适应步长；Adam 收敛更快但更吃显存。",
              "en": "The optimizer decides how you walk: SGD uses the current gradient, momentum adds inertia, Adam adapts per parameter; Adam converges faster but costs more VRAM."},
             {"zh": "学习率是最重要的超参数：过大震荡爆炸，过小几乎不动；异常损失先查学习率，再考虑 warmup 与衰减策略。",
              "en": "The learning rate is the first hyper-parameter: too large oscillates or explodes, too small barely moves; on a broken loss check it before reaching for warmup and decay."},
             {"zh": "训练循环五步法：清零梯度 → 前向 → 计算损失 → 反向 → 更新参数。顺序不可交换，第 1 步最常被漏掉。",
              "en": "The five-step loop: zero grads, forward, loss, backward, step. The order is not interchangeable and step 1 is the one most often dropped."},
             {"zh": "实验要留证据：每个 epoch 记录 train/val 损失与准确率，一次只改一个变量，最优组合必须用对照数据论证。",
              "en": "Experiments must leave evidence: log train/val loss and accuracy per epoch, change one variable at a time, and justify the winning combo with comparison data."},
         ],
         "todo_title": {"zh": "课后待办", "en": "After Class"},
         "todos": [
             {"title": {"zh": "完成实验 4 交付物", "en": "Finish the Lab 4 deliverables"},
              "desc": {"zh": "训练脚本、3×3 超参数对照表、损失/准确率曲线图、一次「训练不收敛」的排查记录。",
                       "en": "Training script, the 3x3 hyper-parameter table, loss/accuracy curves, and one \"does not converge\" debugging log."}},
             {"title": {"zh": "写一条 AI 协同记录", "en": "Write one AI collaboration trace"},
              "desc": {"zh": "记录 AI 给的一条超参数建议，写明你的验证结果，以及它的哪一部分缺乏依据。",
                       "en": "Record one hyper-parameter suggestion from AI, what your run showed, and which part of it had no basis."}},
             {"title": {"zh": "预习 W6：正则化与泛化", "en": "Preview W6: regularisation and generalisation"},
              "desc": {"zh": "Dropout、权重衰减与早停——让本周的训练循环更稳、更不容易过拟合。",
                       "en": "Dropout, weight decay and early stopping — making this week's training loop steadier and less prone to overfitting."}},
         ]},

        # --------------------------------------------------- closing (p29) --
        {"type": "closing",
         "quote": {"zh": "「调参不是碰运气，\n是有依据的实验设计。」",
                   "en": "\"Tuning is not luck;\nit is experimental design.\""},
         "quote_sub": {"zh": "本周交付：能跑通的训练循环 + 一张 3×3 对照表 + 一份不收敛的排查记录。",
                       "en": "This week you deliver: a working training loop + a 3x3 comparison table + one debugging log."},
         "thanks": {"zh": "谢谢大家", "en": "Thank you"},
         "next_label": {"zh": "下周预告", "en": "Next week"},
         "next": {"zh": "W6 · 正则化与泛化：Dropout、权重衰减与早停 —— 让本周训练好的模型，在没见过的数据上一样稳。",
                  "en": "W6 · Regularisation and generalisation: Dropout, weight decay and early stopping — keeping this week's model steady on data it has never seen."}},
    ],
}
