"""Week 2 - PyTorch Fundamentals: Tensors and Autograd  ·  slide spec (bilingual).

Aligned with the official course documents (52015CC3BV):
CU(2) · Module 1 (Week 1-4) · Lab 1 (linear regression with tensors + autograd only).
"""

SPEC = {
    "week": 2,
    "slides": [
        # ---------------------------------------------------------- cover ----
        {"type": "cover",
         "kicker": {"zh": "52015CC3BV · 本科 · 来华项目", "en": "52015CC3BV · UNDERGRADUATE · INTERNATIONAL"},
         "title": {"zh": "PyTorch 基础：张量与自动求导",
                   "en": "PyTorch Fundamentals: Tensors and Autograd"},
         "title_sub": {"zh": "PyTorch Fundamentals: Tensors and Autograd",
                       "en": "Tensors · shapes · broadcasting · computational graphs · gradient descent by hand"},
         "subtitle": {"zh": "Week 2 · 张量创建与属性 · 形状变换与广播 · 计算图与 autograd · 手写梯度下降",
                      "en": "Week 2 · Creating tensors · shapes and broadcasting · graphs and autograd · gradient descent by hand"},
         "chips": [
             ({"zh": "模块一 · W1–4", "en": "Module 1 · W1-4"}, 1.0),
             ({"zh": "180 min · 授课 + 实验 + 小测", "en": "180 min · Lecture + Lab + Quiz"}, 1.5),
             ({"zh": "torch.Tensor · autograd · 广播 · 梯度下降",
                   "en": "torch.Tensor · autograd · broadcasting · gradient descent"}, 1.8),
             ({"zh": "CU(2)", "en": "CU(2)"}, 0.7),
         ]},

        # ------------------------------------------------------- contents ----
        {"type": "contents",
         "right": {"zh": "模块一 · Week 2", "en": "Module 1 · Week 2"},
         "count": {"zh": "5 部分", "en": "5 Parts"},
         "count_label": {"zh": "本周结构", "en": "Part"},
         "tagline": {"zh": "张量是这门课唯一的数据容器，autograd 是唯一要理解的引擎。\n今天用这两样东西，把一条直线学出来。\nA tensor is the container; autograd is the engine.",
                     "en": "A tensor is the only data container this course uses; autograd is the only engine you must understand.\nToday you will learn a straight line using nothing but those two."},
         "timing": {"zh": "理论约 90 min · Lab 80 min · 小测与小结 10 min",
                    "en": "Theory ~90 min · Lab 80 min · Quiz & Summary 10 min"},
         "parts": [
             {"title": {"zh": "张量：深度学习的通用容器", "en": "Tensors as the Universal Container"},
              "title_en": "The Container",
              "desc": {"zh": "张量创建 · 五个关键属性 · 与 NumPy 的关系 · GPU 张量",
                       "en": "Creating tensors · five key attributes · NumPy relation · GPU tensors"}},
             {"title": {"zh": "形状变换与广播", "en": "Shape Manipulation & Broadcasting"},
              "title_en": "Shapes & Broadcasting",
              "desc": {"zh": "view/reshape · unsqueeze/permute · 广播规则 · 现场制造错误",
                       "en": "view/reshape · unsqueeze/permute · broadcast rules · break it on purpose"}},
             {"title": {"zh": "计算图与自动求导", "en": "Computational Graphs & Autograd"},
              "title_en": "Graphs & Autograd",
              "desc": {"zh": "计算图 · requires_grad · backward 与 grad · 梯度排查清单",
                       "en": "The graph · requires_grad · backward and grad · a gradient debug table"}},
             {"title": {"zh": "用张量实现梯度下降", "en": "Gradient Descent with Tensors"},
              "title_en": "Gradient Descent",
              "desc": {"zh": "手写训练循环 · 损失曲线 · 参数收敛验证 · 学习率三档",
                       "en": "The hand-written loop · loss curves · verifying convergence · learning rates"}},
             {"title": {"zh": "Lab · 实验 1 线性回归", "en": "Lab · Experiment 1 Linear Regression"},
              "title_en": "Hands-On Lab",
              "desc": {"zh": "不用 nn.Module · 用张量与 autograd · 记录损失曲线 · 验证收敛",
                       "en": "No nn.Module · tensors and autograd only · record the loss curve · verify convergence"}},
         ]},

        # ------------------------------------------------- Part 01 (p3-6) ---
        {"type": "section", "num": "01",
         "title": {"zh": "张量：深度学习的通用容器", "en": "Tensors as the Universal Container"},
         "title_en": {"zh": "The Container", "en": "The Container"},
         "lead": {"zh": "模型、数据、梯度、损失——在 PyTorch 里它们全都是张量。\n这一部分之后，你拿到一个张量就应该能立刻报出四件事：形状、类型、设备、要不要算梯度。",
                  "en": "Models, data, gradients, losses - in PyTorch they are all tensors.\nAfter this part, hand you a tensor and you should immediately report four things: shape, dtype, device, needs-grad or not."},
         "pillars": [
             {"title": {"zh": "它是容器", "en": "A Container"},
              "sub": {"zh": "数据、参数、梯度都装在里面", "en": "Data, parameters, gradients live inside"}},
             {"title": {"zh": "它有属性", "en": "It Has Attributes"},
              "sub": {"zh": "shape · dtype · device", "en": "shape · dtype · device"}},
             {"title": {"zh": "它认设备", "en": "It Knows Its Device"},
              "sub": {"zh": "CPU 与 GPU 不能混算", "en": "CPU and GPU cannot be mixed"}},
         ]},

        {"type": "cards", "cols": 2, "h": 6.4, "top": 3.5, "gap": 0.62,
         "title": {"zh": "张量是什么，以及为什么不用 list", "en": "What a Tensor Is, and Why Not a List"},
         "right": {"zh": "模块一 · Week 2", "en": "Module 1 · Week 2"},
         "cards": [
             {"title": {"zh": "张量就是 n 维数组", "en": "A Tensor Is an n-D Array"},
              "title_en": "the container",
              "body": [{"zh": "0 维是标量、1 维是向量、2 维是矩阵、3 维以上是张量",
                        "en": "0-D scalar, 1-D vector, 2-D matrix, 3-D and above a tensor"},
                       {"zh": "形状用 torch.Size 描述，例如 (100, 1)",
                        "en": "The shape is a torch.Size, e.g. (100, 1)"},
                       {"zh": "本课程里：输入、参数、梯度、损失都是张量",
                        "en": "Here, inputs, parameters, gradients and the loss are all tensors"}]},
             {"title": {"zh": "为什么不用 Python list", "en": "Why Not a Python List"},
              "title_en": "speed and memory",
              "body": [{"zh": "list 的循环由解释器逐元素执行，慢一到两个数量级",
                        "en": "Loops over a list run element by element in the interpreter - one to two orders slower"},
                       {"zh": "list 不记录形状、不做广播，出错只能靠你自己查",
                        "en": "A list has no shape and no broadcasting; errors are yours to find"},
                       {"zh": "list 上不了 GPU，也接不上自动求导",
                        "en": "A list cannot go on a GPU and cannot join autograd"}]},
             {"title": {"zh": "和 NumPy 的关系", "en": "Relation to NumPy"},
              "title_en": "same memory",
              "body": [{"zh": "torch.from_numpy(x) 与数组共享内存，改一个另一个也变",
                        "en": "torch.from_numpy(x) shares memory: mutate one and the other changes"},
                       {"zh": ".numpy() 可以把张量交回给 matplotlib 画图",
                        "en": ".numpy() hands the tensor back to matplotlib for plotting"},
                       {"zh": "区别只有两条：能上 GPU、能求导",
                        "en": "Only two differences: it can run on a GPU and it can be differentiated"}]},
             {"title": {"zh": "GPU 张量", "en": "GPU Tensors"},
              "title_en": "device matters",
              "body": [{"zh": "x.to(\"cuda\") 把数据搬进显存，结果也留在那里",
                        "en": "x.to(\"cuda\") moves data into VRAM; results stay there"},
                       {"zh": "两个张量必须在同一设备上才能运算，否则直接报错",
                        "en": "Two tensors must share a device or the operation raises immediately"},
                       {"zh": "只用 CPU 也可以，但报告里必须写明设备",
                        "en": "CPU-only is fine, but the report must state the device"}]},
         ]},

        {"type": "table",
         "title": {"zh": "张量的五个关键属性", "en": "Five Key Attributes of a Tensor"},
         "subtitle": {"zh": "看错其中任何一个，程序都不会报错，只会算错",
                      "en": "Get any one wrong and nothing crashes - the answer is just wrong"},
         "right": {"zh": "模块一 · Week 2", "en": "Module 1 · Week 2"},
         "cols": [{"zh": "属性", "en": "Attribute"},
                  {"zh": "在看什么", "en": "What It Tells You"},
                  {"zh": "典型值", "en": "Typical Value"},
                  {"zh": "什么时候会咬你", "en": "When It Bites You"}],
         "widths": [5.2, 6.6, 8.6, 9.0],
         "h": 8.4,
         "bold_first": True,
         "rows": [
             [{"zh": "shape", "en": "shape"},
              {"zh": "每一维的大小", "en": "The size of every dimension"},
              {"zh": "torch.Size([100, 1])", "en": "torch.Size([100, 1])"},
              {"zh": "形状错了不报错，广播会替你「猜」一个结果",
               "en": "A wrong shape does not raise; broadcasting guesses for you"}],
             [{"zh": "dtype", "en": "dtype"},
              {"zh": "元素类型与精度", "en": "Element type and precision"},
              {"zh": "float32 / int64", "en": "float32 / int64"},
              {"zh": "int64 张量不能设 requires_grad，除法还会取整",
               "en": "int64 tensors cannot require grad, and division truncates"}],
             [{"zh": "device", "en": "device"},
              {"zh": "数据在 CPU 还是 GPU 上", "en": "Whether data sits on CPU or GPU"},
              {"zh": "cpu / cuda:0", "en": "cpu / cuda:0"},
              {"zh": "把 cpu 与 cuda 张量混算，直接 RuntimeError",
               "en": "Mixing cpu and cuda tensors raises immediately"}],
             [{"zh": "requires_grad", "en": "requires_grad"},
              {"zh": "这个张量要不要参与求导", "en": "Whether this tensor is differentiated"},
              {"zh": "True / False", "en": "True / False"},
              {"zh": "参数忘了设 True，.grad 永远是 None，训练静默失败",
               "en": "Forget True on a parameter and .grad stays None - training silently fails"}],
             [{"zh": "grad", "en": "grad"},
              {"zh": "累计起来的梯度", "en": "The accumulated gradient"},
              {"zh": "与自身 shape 相同的张量", "en": "A tensor with the same shape"},
              {"zh": "它是累加的：不看零，得到的是一串错数",
               "en": "It accumulates: without zeroing you read a wrong number"}],
         ],
         "note": {"zh": "养成一个习惯：任何一次形状报错、或者结果看着不对劲，先 print(x.shape, x.dtype, x.device)。九成的张量 bug 在这一行里就现形了。",
                  "en": "Build one habit: on any shape error, or when a result looks wrong, print(x.shape, x.dtype, x.device) first. Nine out of ten tensor bugs show up in that one line."}},

        {"type": "code", "top": 3.55, "h": 11.3,
         "title": {"zh": "创建张量与检查属性", "en": "Creating Tensors and Inspecting Them"},
         "subtitle": {"zh": "先看得见，再算得对", "en": "See it clearly before you compute"},
         "right": {"zh": "模块一 · Week 2", "en": "Module 1 · Week 2"},
         "blocks": [
             {"title": {"zh": "create_tensors.py", "en": "create_tensors.py"},
              "size": 10.5,
              "code": {"zh": [
                  "import torch",
                  "",
                  "t = torch.tensor([[1., 2.], [3., 4.]])   # 从 Python 数据构造",
                  "z = torch.zeros(2, 3)                    # 全 0",
                  "o = torch.ones(2, 3)                     # 全 1",
                  "r = torch.randn(2, 3)                    # 标准正态随机",
                  "a = torch.arange(0, 6)                   # 0..5，形状 (6,)",
                  "l = torch.linspace(0, 1, 5)              # [0,1] 上等距 5 点",
                  "",
                  "print(t.shape, t.dtype, t.device)",
                  "# torch.Size([2, 2]) torch.float32 cpu",
                  "",
                  "print(a.shape)                           # (6,)",
                  "print(a.reshape(2, 3).shape)             # (2, 3)",
                  "print(round(r.mean().item(), 2))         # 约 0.0",
                  "print(round(r.std().item(), 2))          # 约 1.0",
                  "",
                  "# dtype 决定精度，device 决定在哪算",
                  "print(torch.zeros(3, dtype=torch.float64).dtype)  # float64",
                  "print(torch.zeros(3).to(\"cuda\").device)          # 需要 GPU",
              ],
              "en": [
                  "import torch",
                  "",
                  "t = torch.tensor([[1., 2.], [3., 4.]])   # from Python data",
                  "z = torch.zeros(2, 3)                    # all zeros",
                  "o = torch.ones(2, 3)                     # all ones",
                  "r = torch.randn(2, 3)                    # standard normal",
                  "a = torch.arange(0, 6)                   # 0..5, shape (6,)",
                  "l = torch.linspace(0, 1, 5)              # 5 points in [0, 1]",
                  "",
                  "print(t.shape, t.dtype, t.device)",
                  "# torch.Size([2, 2]) torch.float32 cpu",
                  "",
                  "print(a.shape)                           # (6,)",
                  "print(a.reshape(2, 3).shape)             # (2, 3)",
                  "print(round(r.mean().item(), 2))         # about 0.0",
                  "print(round(r.std().item(), 2))          # about 1.0",
                  "",
                  "# dtype sets precision, device sets where it runs",
                  "print(torch.zeros(3, dtype=torch.float64).dtype)  # float64",
                  "print(torch.zeros(3).to(\"cuda\").device)          # needs a GPU",
              ]}},
         ],
         "note": {"zh": "注意 torch.arange(0, 6) 默认是 int64 —— 它不能设 requires_grad。要参与训练就直接写 torch.arange(6.)，一个点号就把它变成 float32。",
                  "en": "Note that torch.arange(0, 6) is int64 by default - it cannot require grad. For training write torch.arange(6.): one decimal point makes it float32."}},

        # ------------------------------------------------- Part 02 (p7-11) --
        {"type": "section", "num": "02",
         "title": {"zh": "形状变换与广播", "en": "Shape Manipulation & Broadcasting"},
         "title_en": {"zh": "Shapes & Broadcasting", "en": "Shapes & Broadcasting"},
         "lead": {"zh": "本周唯一一个「不报错但结果错」的区域就在这一节。\n广播是 PyTorch 最方便也最危险的设计：它替你补维度，却不告诉你补了什么。",
                  "en": "This is the one part of the week where code does not fail but the answer is wrong.\nBroadcasting is PyTorch's most convenient and most dangerous design: it adds dimensions for you without telling you."},
         "pillars": [
             {"title": {"zh": "变换", "en": "Transform"},
              "sub": {"zh": "view / reshape / unsqueeze", "en": "view / reshape / unsqueeze"}},
             {"title": {"zh": "广播", "en": "Broadcast"},
              "sub": {"zh": "从最右一维开始对齐", "en": "Align from the rightmost dimension"}},
             {"title": {"zh": "制造错误", "en": "Break It On Purpose"},
              "sub": {"zh": "先看报错，再谈规则", "en": "Read the error first, learn the rule second"}},
         ]},

        {"type": "cards", "cols": 3, "h": 6.8, "top": 3.5,
         "title": {"zh": "形状变换的三组动作", "en": "Three Families of Shape Operations"},
         "right": {"zh": "模块一 · Week 2", "en": "Module 1 · Week 2"},
         "cards": [
             {"title": {"zh": "改形状", "en": "Change the Shape"},
              "title_en": "view / reshape / -1",
              "body": [{"zh": "view：共享内存，要求张量连续，不连续会报错",
                        "en": "view shares memory, needs contiguity, and raises when it is not"},
                       {"zh": "reshape：能共享就共享，不能就复制，日常首选",
                        "en": "reshape shares when it can and copies when it must - the daily default"},
                       {"zh": "-1 表示「这一维你来算」，其余维必须能整除",
                        "en": "-1 means \"you infer it\"; every other dimension must divide evenly"}]},
             {"title": {"zh": "增维与删维", "en": "Add and Remove Dimensions"},
              "title_en": "unsqueeze / squeeze",
              "body": [{"zh": "unsqueeze(1) 把 (6,) 变成 (6,1)，补维最常用",
                        "en": "unsqueeze(1) turns (6,) into (6,1) - the most common rescue"},
                       {"zh": "squeeze(0) 删掉大小为 1 的维，非 1 的维删不掉",
                        "en": "squeeze(0) drops a size-1 dimension; size-n dimensions stay"},
                       {"zh": "补维写清楚，后面所有广播就都可预测",
                        "en": "Write the added dimension explicitly and every later broadcast is predictable"}]},
             {"title": {"zh": "换轴", "en": "Swap Axes"},
              "title_en": "transpose / permute",
              "body": [{"zh": "transpose 只换两个轴；permute 一次给出全部轴的顺序",
                        "en": "transpose swaps two axes; permute states the full order at once"},
                       {"zh": "换轴之后张量通常不连续，view 会直接失败",
                        "en": "After an axis swap the tensor is usually non-contiguous and view fails"},
                       {"zh": "要还原连续：加 .contiguous()，或者改用 reshape",
                        "en": "Restore contiguity with .contiguous(), or just use reshape"}]},
         ]},

        {"type": "code", "top": 3.55, "h": 11.3,
         "title": {"zh": "形状变换与广播：制造错误，再修复", "en": "Shapes and Broadcasting: Break It, Then Fix It"},
         "subtitle": {"zh": "这一页的每一行都建议你亲手敲一遍", "en": "Type every line on this page yourself at least once"},
         "right": {"zh": "模块一 · Week 2", "en": "Module 1 · Week 2"},
         "blocks": [
             {"title": {"zh": "形状变换：view 与 reshape", "en": "Shape ops: view and reshape"},
              "size": 10.5,
              "code": {"zh": [
                  "x = torch.arange(6.)        # (6,)",
                  "a = x.view(2, 3)            # (2,3)，与 x 共享内存",
                  "x[0] = 99",
                  "print(a[0, 0])              # 99 -> 视图不是副本",
                  "",
                  "t = a.t()                   # (3,2)，转置后不连续",
                  "t.view(6)                   # 报错：非连续不能用 view",
                  "t.reshape(6)                # OK：reshape 会复制",
                  "",
                  "# -1 自动推断那一维",
                  "print(x.reshape(2, -1).shape)     # (2, 3)",
                  "print(x.unsqueeze(1).shape)       # (6, 1)",
                  "# unsqueeze(1) 是补维最常用的写法：",
                  "# (6,) -> (6,1)，正好对上 MSE 的广播",
              ],
              "en": [
                  "x = torch.arange(6.)        # (6,)",
                  "a = x.view(2, 3)            # (2,3), shares memory with x",
                  "x[0] = 99",
                  "print(a[0, 0])              # 99 -> a view, not a copy",
                  "",
                  "t = a.t()                   # (3,2), now non-contiguous",
                  "t.view(6)                   # raises: view needs contiguity",
                  "t.reshape(6)                # OK: reshape copies when needed",
                  "",
                  "# -1 infers the missing dimension",
                  "print(x.reshape(2, -1).shape)     # (2, 3)",
                  "print(x.unsqueeze(1).shape)       # (6, 1)",
                  "# unsqueeze(1) is the usual rescue:",
                  "# (6,) -> (6,1), exactly what MSE broadcasting wants",
              ]}},
             {"title": {"zh": "广播：静默错误 vs 报错", "en": "Broadcasting: silent wrong vs loud error"},
              "size": 10.5,
              "code": {"zh": [
                  "w = torch.randn(3)         # (3,)",
                  "X = torch.randn(4, 3)      # (4,3)",
                  "print((X + w).shape)       # (4,3) 尾部对齐，符合直觉",
                  "",
                  "v = torch.randn(3, 1)      # (3,1)",
                  "print((v + w).shape)       # (3,3) 静默变大！",
                  "",
                  "# 修复：把意图写进形状",
                  "w2 = w.reshape(-1, 1)      # (3,1)",
                  "print((v + w2).shape)      # (3,1)",
                  "print(torch.broadcast_shapes((3,1), (3,)))",
                  "# -> (3,3)：规则说合法，但不是你要的",
                  "",
                  "# 报错型：都不是 1 且不相等",
                  "print((torch.randn(4,3) + torch.randn(4,2)).shape)",
                  "# RuntimeError: (4,3) vs (4,2) <- 这才是好错误",
              ],
              "en": [
                  "w = torch.randn(3)         # (3,)",
                  "X = torch.randn(4, 3)      # (4,3)",
                  "print((X + w).shape)       # (4,3) tail-aligned, intuitive",
                  "",
                  "v = torch.randn(3, 1)      # (3,1)",
                  "print((v + w).shape)       # (3,3) silently grows!",
                  "",
                  "# Fix: write the intent into the shape",
                  "w2 = w.reshape(-1, 1)      # (3,1)",
                  "print((v + w2).shape)      # (3,1)",
                  "print(torch.broadcast_shapes((3,1), (3,)))",
                  "# -> (3,3): legal by the rules, not what you want",
                  "",
                  "# The error kind: neither is 1, and they differ",
                  "print((torch.randn(4,3) + torch.randn(4,2)).shape)",
                  "# RuntimeError: (4,3) vs (4,2) <- a good error",
              ]}},
         ],
         "note": {"zh": "左栏最后两行是本周最常用的一句：unsqueeze(1) 把 (6,) 变成 (6,1)。右栏第 6 行则是本周最危险的错误：它不报错，只是把 (3,1) 和 (3,) 悄悄变成 (3,3)。",
                  "en": "The last lines on the left are this week's most used trick: unsqueeze(1) turns (6,) into (6,1). Line 6 on the right is this week's most dangerous bug: it does not raise, it just turns (3,1) and (3,) into (3,3)."}},

        {"type": "table",
         "title": {"zh": "七种写法：哪些会静默出错", "en": "Seven Expressions: Which Ones Fail Silently"},
         "subtitle": {"zh": "会报错的是好错误；不报错却算错的是坏错误",
                      "en": "An error that raises is a good error; a wrong answer that does not is a bad one"},
         "right": {"zh": "模块一 · Week 2", "en": "Module 1 · Week 2"},
         "cols": [{"zh": "写法", "en": "Expression"},
                  {"zh": "形状变化", "en": "Shape Outcome"},
                  {"zh": "报错吗", "en": "Raises?"},
                  {"zh": "说明", "en": "What Happens"}],
         "widths": [8.8, 6.6, 4.4, 9.6],
         "h": 9.4,
         "bold_first": True,
         "rows": [
             [{"zh": "X (4,3) + w (3,)", "en": "X (4,3) + w (3,)"},
              {"zh": "(4,3) + (3,) → (4,3)", "en": "(4,3) + (3,) -> (4,3)"},
              {"zh": "不报", "en": "no"},
              {"zh": "从最右对齐，w 被复制到每一行，符合直觉",
               "en": "Right-aligned; w is copied onto every row - intuitive"}],
             [{"zh": "v (3,1) + w (3,)", "en": "v (3,1) + w (3,)"},
              {"zh": "(3,1) + (3,) → (3,3)", "en": "(3,1) + (3,) -> (3,3)"},
              {"zh": "不报，静默错", "en": "no, silent"},
              {"zh": "(3,1) 沿列复制、(3,) 沿行复制，结果凭空多出一维",
               "en": "(3,1) spreads down columns, (3,) across rows: one extra dimension appears"}],
             [{"zh": "v + w.reshape(-1,1)", "en": "v + w.reshape(-1,1)"},
              {"zh": "(3,1) + (3,1) → (3,1)", "en": "(3,1) + (3,1) -> (3,1)"},
              {"zh": "不报", "en": "no"},
              {"zh": "把意图写进形状，代码自己解释自己",
               "en": "The intent is written into the shape; the code explains itself"}],
             [{"zh": "X (100,1) @ w (1,1)", "en": "X (100,1) @ w (1,1)"},
              {"zh": "(100,1)，内维相等", "en": "(100,1), inner dims match"},
              {"zh": "不报", "en": "no"},
              {"zh": "矩阵乘法不广播，内维必须严格相等",
               "en": "Matrix multiply does not broadcast; inner dims must match exactly"}],
             [{"zh": "X (100,1) @ w (3,)", "en": "X (100,1) @ w (3,)"},
              {"zh": "内维 1 与 3 不相等", "en": "inner dims 1 and 3 differ"},
              {"zh": "报错", "en": "yes"},
              {"zh": "RuntimeError: mat1 and mat2 shapes cannot be multiplied",
               "en": "RuntimeError: mat1 and mat2 shapes cannot be multiplied"}],
             [{"zh": "a (2,3).t().view(6)", "en": "a (2,3).t().view(6)"},
              {"zh": "转置后内存不连续", "en": "non-contiguous after transpose"},
              {"zh": "报错", "en": "yes"},
              {"zh": "RuntimeError: view size is not compatible... 改用 reshape",
               "en": "RuntimeError: view size is not compatible... use reshape instead"}],
             [{"zh": "x (4,6).reshape(-1,3)", "en": "x (4,6).reshape(-1,3)"},
              {"zh": "(4,6) → (8,3)", "en": "(4,6) -> (8,3)"},
              {"zh": "不报", "en": "no"},
              {"zh": "-1 自动推断；其余维必须能整除，否则报错",
               "en": "-1 is inferred; the other dimensions must divide evenly"}],
         ],
         "note": {"zh": "第二行是本课程出现频率最高的错误，也是最危险的一种：它不报错。所以每次写完与形状有关的代码，都要 print 一次结果的 shape —— 这不是调试，这是习惯。",
                  "en": "Row two is the most frequent mistake in this course and the most dangerous: it does not raise. So after any shape-related code, print the result's shape - not as debugging, as a habit."}},

        {"type": "compare",
         "title": {"zh": "广播规则、四个高频错误、五条修复手法",
                   "en": "The Rules, the Four Classic Mistakes, and the Fixes"},
         "subtitle": {"zh": "先读报错，再学规则；先写形状，再写代码",
                      "en": "Read the error first, learn the rule second; write the shape first, the code second"},
         "right": {"zh": "模块一 · Week 2", "en": "Module 1 · Week 2"},
         "columns": [
             {"title": {"zh": "广播的三条规则", "en": "The Three Broadcast Rules"},
              "accent": "1E4FA8", "bg": "F0F5FC",
              "items": [
                  {"zh": "从最右一维开始，逐维向左比较", "en": "Start at the rightmost dimension and walk left"},
                  {"zh": "两维相等 → 直接对齐", "en": "Equal sizes -> align directly"},
                  {"zh": "其中一维是 1 → 沿这一维复制扩展", "en": "One of them is 1 -> copy and stretch along it"},
                  {"zh": "都不是 1 且不相等 → 报错（这是好事）", "en": "Neither is 1 and they differ -> raise (that is good)"},
                  {"zh": "结论：广播只保证「合法」，不保证「符合你的意图」",
                   "en": "Conclusion: broadcasting guarantees legality, not your intent"}]},
             {"title": {"zh": "四个高频形状错误", "en": "Four Classic Shape Mistakes"},
              "accent": "B91C1C", "bg": "FEF2F2",
              "items": [
                  {"zh": "(3,) 与 (3,1) 混用 → 静默得到 (3,3)", "en": "(3,) mixed with (3,1) -> a silent (3,3)"},
                  {"zh": "该做外积的地方忘了补维，结果变成了逐元素相乘",
                   "en": "Forgetting a dimension where an outer product was meant, ending up element-wise"},
                  {"zh": "对转置后的张量用 view → 非连续报错", "en": "view on a transposed tensor -> non-contiguous error"},
                  {"zh": "更新参数时形状不一致 → 广播后 w 悄悄变成 (n,n)",
                   "en": "Updating with a mismatched shape -> w silently becomes (n,n)"},
                  {"zh": "只看 loss 不看 shape：loss 算得出来，结果却是错的",
                   "en": "Watching the loss but not the shape: it computes, and it is wrong"}]},
             {"title": {"zh": "修复与自查五条", "en": "Five Fixes and Self-Checks"},
              "accent": "059669", "bg": "ECFDF5",
              "items": [
                  {"zh": "写形状相关代码前，先把每一行的 shape 写在注释里",
                   "en": "Before shape code, write each line's shape into a comment"},
                  {"zh": "加断言：assert y_hat.shape == y.shape", "en": "Assert it: assert y_hat.shape == y.shape"},
                  {"zh": "把目标统一成 reshape(-1, 1)，别让 (n,) 参战",
                   "en": "Make targets reshape(-1, 1); keep (n,) out of the fight"},
                  {"zh": "非连续张量用 reshape，或 .contiguous().view(...)",
                   "en": "For non-contiguous tensors use reshape, or .contiguous().view(...)"},
                  {"zh": "训练开始前，打印一次数据与参数的形状", "en": "Before training, print the shapes of data and parameters once"}]},
         ],
         "note": {"zh": "课堂演示方式：先故意写错，把报错信息一字一句读出来，再动手修。看清一次报错，胜过背十条规则。",
                  "en": "Classroom method: write it wrong on purpose, read the error message out loud word by word, then fix it. Seeing one error clearly beats memorising ten rules."}},

        # ------------------------------------------------- Part 03 (p12-16) -
        {"type": "section", "num": "03",
         "title": {"zh": "计算图与自动求导", "en": "Computational Graphs & Autograd"},
         "title_en": {"zh": "Graphs & Autograd", "en": "Graphs & Autograd"},
         "lead": {"zh": "autograd 只做一件事：把前向的每一步记下来，反向时按链式法则逐段求导。\n你不需要自己推导，但你必须知道「谁在图上、谁不在」。",
                  "en": "Autograd does exactly one thing: it records every forward step, then walks back applying the chain rule.\nYou never differentiate by hand, but you must know who is on the graph and who is not."},
         "pillars": [
             {"title": {"zh": "计算图", "en": "The Graph"},
              "sub": {"zh": "前向的副产品", "en": "A by-product of the forward pass"}},
             {"title": {"zh": "开关", "en": "The Switch"},
              "sub": {"zh": "requires_grad 决定谁被求导", "en": "requires_grad decides who is differentiated"}},
             {"title": {"zh": "读梯度", "en": "Read the Gradient"},
              "sub": {"zh": "只有叶子张量有 .grad", "en": "Only leaves carry .grad"}},
         ]},

        {"type": "cards", "cols": 3, "h": 6.8, "top": 3.5,
         "title": {"zh": "autograd 的三个概念", "en": "The Three Concepts of Autograd"},
         "right": {"zh": "模块一 · Week 2", "en": "Module 1 · Week 2"},
         "cards": [
             {"title": {"zh": "计算图：前向的副产品", "en": "The Graph: a By-Product"},
              "title_en": "what got recorded",
              "body": [{"zh": "每个涉及梯度的运算都会记下自己是怎么算出来的",
                        "en": "Every operation touching gradients records how it was computed"},
                       {"zh": "非叶子张量带 grad_fn；叶子张量的 .grad 被填充",
                        "en": "Non-leaves carry grad_fn; leaves get their .grad filled"},
                       {"zh": "反向传播用完即释放，想再传要设 retain_graph",
                        "en": "The graph is freed after backward; re-use needs retain_graph"}]},
             {"title": {"zh": "requires_grad：谁要梯度", "en": "requires_grad: Who Needs Gradients"},
              "title_en": "the switch",
              "body": [{"zh": "只有浮点张量能设 requires_grad=True，int 张量不行",
                        "en": "Only floating-point tensors accept requires_grad=True"},
                       {"zh": "数据 X、y 不需要；参数 w、b 必须设",
                        "en": "Data X and y do not need it; parameters w and b must have it"},
                       {"zh": "凡是依赖它的结果，都自动带上 requires_grad",
                        "en": "Anything computed from it inherits requires_grad automatically"}]},
             {"title": {"zh": "backward 与 grad：读梯度", "en": "backward and grad: Reading It"},
              "title_en": "the output",
              "body": [{"zh": "loss.backward() 从一个标量出发，沿图回传",
                        "en": "loss.backward() starts from a scalar and walks back"},
                       {"zh": "只有叶子张量的 .grad 会被填充，形状与它相同",
                        "en": "Only leaves get .grad filled, with the same shape as the leaf"},
                       {"zh": ".grad 是累加的：不清零，上一步的梯度会叠上来",
                        "en": ".grad accumulates: without zeroing, the previous step is added in"}]},
         ]},

        {"type": "code", "top": 3.55, "h": 11.3,
         "title": {"zh": "autograd 最小示例", "en": "The Smallest Autograd Example"},
         "subtitle": {"zh": "八行代码里藏着本周一半的坑", "en": "Eight lines that hide half of this week's pitfalls"},
         "right": {"zh": "模块一 · Week 2", "en": "Module 1 · Week 2"},
         "blocks": [
             {"title": {"zh": "autograd_basics.py", "en": "autograd_basics.py"},
              "size": 11,
              "code": {"zh": [
                  "import torch",
                  "",
                  "x = torch.tensor(3.0, requires_grad=True)   # 叶子张量",
                  "y = x ** 2 + 2 * x + 1                      # 前向 + 建图",
                  "print(y.requires_grad, y.grad_fn)",
                  "# True <AddBackward0> <- 非叶子记录了它怎么算出来",
                  "",
                  "y.backward()                                # 反向：沿图回传",
                  "print(x.grad)                               # tensor(8.) = 2*3 + 2",
                  "",
                  "x.grad = None                               # 梯度默认累加，先清零",
                  "z = (x ** 2).sum(); z.backward()",
                  "print(x.grad)                               # tensor(6.) = 2*3",
                  "",
                  "with torch.no_grad():                       # 推理：不建图",
                  "    print((x * 2).requires_grad)            # False",
                  "print((x * 3).detach().requires_grad)       # False：从图上摘下",
              ],
              "en": [
                  "import torch",
                  "",
                  "x = torch.tensor(3.0, requires_grad=True)   # a leaf tensor",
                  "y = x ** 2 + 2 * x + 1                      # forward + build the graph",
                  "print(y.requires_grad, y.grad_fn)",
                  "# True <AddBackward0> <- a non-leaf remembers how it was made",
                  "",
                  "y.backward()                                # backward: walk the graph",
                  "print(x.grad)                               # tensor(8.) = 2*3 + 2",
                  "",
                  "x.grad = None                               # grad accumulates; clear it",
                  "z = (x ** 2).sum(); z.backward()",
                  "print(x.grad)                               # tensor(6.) = 2*3",
                  "",
                  "with torch.no_grad():                       # inference: no graph",
                  "    print((x * 2).requires_grad)            # False",
                  "print((x * 3).detach().requires_grad)       # False: cut off the graph",
              ]}},
         ],
         "note": {"zh": "把 x.grad = None 那一行注释掉再跑一次：x.grad 会变成 8 + 6 = 14。这就是「梯度累加」的全部真相，也是实验里损失震荡的直接原因。",
                  "en": "Comment out x.grad = None and run again: x.grad becomes 8 + 6 = 14. That is the whole truth about gradient accumulation, and the direct cause of the oscillating loss in the lab."}},

        {"type": "flow", "y": 6.2, "h": 4.9,
         "title": {"zh": "一次参数更新的五个动作", "en": "Five Moves in One Parameter Update"},
         "right": {"zh": "模块一 · Week 2", "en": "Module 1 · Week 2"},
         "steps": [
             {"title": {"zh": "前向", "en": "Forward"},
              "title_en": "Forward",
              "desc": {"zh": "用当前参数算出预测\n y_hat = X @ w + b",
                       "en": "Compute a prediction from\nthe current parameters"}},
             {"title": {"zh": "建图", "en": "Build Graph"},
              "title_en": "Build graph",
              "desc": {"zh": "每一步运算被记进\n计算图（自动发生）",
                       "en": "Every step is recorded in\nthe graph - automatically"}},
             {"title": {"zh": "求损失", "en": "Loss"},
              "title_en": "Scalar loss",
              "desc": {"zh": "把误差压成一个标量：\n loss = MSE(y_hat, y)",
                       "en": "Compress the error into one\nscalar: loss = MSE(y_hat, y)"}},
             {"title": {"zh": "反向", "en": "Backward"},
              "title_en": "Backward",
              "desc": {"zh": "loss.backward() 沿图回传，\n填满每个叶子的 .grad",
                       "en": "loss.backward() walks back and\nfills .grad on every leaf"}},
             {"title": {"zh": "更新与清零", "en": "Update & Zero"},
              "title_en": "Update",
              "desc": {"zh": "在 no_grad 里手改参数，\n然后立刻清零梯度",
                       "en": "Edit the parameters under\nno_grad, then zero the grads"}},
         ],
         "note": {"zh": "第 5 步的两个动作顺序不能颠倒：更新 → 清零。更新必须写在 with torch.no_grad(): 里面，否则 PyTorch 会把「更新」这一步也记进计算图，越训越慢。",
                  "en": "Step 5 is two moves in a fixed order: update, then zero. The update must sit inside with torch.no_grad(): otherwise PyTorch records the update itself into the graph and training slows down as it goes."}},

        {"type": "table",
         "title": {"zh": "梯度不对？按这张表逐条排查", "en": "Gradients Wrong? Work Down This Table"},
         "subtitle": {"zh": "五个症状，五种原因，五条修复", "en": "Five symptoms, five causes, five fixes"},
         "right": {"zh": "模块一 · Week 2", "en": "Module 1 · Week 2"},
         "cols": [{"zh": "症状", "en": "Symptom"},
                  {"zh": "最可能的原因", "en": "Most Likely Cause"},
                  {"zh": "一句话诊断", "en": "One-Line Diagnosis"},
                  {"zh": "修复", "en": "Fix"}],
         "widths": [7.4, 8.4, 6.6, 7.0],
         "h": 9.0,
         "bold_first": True,
         "rows": [
             [{"zh": "损失不下降，来回震荡", "en": "Loss oscillates, never drops"},
              {"zh": "每步没有清零，梯度被累加", "en": "Gradients are never zeroed and accumulate"},
              {"zh": "print(w.grad) 看相邻两步", "en": "print(w.grad) on two consecutive steps"},
              {"zh": "更新后立刻 w.grad.zero_()", "en": "Call w.grad.zero_() right after the update"}],
             [{"zh": "w.grad 一直是 None", "en": "w.grad stays None"},
              {"zh": "它不是叶子，或者 requires_grad=False", "en": "It is not a leaf, or requires_grad=False"},
              {"zh": "print(w.is_leaf, w.requires_grad)", "en": "print(w.is_leaf, w.requires_grad)"},
              {"zh": "只对叶子张量设 requires_grad=True", "en": "Set requires_grad=True on leaves only"}],
             [{"zh": "更新时报 in-place operation 错误", "en": "In-place operation error on the update line"},
              {"zh": "更新被写进了计算图，或对中间张量做原地运算",
               "en": "The update sits inside the graph, or an intermediate was edited in place"},
              {"zh": "看报错是否指向 -= 那一行", "en": "Check whether the error points at the -= line"},
              {"zh": "用 with torch.no_grad(): 包住更新", "en": "Wrap the update in with torch.no_grad():"}],
             [{"zh": "损失越跑越大，甚至变成 nan", "en": "Loss grows until it becomes nan"},
              {"zh": "学习率过大，或梯度未清零", "en": "Learning rate too large, or grads not zeroed"},
              {"zh": "打印 history 的最后五个值", "en": "Print the last five values of history"},
              {"zh": "把 lr 减半再减半，并确认清零", "en": "Halve and halve the lr, and confirm zeroing"}],
             [{"zh": "w 的形状莫名变大", "en": "The shape of w grew unexpectedly"},
              {"zh": "广播把 (n,) 与 (n,1) 扩成了 (n,n)", "en": "Broadcasting turned (n,) and (n,1) into (n,n)"},
              {"zh": "print(w.shape) 对比初始化时的形状", "en": "print(w.shape) against the initial shape"},
              {"zh": "数据与目标统一 reshape(-1, 1)", "en": "Make data and targets reshape(-1, 1)"}],
         ],
         "note": {"zh": "第 1 条和第 3 条是本课程最常出现的两个训练 bug，全都与 autograd 的行为直接相关，而不是与模型有关。",
                  "en": "Rows 1 and 3 are the two most common training bugs in this course, and both come from autograd's behaviour rather than from the model."}},

        # ------------------------------------------------- Part 04 (p17-21) -
        {"type": "section", "num": "04",
         "title": {"zh": "用张量实现梯度下降", "en": "Gradient Descent with Tensors"},
         "title_en": {"zh": "Gradient Descent", "en": "Gradient Descent"},
         "lead": {"zh": "把前三部分拼起来：张量装数据，形状对齐，autograd 给梯度，我们自己写下降那一步。\n下面这段代码就是实验 1 的全部骨架。",
                  "en": "Put the first three parts together: tensors hold the data, shapes line up, autograd supplies the gradient, and we write the descent step ourselves.\nThe code below is the entire skeleton of Lab 1."},
         "pillars": [
             {"title": {"zh": "损失", "en": "The Loss"},
              "sub": {"zh": "MSE 把误差变成一个数", "en": "MSE turns error into one number"}},
             {"title": {"zh": "更新", "en": "The Update"},
              "sub": {"zh": "w -= lr * w.grad", "en": "w -= lr * w.grad"}},
             {"title": {"zh": "复现", "en": "Reproducibility"},
              "sub": {"zh": "固定种子，别人能跑出同一条曲线", "en": "Fix the seed so others get the same curve"}},
         ]},

        {"type": "code", "top": 3.55, "h": 11.3,
         "title": {"zh": "手写线性回归：只有张量和 autograd",
                   "en": "Linear Regression with Tensors and Autograd Only"},
         "subtitle": {"zh": "这段循环里不许出现 nn.Linear，也不许出现 torch.optim",
                      "en": "No nn.Linear and no torch.optim inside this loop"},
         "right": {"zh": "模块一 · Week 2", "en": "Module 1 · Week 2"},
         "blocks": [
             {"title": {"zh": "gd_by_hand.py", "en": "gd_by_hand.py"},
              "size": 10.5,
              "code": {"zh": [
                  "import torch",
                  "torch.manual_seed(42)                  # 固定种子：结果可复现",
                  "",
                  "X = torch.randn(100, 1)                # (100, 1)",
                  "y = 3.0 * X + 2.0 + 0.1 * torch.randn(100, 1)",
                  "w = torch.zeros(1, 1, requires_grad=True)",
                  "b = torch.zeros(1, requires_grad=True)",
                  "lr, history = 0.1, []",
                  "",
                  "for step in range(200):",
                  "    y_hat = X @ w + b                  # 前向：(100,1)",
                  "    loss = ((y_hat - y) ** 2).mean()   # MSE",
                  "    loss.backward()                    # 反向：填 w.grad",
                  "    with torch.no_grad():              # 更新不能建图",
                  "        w -= lr * w.grad",
                  "        b -= lr * b.grad",
                  "    w.grad.zero_(); b.grad.zero_()     # 不清零 -> 梯度累加",
                  "    history.append(loss.item())",
                  "",
                  "print(round(w.item(), 3), round(b.item(), 3))   # 2.987 2.013",
              ],
              "en": [
                  "import torch",
                  "torch.manual_seed(42)                  # fixed seed: reproducible",
                  "",
                  "X = torch.randn(100, 1)                # (100, 1)",
                  "y = 3.0 * X + 2.0 + 0.1 * torch.randn(100, 1)",
                  "w = torch.zeros(1, 1, requires_grad=True)",
                  "b = torch.zeros(1, requires_grad=True)",
                  "lr, history = 0.1, []",
                  "",
                  "for step in range(200):",
                  "    y_hat = X @ w + b                  # forward: (100,1)",
                  "    loss = ((y_hat - y) ** 2).mean()   # MSE",
                  "    loss.backward()                    # backward: fills w.grad",
                  "    with torch.no_grad():              # the update must not be traced",
                  "        w -= lr * w.grad",
                  "        b -= lr * b.grad",
                  "    w.grad.zero_(); b.grad.zero_()     # skip this -> accumulation",
                  "    history.append(loss.item())",
                  "",
                  "print(round(w.item(), 3), round(b.item(), 3))   # 2.987 2.013",
              ]}},
         ],
         "note": {"zh": "三件事必须同时发生在循环里：loss.backward()、装在 with torch.no_grad(): 里的更新、以及 w.grad.zero_()。少任何一件，训练都不会按你预期收敛。",
                  "en": "Three things must happen inside the loop: loss.backward(), the update wrapped in with torch.no_grad():, and w.grad.zero_(). Remove any one and training will not converge as you expect."}},

        {"type": "chart", "w": 19.0, "h": 12.0, "y_max": 65,
         "title": {"zh": "三条损失曲线，一次看清三个坑", "en": "Three Loss Curves, Three Traps at Once"},
         "right": {"zh": "模块一 · Week 2", "en": "Module 1 · Week 2"},
         "categories": [0, 20, 40, 60, 80, 100, 120, 140, 160, 180, 200],
         "x_label": {"zh": "训练步数 step", "en": "Training step"},
         "y_label": {"zh": "MSE 损失", "en": "MSE loss"},
         "series": [
             {"name": {"zh": "正确：每步清零梯度", "en": "Correct: zeroed each step"},
              "color": "1E4FA8", "emphasis": True, "smooth": True, "no_markers": True,
              "values": [13.0, 0.92, 0.14, 0.050, 0.028, 0.019, 0.014, 0.012, 0.011, 0.010, 0.010]},
             {"name": {"zh": "忘了清零：梯度累加", "en": "Never zeroed: accumulation"},
              "color": "D97706", "smooth": True,
              "values": [13.0, 8.9, 4.2, 7.8, 3.6, 9.1, 2.9, 11.4, 5.8, 14.2, 6.1]},
             {"name": {"zh": "学习率 1.0 过大", "en": "lr = 1.0, too large"},
              "color": "B91C1C", "smooth": True,
              "values": [13.0, 16.8, 24.5, 38.2, 52.6, 41.3, 57.8, 44.2, 59.4, 46.8, 61.2]},
         ],
         "notes": [
             {"zh": "蓝线在 40 步左右就贴到底部，之后几乎没有收益",
              "en": "The blue line bottoms out near step 40; after that there is almost nothing to gain"},
             {"zh": "橙线在 3 到 14 之间来回跳：不是学不会，而是梯度被累加",
              "en": "Orange jumps between 3 and 14: not a failure to learn, but accumulated gradients"},
             {"zh": "红线整体往上走：学习率太大，每一步都跨过谷底",
              "en": "Red climbs: the learning rate is too large and every step overshoots the valley"},
             {"zh": "拿到任何损失曲线，先问一句：它有没有单调下降的趋势？",
              "en": "Given any loss curve, ask first: does it have a monotone downward trend?"},
         ],
         "note": {"zh": "实验 1 要交的是这三条里最上面那一条：你自己跑出来的、贴着底部的曲线。另外两条是你要在报告里解释的对照。",
                  "en": "Lab 1 requires the top one of these three: your own run, hugging the floor. The other two are the comparisons you explain in the report."}},

        {"type": "table",
         "title": {"zh": "收敛到哪里才算对：三个数不能混",
                   "en": "Where \"Converged\" Means: Three Numbers, Do Not Mix Them"},
         "subtitle": {"zh": "真值、闭式解、训练解——它们本来就不完全相等",
                      "en": "Truth, closed-form solution, trained solution - they are not supposed to be identical"},
         "right": {"zh": "模块一 · Week 2", "en": "Module 1 · Week 2"},
         "cols": [{"zh": "参数", "en": "Parameter"},
                  {"zh": "数据生成真值", "en": "Generating Truth"},
                  {"zh": "闭式最小二乘解", "en": "Closed-Form OLS"},
                  {"zh": "梯度下降 200 步", "en": "GD, 200 Steps"},
                  {"zh": "相对误差", "en": "Rel. Error"}],
         "widths": [4.4, 6.4, 6.8, 6.8, 5.0],
         "h": 6.6,
         "bold_first": True,
         "rows": [
             [{"zh": "w（斜率）", "en": "w (slope)"},
              {"zh": "3.000", "en": "3.000"},
              {"zh": "2.991", "en": "2.991"},
              {"zh": "2.987", "en": "2.987"},
              {"zh": "0.13%", "en": "0.13%"}],
             [{"zh": "b（截距）", "en": "b (intercept)"},
              {"zh": "2.000", "en": "2.000"},
              {"zh": "2.014", "en": "2.014"},
              {"zh": "2.013", "en": "2.013"},
              {"zh": "0.05%", "en": "0.05%"}],
             [{"zh": "训练集 MSE", "en": "Train MSE"},
              {"zh": "0.0100（噪声方差）", "en": "0.0100 (noise variance)"},
              {"zh": "0.0098", "en": "0.0098"},
              {"zh": "0.0099", "en": "0.0099"},
              {"zh": "不在同一量纲", "en": "not comparable"}],
         ],
         "note": {"zh": "三个数各有各的含义：真值是「我造数据时用的」，闭式解是「在这批样本上最优的」，训练解是「200 步之后我拿到的」。报告里必须写清楚你在跟哪一个比，否则「误差」这个词没有意义。",
                  "en": "Each number means something different: the truth is what you generated with, the closed-form solution is optimal on this sample, and the trained solution is what 200 steps gave you. Your report must say which one you compare against, or the word error means nothing."}},

        {"type": "cards", "cols": 3, "h": 6.8, "top": 3.5,
         "title": {"zh": "学习率三档：太小、合适、太大", "en": "Three Learning Rates: Too Small, Right, Too Large"},
         "right": {"zh": "模块一 · Week 2", "en": "Module 1 · Week 2"},
         "cards": [
             {"title": {"zh": "太小 lr = 0.001", "en": "Too Small, lr = 0.001"},
              "title_en": "looks like it failed",
              "accent": "D97706", "bg": "FFFBEB",
              "body": [{"zh": "损失缓慢下降，曲线几乎是一条平线",
                        "en": "The loss creeps down; the curve looks almost flat"},
                       {"zh": "200 步远没走到谷底，很容易被误判成「模型不行」",
                        "en": "200 steps never reach the bottom - easily misread as a broken model"},
                       {"zh": "对策：先试 0.1，再上下各试一个数量级",
                        "en": "Fix: try 0.1 first, then one order of magnitude either way"}]},
             {"title": {"zh": "合适 lr = 0.1", "en": "Just Right, lr = 0.1"},
              "title_en": "the default here",
              "accent": "059669", "bg": "ECFDF5",
              "body": [{"zh": "损失在几十步内快速下降，之后平稳贴底",
                        "en": "The loss drops within tens of steps, then flattens onto the floor"},
                       {"zh": "这就是实验 1 的默认设置，也是三条曲线的对照基准",
                        "en": "This is the Lab 1 default and the baseline for the comparison"},
                       {"zh": "判断标准：先有一段明显下降，然后是一段平台",
                        "en": "The pattern to look for: a clear descent, then a plateau"}]},
             {"title": {"zh": "太大 lr = 1.0", "en": "Too Large, lr = 1.0"},
              "title_en": "divergence",
              "accent": "B91C1C", "bg": "FEF2F2",
              "body": [{"zh": "损失不降反升，继续下去会出现 nan",
                        "en": "The loss climbs instead of falling, and eventually turns to nan"},
                       {"zh": "每一步都跨过谷底，落到对面更远的地方",
                        "en": "Every step overshoots the valley and lands further away"},
                       {"zh": "对策：减半，再减半；不要指望它自己扛住",
                        "en": "Fix: halve it, then halve it again; do not hope it recovers"}]},
         ]},

        # ------------------------------------------------- Part 05 (p22-27) -
        {"type": "section", "num": "05",
         "title": {"zh": "Lab · 实验 1 线性回归", "en": "Lab · Experiment 1: Linear Regression"},
         "title_en": {"zh": "Tensors and Autograd Only", "en": "Tensors and Autograd Only"},
         "lead": {"zh": "不使用 nn.Module、不使用任何优化器——只用张量和 autograd，把一条直线学出来。\n四个任务：造数据 → 训练 → 记录损失曲线 → 验证参数收敛。",
                  "en": "No nn.Module, no optimiser of any kind - learn a straight line with tensors and autograd alone.\nFour tasks: make the data, train, record the loss curve, verify the parameters converged."},
         "pillars": [
             {"title": {"zh": "造数据", "en": "Make the Data"},
              "sub": {"zh": "固定种子 + 基线损失", "en": "Fixed seed + a baseline loss"}},
             {"title": {"zh": "训练", "en": "Train"},
              "sub": {"zh": "手写循环，不用优化器", "en": "A hand-written loop, no optimiser"}},
             {"title": {"zh": "验证", "en": "Verify"},
              "sub": {"zh": "曲线 + 参数收敛对比", "en": "The curve + a parameter comparison"}},
         ]},

        {"type": "cards", "cols": 2, "h": 5.4, "top": 3.6,
         "title": {"zh": "实验 1 的四个任务", "en": "The Four Tasks of Experiment 1"},
         "right": {"zh": "模块一 · Week 2", "en": "Module 1 · Week 2"},
         "cards": [
             {"title": {"zh": "A · 造数据与基线", "en": "A · Data and Baseline"},
              "title_en": "task A",
              "body": [{"zh": "固定种子生成 y = 3x + 2 + 噪声，n = 100",
                        "en": "Fix the seed and generate y = 3x + 2 + noise, n = 100"},
                       {"zh": "先算 w = b = 0 时的基线损失", "en": "Compute the baseline loss at w = b = 0"},
                       {"zh": "产出：一个「不训练就不行」的数字", "en": "Output: one number proving training is needed"}]},
             {"title": {"zh": "B · 只用张量训练", "en": "B · Train with Tensors Only"},
              "title_en": "task B",
              "body": [{"zh": "w、b 用 zeros(..., requires_grad=True) 初始化",
                        "en": "Initialise w and b with zeros(..., requires_grad=True)"},
                       {"zh": "循环内：前向 → MSE → 反向 → 更新 → 清零",
                        "en": "Inside the loop: forward, MSE, backward, update, zero"},
                       {"zh": "禁止使用 nn.Linear 与任何 torch.optim",
                        "en": "nn.Linear and every torch.optim are forbidden"}]},
             {"title": {"zh": "C · 记录损失曲线", "en": "C · Record the Loss Curve"},
              "title_en": "task C",
              "body": [{"zh": "每个 step 记录 loss.item()，训练后画曲线",
                        "en": "Record loss.item() each step and plot it afterwards"},
                       {"zh": "在图上标出「损失不再明显下降」的位置",
                        "en": "Mark the point where the loss stops dropping noticeably"},
                       {"zh": "产出：loss.png 加一句话的收敛说明", "en": "Output: loss.png plus a one-sentence reading"}]},
             {"title": {"zh": "D · 验证参数收敛", "en": "D · Verify Convergence"},
              "title_en": "task D",
              "body": [{"zh": "与真值 3、2 以及闭式最小二乘解同时对比",
                        "en": "Compare against the truth (3, 2) and the closed-form OLS solution"},
                       {"zh": "写出相对误差，并解释三者为何不等",
                        "en": "State the relative error and explain why the three differ"},
                       {"zh": "产出：一张参数收敛对比表", "en": "Output: a parameter comparison table"}]},
         ]},

        {"type": "code", "top": 3.35, "h": 12.2,
         "title": {"zh": "实验 1 脚本骨架", "en": "Lab 1 Script Skeleton"},
         "subtitle": {"zh": "可以直接改成你的报告主体", "en": "Turn this straight into the body of your report"},
         "right": {"zh": "模块一 · Week 2", "en": "Module 1 · Week 2"},
         "blocks": [
             {"title": {"zh": "lab1_linear_regression.py", "en": "lab1_linear_regression.py"},
              "size": 10.5,
              "code": {"zh": [
                  "import torch, matplotlib.pyplot as plt",
                  "",
                  "torch.manual_seed(42)                 # 固定种子：报告的硬要求",
                  "lr = 0.1",
                  "X = torch.randn(100, 1)               # (100, 1)",
                  "y = 3.0 * X + 2.0 + 0.1 * torch.randn(100, 1)",
                  "",
                  "w = torch.zeros(1, 1, requires_grad=True)",
                  "b = torch.zeros(1, requires_grad=True)",
                  "hist = []",
                  "for s in range(200):",
                  "    loss = ((X @ w + b - y) ** 2).mean()   # MSE",
                  "    loss.backward()                        # 反向",
                  "    with torch.no_grad():                  # 更新不建图",
                  "        w -= lr * w.grad; b -= lr * b.grad",
                  "    w.grad.zero_(); b.grad.zero_()         # 必做：清零",
                  "    hist.append(loss.item())               # 每步记损失",
                  "",
                  "print(\"trained:\", round(w.item(), 3), round(b.item(), 3))",
                  "print(\"truth  :\", 3.0, 2.0)             # 与真值对比",
                  "plt.plot(hist); plt.yscale(\"log\")         # 后期下降看得清",
                  "plt.savefig(\"loss.png\")                  # 提交：损失曲线",
              ],
              "en": [
                  "import torch, matplotlib.pyplot as plt",
                  "",
                  "torch.manual_seed(42)                 # fixed seed: a report requirement",
                  "lr = 0.1",
                  "X = torch.randn(100, 1)               # (100, 1)",
                  "y = 3.0 * X + 2.0 + 0.1 * torch.randn(100, 1)",
                  "",
                  "w = torch.zeros(1, 1, requires_grad=True)",
                  "b = torch.zeros(1, requires_grad=True)",
                  "hist = []",
                  "for s in range(200):",
                  "    loss = ((X @ w + b - y) ** 2).mean()   # MSE",
                  "    loss.backward()                        # backward",
                  "    with torch.no_grad():                  # update, no graph",
                  "        w -= lr * w.grad; b -= lr * b.grad",
                  "    w.grad.zero_(); b.grad.zero_()         # mandatory: zero",
                  "    hist.append(loss.item())               # log the loss",
                  "",
                  "print(\"trained:\", round(w.item(), 3), round(b.item(), 3))",
                  "print(\"truth  :\", 3.0, 2.0)             # compare with the truth",
                  "plt.plot(hist); plt.yscale(\"log\")         # see the late descent",
                  "plt.savefig(\"loss.png\")                  # submit: loss curve",
              ]}},
         ],
         "note": {"zh": "把 lr 分别改成 0.001、0.1、1.0 各跑一次，三条曲线画在同一张图上 —— 这就是作业里要求的对照实验。",
                  "en": "Run it three times with lr = 0.001, 0.1 and 1.0, and plot the three curves together - that is the comparison the assignment asks for."}},

        {"type": "checklist", "top": 3.55, "h": 2.05,
         "title": {"zh": "实验 1 提交清单", "en": "Experiment 1 Submission Checklist"},
         "right": {"zh": "模块一 · Week 2", "en": "Module 1 · Week 2"},
         "items": [
             {"badge": {"zh": "必交", "en": "MUST"}, "accent": "1E4FA8",
              "title": {"zh": "损失曲线图", "en": "Loss curve"},
              "desc": {"zh": "三条学习率曲线叠在同一张图上，并标出各自的收敛点与结论。",
                       "en": "Three learning-rate curves on one figure, each with its convergence point and a reading."}},
             {"badge": {"zh": "必交", "en": "MUST"}, "accent": "1E4FA8",
              "title": {"zh": "参数收敛对比表", "en": "Parameter convergence table"},
              "desc": {"zh": "训练得到的 w、b 与真值、闭式最小二乘解并排，给出相对误差并说明三者为何不相等。",
                       "en": "Trained w and b beside the truth and the closed-form OLS solution, with relative errors and why they differ."}},
             {"badge": {"zh": "必交", "en": "MUST"}, "accent": "1E4FA8",
              "title": {"zh": "形状变换踩坑记录", "en": "Shape pitfall log"},
              "desc": {"zh": "至少两条：写下错误写法、完整报错信息、以及你最终如何修复。",
                       "en": "At least two entries: the wrong expression, the full error message, and how you fixed it."}},
             {"badge": {"zh": "必交", "en": "MUST"}, "accent": "1E4FA8",
              "title": {"zh": "可复现命令", "en": "Reproducible command"},
              "desc": {"zh": "README 里一行命令、固定种子、环境版本齐全，别人能跑出同一条曲线。",
                       "en": "One command in the README plus the seed and the environment version, so others reproduce the same curve."}},
             {"badge": {"zh": "必交", "en": "MUST"}, "accent": "1E4FA8",
              "title": {"zh": "AI 协同记录至少 1 条", "en": "At least one AI collaboration trace"},
              "desc": {"zh": "AI 生成的代码中你发现了什么问题、如何修正，附上修改前后的对照。",
                       "en": "What you found wrong in the AI-generated code and how you fixed it, with a before/after comparison."}},
         ]},

        {"type": "compare",
         "title": {"zh": "AI 生成代码：骨架可用，错误要你自己找",
                   "en": "AI-Generated Code: the Skeleton Works, the Bugs Are Yours"},
         "subtitle": {"zh": "用 AI 生成 → 逐行解释 → 找出形状与广播错误 → 形成对照记录",
                      "en": "Generate with AI, explain line by line, find the shape and broadcast bugs, keep the record"},
         "right": {"zh": "模块一 · Week 2", "en": "Module 1 · Week 2"},
         "columns": [
             {"title": {"zh": "AI 给的那一版（看起来对）", "en": "The Version AI Hands You (Looks Right)"},
              "accent": "1E4FA8", "bg": "F0F5FC",
              "items": [
                  {"zh": "数据生成、前向、MSE、backward 的骨架基本正确",
                   "en": "The skeleton for data, forward, MSE and backward is broadly correct"},
                  {"zh": "循环结构合理，超参数也放在显眼的位置",
                   "en": "The loop is reasonable and the hyper-parameters sit in plain sight"},
                  {"zh": "问题在于它是「看起来对」，不是「验证过对」",
                   "en": "The problem is that it looks right rather than being verified right"},
                  {"zh": "直接提交它，等于把调试责任交给一个不会替你答辩的人",
                   "en": "Submitting it as-is hands the debugging to someone who will not defend your work"}]},
             {"title": {"zh": "逐行检查后找出的四个问题", "en": "Four Bugs Found by Reading Line by Line"},
              "accent": "B91C1C", "bg": "FEF2F2",
              "items": [
                  {"zh": "没有 w.grad.zero_()：梯度累加，损失在 3 到 14 之间震荡",
                   "en": "No w.grad.zero_(): gradients accumulate and the loss swings between 3 and 14"},
                  {"zh": "y 用 (n,) 而不是 (n,1)：广播成 (n,n)，MSE 量级完全错",
                   "en": "y is (n,) not (n,1): broadcasting gives (n,n) and the MSE scale is wrong"},
                  {"zh": "更新没有放进 with torch.no_grad(): 更新被记进图，显存缓慢增长",
                   "en": "The update is outside no_grad: it enters the graph and memory creeps up"},
                  {"zh": "没有固定种子：每次跑出来的曲线都不同，无法做对照",
                   "en": "No fixed seed: every run gives a different curve, so no comparison is possible"}]},
             {"title": {"zh": "逐行解释时必须回答的四个问题", "en": "Four Questions You Must Answer Line by Line"},
              "accent": "059669", "bg": "ECFDF5",
              "items": [
                  {"zh": "这一行输入和输出的 shape 分别是什么？", "en": "What are the input and output shapes of this line?"},
                  {"zh": "它的梯度会被累加吗？谁负责清零？", "en": "Will its gradient accumulate, and who zeroes it?"},
                  {"zh": "它在计算图里吗？为什么在、为什么不在？",
                   "en": "Is it in the graph? Why, or why not?"},
                  {"zh": "把 (3,) 换成 (3,1)，这一行的结果会变成什么？",
                   "en": "Replace (3,) with (3,1): what does this line return now?"},
                  {"zh": "解释不出来的一行，就不要留在提交里", "en": "A line you cannot explain does not belong in the submission"}]},
         ],
         "note": {"zh": "协同记录要写的不是「AI 帮了我」，而是「AI 在这里错了，我是这样发现的」。第二个错误（(n,) 的广播）不会报错，只能靠形状检查发现。",
                  "en": "A trace says \"the AI was wrong here, and this is how I found it\" - not \"the AI helped me\". The second bug, the (n,) broadcast, raises no error and can only be caught by a shape check."}},

        {"type": "cards", "cols": 3, "h": 6.8, "top": 3.5,
         "title": {"zh": "课程思政 · 严谨求实：为什么必须固定随机种子",
                   "en": "Professional Integrity: Why the Seed Must Be Fixed"},
         "right": {"zh": "模块一 · Week 2", "en": "Module 1 · Week 2"},
         "cards": [
             {"title": {"zh": "随机是训练的一部分", "en": "Randomness Is Part of Training"},
              "title_en": "so pin it down",
              "body": [{"zh": "初始化、噪声、打乱顺序都是随机的，它们都会改变结果",
                        "en": "Initialisation, noise and shuffling are random and all change the result"},
                       {"zh": "不固定种子，你的实验就无法被任何人复核 —— 包括三天后的你自己",
                        "en": "Without a seed nobody can re-check your run - including you in three days"},
                       {"zh": "torch.manual_seed(42) 一行，换来的是「可验证」",
                        "en": "One line, torch.manual_seed(42), buys you verifiability"}]},
             {"title": {"zh": "科学结论要求可复现", "en": "Reproducibility Is the Standard"},
              "title_en": "not a nice-to-have",
              "accent": "059669", "bg": "ECFDF5",
              "body": [{"zh": "一次跑出来的好结果不是结论，能被重复出来的才是",
                        "en": "One good run is not a conclusion; a repeatable one is"},
                       {"zh": "报告三件套：种子、环境版本、一行可运行的命令",
                        "en": "Every report carries three things: seed, environment version, one runnable command"},
                       {"zh": "换设备出现微小差异很正常，如实写明即可，不要悄悄取最好那次",
                        "en": "Small cross-device differences are normal; state them instead of quietly keeping the best run"}]},
             {"title": {"zh": "把错误留在记录里", "en": "Keep the Errors in the Record"},
              "title_en": "failures are evidence",
              "accent": "D97706", "bg": "FFFBEB",
              "body": [{"zh": "形状报错和调试过程是能力证据，不是需要藏起来的扣分项",
                        "en": "Shape errors and debugging are evidence of skill, not marks to hide"},
                       {"zh": "只贴成功结果的报告，反而无法说明你是否真的动过手",
                        "en": "A report with only the successful run says nothing about whether you did the work"},
                       {"zh": "严谨求实的底线：不编造输出，不美化曲线",
                        "en": "The bottom line: never fabricate output, never prettify a curve"}]},
         ]},

        # ------------------------------------------------------ quiz (p28) --
        {"type": "quiz", "cols": 2, "h": 4.15, "top": 3.1,
         "title": {"zh": "随堂小测", "en": "Quick Check"},
         "right": {"zh": "模块一 · Week 2", "en": "Module 1 · Week 2"},
         "questions": [
             {"tag": {"zh": "形状", "en": "Shapes"},
              "q": {"zh": "X 的形状是 (100, 1)，w 的形状是 (1, 1)，X @ w 的结果形状是？",
                    "en": "X has shape (100, 1) and w has shape (1, 1). What is the shape of X @ w?"},
              "options": [{"zh": "(100, 1)", "en": "(100, 1)"},
                          {"zh": "(100, 100)", "en": "(100, 100)"},
                          {"zh": "(1, 1)", "en": "(1, 1)"},
                          {"zh": "报错，矩阵乘法需要广播", "en": "An error - matrix multiply needs broadcasting"}]},
             {"tag": {"zh": "广播", "en": "Broadcasting"},
              "q": {"zh": "形状 (3, 1) 的张量与形状 (3,) 的张量相加，结果的形状是？",
                    "en": "A tensor of shape (3, 1) is added to one of shape (3,). What shape comes out?"},
              "options": [{"zh": "(3,)", "en": "(3,)"},
                          {"zh": "(3, 1)", "en": "(3, 1)"},
                          {"zh": "(3, 3)", "en": "(3, 3)"},
                          {"zh": "报错，因为维度数不同", "en": "An error - the ranks differ"}]},
             {"tag": {"zh": "求导", "en": "Autograd"},
              "q": {"zh": "x = torch.tensor(2.0, requires_grad=True); y = x ** 3; y.backward() 之后 x.grad 是？",
                    "en": "x = torch.tensor(2.0, requires_grad=True); y = x ** 3; after y.backward(), x.grad is?"},
              "options": [{"zh": "6", "en": "6"},
                          {"zh": "8", "en": "8"},
                          {"zh": "12", "en": "12"},
                          {"zh": "None", "en": "None"}]},
             {"tag": {"zh": "排查", "en": "Debug"},
              "q": {"zh": "训练中损失始终来回震荡、不下降，最先应该检查什么？",
                    "en": "During training the loss keeps oscillating and never falls. What should you check first?"},
              "options": [{"zh": "换一个更大的模型", "en": "Switch to a bigger model"},
                          {"zh": "每一步是否清零了梯度", "en": "Whether the gradients are zeroed each step"},
                          {"zh": "把数据全部归一化", "en": "Normalise all the data"},
                          {"zh": "换成 GPU 训练", "en": "Move the run onto a GPU"}]},
         ]},

        # --------------------------------------------------- summary (p29) --
        {"type": "summary",
         "title": {"zh": "本周小结", "en": "Week 2 Summary"},
         "right": {"zh": "模块一 · Week 2", "en": "Module 1 · Week 2"},
         "points": [
             {"zh": "张量是唯一的数据容器：拿到它先报出四项 —— shape、dtype、device、requires_grad。",
              "en": "A tensor is the only container: report four things first - shape, dtype, device, requires_grad."},
             {"zh": "形状变换优先 reshape，补维用 unsqueeze(1)；view 只在连续张量上安全，非连续请用 contiguous 或 reshape。",
              "en": "Prefer reshape; add dimensions with unsqueeze(1); view is safe only on contiguous tensors."},
             {"zh": "广播从最右一维对齐、遇 1 就复制：(3,) 与 (3,1) 相加会静默得到 (3,3) —— 这是本周最危险的错误。",
              "en": "Broadcasting aligns from the right and stretches every 1: (3,) plus (3,1) silently gives (3,3) - this week's most dangerous bug."},
             {"zh": "autograd 只有两条规则：只有叶子张量的 .grad 被填充，而且 .grad 是累加的。",
              "en": "Autograd has two rules: only leaves receive .grad, and .grad accumulates."},
             {"zh": "参数更新四件套：backward → no_grad 里更新 → 立刻清零梯度 → 记录损失。顺序不能乱。",
              "en": "Four moves per update: backward, update under no_grad, zero the grads, log the loss - in that order."},
         ],
         "todo_title": {"zh": "课后待办", "en": "After Class"},
         "todos": [
             {"title": {"zh": "完成实验 1 报告", "en": "Finish the Lab 1 report"},
              "desc": {"zh": "损失曲线（三种学习率）、参数收敛对比、形状变换踩坑记录、可复现命令。",
                       "en": "Loss curves for three learning rates, the parameter comparison, the shape pitfall log, and a reproducible command."}},
             {"title": {"zh": "提交至少 1 条 AI 协同记录", "en": "Submit at least one AI collaboration trace"},
              "desc": {"zh": "AI 生成的代码中你发现了什么问题、如何修正，附修改前后的对照。",
                       "en": "What you found wrong in the AI-generated code and how you fixed it, with a before/after comparison."}},
         ]},

        # --------------------------------------------------- closing (p30) --
        {"type": "closing",
         "quote": {"zh": "「模型不会自己变好，\n是你每一步都在正确地改它。」",
                   "en": "\"A model does not improve by itself -\nyou change it correctly, one step at a time.\""},
         "quote_sub": {"zh": "本周交付：一条手写的训练循环 + 一张能解释的损失曲线 + 一份形状踩坑记录。",
                       "en": "This week you deliver: a hand-written training loop + a loss curve you can explain + a shape pitfall log."},
         "thanks": {"zh": "谢谢大家", "en": "Thank you"},
         "next_label": {"zh": "下周预告", "en": "Next week"},
         "next": {"zh": "W3 · 机器学习基础与 scikit-learn 工作流 —— 同一条直线，换一批工具，看框架替你做了什么、又替你藏了什么。",
                  "en": "W3 · Machine learning foundations and the scikit-learn workflow - the same straight line, different tools: what the framework does for you, and what it hides from you."}},
    ],
}
