"""Week 7 — CNNs for Computer Vision · slide spec (bilingual).

Aligned with the official course documents (52015CC3BV):
CU(7) · Module 2 "Core Deep Learning" (Week 5-8).
KT13 convolution, pooling and receptive fields (understand);
KT14 building a CNN, vision applications, GPU training and memory (apply).

Every experimental number in this deck comes from
`scripts/w7_cnn_experiment.py` -> `outputs/w7_cnn.json`
(5 architectures x 5 seeds, plus the shift probe, the confusion matrix, the
gradient-accumulation probe and the memory sweep). Do NOT hand-edit those
numbers; re-run the script instead.

The spine of the week is deliberately NOT "the CNN is more accurate" — the
numbers do not say that. They say the CNN matches a 9x larger MLP, and that
augmentation trades clean accuracy for translation robustness.
"""

EPOCHS_X = [str(i * 6 + 1) for i in range(20)]        # 1, 7, ..., 115

# --- seed 42, every 6 epochs (from outputs/w7_cnn.json) ----------------------
MLP_VAL = [0.7037, 0.9037, 0.9519, 0.9593, 0.9556, 0.9593, 0.9704, 0.9741,
           0.9593, 0.9741, 0.9704, 0.9704, 0.9704, 0.9741, 0.9704, 0.9741,
           0.9741, 0.9741, 0.9741, 0.9741]
CNN_VAL = [0.3111, 0.8259, 0.8852, 0.9296, 0.9407, 0.9556, 0.963, 0.9704,
           0.9667, 0.9667, 0.9704, 0.9704, 0.9704, 0.9667, 0.9741, 0.9741,
           0.9667, 0.9741, 0.9741, 0.9741]
AUG_VAL = [0.1889, 0.6407, 0.7222, 0.7667, 0.7519, 0.8407, 0.8222, 0.8037,
           0.8481, 0.8519, 0.8444, 0.8296, 0.8667, 0.8667, 0.8593, 0.8815,
           0.8667, 0.8926, 0.8926, 0.9]

# --- test-time translation (dx), 5-seed means --------------------------------
SHIFT_X = ["-2", "-1", "0", "+1", "+2"]
SHIFT_MLP = [0.1667, 0.4555, 0.9785, 0.5089, 0.1822]
SHIFT_CNN = [0.2348, 0.6481, 0.9808, 0.6504, 0.2778]
SHIFT_AUG = [0.517, 0.9415, 0.9504, 0.9526, 0.5518]

# --- peak RSS above the interpreter+torch baseline (MB), 32x32 probe ---------
MEM_X = ["32", "64", "128", "256", "512", "1024"]
MEM_OVER = [83.6, 91.3, 104.3, 129.7, 176.5, 275.5]

MOD = {"zh": "模块二 · Week 7", "en": "Module 2 · Week 7"}
PROTO = {"zh": "digits 8×8 · 70/15/15 · 训练集 n=1258 · Adam 1e-3 · batch 64 · 120 轮 · 5 个随机种子",
         "en": "digits 8x8 · 70/15/15 · n_train=1258 · Adam 1e-3 · batch 64 · 120 epochs · 5 seeds"}
# The three charts plot a single seed-42 run, so they need their own subtitle —
# the table's numbers are 5-seed means and must not be read off the curves.
CURVE_PROTO = {"zh": "曲线：seed 42 单次运行的验证准确率，每 6 轮取一点（第 1, 7, …, 115 轮）｜表中统计量为 5 个种子（42–46）的均值",
               "en": "Curve: validation accuracy of one seed-42 run, one point every 6 epochs (1, 7, ..., 115) | table figures are means over 5 seeds (42-46)"}
SHIFT_PROTO = {"zh": "测试时把整张图平移 dx 列（用 0 填充边缘），不动任何权重；每个格是 5 个种子的均值",
               "en": "Test images translated by dx columns at test time (zero-filled edges), no weight change; each cell is a mean over 5 seeds"}
MEM_PROTO = {"zh": "输入用最近邻上采样到 32×32（激活体量 ×16，与真实视觉模型同量级），单次前向+反向，独立子进程测峰值 RSS；macOS 的 ru_maxrss 单位是字节",
             "en": "Input nearest-neighbour upsampled to 32x32 (16x the activation volume, the order of a real vision model); one forward+backward per subprocess, peak RSS; ru_maxrss is in BYTES on macOS"}


def zh(en):  # tiny helper: same string both languages (numbers, code, symbols)
    return {"zh": en, "en": en}


SPEC = {
    "week": 7,
    "slides": [
        # ---------------------------------------------------------- cover ----
        {"type": "cover",
         "kicker": {"zh": "52015CC3BV · 本科 · 来华项目",
                    "en": "52015CC3BV · UNDERGRADUATE · INTERNATIONAL"},
         "title": {"zh": "卷积神经网络与计算机视觉应用",
                   "en": "CNNs for Computer Vision"},
         "title_sub": {"zh": "CNNs for Computer Vision",
                       "en": "Convolution, shape arithmetic, pooling — and where the model is wrong"},
         "subtitle": {"zh": "Week 7 · 卷积与权值共享 · 步长/填充/感受野 · 池化选择 · 数据增强的代价 · 混淆矩阵与错分分析 · 显存与梯度累积 · 实验 6",
                      "en": "Week 7 · Convolution and weight sharing · Stride, padding, receptive field · Pooling choice · The price of augmentation · Confusion matrix and error analysis · Memory and gradient accumulation · Lab 6"},
         "chips": [
             ({"zh": "模块二 · W5–8", "en": "Module 2 · W5-8"}, 1.0),
             ({"zh": "180 min · 授课 + 实验 + 小测", "en": "180 min · Lecture + Lab + Quiz"}, 1.5),
             ({"zh": "KT13 · KT14", "en": "KT13 · KT14"}, 0.9),
             ({"zh": "留学生班 · 英文授课", "en": "International Students"}, 1.0),
         ]},

        # ------------------------------------------------------- contents ----
        {"type": "contents",
         "count": {"zh": "5", "en": "5"},
         "count_label": {"zh": "个部分 · 一天 180 分钟", "en": "PARTS · 180 MINUTES"},
         "tagline": {"zh": "本周的主线不是「CNN 更准」——实测不支持这个说法。\n主线是：CNN 用 1/9 的参数拿到同样的准确率，\n而且更抗平移；但为「抗平移」付的钱，\n会直接从干净测试集的分数里扣。",
                     "en": "This week's spine is NOT \"the CNN is more accurate\" —\nthe numbers do not support that. It is: the CNN matches a\n9x larger MLP and moves better under translation; and the\nprice of that robustness is paid on the clean test set."},
         "timing": {"zh": "复习与导入 10 min\n新课讲授 80 min\n随堂实验 80 min\n小结与作业 10 min",
                    "en": "Review & lead-in 10 min\nLecture 80 min\nLab 80 min\nWrap-up 10 min"},
         "parts": [
             {"title": {"zh": "卷积：从全连接到权值共享", "en": "Convolution: from dense layers to weight sharing"},
              "title_en": {"zh": "Convolution: weight sharing", "en": "Convolution: weight sharing"},
              "desc": {"zh": "为什么图像不能直接铺平 · 参数量对比 17 226 → 1 898",
                       "en": "Why images are not flattened · 17,226 → 1,898 parameters"}},
             {"title": {"zh": "形状的算术", "en": "The arithmetic of shapes"},
              "title_en": {"zh": "Stride · padding · pooling · receptive field", "en": "Stride · padding · pooling · receptive field"},
              "desc": {"zh": "输出尺寸公式 + 实测校验 · 感受野 3 → 4 → 8 → 10 · 池化的选择值 4.1 个点",
                       "en": "Output-size formula checked against real tensors · RF 3 → 4 → 8 → 10 · pooling choice costs 4.1 points"}},
             {"title": {"zh": "训练起来：曲线、增强与代价", "en": "Training it: curves, augmentation and the price"},
              "title_en": {"zh": "Curves, augmentation, robustness", "en": "Curves, augmentation, robustness"},
              "desc": {"zh": "5 个架构的 5 种子总表 · 平移鲁棒性实测 · 增强的账本",
                       "en": "5 architectures x 5 seeds · measured translation robustness · the augment ledger"}},
             {"title": {"zh": "看它错在哪", "en": "Where it fails"},
              "title_en": {"zh": "Confusion matrix and misclassification", "en": "Confusion matrix and misclassification"},
              "desc": {"zh": "1350 个测试样本的混淆矩阵 · 最差类对 · 把错分的数字本身画出来",
                       "en": "Confusion over 1,350 test predictions · the worst class pair · the misclassified digits themselves"}},
             {"title": {"zh": "显存与绿色计算", "en": "Memory and green computing"},
              "title_en": {"zh": "Batch size · gradient accumulation", "en": "Batch size · gradient accumulation"},
              "desc": {"zh": "batch → 峰值内存实测 · 梯度累积的三种权重 · 算力是有限资源",
                       "en": "Measured batch → peak memory · three accumulation weightings · compute is finite"}},
         ]},

        # ================================================== PART 01 =========
        {"type": "section", "num": "01",
         "title": {"zh": "卷积：从全连接到权值共享", "en": "Convolution"},
         "title_en": {"zh": "From dense layers to weight sharing", "en": "From dense layers to weight sharing"},
         "lead": {"zh": "把 8×8 的图铺平成 64 维向量，喂给全连接层——这在大图上会立刻崩掉。\n卷积做的不是「更聪明的分类器」，而是**对参数的数量动手**。",
                  "en": "Flatten an 8x8 image into 64 numbers and hand it to a dense layer — this collapses on real images. Convolution is not a cleverer classifier; it attacks the NUMBER of parameters."},
         "pillars": [
             {"title": {"zh": "局部连接", "en": "Local"}, "sub": {"zh": "一个输出只看一小块", "en": "one output sees a patch"}},
             {"title": {"zh": "权值共享", "en": "Shared"}, "sub": {"zh": "同一个核滑过全图", "en": "one kernel, every position"}},
             {"title": {"zh": "参数可控", "en": "Cheap"}, "sub": {"zh": "参数量与图宽无关", "en": "params do not scale with width"}},
         ]},

        {"type": "cards", "cols": 3, "h": 12.0, "top": 3.6,
         "title": {"zh": "为什么不能直接把图像铺平", "en": "Why images are not simply flattened"},
         "right": {"zh": "Week 7 · 引入", "en": "Week 7 · lead-in"},
         "subtitle": {"zh": "三个理由，每一个都能用本周的实验数字验证",
                      "en": "Three reasons, each checkable against this week's numbers"},
         "cards": [
             {"title": {"zh": "① 参数会爆炸", "en": "1. Parameters explode"},
              "title_en": {"zh": "17 226 vs 1 898", "en": "17,226 vs 1,898"},
              "body": [{"zh": "同一份 digits 数据上，全连接网 17 226 个参数，两层卷积只要 1 898 个。",
                        "en": "On the same digits data the dense net needs 17,226 parameters; two conv layers need 1,898."},
                       {"zh": "这不是「省一点」，是差 9 倍。真实图像的输入维度是它的 1000 倍以上。",
                        "en": "Not a small saving — 9x. Real images have 1000x that input dimension."}],
              "accent": "1E4FA8"},
             {"title": {"zh": "② 铺平会丢掉空间结构", "en": "2. Flattening discards layout"},
              "title_en": {"zh": "邻居关系被销毁", "en": "neighbourhood is destroyed"},
              "body": [{"zh": "铺平之后，8×8 里相邻的两个像素和隔着整行的两个像素，在全连接层眼里没有区别。",
                        "en": "After flattening, two adjacent pixels and two a whole row apart look identical to a dense layer."},
                       {"zh": "卷积层保留了这个结构——这正是它能共享权重的前提。",
                        "en": "A conv layer keeps that structure — which is exactly what makes weight sharing possible."}],
              "accent": "D97706"},
             {"title": {"zh": "③ 平移不该是「新样本」", "en": "3. A shift is not a new object"},
              "title_en": {"zh": "同一手写数字右移 1 列", "en": "same digit, shifted 1 column"},
              "body": [{"zh": "全连接网必须为每个位置单独学一遍。实测：把它右移 1 列，准确率从 0.9785 掉到 0.5089。",
                        "en": "A dense net must relearn it at every position. Measured: shift one column right and accuracy falls 0.9785 → 0.5089."},
                       {"zh": "卷积把「同一个模式出现在哪里」这件事，写进了结构里。",
                        "en": "Convolution bakes \"a pattern, wherever it appears\" into the architecture."}],
              "accent": "059669"},
         ]},

        {"type": "code",
         "title": {"zh": "卷积就是一次滑动点积——先把这句话写成代码", "en": "A convolution is one sliding dot product — write it once by hand"},
         "right": {"zh": "KT13", "en": "KT13"},
         "subtitle": {"zh": "手写实现不是让你以后都手写，是为了让「特征图」「步长」「填充」这三个词有具体含义",
                      "en": "The hand-written version is not what you will ship; it is what makes feature map, stride and padding mean something"},
         "blocks": [
             {"title": {"zh": "① 朴素实现：一个 3×3 核滑过 8×8", "en": "1. Naive: one 3x3 kernel over an 8x8 image"},
              "size": 10,
              "code": {"zh": [
                  "def conv2d_naive(img, kernel, stride=1, pad=0):",
                  "    # img: (H, W)   kernel: (kh, kw)",
                  "    H, W = img.shape",
                  "    kh, kw = kernel.shape",
                  "    if pad:",
                  "        img = F.pad(img, (pad,) * 4)",
                  "        H, W = H + 2 * pad, W + 2 * pad",
                  "    oh = (H - kh) // stride + 1",
                  "    ow = (W - kw) // stride + 1",
                  "    out = torch.zeros(oh, ow)",
                  "    for i in range(oh):",
                  "        for j in range(ow):",
                  "            patch = img[i*stride : i*stride+kh,",
                  "                        j*stride : j*stride+kw]",
                  "            out[i, j] = (patch * kernel).sum()",
                  "    return out",
              ],
              "en": [
                  "def conv2d_naive(img, kernel, stride=1, pad=0):",
                  "    # img: (H, W)   kernel: (kh, kw)",
                  "    H, W = img.shape",
                  "    kh, kw = kernel.shape",
                  "    if pad:",
                  "        img = F.pad(img, (pad,) * 4)",
                  "        H, W = H + 2 * pad, W + 2 * pad",
                  "    oh = (H - kh) // stride + 1",
                  "    ow = (W - kw) // stride + 1",
                  "    out = torch.zeros(oh, ow)",
                  "    for i in range(oh):",
                  "        for j in range(ow):",
                  "            patch = img[i*stride : i*stride+kh,",
                  "                        j*stride : j*stride+kw]",
                  "            out[i, j] = (patch * kernel).sum()",
                  "    return out",
              ]}},
             {"title": {"zh": "② 与 nn.Conv2d 对齐（断言，不是相信）", "en": "2. Check it against nn.Conv2d (assert, do not trust)"},
              "size": 10,
              "code": {"zh": [
                  "torch.manual_seed(0)",
                  "img    = torch.randn(8, 8)",
                  "kernel = torch.randn(3, 3)",
                  "",
                  "mine = conv2d_naive(img, kernel, stride=1, pad=1)",
                  "",
                  "conv = nn.Conv2d(1, 1, 3, stride=1, padding=1,",
                  "                 bias=False)",
                  "conv.weight.data = kernel.view(1, 1, 3, 3)",
                  "ref = conv(img.view(1, 1, 8, 8))[0, 0]",
                  "",
                  "assert mine.shape == ref.shape == (8, 8)",
                  "assert torch.allclose(mine, ref, atol=1e-5)",
                  "print('hand-written == nn.Conv2d')",
                  "",
                  "# 感受野：这一层的每个输出看了输入多少像素",
                  "# 3x3 核 -> 3；再叠一层 3x3 -> 5；再加池化 -> 更长",
              ],
              "en": [
                  "torch.manual_seed(0)",
                  "img    = torch.randn(8, 8)",
                  "kernel = torch.randn(3, 3)",
                  "",
                  "mine = conv2d_naive(img, kernel, stride=1, pad=1)",
                  "",
                  "conv = nn.Conv2d(1, 1, 3, stride=1, padding=1,",
                  "                 bias=False)",
                  "conv.weight.data = kernel.view(1, 1, 3, 3)",
                  "ref = conv(img.view(1, 1, 8, 8))[0, 0]",
                  "",
                  "assert mine.shape == ref.shape == (8, 8)",
                  "assert torch.allclose(mine, ref, atol=1e-5)",
                  "print('hand-written == nn.Conv2d')",
                  "",
                  "# receptive field: how much input one output sees",
                  "# 3x3 -> 3; a second 3x3 -> 5; add pooling -> more",
              ]}},
         ],
         "note": {"zh": "跑通这一页你就知道了：所谓「卷积」的全部算术，就是「取一块、逐元素相乘、求和」重复若干次。剩下的都是工程。",
                  "en": "Once this page runs you know that all a convolution does is take a patch, multiply element-wise, and sum — repeated. Everything else is engineering."}},

        {"type": "table",
         "title": {"zh": "参数量：逐层对账", "en": "Where the parameters actually are"},
         "right": {"zh": "实测", "en": "measured"},
         "subtitle": {"zh": "同一份 digits 8×8 数据，同一个切分。参数量由代码数出来，不是估算",
                      "en": "Same digits 8x8 data, same split. Parameter counts are counted by the code, not estimated"},
         "cols": [{"zh": "层", "en": "Layer"}, {"zh": "形状", "en": "Shape"},
                  {"zh": "参数", "en": "Params"}, {"zh": "累计", "en": "Running"}],
         "rows": [
             [{"zh": "输入", "en": "Input"}, {"zh": "1×8×8", "en": "1x8x8"}, "0", "0"],
             [{"zh": "全连接 64→128", "en": "Dense 64→128"}, {"zh": "64→128", "en": "64→128"}, "8 320", "8 320"],
             [{"zh": "全连接 128→64", "en": "Dense 128→64"}, {"zh": "128→64", "en": "128→64"}, "8 256", "16 576"],
             [{"zh": "全连接 64→10", "en": "Dense 64→10"}, {"zh": "64→10", "en": "64→10"}, "650", "17 226"],
             [{"zh": "卷积 1→8，3×3", "en": "Conv 1→8, 3x3"}, {"zh": "8×8×8", "en": "8x8x8"}, "80", "80"],
             [{"zh": "卷积 8→16，3×3", "en": "Conv 8→16, 3x3"}, {"zh": "16×4×4", "en": "16x4x4"}, "1 168", "1 248"],
             [{"zh": "全连接 64→10", "en": "Dense 64→10"}, {"zh": "64→10", "en": "64→10"}, "650", "1 898"],
         ],
         "widths": [7.6, 6.0, 7.4, 8.4],
         "bold_first": True,
         "note": {"zh": "上半是本周对照用的全连接网，下半是两层卷积加一个线性头。17 226 → 1 898，少 9 倍；而两者的测试准确率是 0.979 与 0.981——差 0.002，不到一个标准差（0.008）。",
                  "en": "Top block is the dense net used as this week's control, bottom is two conv layers plus a linear head. 17,226 → 1,898, 9x fewer; test accuracy 0.979 against 0.981 — a 0.002 gap, smaller than one standard deviation (0.008)."}},

        {"type": "compare",
         "title": {"zh": "权值共享买到了什么，又付出了什么", "en": "What weight sharing buys, and what it costs"},
         "right": {"zh": "KT13", "en": "KT13"},
         "columns": [
             {"title": {"zh": "买到的", "en": "What you get"},
              "accent": "059669",
              "items": [
                  {"zh": "参数量与图像宽度**无关**——同一个 3×3 核滑过 8×8 和 1024×1024",
                   "en": "Parameter count is INDEPENDENT of image width — the same 3x3 kernel walks an 8x8 and a 1024x1024"},
                  {"zh": "「同一个模式在任何位置」被写进结构，而不是靠数据学出来",
                   "en": "\"a pattern, anywhere\" is built into the architecture instead of learned from data"},
                  {"zh": "实测：平移一列，卷积网 0.6481，全连接 0.4555（+19 个点）",
                   "en": "Measured: shift one column, 0.6481 for the CNN against 0.4555 for the dense net (+19 points)"},
              ]},
             {"title": {"zh": "付出的", "en": "What it costs"},
              "accent": "D97706",
              "items": [
                  {"zh": "局部性是**假设**，不是真理。如果你的模式是全局的（比如「整张图的亮度分布」），这个假设就是错的",
                   "en": "Locality is an ASSUMPTION, not a fact. If your pattern is global (the overall brightness histogram), the assumption is wrong"},
                  {"zh": "感受野是有限的——最后一层卷积只看得到 8×8 的输入（正好整图），但真实模型需要很多层才能看全",
                   "en": "The receptive field is finite — the last conv here sees the whole 8x8, but real models need many layers to see everything"},
                  {"zh": "池化会丢位置信息，而有些任务恰恰要位置",
                   "en": "Pooling throws away position, and some tasks need position"},
              ]},
         ],
         "note": {"zh": "一句话记法：卷积不是「更强的层」，是「一个关于数据结构的假设换来的参数效率」。假设错了，它比全连接更差。",
                  "en": "One line to remember: a conv layer is not a stronger layer, it is parameter efficiency bought with an assumption about the data. When the assumption is wrong, it is worse than dense."}},

        # ================================================== PART 02 =========
        {"type": "section", "num": "02",
         "title": {"zh": "形状的算术", "en": "The arithmetic of shapes"},
         "title_en": {"zh": "Stride, padding, pooling, receptive field", "en": "Stride, padding, pooling, receptive field"},
         "lead": {"zh": "形状错误是深度学习里最常见的报错，也是最容易一次学会的。\n下面每一条公式，都在真实张量上验算过。",
                  "en": "Shape errors are the most common failure in deep learning and the cheapest to eliminate. Every formula below is checked against a real tensor."},
         "pillars": [
             {"title": {"zh": "输出尺寸", "en": "Output size"}, "sub": {"zh": "(H+2p−k)/s+1", "en": "(H+2p-k)/s+1"}},
             {"title": {"zh": "感受野", "en": "Receptive field"}, "sub": {"zh": "3 → 4 → 8 → 10", "en": "3 → 4 → 8 → 10"}},
             {"title": {"zh": "池化", "en": "Pooling"}, "sub": {"zh": "选择值 4.1 个点", "en": "worth 4.1 points"}},
         ]},

        {"type": "code",
         "title": {"zh": "输出尺寸公式，与真实张量逐项核对", "en": "The output-size formula, checked against real tensors"},
         "right": {"zh": "KT13 · 可验证", "en": "KT13 · verifiable"},
         "subtitle": {"zh": "四条公式全部与模型真实前向的形状一致（脚本里的断言，不是我说的一致）",
                      "en": "All four formulas match the model's real forward pass — an assertion in the script, not a claim"},
         "blocks": [
             {"title": {"zh": "① 公式", "en": "1. The formula"},
              "size": 11,
              "code": {"zh": [
                  "def out_size(size, k, s, p):",
                  "    return (size + 2 * p - k) // s + 1",
                  "",
                  "# 常用取值速查（输入 8x8）",
                  "#  k=3, s=1, p=1  ->  8   尺寸不变",
                  "#  k=3, s=1, p=0  ->  6   每层小 2",
                  "#  k=2, s=2, p=0  ->  4   池化：减半",
                  "#  k=3, s=2, p=1  ->  4   下采样",
                  "#  k=1, s=1, p=0  ->  8   1x1 卷积：只换通道",
                  "",
                  "k, s, p = 3, 1, 1",
                  "print(out_size(8, k, s, p))     # 8",
              ],
              "en": [
                  "def out_size(size, k, s, p):",
                  "    return (size + 2 * p - k) // s + 1",
                  "",
                  "# common cases (8x8 input)",
                  "#  k=3, s=1, p=1  ->  8   same size",
                  "#  k=3, s=1, p=0  ->  6   two smaller",
                  "#  k=2, s=2, p=0  ->  4   pooling: halve",
                  "#  k=3, s=2, p=1  ->  4   downsample",
                  "#  k=1, s=1, p=0  ->  8   1x1 conv: channels only",
                  "",
                  "k, s, p = 3, 1, 1",
                  "print(out_size(8, k, s, p))     # 8",
              ]}},
             {"title": {"zh": "② 与真实前向对照（脚本实际跑的）", "en": "2. Against the real forward (what the script runs)"},
              "size": 11,
              "code": {"zh": [
                  "stages = [('conv',3,1,1), ('pool',2,2,0),",
                  "          ('conv',3,1,1), ('pool',2,2,0)]",
                  "",
                  "size = 8",
                  "for kind, k, s, p in stages:",
                  "    size = out_size(size, k, s, p)",
                  "    print(kind, '->', size)",
                  "# conv -> 8",
                  "# pool -> 4",
                  "# conv -> 4",
                  "# pool -> 2",
                  "",
                  "# 实测（脚本断言）：",
                  "# conv  formula 8  forward 8   OK",
                  "# pool  formula 4  forward 4   OK",
                  "# conv  formula 4  forward 4   OK",
                  "# pool  formula 2  forward 2   OK",
                  "# flatten = 16 * 2 * 2 = 64",
              ],
              "en": [
                  "stages = [('conv',3,1,1), ('pool',2,2,0),",
                  "          ('conv',3,1,1), ('pool',2,2,0)]",
                  "",
                  "size = 8",
                  "for kind, k, s, p in stages:",
                  "    size = out_size(size, k, s, p)",
                  "    print(kind, '->', size)",
                  "# conv -> 8",
                  "# pool -> 4",
                  "# conv -> 4",
                  "# pool -> 2",
                  "",
                  "# measured (asserted by the script):",
                  "# conv  formula 8  forward 8   OK",
                  "# pool  formula 4  forward 4   OK",
                  "# conv  formula 4  forward 4   OK",
                  "# pool  formula 2  forward 2   OK",
                  "# flatten = 16 * 2 * 2 = 64",
              ]}},
         ],
         "note": {"zh": "报「shape mismatch」时先算这一页，不要先改代码。90% 的形状错误在这一页就能定位。",
                  "en": "When a shape mismatch fires, do this page first, not the code. Most shape errors are located here."}},

        {"type": "table",
         "title": {"zh": "感受野：每一层的输出，到底看了输入多少", "en": "Receptive field: how much input each stage can see"},
         "right": {"zh": "KT13 · 关键", "en": "KT13 · key"},
         "subtitle": {"zh": "RF 按 rf = rf + (k−1)×jump 递推，jump 每层乘 stride；特征图尺寸由上一页的公式给出",
                      "en": "RF is built by rf = rf + (k-1) x jump, where jump multiplies by stride each stage; feature-map sizes come from the previous page"},
         "cols": [{"zh": "阶段", "en": "Stage"}, {"zh": "k", "en": "k"},
                  {"zh": "s", "en": "s"}, {"zh": "特征图", "en": "Feature map"},
                  {"zh": "感受野", "en": "Receptive field"}, {"zh": "jump", "en": "jump"}],
         "rows": [
             [{"zh": "输入", "en": "Input"}, {"zh": "—", "en": "-"}, {"zh": "—", "en": "-"}, "8×8", "1", "1"],
             [{"zh": "卷积 1", "en": "Conv 1"}, "3", "1", "8×8", "3", "1"],
             [{"zh": "最大池化", "en": "MaxPool"}, "2", "2", "4×4", "4", "2"],
             [{"zh": "卷积 2", "en": "Conv 2"}, "3", "1", "4×4", "**8**", "2"],
             [{"zh": "最大池化", "en": "MaxPool"}, "2", "2", "2×2", "10", "4"],
         ],
         "widths": [5.2, 3.4, 3.4, 6.0, 6.4, 5.0],
         "bold_first": True,
         "note": {"zh": "**关键一行是「卷积 2」：感受野 8，正好等于整张图。** 换句话说，在本周这个 8×8 的数据上，第二层卷积已经能看到全图——网络不可能再靠「多叠卷积」获得更多平移不变性。这不是模型不好，是数据太小。",
                  "en": "The row that matters is Conv 2: receptive field 8, exactly the whole image. On this 8x8 data the second convolution already sees everything, so no amount of extra depth adds translation invariance. That is the data being small, not the model being weak."}},

        {"type": "cards", "cols": 3, "h": 11.6, "top": 3.7,
         "title": {"zh": "池化在做什么——三个作用，一个代价", "en": "What pooling does — three jobs, one price"},
         "right": {"zh": "KT13", "en": "KT13"},
         "subtitle": {"zh": "不是「为了降维」，是三个具体作用；而代价在最后一格里，本周实测 4.1 个点",
                      "en": "Not \"to reduce dimensions\" — three concrete jobs; the price is in the last card, measured at 4.1 points this week"},
         "cards": [
             {"title": {"zh": "① 缩小特征图", "en": "1. Shrinks the map"},
              "body": [{"zh": "8×8 → 4×4 → 2×2。后续层的算力与显存按面积下降。",
                        "en": "8x8 → 4x4 → 2x2. Compute and memory in later layers fall with the area."},
                       {"zh": "这是最常被当成全部的那个作用。",
                        "en": "This is the one everyone mistakes for the whole story."}],
              "accent": "1E4FA8"},
             {"title": {"zh": "② 扩大感受野", "en": "2. Grows the receptive field"},
              "body": [{"zh": "stride 2 的池化让 jump 翻倍。没有它，叠再多 3×3 也只有 3、5、7…",
                        "en": "Stride-2 pooling doubles the jump. Without it, stacked 3x3 convs only reach 3, 5, 7..."},
                       {"zh": "看上一页：加上池化后，第二层卷积就覆盖了整张图。",
                        "en": "See the previous page: with pooling, the second conv already covers the image."}],
              "accent": "059669"},
             {"title": {"zh": "③ 引入小范围容忍，代价：丢位置", "en": "3. Tolerates small shifts — and loses position"},
              "body": [{"zh": "「这一片里有强响应」比「正好第 3 行第 5 列有强响应」更稳。",
                        "en": "\"a strong response somewhere in this patch\" is steadier than \"exactly at row 3, column 5\"."},
                       {"zh": "代价：需要「在哪里」的任务（分割、检测、关键点）必须把位置信息补回来——这是后面几周的事。",
                        "en": "The price: tasks that need WHERE (segmentation, detection, keypoints) must restore position. That is later weeks."}],
              "accent": "D97706"},
         ]},

        {"type": "table",
         "title": {"zh": "池化方式的选择，值 4.1 个点", "en": "The pooling choice is worth 4.1 points"},
         "right": {"zh": "实测 · 5 种子", "en": "measured · 5 seeds"},
         "subtitle": {"zh": "除池化方式外，两个架构**逐字节相同**：同样的通道数、同样的核、同样的学习率与轮数",
                      "en": "Apart from the pooling function the two architectures are byte-for-byte identical: same channels, same kernels, same learning rate and epochs"},
         "cols": [{"zh": "架构", "en": "Architecture"}, {"zh": "池化", "en": "Pooling"},
                  {"zh": "参数量", "en": "Params"}, {"zh": "训练 acc", "en": "Train acc"},
                  {"zh": "验证 acc", "en": "Val acc"}, {"zh": "测试 acc", "en": "Test acc"}],
         "rows": [
             [{"zh": "CNN 小", "en": "CNN small"}, {"zh": "最大池化", "en": "Max"}, "1 898",
              "0.999±0.001", "0.970±0.010", "**0.981±0.008**"],
             [{"zh": "CNN 小", "en": "CNN small"}, {"zh": "平均池化", "en": "Average"}, "1 898",
              "0.950±0.009", "0.929±0.016", "**0.940±0.008**"],
         ],
         "widths": [4.6, 4.2, 4.4, 5.4, 5.4, 5.4],
         "bold_first": True,
         "note": {"zh": "差 0.041，是 5 个标准差的 5 倍——这不是噪声。平均池化在这个任务上把「最强的那个响应」抹平了，而手写数字的判别信息恰恰在「笔画最集中的地方」。选池化函数是在选择你愿意保留什么。",
                  "en": "A 0.041 gap, five times the standard deviation — not noise. Average pooling smooths away the strongest response, and for handwritten digits the discriminative information is exactly where the stroke is densest. Choosing a pooling function is choosing what to keep."}},

        # ================================================== PART 03 =========
        {"type": "section", "num": "03",
         "title": {"zh": "训练起来：曲线、增强与代价", "en": "Training it"},
         "title_en": {"zh": "Curves, augmentation, and the price", "en": "Curves, augmentation, and the price"},
         "lead": {"zh": "本周 5 个架构、每个 5 个随机种子。所有差异都写成「均值 ± 标准差」，\n差异不到一个标准差就写「未观察到显著差异」。",
                  "en": "Five architectures, five seeds each. Every difference is reported as mean ± sd; a difference smaller than one sd is written up as not observed."},
         "pillars": [
             {"title": {"zh": "5 架构", "en": "5 models"}, "sub": {"zh": "全连接 / 卷积 / 宽 / 平均池化 / 增强", "en": "dense / conv / wide / avgpool / aug"}},
             {"title": {"zh": "5 种子", "en": "5 seeds"}, "sub": {"zh": "42–46，均值 ± 标准差", "en": "42-46, mean ± sd"}},
             {"title": {"zh": "1 个对照问题", "en": "1 question"}, "sub": {"zh": "这个改动值不值？", "en": "was it worth it?"}},
         ]},

        {"type": "chart",
         "title": {"zh": "验证准确率：三条曲线，同一个训练协议", "en": "Validation accuracy: three curves, one training protocol"},
         "right": {"zh": "seed 42", "en": "seed 42"},
         "subtitle": CURVE_PROTO,
         "categories": EPOCHS_X,
         "series": [
             {"name": {"zh": "全连接 64-128-64-10", "en": "Dense 64-128-64-10"},
              "values": MLP_VAL, "color": "1E4FA8", "smooth": False},
             {"name": {"zh": "CNN 8/16", "en": "CNN 8/16"},
              "values": CNN_VAL, "color": "059669", "smooth": False, "emphasis": True},
             {"name": {"zh": "CNN + ±1px 增强", "en": "CNN + ±1px augmentation"},
              "values": AUG_VAL, "color": "D97706", "smooth": False},
         ],
         "x_label": {"zh": "训练轮次 epoch", "en": "epoch"},
         "y_label": {"zh": "验证准确率", "en": "validation accuracy"},
         "w": 19.0, "h": 11.2,
         "notes": [
             {"zh": "三条曲线在 20 轮后全部进入平台，之后翻转都是噪声。",
              "en": "All three plateau after ~20 epochs; later wiggles are noise."},
             {"zh": "卷积网起步更慢（第 1 轮 0.31 vs 0.70），40 轮后反超。",
              "en": "The CNN starts slower (0.31 vs 0.70 at epoch 1) and overtakes by epoch 40."},
             {"zh": "增强那条曲线**更低但更稳**——这不是训练失败，是它在解一个更难的问题。",
              "en": "The augmented curve is LOWER and steadier — not a training failure, a harder objective."},
         ]},

        {"type": "table",
         "title": {"zh": "五个架构的总账", "en": "The five architectures, in one table"},
         "right": {"zh": PROTO, "en": PROTO},
         "cols": [{"zh": "架构", "en": "Architecture"}, {"zh": "参数量", "en": "Params"},
                  {"zh": "训练 acc", "en": "Train acc"}, {"zh": "验证 acc", "en": "Val acc"},
                  {"zh": "测试 acc", "en": "Test acc"}],
         "rows": [
             [{"zh": "全连接 64-128-64-10", "en": "Dense 64-128-64-10"}, "17 226",
              "1.000±0.000", "0.966±0.008", "0.979±0.008"],
             [{"zh": "CNN 8/16（基准）", "en": "CNN 8/16 (baseline)"}, "1 898",
              "0.999±0.001", "0.970±0.010", "**0.981±0.008**"],
             [{"zh": "CNN 宽 16/32", "en": "CNN wide 16/32"}, "21 312",
              "0.999±0.001", "0.976±0.006", "0.987±0.008"],
             [{"zh": "CNN + 平均池化", "en": "CNN + average pooling"}, "1 898",
              "0.950±0.009", "0.929±0.016", "0.940±0.008"],
             [{"zh": "CNN + ±1px 增强", "en": "CNN + ±1px augmentation"}, "1 898",
              "0.954±0.012", "0.939±0.017", "0.950±0.022"],
         ],
         "widths": [8.4, 4.4, 5.6, 5.4, 5.6],
         "bold_first": True,
         "note": {"zh": "三件事：① 卷积与全连接的测试差 0.002 < 一个标准差 0.008 → **写「未观察到显著差异」**，不写「卷积更好」。② 变宽（21 312 参数）确实更好，0.987，但它已经比全连接还大——你付出的是参数。③ 增强单独看是**变差**的：0.981 → 0.950。下一页解释为什么这不是失败。",
                  "en": "Three things. (1) Conv against dense is a 0.002 gap against a 0.008 sd, so we write NOT OBSERVED, not \"conv wins\". (2) Going wide (21,312 params) genuinely helps, 0.987 — but it is now bigger than the dense net; you paid in parameters. (3) Augmentation on its own is WORSE: 0.981 → 0.950. Next page explains why that is not a failure."}},

        {"type": "chart",
         "title": {"zh": "把测试图平移一下，差距就出来了", "en": "Translate the test images and the gap appears"},
         "right": {"zh": "实测 · 5 种子", "en": "measured · 5 seeds"},
         "subtitle": SHIFT_PROTO,
         "categories": SHIFT_X,
         "series": [
             {"name": {"zh": "全连接", "en": "Dense"}, "values": SHIFT_MLP,
              "color": "B91C1C", "smooth": False},
             {"name": {"zh": "CNN 8/16", "en": "CNN 8/16"}, "values": SHIFT_CNN,
              "color": "1E4FA8", "smooth": False},
             {"name": {"zh": "CNN + ±1px 增强", "en": "CNN + ±1px augmentation"},
              "values": SHIFT_AUG, "color": "059669", "smooth": False, "emphasis": True},
         ],
         "x_label": {"zh": "测试时平移 dx（列）", "en": "test-time shift dx (columns)"},
         "y_label": {"zh": "测试准确率", "en": "test accuracy"},
         "w": 19.0, "h": 11.2, "y_max": 1.0,
         "notes": [
             {"zh": "dx = −1：全连接 0.4555 / 卷积 0.6481 / 增强 0.9415。",
              "en": "At dx = -1: dense 0.4555, conv 0.6481, augmented 0.9415."},
             {"zh": "注意 dx = 0 那一列：增强只有 0.9504，是三条里**最低**的。",
              "en": "Look at dx = 0: the augmented model is the LOWEST of the three at 0.9504."},
             {"zh": "增强没有提升上限，它把曲线**压平**了。",
              "en": "Augmentation did not raise the ceiling; it flattened the curve."},
         ]},

        {"type": "compare",
         "title": {"zh": "增强的账本：买 +29 个点，付 −3 个点", "en": "The augmentation ledger: +29 bought, −3 paid"},
         "right": {"zh": "本周最值得记住的一页", "en": "the page worth remembering"},
         "columns": [
             {"title": {"zh": "买到（鲁棒性）", "en": "Bought (robustness)"},
              "accent": "059669",
              "items": [
                  {"zh": "dx = −1：0.6481 → **0.9415**，+29.3 个点",
                   "en": "dx = -1: 0.6481 → 0.9415, +29.3 points"},
                  {"zh": "dx = −2：0.2348 → **0.5170**，+28.2 个点",
                   "en": "dx = -2: 0.2348 → 0.5170, +28.2 points"},
                  {"zh": "训练曲线不再冲上 1.000（第 115 轮 0.9292），过拟合被压住",
                   "en": "The training curve no longer runs to 1.000 (0.9292 at epoch 115); overfitting is held back"},
              ]},
             {"title": {"zh": "付出（干净精度）", "en": "Paid (clean accuracy)"},
              "accent": "B91C1C",
              "items": [
                  {"zh": "dx = 0：0.9808 → **0.9504**，−3.0 个点",
                   "en": "dx = 0: 0.9808 → 0.9504, -3.0 points"},
                  {"zh": "训练准确率也从 0.9912 掉到 0.9292——**代价不是噪声，是系统性的**",
                   "en": "Training accuracy falls 0.9912 → 0.9292 too — the cost is systematic, not noise"},
                  {"zh": "多花的时间：120 轮里每轮多做两次随机平移（可忽略）；真正贵的是你要重新调正则与轮数",
                   "en": "Time cost is negligible (two RNG shifts per batch); the real cost is re-tuning regularisation and epochs"},
              ]},
         ],
         "note": {"zh": "**所以「加增强对不对」没有统一答案。** 问的是：你的模型会遇到平移过的输入吗？如果用户是拿手机拍的——会，那就买。如果输入已经被裁齐对齐——不会，那你只是在白买。",
                  "en": "So there is no universal answer to \"should I augment\". The question is whether your model will meet translated inputs. If users photograph the thing — yes, buy. If inputs are already cropped and aligned — no, you are buying nothing."}},

        # ================================================== PART 04 =========
        {"type": "section", "num": "04",
         "title": {"zh": "看它错在哪", "en": "Where it fails"},
         "title_en": {"zh": "Confusion matrix and misclassification", "en": "Confusion matrix and misclassification"},
         "lead": {"zh": "「98%」不是一个结果，是一个不完整的句子。\n混淆矩阵才是把「98%」翻译成「它在哪两类之间犹豫」的那张表。",
                  "en": "\"98%\" is not a result, it is an unfinished sentence. The confusion matrix is the table that turns it into \"which two classes it hesitates between\"."},
         "pillars": [
             {"title": {"zh": "1350", "en": "1350"}, "sub": {"zh": "个测试预测（5 种子合计）", "en": "test predictions (5 seeds)"}},
             {"title": {"zh": "26", "en": "26"}, "sub": {"zh": "个非对角错误", "en": "off-diagonal errors"}},
             {"title": {"zh": "数字 8", "en": "the digit 8"}, "sub": {"zh": "最差类，召回 0.9538", "en": "worst class, recall 0.9538"}},
         ]},

        {"type": "table",
         "title": {"zh": "混淆矩阵：5 个种子、1350 个测试预测之和", "en": "Confusion matrix: 1,350 test predictions over 5 seeds"},
         "right": {"zh": "CNN 8/16", "en": "CNN 8/16"},
         "subtitle": {"zh": "行＝真实标签，列＝模型判断。对角是正确，非对角是错误。合计 1350，正确 1324（0.9807）",
                      "en": "Row = true label, column = prediction. Diagonal is correct, off-diagonal is wrong. Total 1,350; correct 1,324 (0.9807)"},
         "cols": [{"zh": "真↓ 判→", "en": "true ↓ / pred →"}, "0", "1", "2", "3", "4",
                  "5", "6", "7", "8", "9"],
         "head_size": 11.5, "body_size": 10,
         "rows": [
             ["0", "**135**", "0", "0", "0", "0", "0", "0", "0", "0", "0"],
             ["1", "0", "**132**", "0", "0", "0", "1", "1", "0", "2", "2"],
             ["2", "0", "0", "**131**", "0", "0", "0", "0", "0", "1", "0"],
             ["3", "0", "1", "0", "**134**", "0", "0", "0", "1", "0", "1"],
             ["4", "1", "0", "0", "0", "**133**", "0", "0", "0", "0", "1"],
             ["5", "0", "0", "0", "0", "0", "**136**", "0", "1", "0", "1"],
             ["6", "0", "0", "0", "0", "0", "0", "**133**", "0", "2", "0"],
             ["7", "0", "0", "0", "0", "1", "0", "0", "**133**", "0", "1"],
             ["8", "0", "**3**", "**1**", "0", "0", "**1**", "0", "**1**", "**124**", "0"],
             ["9", "0", "0", "0", "0", "0", "1", "0", "0", "1", "**133**"],
         ],
         "widths": [3.4, 2.6, 2.6, 2.6, 2.6, 2.6, 2.6, 2.6, 2.6, 2.6, 2.63],
         "bold_first": True,
         "note": {"zh": "读法只有一句：**看非对角**。数字 0 是满分（135/135），数字 8 最差（124/130，召回 0.9538）。最差的类对是 8→1（3 次）、1→8 与 1→9（各 2 次）、6→8（2 次）。**全部 26 个错误里，有 12 个与数字 8 有关（46.2%）。**",
                  "en": "One reading rule: look off-diagonal. Digit 0 is perfect (135/135); digit 8 is worst (124/130, recall 0.9538). Worst pairs: 8→1 (3), 1→8 and 1→9 (2 each), 6→8 (2). Of all 26 errors, 12 involve the digit 8 (46.2%)."}},

        {"type": "code",
         "title": {"zh": "把错分的那个数字本身画出来", "en": "Draw the misclassified digit itself"},
         "right": {"zh": "seed 42 · 5 / 270 错", "en": "seed 42 · 5 wrong of 270"},
         "subtitle": {"zh": "灰度用字符表示：空格=0，@=最亮。这些是真实测试样本的像素，不是示意图",
                      "en": "Grey levels as characters: space = 0, @ = brightest. These are the real test pixels, not an illustration"},
         "blocks": [
             {"title": {"zh": "真 8，被判成 7（置信 0.9829）", "en": "True 8, predicted 7 (confidence 0.9829)"},
              "size": 13,
              "code": {"zh": [
                  "   +@*  ",
                  "  .#+#: ",
                  "   * *. ",
                  "   ++@: ",
                  " .@@@=  ",
                  " .@-*   ",
                  "  %:#   ",
                  "  .%+   ",
                  "",
                  "真类概率只有 0.0144",
                  "# 下半部分被写断，",
                  "# 上部只剩一撇——",
                  "# 人眼看也像 7。",
              ],
              "en": [
                  "   +@*  ",
                  "  .#+#: ",
                  "   * *. ",
                  "   ++@: ",
                  " .@@@=  ",
                  " .@-*   ",
                  "  %:#   ",
                  "  .%+   ",
                  "",
                  "true-class prob 0.0144",
                  "# the lower loop is broken;",
                  "# only the upper stroke",
                  "# survives - reads like 7.",
              ]}},
             {"title": {"zh": "真 6，被判成 8（置信 0.8852）", "en": "True 6, predicted 8 (confidence 0.8852)"},
              "size": 13,
              "code": {"zh": [
                  "   *@#  ",
                  "  -@*@: ",
                  " .@* +  ",
                  " -@+    ",
                  " +@@+   ",
                  " .@*@-  ",
                  "  *@@=  ",
                  "   +%   ",
                  "",
                  "真类概率 0.0271",
                  "# 这个 6 的**下半环是闭合的**，",
                  "# 而 6 的下半环不该闭合。",
                  "# 混淆矩阵里 6→8 出现 2 次，",
                  "# 这就是那 2 次长什么样。",
              ],
              "en": [
                  "   *@#  ",
                  "  -@*@: ",
                  " .@* +  ",
                  " -@+    ",
                  " +@@+   ",
                  " .@*@-  ",
                  "  *@@=  ",
                  "   +%   ",
                  "",
                  "true-class prob 0.0271",
                  "# this 6 has a CLOSED lower",
                  "# loop, which a 6 should not.",
                  "# 6->8 appears twice in the",
                  "# matrix; this is what it is.",
              ]}},
         ],
         "note": {"zh": "这才是「错分分析」。不是「模型还不够好」，而是「**它在一个下半环闭合的 6 上会把 8 叫出来**」——后者是一个可以修的东西（补这类样本、或者换损失权重），前者不是。",
                  "en": "This is error analysis. Not \"the model is not good enough\" but \"it calls 8 on a 6 whose lower loop closes\" — the second is fixable (add such samples, or re-weight the loss); the first is not."}},

        {"type": "checklist",
         "title": {"zh": "错分分析的交付标准", "en": "What a complete error analysis contains"},
         "right": {"zh": "实验 6 要求", "en": "Lab 6 requires"},
         "subtitle": {"zh": "五条，缺一条就是「只报了一个总数」——这正是本周实验报告最常见的失分点",
                      "en": "Five items. Miss one and you have reported a single aggregate number, which is the single most common way Lab 6 loses marks"},
         "items": [
             {"badge": {"zh": "① 指标", "en": "1. Metric"}, "accent": "1E4FA8",
              "title": {"zh": "打印混淆矩阵，不是只打印准确率", "en": "Print the confusion matrix, not just accuracy"},
              "desc": {"zh": "本周 0.981 的准确率底下藏着 26 个错误，其中 12 个与数字 8 有关。准确率一个字都没提。",
                       "en": "Behind 0.981 sit 26 errors, 12 of them involving the digit 8. The accuracy number says none of this."}},
             {"badge": {"zh": "② 最差类对", "en": "2. Worst pair"}, "accent": "059669",
              "title": {"zh": "点名最差的两个类，并给出次数", "en": "Name the worst class pair and its count"},
              "desc": {"zh": "「8 被当成 1，3 次」比「模型在某些类上表现较差」有用一百倍。",
                       "en": "\"8 read as 1, three times\" is a hundred times more useful than \"the model does worse on some classes\"."}},
             {"badge": {"zh": "③ 具体样本", "en": "3. Examples"}, "accent": "D97706",
              "title": {"zh": "至少 3 个具体错分样本，附上模型概率", "en": "At least 3 concrete cases with model probabilities"},
              "desc": {"zh": "要的是「真 8 判 7，置信 0.9829，真类概率 0.0144」这种句子——概率能区分「犹豫」和「错了还自信」。",
                       "en": "Sentences like \"true 8, predicted 7, confidence 0.9829, true-class probability 0.0144\" — the probabilities separate hesitation from confident error."}},
             {"badge": {"zh": "④ 假设", "en": "4. Hypothesis"}, "accent": "B91C1C",
              "title": {"zh": "每条错误配一个可检验的原因假设", "en": "Every case gets a testable hypothesis"},
              "desc": {"zh": "「这个 6 的下半环闭合」是假设，而且可以检验：找一批下半环闭合的 6，看是否都被判成 8。",
                       "en": "\"this 6 has a closed lower loop\" is a hypothesis, and it is checkable: collect such 6s and see whether they all become 8."}},
             {"badge": {"zh": "⑤ 下一步", "en": "5. Next step"}, "accent": "0E3F8C",
              "title": {"zh": "写出「我打算试什么」和「怎么判断有没有用」", "en": "State what you will try and how you will judge it"},
              "desc": {"zh": "同一个切分、同一个指标、一次只改一处——这是全课程不变的那条规则。",
                       "en": "Same split, same metric, one change at a time — the rule that does not change all semester."}},
         ]},

        # ================================================== PART 05 =========
        {"type": "section", "num": "05",
         "title": {"zh": "显存与绿色计算", "en": "Memory and green computing"},
         "title_en": {"zh": "Batch size, gradient accumulation, finite compute", "en": "Batch size, gradient accumulation, finite compute"},
         "lead": {"zh": "显存不足（OOM）是本周最常见的实验卡点。\n但「显存不够」几乎从来不是硬件问题，是 batch size 的问题。",
                  "en": "Out-of-memory is the most common blocker in this week's lab. And it is almost never a hardware problem — it is a batch-size problem."},
         "pillars": [
             {"title": {"zh": "先降 batch", "en": "Batch first"}, "sub": {"zh": "最便宜的一刀", "en": "the cheapest lever"}},
             {"title": {"zh": "再累积", "en": "Then accumulate"}, "sub": {"zh": "免费换回等效 batch", "en": "buy the batch back for free"}},
             {"title": {"zh": "最后才加显存", "en": "Hardware last"}, "sub": {"zh": "算力是有限资源", "en": "compute is finite"}},
         ]},

        {"type": "chart",
         "title": {"zh": "batch size 与峰值内存：实测的线性关系", "en": "Batch size against peak memory: measured"},
         "right": {"zh": "实测 · 独立子进程", "en": "measured · separate processes"},
         "subtitle": MEM_PROTO,
         "categories": MEM_X,
         "series": [
             {"name": {"zh": "超出基线的峰值内存（MB）", "en": "peak memory over baseline (MB)"},
              "values": MEM_OVER, "color": "D97706", "smooth": False, "emphasis": True},
         ],
         "x_label": {"zh": "batch size", "en": "batch size"},
         "y_label": {"zh": "峰值内存增量 MB", "en": "MB over baseline"},
         "w": 19.0, "h": 11.2,
         "notes": [
             {"zh": "基线（只导入 torch）306.5 MB。", "en": "Baseline (torch imported, nothing running): 306.5 MB."},
             {"zh": "batch 32 → 1024：增量 83.6 → 275.5 MB，3.3 倍，与 batch 同步增长。",
              "en": "Batch 32 → 1024: 83.6 → 275.5 MB, 3.3x, growing with batch."},
             {"zh": "**下降 batch 是唯一一个「不改变数学、只改变内存」的旋钮。**",
              "en": "Dropping the batch is the only knob that changes memory without changing the maths."},
         ]},

        {"type": "table",
         "title": {"zh": "梯度累积：等效 batch 可以被买回来，但要付对价钱", "en": "Gradient accumulation: the effective batch can be bought back — at the right price"},
         "right": {"zh": "实测 · 5 种子", "en": "measured · 5 seeds"},
         "subtitle": {"zh": "四种写法，除最后一步的梯度权重外完全相同。判定标准是「与真 batch 128 是否逐项一致」",
                      "en": "Four variants, identical except for how the accumulated gradient is weighted. The test is whether each reproduces the true batch-128 run seed by seed"},
         "cols": [{"zh": "写法", "en": "Weighting"},
                  {"zh": "5 个种子的测试精度（42–46）", "en": "Test accuracy per seed (42-46)"},
                  {"zh": "与真 batch 128 一致", "en": "Matches true batch 128"}],
         "rows": [
             [{"zh": "真 batch 128（基准）", "en": "True batch 128 (reference)"},
              "0.9704 / 0.9815 / 0.9778 / 0.9926 / 0.9815", {"zh": "— 基准", "en": "- reference"}],
             [{"zh": "4×32，权重 = 微批大小 / 组大小", "en": "4x32, weight = micro-batch / group size"},
              "0.9704 / 0.9815 / 0.9778 / 0.9926 / 0.9815", {"zh": "**5 / 5 完全一致**", "en": "**5 / 5 identical**"}],
             [{"zh": "4×32，权重 = 1 / 累积步数", "en": "4x32, weight = 1 / accumulation steps"},
              "0.9704 / 0.9852 / 0.9778 / 0.9889 / 0.9815", {"zh": "3 / 5", "en": "3 / 5"}],
             [{"zh": "4×32，权重 = 1（忘了缩放）", "en": "4x32, weight = 1 (forgot to scale)"},
              "0.9704 / 0.9852 / 0.9741 / 0.9889 / 0.9815", {"zh": "2 / 5", "en": "2 / 5"}],
         ],
         "widths": [7.6, 13.6, 8.2],
         "bold_first": True,
         "note": {"zh": "第二行才是正确的写法：**每一微批的权重是「它占这一组样本的比例」，不是「1/累积步数」。** 两者只在「所有微批一样大」时才等价——而每个 epoch 的最后一组往往不一样大。第三行那 2/5 的不一致，就是这 2 个种子踩到了那个尾巴。至于第四行：Adam 会按梯度的二阶矩归一化，所以「整体放大 4 倍」几乎被它吃掉——用 SGD 就完全不是这样了。",
                  "en": "Row two is the correct form: each micro-batch is weighted by its SHARE of the group, not by 1/accumulation-steps. The two agree only while every micro-batch has the same size, and the last group of an epoch usually does not. Row three's 3/5 mismatch is two seeds hitting that tail. Row four: Adam normalises by the second moment, so a uniform 4x scaling is largely absorbed — with SGD it is nothing like this."}},

        {"type": "checklist",
         "title": {"zh": "OOM 的处置顺序", "en": "What to do when you run out of memory"},
         "right": {"zh": "KT14 · 实验 6 必踩", "en": "KT14 · Lab 6 will hit this"},
         "subtitle": {"zh": "从上往下试。越往下，代价越大——最后两条已经不是「调参」，是换硬件或换方案",
                      "en": "Work down the list. Every step down costs more; the last two are no longer tuning, they are new hardware or a new plan"},
         "items": [
             {"badge": {"zh": "1 · 免费", "en": "1 · free"}, "accent": "059669",
              "title": {"zh": "先把 batch size 减半", "en": "Halve the batch size first"},
              "desc": {"zh": "不改变任何数学，只改变内存。副作用是梯度更吵——用 2 倍步数或更高的学习率补偿。先做这个，别先怀疑硬件。",
                       "en": "Changes memory, not maths. The side effect is noisier gradients — compensate with more steps or a higher learning rate. Do this before suspecting the hardware."}},
             {"badge": {"zh": "2 · 免费", "en": "2 · free"}, "accent": "059669",
              "title": {"zh": "梯度累积：把等效 batch 买回来", "en": "Gradient accumulation: buy the effective batch back"},
              "desc": {"zh": "实测：4×32 用对权重时与真 batch 128 **逐项一致（5/5）**。代价是时间，不是精度。见上一页第 2 行。",
                       "en": "Measured: 4x32 with the right weighting reproduces true batch 128 exactly, 5/5. You pay in time, not accuracy. See row two of the previous page."}},
             {"badge": {"zh": "3 · 便宜", "en": "3 · cheap"}, "accent": "1E4FA8",
              "title": {"zh": "混合精度（AMP）", "en": "Mixed precision (AMP)"},
              "desc": {"zh": "torch.amp.autocast + GradScaler，激活占半。注意：它改变数值，所以要重新确认指标没漂——不是免费，是便宜。",
                       "en": "torch.amp.autocast plus GradScaler, activations halved. It changes the numerics, so re-confirm the metric — cheap, not free."}},
             {"badge": {"zh": "4 · 有代价", "en": "4 · costs"}, "accent": "D97706",
              "title": {"zh": "梯度检查点 / 更小的输入", "en": "Gradient checkpointing / smaller input"},
              "desc": {"zh": "用时间换内存，通常慢 20–30%。缩小输入分辨率会改变任务本身——改之前想清楚你在测什么。",
                       "en": "Time for memory, typically 20-30% slower. Shrinking the input changes the task itself — decide what you are measuring before you change it."}},
             {"badge": {"zh": "5 · 最后", "en": "5 · last"}, "accent": "B91C1C",
              "title": {"zh": "降模型规模，或者承认这个任务本机做不了", "en": "Shrink the model, or admit the task does not fit"},
              "desc": {"zh": "**加显存是最后一条，不是第一条。** 本周实测：这个 8×8 模型峰值才 390 MB——先算清楚你到底需要多少，再谈买卡。",
                       "en": "Buying a GPU is LAST, not first. Measured this week: this 8x8 model peaks at 390 MB. Compute what you actually need before shopping."}},
         ]},

        {"type": "cards", "cols": 3, "h": 11.4, "top": 3.7,
         "title": {"zh": "绿色计算：算力是有限资源", "en": "Green computing: compute is finite"},
         "right": {"zh": "思政", "en": "civic"},
         "subtitle": {"zh": "同一份数据，同一个准确率，参数量差 9 倍——这句话在本周有实测支撑，不是口号",
                      "en": "Same data, same accuracy, 9x fewer parameters — measured this week, not a slogan"},
         "cards": [
             {"title": {"zh": "参数量就是电费", "en": "Parameters are a bill"},
              "body": [{"zh": "17 226 参数拿 0.979，1 898 参数拿 0.981。多出来的 15 328 个参数，在训练和推理里都要算、要传、要供电。",
                        "en": "17,226 parameters reach 0.979; 1,898 reach 0.981. Those 15,328 extra parameters must be computed, moved and powered, in training and at inference."},
                       {"zh": "「用更少的成本达成目标」不是清高，是先问一句：这个规模是必要的吗？",
                        "en": "\"Reach the goal with less\" is not piety; it starts with one question: was this size necessary?"}],
              "accent": "059669"},
             {"title": {"zh": "先量，再买", "en": "Measure before you buy"},
              "body": [{"zh": "本周实测这个模型峰值 390 MB，batch 1024 也只要 582 MB。**它永远不会 OOM。**",
                        "en": "Measured: this model peaks at 390 MB, and batch 1024 only reaches 582 MB. It will never OOM."},
                       {"zh": "在申请算力之前先把峰值量出来。大多数「我需要更大的机子」其实是「我把输入搞太大了」。",
                        "en": "Measure the peak before requesting compute. Most \"I need a bigger machine\" is \"I made the input too big\"."}],
              "accent": "1E4FA8"},
             {"title": {"zh": "无效的优化要如实写", "en": "Report the optimisations that did not work"},
              "body": [{"zh": "本周的增强就是例子：它让干净精度掉了 3 个点。要是只报平移实验那 29 个点，就是在选择性汇报。",
                        "en": "This week's augmentation is the example: it costs 3 points of clean accuracy. Reporting only the 29-point robustness gain would be selective reporting."},
                       {"zh": "AI 给的显存优化建议，实测后**有效和无效都要标注**——这就是本周的 AI 协同任务。",
                        "en": "For AI-suggested memory optimisations, label which ones actually worked and which did not — that is this week's AI-collaboration task."}],
              "accent": "D97706"},
         ]},

        # ============================================== quiz / summary ======
        {"type": "quiz",
         "title": {"zh": "随堂小测", "en": "In-class quiz"},
         "right": {"zh": "4 题 · 5 min", "en": "4 items · 5 min"},
         "subtitle": {"zh": "不看笔记。答不出的题，就是本周末要补的地方",
                      "en": "Closed book. Whatever you cannot answer is what to revise this week"},
         "cols": 2,
         "questions": [
             {"tag": {"zh": "题 1", "en": "Q1"},
              "q": {"zh": "8×8 输入，先用 3×3 卷积（s=1, p=1），再过 2×2 最大池化（s=2）。输出特征图多大？换成 s=2, p=0 的卷积呢？",
                    "en": "8x8 input, 3x3 conv with s=1 p=1, then 2x2 max pooling with s=2. What is the feature-map size? And with a 3x3 conv, s=2, p=0?"},
              "options": [
                  {"zh": "A. 4×4；再做卷积就是 2×2", "en": "A. 4x4; a further conv gives 2x2"},
                  {"zh": "B. 8×8 不变；4×4", "en": "B. stays 8x8; 4x4"},
                  {"zh": "C. 4×4；输出还是 4×4", "en": "C. 4x4; a further conv stays 4x4"},
              ]},
             {"tag": {"zh": "题 2", "en": "Q2"},
              "q": {"zh": "本周卷积网 1 898 参数拿到 0.981，全连接 17 226 拿到 0.979。写「卷积更好」对不对？该怎么说？",
                    "en": "This week the CNN reaches 0.981 with 1,898 parameters and the dense net reaches 0.979 with 17,226. Is \"the CNN is better\" correct? What should you write?"},
              "options": [
                  {"zh": "A. 对，0.981 > 0.979", "en": "A. Yes, 0.981 > 0.979"},
                  {"zh": "B. 差 0.002 小于一个标准差 0.008 → 未观察到显著差异，但参数量少 9 倍", "en": "B. A 0.002 gap is under the 0.008 sd → not observed, with 9x fewer parameters"},
                  {"zh": "C. 要看训练时间才能判断", "en": "C. Cannot tell without training time"},
              ]},
             {"tag": {"zh": "题 3", "en": "Q3"},
              "q": {"zh": "模型加了 ±1px 增强后，干净测试集掉到 0.9504，但平移 −1 时从 0.6481 升到 0.9415。这个改动「有没有用」？",
                    "en": "With ±1px augmentation, clean test accuracy drops to 0.9504 but shift-by-(-1) rises from 0.6481 to 0.9415. Did the change help?"},
              "options": [
                  {"zh": "A. 有用，鲁棒性大涨", "en": "A. Yes, robustness improved a lot"},
                  {"zh": "B. 没用，干净精度掉了", "en": "B. No, clean accuracy dropped"},
                  {"zh": "C. 取决于真实输入里有没有平移——这是个产品问题，不是模型问题", "en": "C. It depends on whether real inputs are ever translated — a product question, not a model question"},
              ]},
             {"tag": {"zh": "题 4", "en": "Q4"},
              "q": {"zh": "你要跑 batch 128，但显存只放得下 32。用 4×32 梯度累积，为什么权重不能简单写 1/4？",
                    "en": "You want batch 128 but memory only fits 32. With 4x32 gradient accumulation, why is a weight of 1/4 not correct?"},
              "options": [
                  {"zh": "A. 每个 epoch 最后一组的微批大小不等，简单平均会有偏", "en": "A. The last group of an epoch is unevenly split, so a plain average is biased"},
                  {"zh": "B. 因为 Adam 不收敛", "en": "B. Because Adam does not converge"},
                  {"zh": "C. 其实完全等价，1/4 就行", "en": "C. It is exactly equivalent; 1/4 is fine"},
              ]},
         ]},

        {"type": "summary",
         "title": {"zh": "本周小结", "en": "Summary"},
         "right": MOD,
         "subtitle": PROTO,
         "points": [
             {"zh": "卷积不是「更强的层」，是「用局部性假设换参数效率」。同一数据上参数量差 9 倍，准确率差 0.002。",
              "en": "A conv layer is not stronger; it trades a locality assumption for parameter efficiency. 9x fewer parameters, 0.002 accuracy difference."},
             {"zh": "形状的算术必须先算再做。输出尺寸四条公式与真实张量逐项一致；感受野第二层就覆盖整图。",
              "en": "Do the shape arithmetic before the code. Four formulas match real tensors; the receptive field covers the image by the second conv."},
             {"zh": "池化函数是**选择**，不是默认。最大池化与平均池化差 4.1 个点，是标准差的 5 倍。",
              "en": "The pooling function is a CHOICE, not a default. Max against average is worth 4.1 points, five standard deviations."},
             {"zh": "增强买鲁棒性、付干净精度：+29 个点换 −3 个点。**用不用取决于输入会不会被平移。**",
              "en": "Augmentation buys robustness and pays clean accuracy: +29 points for -3. Whether to buy depends on whether inputs get translated."},
             {"zh": "「98%」不是结果。混淆矩阵、最差类对、具体样本加概率、可检验的假设——四件都齐才叫错分分析。",
              "en": "\"98%\" is not a result. Confusion matrix, worst pair, concrete cases with probabilities, a testable hypothesis — all four, or it is not an error analysis."},
             {"zh": "显存不够先降 batch，再用梯度累积买回等效 batch。权重用「微批占组大小的比例」时，实测与真 batch 逐项一致。",
              "en": "Out of memory: drop the batch, then buy the effective batch back with accumulation. With the share-of-group weighting it reproduces the true batch exactly."},
         ],
         "todos": [
             {"title": {"zh": "实验 6 · 必交", "en": "Lab 6 · required"},
              "desc": {"zh": "CNN 图像分类 + 数据增强；记录训练曲线、混淆矩阵、≥3 个错分案例（附概率与假设）。对应实验 6 指导书。",
                       "en": "CNN image classification with augmentation; training curves, confusion matrix, 3+ misclassified cases with probabilities and hypotheses. See the Lab 6 handout."}},
             {"title": {"zh": "项目里程碑 M7", "en": "Capstone milestone M7"},
              "desc": {"zh": "推进准则：`python src/evaluate.py` 能打印指标；模型来源已记录（用了谁家的预训练权重、什么许可）；误差分析点名最差类对。",
                       "en": "Push: `python src/evaluate.py` prints the metric; model provenance recorded (which pretrained weights, which licence); error analysis names the worst class pair."}},
             {"title": {"zh": "课后预判（写 5 行）", "en": "After-class prediction (5 lines)"},
              "desc": {"zh": "「如果我的图像变成 256×256，本周的架构会出现哪些新问题？」（提示：感受野、参数、显存、池化次数各想一遍）",
                       "en": "If my images became 256x256, what new problems would this week's architecture have? Think about receptive field, parameters, memory and the number of pooling steps."}},
         ]},

        {"type": "closing",
         "quote": {"zh": "「准确率高不高」是个不完整的问题。\n完整的问题是：它在哪两类之间犹豫，错的那几个长什么样。",
                   "en": "\"How accurate is it\" is an incomplete question. The complete one: which two classes does it hesitate between, and what do the wrong ones look like?"},
         "quote_sub": {"zh": "本周所有数字来自 `scripts/w7_cnn_experiment.py` → `outputs/w7_cnn.json`（5 架构 × 5 种子 + 平移探针 + 混淆矩阵 + 累积探针 + 内存扫描）。",
                       "en": "Every number this week comes from `scripts/w7_cnn_experiment.py` -> `outputs/w7_cnn.json` (5 architectures x 5 seeds, plus the shift probe, the confusion matrix, the accumulation probe and the memory sweep)."},
         "thanks": {"zh": "谢谢大家", "en": "Thank you"},
         "next": {"zh": "Week 8 · 序列模型与文本数据处理 —— 文本怎么变成张量、填充与掩码为什么会吃掉你的精度、LSTM 门控在解决什么。本周实验 7：分词 → 词表 → 嵌入 → LSTM → 分类。",
                  "en": "Week 8 · Sequence Models and Text Data — how text becomes a tensor, why padding and masking quietly eat your accuracy, and what LSTM gates solve. Lab 7: tokenise → vocabulary → embeddings → LSTM → classify."},
         "sign": {"zh": "AI Application Development · Week 7 Lecture · {n} / {n}",
                  "en": "AI Application Development · Week 7 Lecture · {n} / {n}"}},
    ],
}
