"""Week 1 — Introduction to AI Application Development  ·  slide spec (bilingual).

Aligned with the official course documents (52015CC3BV):
CU(1) · Module 1 (Week 1-4) · Lab 0 (environment / reproducibility / record repo).
"""

SPEC = {
    "week": 1,
    "slides": [
        # ---------------------------------------------------------- cover ----
        {"type": "cover",
         "kicker": {"zh": "52015CC3BV · 本科 · 来华项目", "en": "52015CC3BV · UNDERGRADUATE · INTERNATIONAL"},
         "title": {"zh": "AI 应用开发导论与岗位认知", "en": "Introduction to AI Application Development"},
         "title_sub": {"zh": "Introduction to AI Application Development",
                       "en": "From idea to deployed AI · roles · environment · reproducibility"},
         "subtitle": {"zh": "Week 1 · 技术栈与流程 · 岗位能力模型 · 环境与工具链 · 可复现性三要素",
                      "en": "Week 1 · Stack & workflow · role competency · toolchain · the three pillars of reproducibility"},
         "chips": [
             ({"zh": "模块一 · W1–4", "en": "Module 1 · W1-4"}, 1.0),
             ({"zh": "180 min · 授课 + 实验 + 小测", "en": "180 min · Lecture + Lab + Quiz"}, 1.5),
             ({"zh": "Python · conda · PyTorch · GPU · Notebook", "en": "Python · conda · PyTorch · GPU · Notebook"}, 1.8),
             ({"zh": "留学生班 · 英文授课", "en": "International Students"}, 1.0),
         ]},

        # ------------------------------------------------------- contents ----
        {"type": "contents",
         "right": {"zh": "模块一 · Week 1", "en": "Module 1 · Week 1"},
         "count": {"zh": "5 部分", "en": "5 Parts"},
         "count_label": {"zh": "本周结构", "en": "Part"},
         "tagline": {"zh": "先看清这门课要造什么、需要什么能力，\n再把你的工作台搭建到「可复现」。\nKnow the destination before you start walking.",
                     "en": "Know what you will build and what it takes, then set up a workbench that is reproducible."},
         "timing": {"zh": "理论约 90 min · Lab 80 min · 小测与小结 10 min",
                    "en": "Theory ~90 min · Lab 80 min · Quiz & Summary 10 min"},
         "parts": [
             {"title": {"zh": "AI 应用开发是什么", "en": "What Is AI Application Development"},
              "title_en": "What It Is",
              "desc": {"zh": "技术栈分层 · 从想法到上线 · 产业生态",
                       "en": "Stack layers · idea-to-production · the industry landscape"}},
             {"title": {"zh": "AI 工程师岗位能力模型", "en": "The AI Engineer Role"},
              "title_en": "The Role",
              "desc": {"zh": "岗位角色 · 能力矩阵 · 典型工作流",
                       "en": "Roles · competency matrix · a typical workflow"}},
             {"title": {"zh": "开发环境与工具链", "en": "Environment & Toolchain"},
              "title_en": "Environment",
              "desc": {"zh": "Python/conda/PyTorch/GPU/Notebook · 环境验证",
                       "en": "Python/conda/PyTorch/GPU/Notebook · verifying the setup"}},
             {"title": {"zh": "可复现性与 AI 使用边界", "en": "Reproducibility & AI Boundaries"},
              "title_en": "Reproducibility",
              "desc": {"zh": "种子/配置/版本三要素 · 过程留痕 · 学术诚信",
                       "en": "Seed/config/version · process traces · academic integrity"}},
             {"title": {"zh": "Lab · 实验 0 环境与记录仓库", "en": "Lab · Environment & Record Repo"},
              "title_en": "Hands-On Lab",
              "desc": {"zh": "环境搭建 · GPU 验证 · 固定种子跑两次 · 建记录仓库",
                       "en": "Setup · GPU check · two seeded runs · build a record repo"}},
         ]},

        # ------------------------------------------------- Part 01 (p3-7) ---
        {"type": "section", "num": "01",
         "title": {"zh": "AI 应用开发是什么", "en": "What Is AI Application Development"},
         "title_en": {"zh": "What It Is", "en": "What It Is"},
         "lead": {"zh": "AI 应用开发不是「训练一个模型」，而是「把一个模型变成别人能用的系统」。\n这一部分之后，你应该能画出从想法到上线的完整流水线。",
                  "en": "AI application development is not \"training a model\" — it is turning a model into a system other people can use.\nAfter this part you can draw the full pipeline from idea to production."},
         "pillars": [
             {"title": {"zh": "面向系统", "en": "Systems, Not Models"},
              "sub": {"zh": "模型只是流水线的一环", "en": "A model is one part of a pipeline"}},
             {"title": {"zh": "端到端", "en": "End-to-End"},
              "sub": {"zh": "数据 → 训练 → 评估 → 服务", "en": "Data -> train -> evaluate -> serve"}},
             {"title": {"zh": "工程约束", "en": "Engineering Constraints"},
              "sub": {"zh": "时延 · 成本 · 可维护", "en": "Latency · cost · maintainability"}},
         ]},

        {"type": "compare",
         "title": {"zh": "传统软件开发 vs AI 应用开发", "en": "Traditional Software vs AI Applications"},
         "right": {"zh": "模块一 · Week 1", "en": "Module 1 · Week 1"},
         "columns": [
             {"title": {"zh": "传统软件开发", "en": "Traditional Software"}, "accent": "6B7280",
              "bg": "F5F7FA",
              "items": [
                  {"zh": "行为由人写的规则完全确定", "en": "Behaviour is fully determined by hand-written rules"},
                  {"zh": "输出可预测、可断言", "en": "Outputs are predictable and assertable"},
                  {"zh": "测试即验证（等于预期即通过）", "en": "Testing means verification (equal to expectation)"},
                  {"zh": "难点在逻辑复杂度", "en": "Difficulty lives in logic complexity"}]},
             {"title": {"zh": "AI 应用开发", "en": "AI Applications"}, "accent": "1E4FA8",
              "bg": "F0F5FC",
              "items": [
                  {"zh": "行为由数据「学」出来，带概率性", "en": "Behaviour is learned from data and is probabilistic"},
                  {"zh": "输出是分布，需要指标而非断言", "en": "Outputs form a distribution; you need metrics, not assertions"},
                  {"zh": "评估 = 统计度量（精度/时延/成本）", "en": "Evaluation means statistical metrics (accuracy / latency / cost)"},
                  {"zh": "难点在数据、泛化与工程化", "en": "Difficulty lives in data, generalisation and engineering"}]},
         ],
         "note": {"zh": "同一句话：传统软件「我告诉你规则」，AI 应用「我给你例子，你自己总结规则」——因此你还要为「它总结错了」负责。",
                  "en": "One line: classic software says \"here are the rules\"; an AI application says \"here are examples, infer the rules\" — so you also own the failure to generalise."}},

        {"type": "flow", "y": 6.4, "h": 4.7,
         "title": {"zh": "从想法到上线：六步流水线", "en": "From Idea to Production: Six Steps"},
         "right": {"zh": "模块一 · Week 1", "en": "Module 1 · Week 1"},
         "steps": [
             {"title": {"zh": "问题定义", "en": "Define"},
              "title_en": "Define",
              "desc": {"zh": "目标用户、要解决的问题、\n成功与失败判据", "en": "Users, the problem,\nsuccess and failure criteria"}},
             {"title": {"zh": "数据", "en": "Data"},
              "title_en": "Data",
              "desc": {"zh": "获取、清洗、划分、\n标注与合规", "en": "Acquire, clean, split,\nlabel and stay compliant"}},
             {"title": {"zh": "建模", "en": "Model"},
              "title_en": "Model",
              "desc": {"zh": "基线 → 简单模型 →\n改进模型", "en": "Baseline -> simple ->\nstronger model"}},
             {"title": {"zh": "评估", "en": "Evaluate"},
              "title_en": "Evaluate",
              "desc": {"zh": "离线指标、错误分析、\n与业务代价对齐", "en": "Offline metrics, error analysis,\nalign with business cost"}},
             {"title": {"zh": "部署", "en": "Deploy"},
              "title_en": "Deploy",
              "desc": {"zh": "封装接口、时延与吞吐、\n异常输入处理", "en": "Serve an API, measure latency\nand throughput, handle bad input"}},
             {"title": {"zh": "运维", "en": "Operate"},
              "title_en": "Operate",
              "desc": {"zh": "监控、版本、漂移\n与再训练", "en": "Monitor, version, detect\ndrift and retrain"}},
         ],
         "note": {"zh": "本课程 16 周就是沿这条线展开：W1–4 打地基，W5–8 练模型，W9–12 上现代应用，W13–16 做工程与综合项目。",
                  "en": "The 16 weeks follow exactly this line: W1-4 foundations, W5-8 model training, W9-12 modern applications, W13-16 engineering and the capstone."}},

        {"type": "cards", "cols": 3, "h": 5.0, "top": 3.6,
         "title": {"zh": "AI 应用技术栈：四层结构", "en": "The AI Application Stack: Four Layers"},
         "right": {"zh": "模块一 · Week 1", "en": "Module 1 · Week 1"},
         "cards": [
             {"title": {"zh": "应用层", "en": "Application Layer"},
              "title_en": "what users touch",
              "body": [{"zh": "界面、API、业务流程", "en": "UI, API, business flow"},
                       {"zh": "决定「有没有人用」", "en": "Decides whether anyone uses it"}]},
             {"title": {"zh": "模型层", "en": "Model Layer"},
              "title_en": "what predicts",
              "body": [{"zh": "训练/微调、推理、评估", "en": "Train / fine-tune, infer, evaluate"},
                       {"zh": "本课程的主战场", "en": "The main arena of this course"}]},
             {"title": {"zh": "数据层", "en": "Data Layer"},
              "title_en": "what feeds it",
              "body": [{"zh": "采集、存储、清洗、版本", "en": "Collect, store, clean, version"},
                       {"zh": "数据决定上限", "en": "Data sets the ceiling"}]},
             {"title": {"zh": "基础设施层", "en": "Infrastructure"},
              "title_en": "what runs it",
              "body": [{"zh": "算力（GPU）、容器、调度", "en": "Compute (GPU), containers, scheduling"},
                       {"zh": "决定成本与速度", "en": "Decides cost and speed"}]},
             {"title": {"zh": "贯穿：MLOps", "en": "Cross-Cutting: MLOps"},
              "title_en": "how it stays alive",
              "body": [{"zh": "实验管理、版本、监控", "en": "Tracking, versioning, monitoring"},
                       {"zh": "W14 专门讲", "en": "Covered in W14"}]},
             {"title": {"zh": "贯穿：负责任 AI", "en": "Cross-Cutting: Responsible AI"},
              "title_en": "how it stays safe",
              "body": [{"zh": "公平、可解释、安全", "en": "Fairness, explainability, safety"},
                       {"zh": "W15 专门讲", "en": "Covered in W15"}]},
         ]},

        {"type": "table",
         "title": {"zh": "产业生态与典型应用", "en": "Landscape and Representative Applications"},
         "right": {"zh": "模块一 · Week 1", "en": "Module 1 · Week 1"},
         "cols": [{"zh": "领域", "en": "Domain"},
                  {"zh": "典型任务", "en": "Typical Task"},
                  {"zh": "关键指标", "en": "Key Metric"},
                  {"zh": "本课程对应", "en": "In This Course"}],
         "widths": [4.6, 9.4, 6.4, 9.0],
         "h": 7.0,
         "bold_first": True,
         "rows": [
             [{"zh": "计算机视觉", "en": "Computer Vision"},
              {"zh": "图像分类、缺陷检测、分割", "en": "Classification, defect detection, segmentation"},
              {"zh": "mAP / 精度 / 漏检率", "en": "mAP / accuracy / miss rate"},
              {"zh": "W7 CNN · W9 迁移学习", "en": "W7 CNN · W9 transfer"}],
             [{"zh": "自然语言处理", "en": "NLP"},
              {"zh": "文本分类、序列标注、情感分析", "en": "Text classification, tagging, sentiment"},
              {"zh": "F1 / 精度 / 忠实度", "en": "F1 / accuracy / faithfulness"},
              {"zh": "W8 LSTM · W10 Transformer", "en": "W8 LSTM · W10 Transformer"}],
             [{"zh": "大模型应用", "en": "LLM Applications"},
              {"zh": "信息抽取、问答、检索增强", "en": "Extraction, QA, retrieval-augmented generation"},
              {"zh": "解析成功率 / 命中率", "en": "Parse success / hit rate"},
              {"zh": "W11 提示工程 · W12 RAG", "en": "W11 prompting · W12 RAG"}],
             [{"zh": "工程与运维", "en": "Engineering & Ops"},
              {"zh": "推理服务、监控、版本管理", "en": "Inference service, monitoring, versioning"},
              {"zh": "P95 时延 / 吞吐 / 漂移", "en": "P95 latency / throughput / drift"},
              {"zh": "W13 部署 · W14 MLOps", "en": "W13 deployment · W14 MLOps"}],
         ],
         "note": {"zh": "无论哪个领域，衡量的东西都一样：预测得对不对（质量）+ 跑得多快多贵（工程）。",
                  "en": "Whatever the domain, you always measure the same two things: is the prediction right (quality) and how fast/cheap is it (engineering)."}},

        # -------------------------------------------------- Part 02 (p8-11) --
        {"type": "section", "num": "02",
         "title": {"zh": "AI 工程师岗位能力模型", "en": "The AI Engineer Role"},
         "title_en": {"zh": "The Role", "en": "The Role"},
         "lead": {"zh": "产业要的不是「会调库的人」，而是「能把模型送进生产的人」。\n这一部分把岗位要求翻译成你本学期要练的能力。",
                  "en": "Industry does not want someone who can call a library — it wants someone who can ship a model into production.\nThis part translates job requirements into the skills you will practise this semester."},
         "pillars": [
             {"title": {"zh": "三类角色", "en": "Three Roles"},
              "sub": {"zh": "数据 / 模型 / 工程", "en": "Data / Model / Engineering"}},
             {"title": {"zh": "能力矩阵", "en": "Competency Matrix"},
              "sub": {"zh": "知识 · 技能 · 素养", "en": "Knowledge · skill · attitude"}},
             {"title": {"zh": "工作流", "en": "Workflow"},
              "sub": {"zh": "从需求到上线的一天", "en": "A day from requirement to release"}},
         ]},

        {"type": "cards", "cols": 3, "h": 5.4, "top": 3.6,
         "title": {"zh": "三类核心角色", "en": "Three Core Roles"},
         "right": {"zh": "模块一 · Week 1", "en": "Module 1 · Week 1"},
         "cards": [
             {"title": {"zh": "数据工程", "en": "Data Engineer"},
              "title_en": "data",
              "body": [{"zh": "把原始数据变成可训练的数据集", "en": "Turn raw data into trainable datasets"},
                       {"zh": "技能：清洗、划分、Dataset/DataLoader", "en": "Skills: cleaning, splitting, Dataset/DataLoader"},
                       {"zh": "对应 W3 · 实验 2", "en": "Maps to W3 · Lab 2"}]},
             {"title": {"zh": "模型工程", "en": "Model Engineer"},
              "title_en": "model",
              "body": [{"zh": "选择/搭建/训练/评估模型", "en": "Choose, build, train and evaluate models"},
                       {"zh": "技能：nn.Module、训练循环、调参", "en": "Skills: nn.Module, training loop, tuning"},
                       {"zh": "对应 W4–W10", "en": "Maps to W4-W10"}]},
             {"title": {"zh": "应用/部署工程", "en": "Application Engineer"},
              "title_en": "engineering",
              "body": [{"zh": "把模型封装成稳定可用的服务", "en": "Wrap the model into a stable, usable service"},
                       {"zh": "技能：接口、时延、监控、版本", "en": "Skills: APIs, latency, monitoring, versioning"},
                       {"zh": "对应 W13–W14", "en": "Maps to W13-W14"}]},
         ]},

        {"type": "table",
         "title": {"zh": "岗位能力矩阵（本学期对应训练）", "en": "Competency Matrix (and Where You Train It)"},
         "right": {"zh": "模块一 · Week 1", "en": "Module 1 · Week 1"},
         "cols": [{"zh": "能力维度", "en": "Dimension"},
                  {"zh": "具体要求", "en": "What It Means"},
                  {"zh": "训练环节", "en": "Where You Train It"}],
         "widths": [6.0, 14.0, 9.4],
         "h": 8.8,
         "bold_first": True,
         "rows": [
             [{"zh": "工程基础", "en": "Engineering basics"},
              {"zh": "环境搭建、版本控制、代码规范、可复现", "en": "Setup, version control, code style, reproducibility"},
              {"zh": "W1 实验 0 · 全学期", "en": "W1 Lab 0 · all term"}],
             [{"zh": "数据处理", "en": "Data handling"},
              {"zh": "清洗、划分、泄漏识别、Dataset/DataLoader", "en": "Cleaning, splitting, leakage, Dataset/DataLoader"},
              {"zh": "W3 实验 2", "en": "W3 Lab 2"}],
             [{"zh": "建模与训练", "en": "Modelling & training"},
              {"zh": "nn.Module、损失与优化器、正则化", "en": "nn.Module, loss & optimizers, regularisation"},
              {"zh": "W4–W6 实验 3–5", "en": "W4-W6 Labs 3-5"}],
             [{"zh": "评估与分析", "en": "Evaluation & analysis"},
              {"zh": "按代价选指标、错误分析、消融实验", "en": "Cost-aware metrics, error analysis, ablations"},
              {"zh": "W6 实验 5 · 各周对照表", "en": "W6 Lab 5 · weekly comparisons"}],
             [{"zh": "现代 AI 应用", "en": "Modern AI"},
              {"zh": "Transformer、提示工程、RAG", "en": "Transformers, prompt engineering, RAG"},
              {"zh": "W10–W12 实验 9–11", "en": "W10-W12 Labs 9-11"}],
             [{"zh": "工程化与素养", "en": "Ops & professionalism"},
              {"zh": "部署、MLOps、负责任 AI、AI 协同留痕", "en": "Deployment, MLOps, responsible AI, AI-use traces"},
              {"zh": "W13–W16 · 全学期", "en": "W13-W16 · all term"}],
         ],
         "note": {"zh": "矩阵里没有一项叫「会背算法」。所有能力都用「你能交付什么」来定义。",
                  "en": "Not one row says \"can recite algorithms\". Every competency is defined by what you can deliver."}},

        {"type": "flow", "y": 6.6, "h": 4.5,
         "title": {"zh": "一位 AI 工程师的一周", "en": "A Week in the Life of an AI Engineer"},
         "right": {"zh": "模块一 · Week 1", "en": "Module 1 · Week 1"},
         "steps": [
             {"title": {"zh": "对齐需求", "en": "Align"},
              "title_en": "Align",
              "desc": {"zh": "和业务方确认问题、\n指标与失败判据", "en": "Confirm the problem,\nmetric and failure criteria"}},
             {"title": {"zh": "摸数据", "en": "Explore"},
              "title_en": "Explore data",
              "desc": {"zh": "看分布、缺失、\n不平衡与泄漏", "en": "Distributions, missing values,\nimbalance and leakage"}},
             {"title": {"zh": "打基线", "en": "Baseline"},
              "title_en": "Baseline",
              "desc": {"zh": "先用最笨的方法\n拿到一个数", "en": "Get a number with\nthe dumbest method"}},
             {"title": {"zh": "迭代", "en": "Iterate"},
              "title_en": "Iterate",
              "desc": {"zh": "一次只改一个变量，\n记录对照", "en": "Change one variable at a time,\nlog the comparison"}},
             {"title": {"zh": "交付", "en": "Ship"},
              "title_en": "Ship",
              "desc": {"zh": "封装服务、写文档、\n做监控", "en": "Serve it, document it,\nmonitor it"}},
         ],
         "note": {"zh": "注意第 3、4 步：先要有基线，再谈改进；一次只改一个变量，否则你无法解释结果。这两条是本课程评分表里的硬指标。",
                  "en": "Note steps 3 and 4: baseline first, then improve; change one variable at a time or you cannot explain the result. Both are hard criteria in this course's rubric."}},

        # -------------------------------------------------- Part 03 (p12-15) -
        {"type": "section", "num": "03",
         "title": {"zh": "开发环境与工具链", "en": "Environment & Toolchain"},
         "title_en": {"zh": "Environment", "en": "Environment"},
         "lead": {"zh": "环境问题的代价被严重低估：一次「跑不起来」可能吃掉你整周的进度。\n这一部分的目标是——一次配好，长期可用。",
                  "en": "Environment problems are massively under-estimated: one \"it won't run\" can eat your whole week.\nThe goal of this part: set it up once, use it all term."},
         "pillars": [
             {"title": {"zh": "隔离", "en": "Isolation"},
              "sub": {"zh": "每个项目一个环境", "en": "One environment per project"}},
             {"title": {"zh": "可验证", "en": "Verifiable"},
              "sub": {"zh": "GPU 与依赖能被检查", "en": "GPU and deps can be checked"}},
             {"title": {"zh": "可迁移", "en": "Portable"},
              "sub": {"zh": "换机器能重建", "en": "Rebuildable elsewhere"}},
         ]},

        {"type": "cards", "cols": 3, "h": 6.4, "top": 3.6,
         "title": {"zh": "工具链五件套", "en": "The Toolchain"},
         "right": {"zh": "模块一 · Week 1", "en": "Module 1 · Week 1"},
         "cards": [
             {"title": {"zh": "Python + conda", "en": "Python + conda"},
              "title_en": "isolation",
              "body": [{"zh": "用 conda 建隔离环境，避免依赖打架", "en": "Create isolated envs with conda to avoid dependency clashes"},
                       {"zh": "把 environment.yml 纳入版本库", "en": "Commit environment.yml to the repo"}]},
             {"title": {"zh": "PyTorch", "en": "PyTorch"},
              "title_en": "the framework",
              "body": [{"zh": "本课程统一使用 PyTorch", "en": "This course standardises on PyTorch"},
                       {"zh": "能用 CPU / GPU 两种后端", "en": "Runs on both CPU and GPU backends"}]},
             {"title": {"zh": "GPU / CUDA", "en": "GPU / CUDA"},
              "title_en": "the accelerator",
              "body": [{"zh": "确认 torch.cuda.is_available() 为真", "en": "Confirm torch.cuda.is_available() is True"},
                       {"zh": "记下显卡型号与显存", "en": "Record GPU model and memory"}]},
             {"title": {"zh": "Notebook / IDE", "en": "Notebook / IDE"},
              "title_en": "the workbench",
              "body": [{"zh": "实验用 Notebook 快速试错", "en": "Use notebooks for fast experiments"},
                       {"zh": "正式代码落成 .py 模块", "en": "Move production code into .py modules"}]},
             {"title": {"zh": "Git", "en": "Git"},
              "title_en": "the time machine",
              "body": [{"zh": "每周至少一次有意义的提交", "en": "At least one meaningful commit per week"},
                       {"zh": "提交信息写清「改了什么、为什么」", "en": "Messages state what changed and why"}]},
             {"title": {"zh": "实验记录仓库", "en": "Record Repository"},
              "title_en": "the trace",
              "body": [{"zh": "每次实验的参数、指标、结论", "en": "Params, metrics and conclusions per run"},
                       {"zh": "是期末「开发轨迹」评分的依据", "en": "The evidence for the end-of-term dev-trace grade"}]},
         ]},

        {"type": "code", "top": 3.55, "h": 11.2,
         "title": {"zh": "环境自检脚本：三行确认可用", "en": "Environment Self-Check: Three Lines"},
         "right": {"zh": "模块一 · Week 1", "en": "Module 1 · Week 1"},
         "blocks": [
             {"title": "check_env.py",
              "code": {"zh": [
                  "import sys, torch, platform",
                  "",
                  "print(\"python :\", sys.version.split()[0])",
                  "print(\"torch  :\", torch.__version__)",
                  "print(\"device :\", \"cuda\" if torch.cuda.is_available() else \"cpu\")",
                  "if torch.cuda.is_available():",
                  "    print(\"gpu    :\", torch.cuda.get_device_name(0))",
                  "    print(\"vram   :\", round(",
                  "        torch.cuda.get_device_properties(0).total_memory / 1e9, 2), \"GB\")",
                  "# 期望：torch 版本与你安装的一致；",
                  "# device 为 cuda（若有 NVIDIA GPU），否则为 cpu。",
              ],
              "en": [
                  "import sys, torch, platform",
                  "",
                  "print(\"python :\", sys.version.split()[0])",
                  "print(\"torch  :\", torch.__version__)",
                  "print(\"device :\", \"cuda\" if torch.cuda.is_available() else \"cpu\")",
                  "if torch.cuda.is_available():",
                  "    print(\"gpu    :\", torch.cuda.get_device_name(0))",
                  "    print(\"vram   :\", round(",
                  "        torch.cuda.get_device_properties(0).total_memory / 1e9, 2), \"GB\")",
                  "# Expect: torch version matches your install;",
                  "# device is cuda (with an NVIDIA GPU) or cpu otherwise.",
              ]}},
         ],
         "note": {"zh": "三条要点：版本对得上、设备能被识别、显存看得见。截图留档，作为实验 0 的第一份证据。",
                  "en": "Three checks: versions match, device is detected, VRAM is visible. Screenshot it as your first piece of Lab 0 evidence."}},

        {"type": "checklist", "top": 3.55, "h": 2.15,
         "title": {"zh": "环境就绪清单", "en": "Environment Readiness Checklist"},
         "right": {"zh": "模块一 · Week 1", "en": "Module 1 · Week 1"},
         "items": [
             {"badge": {"zh": "必做", "en": "MUST"}, "accent": "1E4FA8",
              "title": {"zh": "隔离环境已建立", "en": "Isolated environment created"},
              "desc": {"zh": "conda 环境可用，environment.yml 已导出并提交到仓库。",
                       "en": "A conda env works and environment.yml is exported and committed."}},
             {"badge": {"zh": "必做", "en": "MUST"}, "accent": "1E4FA8",
              "title": {"zh": "PyTorch 可导入且版本正确", "en": "PyTorch imports at the right version"},
              "desc": {"zh": "python -c \"import torch; print(torch.__version__)\" 正常输出。",
                       "en": "python -c \"import torch; print(torch.__version__)\" prints normally."}},
             {"badge": {"zh": "必做", "en": "MUST"}, "accent": "1E4FA8",
              "title": {"zh": "GPU 状态已确认并记录", "en": "GPU status confirmed and recorded"},
              "desc": {"zh": "明确 is_available() 结果；无 GPU 也可，但必须在报告里写明并说明运行在 CPU。",
                       "en": "State the is_available() result; CPU-only is fine but must be stated in the report."}},
             {"badge": {"zh": "必做", "en": "MUST"}, "accent": "1E4FA8",
              "title": {"zh": "实验记录仓库已建立", "en": "Record repository created"},
              "desc": {"zh": "Git 仓库就绪，含 README 说明结构与命名约定，并能通过链接访问。",
                       "en": "A git repo with a README covering structure and naming, reachable by link."}},
             {"badge": {"zh": "加分", "en": "BONUS"}, "accent": "059669",
              "title": {"zh": "IDE 与断点调试可用", "en": "IDE with breakpoint debugging works"},
              "desc": {"zh": "能在 .py 文件里打断点并单步执行，而非只靠 print 调试。",
                       "en": "You can set breakpoints and step through a .py file, not just use print."}},
         ]},

        # -------------------------------------------------- Part 04 (p16-20) -
        {"type": "section", "num": "04",
         "title": {"zh": "可复现性与 AI 使用边界", "en": "Reproducibility & AI Boundaries"},
         "title_en": {"zh": "Reproducibility", "en": "Reproducibility"},
         "lead": {"zh": "「我这里能跑」不是结论。「换台机器、换个时间，结果一样」才是。\n同时，本课程允许你用 AI，但要求你留下可核查的痕迹。",
                  "en": "\"It runs on my machine\" is not a result. \"Same result on another machine, another day\" is.\nThis course lets you use AI, but requires an auditable trace."},
         "pillars": [
             {"title": {"zh": "三要素", "en": "Three Pillars"},
              "sub": {"zh": "种子 · 配置 · 版本", "en": "Seed · config · version"}},
             {"title": {"zh": "可核查", "en": "Auditable"},
              "sub": {"zh": "别人能复算你的数", "en": "Others can re-compute your number"}},
             {"title": {"zh": "诚实留痕", "en": "Honest Traces"},
              "sub": {"zh": "用了 AI 就写清楚", "en": "If you used AI, say so"}},
         ]},

        {"type": "cards", "cols": 3, "h": 5.0, "top": 3.6,
         "title": {"zh": "可复现性三要素", "en": "The Three Pillars of Reproducibility"},
         "right": {"zh": "模块一 · Week 1", "en": "Module 1 · Week 1"},
         "cards": [
             {"title": {"zh": "① 随机种子", "en": "1 · Seed"},
              "title_en": "seed",
              "body": [{"zh": "固定 Python / NumPy / PyTorch 三处种子", "en": "Fix seeds in Python, NumPy and PyTorch"},
                       {"zh": "否则一次结果无法被另一次验证", "en": "Otherwise one run cannot be verified against another"}]},
             {"title": {"zh": "② 配置记录", "en": "2 · Config"},
              "title_en": "config",
              "body": [{"zh": "超参数、数据路径、批大小全部写进文件", "en": "Hyper-parameters, data paths and batch sizes go into a file"},
                       {"zh": "不靠记忆，不靠口头约定", "en": "Not from memory, not from a verbal agreement"}]},
             {"title": {"zh": "③ 版本管理", "en": "3 · Version"},
              "title_en": "version",
              "body": [{"zh": "代码版本 + 环境版本 + 数据版本", "en": "Code version + environment version + data version"},
                       {"zh": "三者缺一，结果就无法追溯", "en": "Miss one and the result cannot be traced"}]},
         ]},

        {"type": "compare",
         "title": {"zh": "不可复现 vs 可复现", "en": "Irreproducible vs Reproducible"},
         "right": {"zh": "模块一 · Week 1", "en": "Module 1 · Week 1"},
         "columns": [
             {"title": {"zh": "不可复现的典型做法", "en": "Typical Irreproducible Practice"}, "accent": "B91C1C",
              "bg": "FEF2F2",
              "items": [
                  {"zh": "种子没设，每次跑出来都不一样", "en": "No seed set, every run differs"},
                  {"zh": "超参数散在代码各处、随手改", "en": "Hyper-parameters scattered and edited ad hoc"},
                  {"zh": "依赖没记录，换机器就报错", "en": "Dependencies unrecorded; breaks on another machine"},
                  {"zh": "只保存最好的那次结果", "en": "Only the best run is kept"},
                  {"zh": "报告里没有可运行的命令", "en": "No runnable command in the report"}]},
             {"title": {"zh": "可复现的标准做法", "en": "Standard Reproducible Practice"}, "accent": "059669",
              "bg": "ECFDF5",
              "items": [
                  {"zh": "一行 set_seed(42) 固定全部随机源", "en": "One set_seed(42) fixing every random source"},
                  {"zh": "配置集中在 config.yaml / 字典", "en": "Config centralised in config.yaml / a dict"},
                  {"zh": "environment.yml + requirements.txt 入库", "en": "environment.yml + requirements.txt committed"},
                  {"zh": "每次运行都有日志与指标记录", "en": "Every run has a log and a metrics record"},
                  {"zh": "README 里一行命令即可复现", "en": "One command in the README reproduces it"}]},
         ],
         "note": {"zh": "本课程所有实验报告都要求给出「可复现命令」。写不出命令 = 这个结果不算数。",
                  "en": "Every lab report in this course must give a reproducible command. No command, no credit."}},

        {"type": "code", "top": 3.55, "h": 11.2,
         "title": {"zh": "固定种子：三行覆盖全部随机源", "en": "Fixing the Seed: Three Lines, Every Source"},
         "right": {"zh": "模块一 · Week 1", "en": "Module 1 · Week 1"},
         "blocks": [
             {"title": "reproducibility.py",
              "code": {"zh": [
                  "import random, numpy as np, torch",
                  "",
                  "def set_seed(seed: int = 42) -> None:",
                  "    random.seed(seed)          # Python 内置随机",
                  "    np.random.seed(seed)       # NumPy",
                  "    torch.manual_seed(seed)    # PyTorch（CPU）",
                  "    torch.cuda.manual_seed_all(seed)  # 全部 GPU",
                  "",
                  "set_seed(42)",
                  "a = [torch.rand(3) for _ in range(2)]",
                  "# 关键实验：同一进程里重新播种，再抽一次，",
                  "# 观察两次结果是否一致 —— 这就是实验 0 的对比。",
              ],
              "en": [
                  "import random, numpy as np, torch",
                  "",
                  "def set_seed(seed: int = 42) -> None:",
                  "    random.seed(seed)          # Python built-in RNG",
                  "    np.random.seed(seed)       # NumPy",
                  "    torch.manual_seed(seed)    # PyTorch (CPU)",
                  "    torch.cuda.manual_seed_all(seed)  # all GPUs",
                  "",
                  "set_seed(42)",
                  "a = [torch.rand(3) for _ in range(2)]",
                  "# Key experiment: re-seed in the same process, draw again,",
                  "# and compare the two results - this is Lab 0's comparison.",
              ]}},
         ],
         "note": {"zh": "注意：固定种子只保证「同一环境内可复现」。跨设备/跨版本的微小差异属正常，报告里应如实说明。",
                  "en": "Note: a fixed seed guarantees reproducibility within one environment only. Small cross-device or cross-version differences are normal and must be stated honestly."}},

        {"type": "cards", "cols": 3, "h": 5.4, "top": 3.6,
         "title": {"zh": "AI 使用边界与过程留痕", "en": "AI Boundaries and Process Traces"},
         "right": {"zh": "模块一 · Week 1", "en": "Module 1 · Week 1"},
         "cards": [
             {"title": {"zh": "可以用 AI 做什么", "en": "What AI May Do"},
              "title_en": "allowed",
              "bg": "ECFDF5", "accent": "059669",
              "body": [{"zh": "解释概念、生成草稿代码、查找 API", "en": "Explain concepts, draft code, look up APIs"},
                       {"zh": "帮你写文档框架与测试用例", "en": "Help draft docs and test cases"},
                       {"zh": "充当「不会累的结对伙伴」", "en": "Act as a tireless pair partner"}]},
             {"title": {"zh": "不可以做什么", "en": "What AI May Not Do"},
              "title_en": "forbidden",
              "bg": "FEF2F2", "accent": "B91C1C",
              "body": [{"zh": "直接提交看不懂的代码", "en": "Submit code you cannot explain"},
                       {"zh": "用 AI 结论替代自己的验证", "en": "Let AI conclusions replace your own verification"},
                       {"zh": "把 AI 生成内容当作原创成果", "en": "Present AI output as your own original work"}]},
             {"title": {"zh": "必须留下什么", "en": "What Must Be Recorded"},
              "title_en": "trace",
              "body": [{"zh": "每条协同记录：提问 + AI 回答 + 你改了什么", "en": "Per trace: prompt + AI answer + what you changed"},
                       {"zh": "明确指出 AI 出错的地方", "en": "Point out explicitly where the AI was wrong"},
                       {"zh": "计入形成性考核的 10 分", "en": "Counts toward the 10 marks of formative assessment"}]},
         ]},

        {"type": "code", "top": 3.55, "h": 11.2,
         "title": {"zh": "AI 协同记录模板", "en": "AI Collaboration Log Template"},
         "right": {"zh": "模块一 · Week 1", "en": "Module 1 · Week 1"},
         "blocks": [
             {"title": "AI_USE.md",
              "code": {"zh": [
                  "## 协同记录 #01 · 2026-09-xx",
                  "",
                  "**我想要的**：用 autograd 手写一次梯度下降。",
                  "",
                  "**AI 给了什么**：一段 w -= lr * w.grad 的循环。",
                  "",
                  "**我发现了什么问题**：",
                  "- 没有在每步前清零梯度 → 梯度被累加，损失震荡；",
                  "- 形状 (3,) 与 (3,1) 混用，广播后结果和预期不同。",
                  "",
                  "**我怎么改的**：加 w.grad.zero_()；统一 reshape(-1, 1)。",
                  "",
                  "**结论**：AI 的骨架可用，但两处错误必须自己发现",
                  "—— 这是本课程 AI 协同的核心要求。",
              ],
              "en": [
                  "## Trace #01 - 2026-09-xx",
                  "",
                  "**What I wanted**: hand-write one gradient-descent step with autograd.",
                  "",
                  "**What the AI gave**: a loop doing w -= lr * w.grad.",
                  "",
                  "**What I found wrong**:",
                  "- gradients were never zeroed -> accumulated, loss oscillated;",
                  "- shapes (3,) and (3,1) mixed, broadcasting gave the wrong result.",
                  "",
                  "**How I fixed it**: added w.grad.zero_(); unified reshape(-1, 1).",
                  "",
                  "**Conclusion**: the skeleton was usable, but the two bugs had to be",
                  "found by me - that is the core requirement of AI collaboration here.",
              ]}},
         ],
         "note": {"zh": "一条合格的协同记录必须有「AI 错在哪」。只写「AI 帮了我」的记录不计分。",
                  "en": "A valid trace must state where the AI was wrong. \"The AI helped me\" alone earns nothing."}},

        # -------------------------------------------------- Part 05 (p21-25) -
        {"type": "section", "num": "05",
         "title": {"zh": "Lab · 实验 0", "en": "Lab · Experiment 0"},
         "title_en": {"zh": "Environment, Reproducibility, Record Repo", "en": "Environment, Reproducibility, Record Repo"},
         "lead": {"zh": "这是全学期唯一一次「不写模型」的实验，但它决定你后面 15 周是否顺利。\n四个任务：搭环境 → 验 GPU → 跑两次固定种子 → 建记录仓库。",
                  "en": "The only lab this term that trains no model - and it decides whether the next 15 weeks go smoothly.\nFour tasks: set up, verify GPU, run twice with a fixed seed, build the record repo."},
         "pillars": [
             {"title": {"zh": "搭建", "en": "Set Up"},
              "sub": {"zh": "conda + PyTorch", "en": "conda + PyTorch"}},
             {"title": {"zh": "验证", "en": "Verify"},
              "sub": {"zh": "GPU 与版本可查", "en": "GPU and versions checked"}},
             {"title": {"zh": "留痕", "en": "Record"},
              "sub": {"zh": "仓库与截图", "en": "Repo and screenshots"}},
         ]},

        {"type": "cards", "cols": 2, "h": 5.2, "top": 3.6,
         "title": {"zh": "实验 0 的四个任务", "en": "The Four Tasks of Experiment 0"},
         "right": {"zh": "模块一 · Week 1", "en": "Module 1 · Week 1"},
         "cards": [
             {"title": {"zh": "A · 环境搭建与 GPU 验证", "en": "A · Set up and verify GPU"},
              "title_en": "task A",
              "body": [{"zh": "建 conda 环境，装 PyTorch，运行环境自检脚本", "en": "Create a conda env, install PyTorch, run the self-check"},
                       {"zh": "产出：环境信息截图 + environment.yml", "en": "Output: environment screenshot + environment.yml"}]},
             {"title": {"zh": "B · 固定种子跑两次", "en": "B · Two seeded runs"},
              "title_en": "task B",
              "body": [{"zh": "用同一脚本、同一 seed 跑两遍，对比两次结果", "en": "Run the same script twice with the same seed and compare"},
                       {"zh": "再故意去掉种子跑一次，观察差异", "en": "Then drop the seed deliberately and observe the difference"}]},
             {"title": {"zh": "C · 解释为什么需要固定种子", "en": "C · Explain why seeds matter"},
              "title_en": "task C",
              "body": [{"zh": "用你自己两次运行的实测差异作答", "en": "Answer using the difference you actually measured"},
                       {"zh": "不许照抄课件原话", "en": "Do not copy the slide wording"}]},
             {"title": {"zh": "D · 建立个人实验记录仓库", "en": "D · Build your record repository"},
              "title_en": "task D",
              "body": [{"zh": "建 Git 仓库，写 README 说明目录与命名约定", "en": "Create a git repo with a README covering layout and naming"},
                       {"zh": "提交第一份记录：环境信息与两次运行结果", "en": "Commit the first record: environment info and the two runs"}]},
         ]},

        {"type": "code", "top": 3.55, "h": 11.2,
         "title": {"zh": "实验脚本：同一份代码，跑两次", "en": "Lab Script: One Script, Two Runs"},
         "right": {"zh": "模块一 · Week 1", "en": "Module 1 · Week 1"},
         "blocks": [
             {"title": "lab0_seed_demo.py",
              "code": {"zh": [
                  "import random, numpy as np, torch",
                  "",
                  "def set_seed(s):",
                  "    random.seed(s); np.random.seed(s)",
                  "    torch.manual_seed(s); torch.cuda.manual_seed_all(s)",
                  "",
                  "def draw(seed=None):",
                  "    if seed is not None:",
                  "        set_seed(seed)",
                  "    return torch.rand(4).tolist()",
                  "",
                  "print(\"run1 :\", draw(42))   # 与 run2 完全一致",
                  "print(\"run2 :\", draw(42))   # ← 固定种子：相同",
                  "print(\"no-seed:\", draw())   # ← 不固定：随机",
                  "",
                  "# 报告要求：把这三行的实际输出贴进实验记录，",
                  "# 并写一句你自己的结论。",
              ],
              "en": [
                  "import random, numpy as np, torch",
                  "",
                  "def set_seed(s):",
                  "    random.seed(s); np.random.seed(s)",
                  "    torch.manual_seed(s); torch.cuda.manual_seed_all(s)",
                  "",
                  "def draw(seed=None):",
                  "    if seed is not None:",
                  "        set_seed(seed)",
                  "    return torch.rand(4).tolist()",
                  "",
                  "print(\"run1 :\", draw(42))   # identical to run2",
                  "print(\"run2 :\", draw(42))   # <- fixed seed: same",
                  "print(\"no-seed:\", draw())   # <- unfixed: random",
                  "",
                  "# Report: paste the three actual outputs into your record",
                  "# and add one conclusion sentence of your own.",
              ]}},
         ],
         "note": {"zh": "run1 与 run2 必须逐位相同。若不同，多半是还有一处随机源没固定（常见：DataLoader 的 shuffle、新增的 worker）。",
                  "en": "run1 and run2 must match bit-for-bit. If not, some random source is still unfixed (usually DataLoader shuffle or extra workers)."}},

        {"type": "code", "top": 3.55, "h": 11.2,
         "title": {"zh": "记录仓库的目录约定", "en": "Record Repository Layout"},
         "right": {"zh": "模块一 · Week 1", "en": "Module 1 · Week 1"},
         "blocks": [
             {"title": {"zh": "记录仓库结构", "en": "Record repository layout"},
              "code": {"zh": [
                  "ai-course-labs/",
                  "├── README.md          # 课程信息、目录说明、命名约定",
                  "├── environment.yml    # 环境快照（conda export）",
                  "├── w01-lab0/",
                  "│   ├── check_env.txt  # 环境自检输出",
                  "│   ├── seed_demo.py",
                  "│   └── report.md      # 三次输出 + 你的结论",
                  "├── w02-lab1/          # 每周一个目录，命名统一",
                  "└── AI_USE.md          # 全学期 AI 协同记录，按 #01 #02 编号",
              ],
              "en": [
                  "ai-course-labs/",
                  "├── README.md          # course info, layout, naming rules",
                  "├── environment.yml    # environment snapshot (conda export)",
                  "├── w01-lab0/",
                  "│   ├── check_env.txt  # self-check output",
                  "│   ├── seed_demo.py",
                  "│   └── report.md      # three outputs + your conclusion",
                  "├── w02-lab1/          # one directory per week, same pattern",
                  "└── AI_USE.md          # term-long AI trace, numbered #01 #02 ...",
              ]}},
         ],
         "note": {"zh": "目录结构从第一周就固定，后面 15 周直接往里加。命名约定混乱是期末「开发轨迹」失分的最常见原因。",
                  "en": "Fix this layout in week 1 and simply add to it for 15 weeks. Messy naming is the single most common cause of losing dev-trace marks."}},

        {"type": "checklist", "top": 3.55, "h": 2.15,
         "title": {"zh": "实验 0 提交清单", "en": "Experiment 0 Submission Checklist"},
         "right": {"zh": "模块一 · Week 1", "en": "Module 1 · Week 1"},
         "items": [
             {"badge": {"zh": "必交", "en": "MUST"}, "accent": "1E4FA8",
              "title": {"zh": "环境信息截图", "en": "Environment screenshot"},
              "desc": {"zh": "含 Python / PyTorch 版本与设备信息；无 GPU 需注明运行在 CPU。",
                       "en": "Shows Python / PyTorch versions and the device; note CPU-only if applicable."}},
             {"badge": {"zh": "必交", "en": "MUST"}, "accent": "1E4FA8",
              "title": {"zh": "两次运行的实测输出", "en": "Actual output of the two runs"},
              "desc": {"zh": "run1、run2、no-seed 三行真实输出，不得编造。",
                       "en": "Real outputs of run1, run2 and no-seed. Do not fabricate."}},
             {"badge": {"zh": "必交", "en": "MUST"}, "accent": "1E4FA8",
              "title": {"zh": "一段自己的结论", "en": "Your own conclusion"},
              "desc": {"zh": "用实测差异解释「为什么需要固定种子」，禁止照抄课件。",
                       "en": "Explain why seeds matter using your measured difference; no copying."}},
             {"badge": {"zh": "必交", "en": "MUST"}, "accent": "1E4FA8",
              "title": {"zh": "记录仓库链接", "en": "Record repository link"},
              "desc": {"zh": "可访问的 Git 仓库地址，README 完整，第一份记录已提交。",
                       "en": "A reachable git URL with a complete README and the first record committed."}},
             {"badge": {"zh": "必交", "en": "MUST"}, "accent": "1E4FA8",
              "title": {"zh": "问题定义单草案", "en": "Problem-definition draft"},
              "desc": {"zh": "目标用户、待解决问题、可用数据、拟用指标、失败判据。",
                       "en": "Users, problem, available data, intended metric, failure criteria."}},
         ]},

        # ------------------------------------------------------ quiz (p26) --
        {"type": "quiz", "cols": 2,
         "title": {"zh": "随堂小测", "en": "Quick Check"},
         "right": {"zh": "模块一 · Week 1", "en": "Module 1 · Week 1"},
         "questions": [
             {"tag": {"zh": "概念", "en": "Concept"},
              "q": {"zh": "「AI 应用开发」与「训练一个模型」是同一件事吗？为什么？",
                    "en": "Is \"AI application development\" the same as \"training a model\"? Why?"},
              "options": [{"zh": "是，模型即应用", "en": "Yes - the model is the app"},
                          {"zh": "否，模型只是端到端流水线中的一环", "en": "No - a model is one link in an end-to-end pipeline"},
                          {"zh": "否，AI 应用不需要模型", "en": "No - AI apps need no model"},
                          {"zh": "取决于数据量", "en": "It depends on the data size"}]},
             {"tag": {"zh": "岗位", "en": "Role"},
              "q": {"zh": "下面哪一项最接近「应用/部署工程师」的核心职责？",
                    "en": "Which best matches the core duty of an application/deployment engineer?"},
              "options": [{"zh": "清洗与划分数据", "en": "Cleaning and splitting data"},
                          {"zh": "选择损失函数并调参", "en": "Choosing the loss and tuning hyper-parameters"},
                          {"zh": "把模型封装成稳定可用的服务", "en": "Wrapping the model into a stable, usable service"},
                          {"zh": "撰写论文", "en": "Writing papers"}]},
             {"tag": {"zh": "可复现", "en": "Reproducibility"},
              "q": {"zh": "固定随机种子后，两次运行结果仍不同，最可能的原因是？",
                    "en": "After fixing the seed, two runs still differ. The likeliest cause?"},
              "options": [{"zh": "GPU 太旧", "en": "The GPU is too old"},
                          {"zh": "仍有未固定的随机源（如 shuffle / worker）", "en": "A random source is still unfixed (e.g. shuffle / workers)"},
                          {"zh": "PyTorch 有 bug", "en": "PyTorch has a bug"},
                          {"zh": "种子数值不够大", "en": "The seed value is not large enough"}]},
             {"tag": {"zh": "AI 边界", "en": "AI Boundaries"},
              "q": {"zh": "下列哪种做法符合本课程的 AI 使用要求？",
                    "en": "Which practice meets this course's AI-use policy?"},
              "options": [{"zh": "让 AI 写好全部代码后直接提交", "en": "Let AI write everything, then submit as-is"},
                          {"zh": "用 AI 生成后逐行解释，并记录发现的问题", "en": "Generate with AI, explain line by line, log the problems found"},
                          {"zh": "完全不用 AI 才是唯一正解", "en": "Never using AI is the only correct answer"},
                          {"zh": "只要在结尾写一句「用了 AI」即可", "en": "One line saying \"I used AI\" at the end suffices"}]},
         ]},

        # --------------------------------------------------- summary (p27) --
        {"type": "summary",
         "title": {"zh": "本周小结", "en": "Week 1 Summary"},
         "right": {"zh": "模块一 · Week 1", "en": "Module 1 · Week 1"},
         "points": [
             {"zh": "AI 应用开发 = 端到端流水线：问题定义 → 数据 → 建模 → 评估 → 部署 → 运维，模型只是其中一环。",
              "en": "AI application development is an end-to-end pipeline: define -> data -> model -> evaluate -> deploy -> operate; the model is one link."},
             {"zh": "岗位能力用「能交付什么」定义：数据、建模、评估、工程化、负责任与留痕六类。",
              "en": "Competency is defined by deliverables: data, modelling, evaluation, engineering, responsibility and traces."},
             {"zh": "环境要一次配好：隔离环境 + PyTorch + GPU 可验证 + Git + 实验记录仓库。",
              "en": "Set the environment up once: isolated env + PyTorch + verifiable GPU + Git + a record repository."},
             {"zh": "可复现性三要素：固定种子、集中配置、版本管理。缺一项，结果就无法追溯。",
              "en": "Three pillars: fixed seed, centralised config, versioning. Miss one and results cannot be traced."},
             {"zh": "AI 可以用，但必须留下「AI 错在哪、我怎么改」的可核查记录。",
              "en": "AI is allowed, but you must leave an auditable record of what the AI got wrong and how you fixed it."},
         ],
         "todo_title": {"zh": "课后待办", "en": "After Class"},
         "todos": [
             {"title": {"zh": "提交实验 0 五项材料", "en": "Submit the five Lab 0 items"},
              "desc": {"zh": "环境截图、两次运行输出、自己的结论、记录仓库链接、问题定义单草案。",
                       "en": "Environment screenshot, two run outputs, your conclusion, repo link, problem-definition draft."}},
             {"title": {"zh": "预习 W2：PyTorch 张量与自动求导", "en": "Preview W2: tensors and autograd"},
              "desc": {"zh": "读《动手学深度学习（PyTorch 版）》张量与自动求导相关章节，先跑通官方示例。",
                       "en": "Read the tensors and autograd chapters of the PyTorch edition of Dive into Deep Learning and run the official example."}},
         ]},

        # --------------------------------------------------- closing (p28) --
        {"type": "closing",
         "quote": {"zh": "「先把工作台搭稳，\n再谈模型有多聪明。」",
                   "en": "\"Build a stable workbench first;\nthen talk about how clever the model is.\""},
         "quote_sub": {"zh": "本周交付：可用环境 + 可复现记录 + 一个想做的题目。",
                       "en": "This week you deliver: a working environment + reproducible records + one idea worth building."},
         "thanks": {"zh": "谢谢大家", "en": "Thank you"},
         "next_label": {"zh": "下周预告", "en": "Next week"},
         "next": {"zh": "W2 · PyTorch 基础：张量、广播与自动求导 —— 不借助 nn.Module，只用张量手写一次线性回归。",
                  "en": "W2 · PyTorch fundamentals: tensors, broadcasting and autograd - hand-write a linear regression with tensors only."}},
    ],
}
