"""Week 6 — Evaluation, Overfitting and Regularization · slide spec (bilingual).

Aligned with the official course documents (52015CC3BV):
CU(6) · Module 2 "Core Deep Learning" (Week 5-8).
KT11 evaluation metrics and protocols (precision/recall/F1/confusion matrix),
KT12 overfitting diagnosis and regularisation (early stop / weight decay /
dropout / augmentation).

Every experimental number in this deck comes from
`scripts/w6_overfit_experiment.py` -> `outputs/w6_regularisation.json`
(5 seeds x 6 arms). Do NOT hand-edit those numbers; re-run the script instead.
"""

EPOCHS_X = [str(i * 20 + 1) for i in range(20)]

# --- seed 42, every 20 epochs (from outputs/w6_regularisation.json) ----------
TRAIN_ACC = [0.1, 0.725, 0.9875, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
             1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
VAL_ACC = [0.1, 0.4815, 0.8074, 0.8185, 0.8296, 0.8333, 0.8296, 0.837, 0.837,
           0.8333, 0.837, 0.837, 0.8333, 0.8407, 0.837, 0.837, 0.837,
           0.8407, 0.8333, 0.837]
VAL_LOSS_BASE = [2.2906, 1.5293, 0.7305, 0.65, 0.6357, 0.6704, 0.6983, 0.7168,
                 0.742, 0.7549, 0.7706, 0.7859, 0.7947, 0.8054, 0.8193, 0.8309,
                 0.8389, 0.8472, 0.8593, 0.8672]
VAL_LOSS_WD = [2.292, 1.7454, 0.9045, 0.7215, 0.6261, 0.612, 0.5973, 0.6032,
               0.6098, 0.5859, 0.6025, 0.5929, 0.5794, 0.5808, 0.5953, 0.6027,
               0.5895, 0.5928, 0.6088, 0.5956]

MOD = {"zh": "模块二 · Week 6", "en": "Module 2 · Week 6"}
PROTO = {"zh": "digits 8×8 · 70/15/15 · 训练集 n=80 · 64-128-64-10 MLP · Adam 1e-3 · 400 轮 · 5 个随机种子",
         "en": "digits 8x8 · 70/15/15 · n_train=80 · 64-128-64-10 MLP · Adam 1e-3 · 400 epochs · 5 seeds"}
# The two charts plot a single seed-42 run (one point every 20 epochs), so they
# need their own subtitle — the table's numbers are 5-seed means and must not be
# mistaken for the curve values.
CURVE_PROTO = {"zh": "曲线：seed 42 单次运行，每 20 轮取一点（第 1, 21, …, 381 轮）｜表中统计量为 5 个种子（42–46）的均值",
               "en": "Curve: one seed-42 run, one point every 20 epochs (epochs 1, 21, ..., 381) | table figures are means over 5 seeds (42-46)"}


def zh(en):  # tiny helper: same string both languages (numbers, code, symbols)
    return {"zh": en, "en": en}


SPEC = {
    "week": 6,
    "slides": [
        # ---------------------------------------------------------- cover ----
        {"type": "cover",
         "kicker": {"zh": "52015CC3BV · 本科 · 来华项目",
                    "en": "52015CC3BV · UNDERGRADUATE · INTERNATIONAL"},
         "title": {"zh": "模型评估、过拟合与正则化",
                   "en": "Evaluation, Overfitting and Regularization"},
         "title_sub": {"zh": "Evaluation, Overfitting and Regularization",
                       "en": "Measure honestly, diagnose with evidence, regularise with restraint"},
         "subtitle": {"zh": "Week 6 · 指标与业务代价 · 评估协议 · 偏差-方差诊断 · 早停/权重衰减/Dropout/增强 · 实验 5",
                      "en": "Week 6 · Metrics and business cost · Evaluation protocol · Bias-variance diagnosis · Early stop / weight decay / dropout / augmentation · Lab 5"},
         "chips": [
             ({"zh": "模块二 · W5–8", "en": "Module 2 · W5-8"}, 1.0),
             ({"zh": "180 min · 授课 + 实验 + 小测", "en": "180 min · Lecture + Lab + Quiz"}, 1.5),
             ({"zh": "KT11 · KT12", "en": "KT11 · KT12"}, 0.9),
             ({"zh": "留学生班 · 英文授课", "en": "International Students"}, 1.0),
         ]},

        # ------------------------------------------------------- contents ----
        {"type": "contents",
         "right": MOD,
         "count": {"zh": "5 部分", "en": "5 Parts"},
         "count_label": {"zh": "本周结构", "en": "Part"},
         "tagline": {"zh": "训练集上的分数从来不是你的成绩单。\n本周回答三个问题：\n该看哪个数字、这个数字可不可信、怎么让它变可信。",
                     "en": "The score on your training set was never your report card.\nThis week answers three questions: which number to read, whether it can be trusted, and how to make it trustworthy."},
         "timing": {"zh": "理论约 90 min · Lab 80 min · 小测与小结 10 min",
                    "en": "Theory ~90 min · Lab 80 min · Quiz & Summary 10 min"},
         "parts": [
             {"title": {"zh": "评估指标：选对那个数字", "en": "Metrics: Choosing the Right Number"},
              "title_en": {"zh": "Metrics", "en": "Metrics"},
              "desc": {"zh": "准确率的陷阱 · 混淆矩阵 · 精确率/召回率/F1 · 业务代价",
                       "en": "The accuracy trap · confusion matrix · precision/recall/F1 · business cost"}},
             {"title": {"zh": "评估协议：数字可不可信", "en": "Protocol: Can the Number Be Trusted"},
              "title_en": {"zh": "Protocol", "en": "Protocol"},
              "desc": {"zh": "70/15/15 · 分层抽样 · 测试集只碰一次 · K 折交叉验证 · 数据泄漏",
                       "en": "70/15/15 · stratification · touch the test set once · K-fold · leakage"}},
             {"title": {"zh": "偏差-方差：按证据诊断", "en": "Bias and Variance: Diagnose with Evidence"},
              "title_en": {"zh": "Diagnosis", "en": "Diagnosis"},
              "desc": {"zh": "欠拟合 / 刚好 / 过拟合 · 从曲线读数 · 症状到对策",
                       "en": "Underfit / just right / overfit · reading curves · symptoms to remedies"}},
             {"title": {"zh": "正则化：四个刹车及其代价", "en": "Regularization: Four Brakes and Their Cost"},
              "title_en": {"zh": "Regularization", "en": "Regularization"},
              "desc": {"zh": "早停 · 权重衰减 · Dropout · 数据增强 · 本机实测对照",
                       "en": "Early stop · weight decay · dropout · augmentation · measured comparison"}},
             {"title": {"zh": "Lab · 实验 5 过拟合复现与正则化对比", "en": "Lab · Overfitting Reproduction and Regularization"},
              "title_en": {"zh": "Hands-On Lab", "en": "Hands-On Lab"},
              "desc": {"zh": "先制造过拟合 · 再逐一施加四种手段 · 用验证损失量化效果",
                       "en": "Manufacture overfitting first · then apply four remedies · quantify with validation loss"}},
         ]},

        # ------------------------------------------------- Part 01 (p3-7) ---
        {"type": "section", "num": "01",
         "title": {"zh": "评估指标：选对那个数字", "en": "Metrics: Choosing the Right Number"},
         "title_en": {"zh": "Metrics", "en": "Metrics"},
         "lead": {"zh": "「准确率 99%」是一个可以被制造出来的数字。\n当你决定优化什么，你就决定了模型会牺牲什么——所以先想清楚代价由谁承担。",
                  "en": "\"99% accuracy\" is a number you can manufacture.\nThe moment you choose what to optimise, you choose what the model will sacrifice — so decide first who pays the cost."},
         "pillars": [
             {"title": {"zh": "准确率会骗人", "en": "Accuracy Misleads"},
              "sub": {"zh": "不平衡数据下尤甚", "en": "Especially on imbalanced data"}},
             {"title": {"zh": "混淆矩阵是源头", "en": "The Matrix Is the Source"},
              "sub": {"zh": "四个格子推出所有指标", "en": "Four cells generate every metric"}},
             {"title": {"zh": "代价决定选择", "en": "Cost Decides"},
              "sub": {"zh": "漏报与误报代价不同", "en": "A miss and a false alarm cost differently"}},
         ]},

        {"type": "cards", "cols": 3, "h": 12.0, "top": 3.6,
         "title": {"zh": "先看一个真实会发生的失败", "en": "Start with a Failure That Really Happens"},
         "subtitle": {"zh": "同一个模型，换一个指标，故事完全相反",
                      "en": "The same model, a different metric, the opposite story"},
         "right": MOD,
         "cards": [
             {"title": {"zh": "99% 准确率的检测系统", "en": "The 99%-Accuracy Detector"},
              "title_en": {"zh": "the trap", "en": "the trap"},
              "accent": "#B91C1C", "bg": "#FEF2F2", "title_color": "#B91C1C",
              "body": [
                  {"zh": "测试集 1000 个样本，其中只有 10 个是真正的缺陷样本。",
                   "en": "1,000 test samples; only 10 of them are genuine defects."},
                  {"zh": "模型永远输出「正常」——准确率 (990/1000) = 99.0%。",
                   "en": "The model always answers \"normal\" — accuracy (990/1000) = 99.0%."},
                  {"zh": "但它一个缺陷都没抓到：召回率 = 0%。产线上一件都拦不住。",
                   "en": "Yet it catches zero defects: recall = 0%. Not one item is stopped on the line."},
                  {"zh": "准确率在这里不是「好」，而是「没用」——数据不平衡替模型把分数刷高了。",
                   "en": "Accuracy here is not \"good\", it is \"useless\" — class imbalance inflates the score for free."},
              ]},
             {"title": {"zh": "把代价写下来", "en": "Write the Cost Down"},
              "title_en": {"zh": "cost asymmetry", "en": "cost asymmetry"},
              "accent": "#D97706", "bg": "#FFFBEB", "title_color": "#B45309",
              "body": [
                  {"zh": "漏报一个真缺陷（FN）：客户收到废品，退货 + 信誉损失。",
                   "en": "Missing a true defect (FN): the customer receives scrap — recall plus reputation."},
                  {"zh": "误报一个正常件（FP）：一次复检工时，几块钱。",
                   "en": "Flagging a good item (FP): one re-inspection, a few yuan."},
                  {"zh": "两者代价差 100 倍，却在准确率里被当成一样重。",
                   "en": "The two costs differ 100-fold, yet accuracy weighs them identically."},
                  {"zh": "指标选择的本质，是把你真正在乎的代价写进公式。",
                   "en": "Choosing a metric is really writing the cost you care about into a formula."},
              ]},
             {"title": {"zh": "于是你该问的问题", "en": "So the Questions You Should Ask"},
              "title_en": {"zh": "decision questions", "en": "decision questions"},
              "accent": "#1E4FA8", "bg": "#F0F5FC",
              "body": [
                  {"zh": "① 这个系统错了以后，谁会疼？怎么疼？",
                   "en": "1) When this system is wrong, who hurts, and how?"},
                  {"zh": "② 两类错误（漏报 / 误报）谁的代价更高？高多少倍？",
                   "en": "2) Of the two error types (miss / false alarm), which costs more — by how many times?"},
                  {"zh": "③ 类别比例是多少？不平衡到什么程度？",
                   "en": "3) What is the class ratio? How imbalanced is it?"},
                  {"zh": "④ 这个业务有下游兜底吗？还是这里就是唯一一道闸门？",
                   "en": "4) Is there a downstream safety net, or is this the only gate?"},
              ]},
         ]},

        {"type": "table",
         "title": {"zh": "四个格子推出全部指标", "en": "Four Cells Generate Every Metric"},
         "subtitle": {"zh": "混淆矩阵（Confusion Matrix）：先把它数对，指标才有意义",
                      "en": "Count the confusion matrix correctly first — only then do metrics mean anything"},
         "right": MOD,
         "cols": [{"zh": "格子", "en": "Cell"}, {"zh": "含义", "en": "Meaning"},
                  {"zh": "由它导出的指标", "en": "Metric it feeds"},
                  {"zh": "谁最关心", "en": "Who cares most"}],
         "widths": [4.3, 9.4, 8.2, 7.5],
         "head_size": 12.0, "body_size": 11.0,
         "rows": [
             [{"zh": "TP 真阳性", "en": "TP true positive"},
              {"zh": "真的是缺陷，模型也判成缺陷", "en": "Truly a defect; model also says defect"},
              {"zh": "精确率（分子）、召回率（分子）", "en": "precision (numerator), recall (numerator)"},
              {"zh": "产线：这是唯一真正拦下来的一类", "en": "The line: the only items actually stopped"}],
             [{"zh": "FN 假阴性（漏报）", "en": "FN false negative (miss)"},
              {"zh": "真的是缺陷，模型判成正常", "en": "Truly a defect; model says normal"},
              {"zh": "召回率（分母）", "en": "recall (denominator)"},
              {"zh": "客户与质检：代价最高的一类", "en": "Customer and QA: the costliest cell"}],
             [{"zh": "FP 假阳性（误报）", "en": "FP false positive (false alarm)"},
              {"zh": "本来是正常件，模型判成缺陷", "en": "Actually fine; model says defect"},
              {"zh": "精确率（分母）", "en": "precision (denominator)"},
              {"zh": "产线与复检岗：浪费工时", "en": "The line and re-inspection: wasted hours"}],
             [{"zh": "TN 真阴性", "en": "TN true negative"},
              {"zh": "正常件判成正常", "en": "Fine item judged fine"},
              {"zh": "准确率（分子）——TN 撑起准确率", "en": "accuracy (numerator) — TN props accuracy up"},
              {"zh": "没人关心，但它最容易把准确率刷好看", "en": "Nobody watches it, yet it is the cheap way to inflate accuracy"}],
         ],
         "note": {"zh": "上面经典失败的 99% 就是靠 990 个 TN 堆出来的。记住：TP / FP / FN / TN 只要数对，四个指标都是算术题。",
                  "en": "The famous 99% above was built entirely out of 990 TNs. Once TP / FP / FN / TN are counted, every metric is arithmetic."}},

        {"type": "code",
         "title": {"zh": "把矩阵数出来，再看指标", "en": "Count the Matrix, Then Read the Metrics"},
         "subtitle": {"zh": "永远先看混淆矩阵，再看单个数字——顺序反了就容易被骗",
                      "en": "Always read the matrix before a single number — reverse the order and you get fooled"},
         "right": MOD,
         "blocks": [
             {"title": {"zh": "① 数出矩阵", "en": "1. Count the matrix"},
              "size": 10.5,
              "code": {
                  "zh": [
                      "from sklearn.metrics import confusion_matrix",
                      "import numpy as np",
                      "",
                      "cm = confusion_matrix(y_true, y_pred, labels=[0, 1])",
                      "tn, fp, fn, tp = cm.ravel()",
                      "",
                      "print(cm)                       # 先看这张表",
                      "# [[990   0]",
                      "#  [ 10   0]]   <- 10 个缺陷全判成正常",
                      "",
                      "acc = (tp + tn) / cm.sum()",
                      "prec = tp / (tp + fp) if tp + fp else 0.0",
                      "rec  = tp / (tp + fn) if tp + fn else 0.0",
                      "f1   = 2 * prec * rec / (prec + rec) if prec + rec else 0.0",
                      "print(f'acc={acc:.3f} prec={prec:.3f} rec={rec:.3f} f1={f1:.3f}')",
                      "# acc=0.990 prec=0.000 rec=0.000 f1=0.000",
                  ],
                  "en": [
                      "from sklearn.metrics import confusion_matrix",
                      "import numpy as np",
                      "",
                      "cm = confusion_matrix(y_true, y_pred, labels=[0, 1])",
                      "tn, fp, fn, tp = cm.ravel()",
                      "",
                      "print(cm)                       # read this table first",
                      "# [[990   0]",
                      "#  [ 10   0]]   <- all 10 defects called normal",
                      "",
                      "acc = (tp + tn) / cm.sum()",
                      "prec = tp / (tp + fp) if tp + fp else 0.0",
                      "rec  = tp / (tp + fn) if tp + fn else 0.0",
                      "f1   = 2 * prec * rec / (prec + rec) if prec + rec else 0.0",
                      "print(f'acc={acc:.3f} prec={prec:.3f} rec={rec:.3f} f1={f1:.3f}')",
                      "# acc=0.990 prec=0.000 rec=0.000 f1=0.000",
                  ]}},
             {"title": {"zh": "② 精确率与召回率的取舍", "en": "2. The precision / recall trade-off"},
              "size": 10.5,
              "code": {
                  "zh": [
                      "# 同一批预测分数，换阈值就换一套指标",
                      "for t in (0.3, 0.5, 0.7, 0.9):",
                      "    yp = (probs >= t).astype(int)",
                      "    tn, fp, fn, tp = confusion_matrix(",
                      "        y_true, yp, labels=[0, 1]).ravel()",
                      "    p = tp / (tp + fp) if tp + fp else 0.0",
                      "    r = tp / (tp + fn) if tp + fn else 0.0",
                      "    print(f't={t}  P={p:.3f}  R={r:.3f}')",
                      "",
                      "# t=0.3  P=0.42  R=0.91   <- 阈值低，抓得多也报得多",
                      "# t=0.5  P=0.61  R=0.74",
                      "# t=0.7  P=0.80  R=0.48",
                      "# t=0.9  P=0.95  R=0.17   <- 阈值高，准但漏",
                      "",
                      "# 没有免费的午餐：P 与 R 此消彼长，",
                      "# 选哪个点取决于你把代价放在哪一侧。",
                  ],
                  "en": [
                      "# same scores, different threshold, different metrics",
                      "for t in (0.3, 0.5, 0.7, 0.9):",
                      "    yp = (probs >= t).astype(int)",
                      "    tn, fp, fn, tp = confusion_matrix(",
                      "        y_true, yp, labels=[0, 1]).ravel()",
                      "    p = tp / (tp + fp) if tp + fp else 0.0",
                      "    r = tp / (tp + fn) if tp + fn else 0.0",
                      "    print(f't={t}  P={p:.3f}  R={r:.3f}')",
                      "",
                      "# t=0.3  P=0.42  R=0.91   <- low bar: catch more, alarm more",
                      "# t=0.5  P=0.61  R=0.74",
                      "# t=0.7  P=0.80  R=0.48",
                      "# t=0.9  P=0.95  R=0.17   <- high bar: precise but blind",
                      "",
                      "# No free lunch: P and R trade off;",
                      "# where you sit depends on which side pays.",
                  ]}},
         ],
         "note": {"zh": "阈值本身也是一个要「按代价选」的超参数——不要默认 0.5。",
                  "en": "The threshold is a hyper-parameter you also choose by cost — do not leave it at 0.5 by default."}},

        {"type": "compare",
         "title": {"zh": "指标选择：把代价翻译成公式", "en": "Choosing a Metric: Translating Cost into a Formula"},
         "subtitle": {"zh": "每类指标对应一种「你更怕哪种错」",
                      "en": "Each metric family encodes which mistake you fear more"},
         "right": MOD,
         "columns": [
             {"title": {"zh": "漏报代价高", "en": "A Miss Is Expensive"},
              "accent": "#B91C1C", "bg": "#FEF2F2",
              "items": [
                  {"zh": "看召回率（Recall）= TP / (TP + FN)", "en": "Read recall = TP / (TP + FN)"},
                  {"zh": "宁可误报，不可漏报：安全告警、疾病筛查、缺陷拦截",
                   "en": "Prefer a false alarm to a miss: safety alerts, screening, defect blocking"},
                  {"zh": "代价：误报上升，复检工时增加", "en": "Price paid: more false alarms, more inspection hours"},
                  {"zh": "必要时加人工复核环节，把 FP 挡在最后一道",
                   "en": "Add a human review stage to absorb the FPs at the end"},
              ]},
             {"title": {"zh": "误报代价高", "en": "A False Alarm Is Expensive"},
              "accent": "#D97706", "bg": "#FFFBEB",
              "items": [
                  {"zh": "看精确率（Precision）= TP / (TP + FP)", "en": "Read precision = TP / (TP + FP)"},
                  {"zh": "不能打扰用户：垃圾邮件拦截、自动推荐、自动处置",
                   "en": "Do not disturb the user: spam filters, auto-recommendation, auto-remediation"},
                  {"zh": "代价：漏掉一部分真目标", "en": "Price paid: some true targets are missed"},
                  {"zh": "把阈值调高即可换到高精确率", "en": "Raise the threshold to buy precision"},
              ]},
             {"title": {"zh": "两者都要，比例固定", "en": "Both, with a Fixed Budget"},
              "accent": "#1E4FA8", "bg": "#F0F5FC",
              "items": [
                  {"zh": "看 F1 = 2PR / (P + R)，调和平均", "en": "Read F1 = 2PR / (P + R), the harmonic mean"},
                  {"zh": "调和平均会被短板拖住：P 或 R 有一个很低，F1 就上不去",
                   "en": "A harmonic mean is pulled down by the weaker side: a low P or R caps F1"},
                  {"zh": "适合在数据不平衡且两类错误都不可忽视时汇报",
                   "en": "Report it when classes are imbalanced and neither error type is negligible"},
                  {"zh": "排序能力看 AUC / PR-AUC；代价不对称时用代价加权",
                   "en": "For ranking, look at AUC / PR-AUC; when costs are asymmetric, weight them"},
              ]},
         ],
         "note": {"zh": "汇报时给一个数字是不够的：写清「在什么阈值下、哪个类别的 P/R、类别比例多少」，否则无法被别人复核。",
                  "en": "One number is not a report. State the threshold, the per-class P/R and the class ratio — otherwise nobody can reproduce it."}},

        # ------------------------------------------------- Part 02 (p8-12) --
        {"type": "section", "num": "02",
         "title": {"zh": "评估协议：数字可不可信", "en": "Protocol: Can the Number Be Trusted"},
         "title_en": {"zh": "Protocol", "en": "Protocol"},
         "lead": {"zh": "一个算错的数据划分，能让模型的成绩凭空涨 20 个百分点。\n这不是模型变好了，是你把答案提前告诉了它。",
                  "en": "One wrong split can add twenty points of accuracy out of thin air.\nThe model did not improve — you simply told it the answers in advance."},
         "pillars": [
             {"title": {"zh": "先划分，后处理", "en": "Split First"},
              "sub": {"zh": "标准化/增强只在训练集上拟合", "en": "Fit scaling/augmentation on train only"}},
             {"title": {"zh": "测试集只碰一次", "en": "Touch Test Once"},
              "sub": {"zh": "用它调参就不再是测试集", "en": "Tuning on it destroys its meaning"}},
             {"title": {"zh": "小数据用 K 折", "en": "K-Fold for Small Data"},
              "sub": {"zh": "一次划分的运气成分太大", "en": "A single split is mostly luck"}},
         ]},

        {"type": "splitbar",
         "title": {"zh": "三段式划分：各司其职", "en": "Three-Way Split: Each Part Has One Job"},
         "subtitle": {"zh": "70 / 15 / 15 —— 谁都不能越界干活",
                      "en": "70 / 15 / 15 — nobody is allowed to do someone else's job"},
         "right": MOD,
         "segments": [
             {"value": 70, "title": {"zh": "训练集", "en": "Train"}, "pct": "70%",
              "color": "#1E4FA8",
              "desc": {"zh": "模型参数在这里更新。只会越拟合越好，所以它自己的分数永远不能当成绩。",
                       "en": "Parameters are updated here. Fit only improves, so its own score can never be the report card."}},
             {"value": 15, "title": {"zh": "验证集", "en": "Validation"}, "pct": "15%",
              "color": "#D97706",
              "desc": {"zh": "超参数、阈值、早停的决策依据。你可以多次用它，但每用一次就多一分过拟合的风险。",
                       "en": "Where hyper-parameters, thresholds and early stopping are decided. You may reuse it — each reuse costs a little honesty."}},
             {"value": 15, "title": {"zh": "测试集", "en": "Test"}, "pct": "15%",
              "color": "#059669",
              "desc": {"zh": "上锁。只在全部决策定稿后跑一次，得到唯一的最终数字。看过它就不能再回头调参。",
                       "en": "Padlocked. Run once, after every decision is frozen, for the single final number. Once seen, you may not go back and tune."}},
         ],
         "note": {"zh": "本课程的实验 5 就按 70/15/15 分层划分、并在 5 个随机种子上重复——单次划分的结果我们不当作结论。",
                  "en": "Lab 5 of this course uses a stratified 70/15/15 split repeated over five seeds — a single split is never treated as a conclusion."}},

        {"type": "cards", "cols": 3, "h": 12.0, "top": 3.6,
         "title": {"zh": "三个会让分数虚高的典型错误", "en": "Three Classic Ways to Inflate a Score"},
         "subtitle": {"zh": "它们的共同点是：答案在评估之前就泄露出去了",
                      "en": "Their common root: the answer leaks out before evaluation"},
         "right": MOD,
         "cards": [
             {"title": {"zh": "数据泄漏（Data Leakage）", "en": "Data Leakage"},
              "title_en": {"zh": "wrong order", "en": "wrong order"},
              "accent": "#B91C1C", "bg": "#FEF2F2", "title_color": "#B91C1C",
              "body": [
                  {"zh": "错误顺序：先对全量数据标准化 / 过采样 / 增强，再划分。",
                   "en": "Wrong order: normalise / oversample / augment the whole dataset, then split."},
                  {"zh": "后果：验证集的均值与方差里，掺进了验证集自己的信息。",
                   "en": "Result: the validation set's own statistics leak into its own preprocessing."},
                  {"zh": "典型症状：验证准确率 0.99，换一批真实数据掉到 0.7。",
                   "en": "Symptom: validation accuracy 0.99, then 0.7 on a genuinely fresh batch."},
                  {"zh": "正确顺序：先划分 → 只用训练集拟合预处理 → 再 transform 验证/测试集。",
                   "en": "Correct order: split first, fit preprocessing on train only, then transform val/test."},
              ]},
             {"title": {"zh": "用测试集调参", "en": "Tuning on the Test Set"},
              "title_en": {"zh": "peeking", "en": "peeking"},
              "accent": "#D97706", "bg": "#FFFBEB", "title_color": "#B45309",
              "body": [
                  {"zh": "做法：看测试集结果 → 改学习率 → 再看 → 再改……循环 20 次。",
                   "en": "The loop: read test result, change the learning rate, read again, change again — twenty times."},
                  {"zh": "后果：测试集被当成了验证集，你报出的数字是「挑出来的最好一次」。",
                   "en": "Result: the test set silently became a validation set; you report the best of twenty draws."},
                  {"zh": "本质：每看一次测试集，它就少了一次独立的证据价值。",
                   "en": "In essence: every peek spends one unit of its value as independent evidence."},
                  {"zh": "本课程要求：测试集结果只出现在最终提交里，且附上这之前的所有决策记录。",
                   "en": "Course rule: the test result appears only in the final submission, alongside a log of every earlier decision."},
              ]},
             {"title": {"zh": "不重复、不设种子", "en": "One Run, No Seed"},
              "title_en": {"zh": "noise as signal", "en": "noise as signal"},
              "accent": "#1E4FA8", "bg": "#F0F5FC",
              "body": [
                  {"zh": "只跑一次、只看一个随机种子，然后把 1 个百分点的差异当成「方法更优」。",
                   "en": "Run once, with one seed, then treat a 1-point difference as \"this method is better\"."},
                  {"zh": "后果：验证集只有几百个样本时，1 个百分点可能就等于 2 个样本的运气。",
                   "en": "Result: with a few hundred validation samples, one point can be two samples of luck."},
                  {"zh": "本周实测中，同一个改动在不同种子下的波动达到 ±3 个百分点。",
                   "en": "In this week's measurements, the same change swung by ±3 points across seeds."},
                  {"zh": "正确做法：至少 3–5 个种子，报告均值 ± 标准差，并说明结论是否稳定。",
                   "en": "Correct practice: 3-5 seeds minimum, report mean ± sd, and state whether the conclusion holds."},
              ]},
         ]},

        {"type": "kfold",
         "title": {"zh": "K 折交叉验证：小数据时的更稳做法", "en": "K-Fold Cross-Validation: Steadier on Small Data"},
         "subtitle": {"zh": "同一份数据，轮流当验证集，取平均",
                      "en": "Take turns being the validation set, then average"},
         "right": MOD, "k": 5, "rows": 5, "w": 17.0,
         "notes": [
             {"zh": "每一折轮流当验证集，训练 K 次，得到 K 个分数。",
              "en": "Each fold takes a turn as validation; K trainings give K scores."},
             {"zh": "报告「均值 ± 标准差」，把划分运气显式地写出来。",
              "en": "Report mean ± sd, making split luck explicit rather than hidden."},
             {"zh": "代价：训练时间是单次的 K 倍。数据够多时不必用。",
              "en": "Cost: K times the training time. With plenty of data, skip it."},
             {"zh": "类别不平衡时必须用分层 K 折（StratifiedKFold）。",
              "en": "With imbalanced classes, stratify — use StratifiedKFold."},
             {"zh": "本课程要求：实验报告需给出「是否跨种子/跨折稳定」的说明。",
              "en": "Course rule: reports must state whether the result holds across seeds or folds."},
         ],
         "note": {"zh": "K 折不是为了让分数更高，而是为了让「分数不确定性」被看见。",
                  "en": "K-fold does not raise the score; it makes the uncertainty in the score visible."}},

        # ------------------------------------------------- Part 03 (p13-17) -
        {"type": "section", "num": "03",
         "title": {"zh": "偏差-方差：按证据诊断", "en": "Bias and Variance: Diagnose with Evidence"},
         "title_en": {"zh": "Diagnosis", "en": "Diagnosis"},
         "lead": {"zh": "不要「感觉好像过拟合了」。\n过拟合有且只有一个可靠的证据：训练损失还在降，验证损失已经开始升。",
                  "en": "Never \"it feels like it is overfitting\".\nThere is one reliable piece of evidence: training loss still falling while validation loss has turned upward."},
         "pillars": [
             {"title": {"zh": "看损失，不看准确率", "en": "Read Loss, Not Accuracy"},
              "sub": {"zh": "准确率有天花板，会掩盖退化", "en": "Accuracy has a ceiling and hides decay"}},
             {"title": {"zh": "成对读数", "en": "Read Them Together"},
              "sub": {"zh": "训练与验证必须画在同一张图上", "en": "Train and validation on one chart"}},
             {"title": {"zh": "诊断先于开药", "en": "Diagnose Before Prescribing"},
              "sub": {"zh": "欠拟合和过拟合的对策相反", "en": "Underfit and overfit need opposite remedies"}},
         ]},

        {"type": "compare",
         "title": {"zh": "三种状态，三条曲线", "en": "Three States, Three Curve Shapes"},
         "subtitle": {"zh": "看两条线的「位置」与「走向」，不看某一个点的数值",
                      "en": "Read the position and the direction of two lines — not the value of one point"},
         "right": MOD,
         "columns": [
             {"title": {"zh": "欠拟合（高偏差）", "en": "Underfitting (high bias)"},
              "accent": "#6B7280", "bg": "#F5F7FA",
              "items": [
                  {"zh": "训练损失高且降不下去", "en": "Training loss is high and will not fall"},
                  {"zh": "验证损失同样高，两条线贴得很近", "en": "Validation loss is equally high; the two lines sit close"},
                  {"zh": "本轮实测的证据：数据增强臂训练准确率只到 0.960，测试 0.824",
                   "en": "Evidence from this week: the augmentation arm reaches only 0.960 train accuracy, 0.824 test"},
                  {"zh": "对策：加容量、加特征、减少正则强度、训练更久——不是加正则",
                   "en": "Remedy: more capacity, better features, less regularisation, train longer — not more regularisation"},
              ]},
             {"title": {"zh": "拟合良好", "en": "Well Fitted"},
              "accent": "#059669", "bg": "#ECFDF5",
              "items": [
                  {"zh": "训练损失降到低位并趋于平缓", "en": "Training loss settles low and flattens"},
                  {"zh": "验证损失跟着降，并在最低点附近平稳", "en": "Validation loss follows it down and stays flat near its minimum"},
                  {"zh": "两条线之间有缺口，但缺口稳定、不再扩大", "en": "A gap remains, but it is stable and stops widening"},
                  {"zh": "这是一个可以交付的状态，不是一个「完美」的状态", "en": "This is a shippable state, not a perfect one"},
              ]},
             {"title": {"zh": "过拟合（高方差）", "en": "Overfitting (high variance)"},
              "accent": "#B91C1C", "bg": "#FEF2F2",
              "items": [
                  {"zh": "训练损失持续下降，一路逼近 0", "en": "Training loss keeps falling toward zero"},
                  {"zh": "验证损失降到某轮后掉头上升", "en": "Validation loss falls to some epoch, then turns upward"},
                  {"zh": "两条线的缺口持续扩大", "en": "The gap between the two lines keeps widening"},
                  {"zh": "本轮实测的证据：训练准确率 1.000，验证损失从第 85 轮的 0.516 升到第 400 轮的 0.671",
                   "en": "Evidence from this week: train accuracy 1.000 while validation loss rises from 0.516 at epoch 85 to 0.671 at epoch 400"},
              ]},
         ],
         "note": {"zh": "注意：验证「准确率」在同一批实验里几乎没变（0.856 上下）。所以判断过拟合必须看损失。",
                  "en": "Note: validation accuracy barely moved in the same experiments (around 0.856). That is why overfitting must be judged on loss."}},

        {"type": "chart",
         "title": {"zh": "过拟合长什么样：训练 vs 验证（本机实测）", "en": "What Overfitting Looks Like: Train vs Validation (measured)"},
         "subtitle": CURVE_PROTO,
         "right": MOD, "markers": False, "smooth": True,
         "x": 2.22, "y": 3.7, "w": 19.0, "h": 11.6,
         "y_max": 1.0, "markers_legend": True,
         "categories": EPOCHS_X,
         "series": [
             {"name": {"zh": "训练准确率", "en": "Train accuracy"},
              "values": TRAIN_ACC, "color": "#1E4FA8"},
             {"name": {"zh": "验证准确率", "en": "Validation accuracy"},
              "values": VAL_ACC, "color": "#D97706"},
         ],
         "x_label": {"zh": "训练轮次（每 20 轮取一点）", "en": "Epoch (one point every 20)"},
         "y_label": {"zh": "准确率", "en": "Accuracy"},
         "notes": [
             {"zh": "训练准确率在第 41 轮就已经到 0.9875，第 61 轮起恒为 1.000。",
              "en": "Train accuracy hits 0.9875 by epoch 41 and is pinned at 1.000 from epoch 61 on."},
             {"zh": "验证准确率卡在 0.83–0.84 一线，之后 300 多轮几乎没有任何提升。",
              "en": "Validation accuracy sticks at 0.83-0.84 and gains nothing over the next 300 epochs."},
             {"zh": "只画这一张图，你已经可以判定：模型已经记住训练集，而不是学到规律。",
              "en": "From this chart alone you can already conclude: the model has memorised the training set."},
             {"zh": "但准确率是粗尺子——它把「变差」这件事藏起来了。下一张图才是关键。",
              "en": "But accuracy is a coarse ruler — it hides the degradation. The next chart is the decisive one."},
         ]},

        {"type": "chart",
         "title": {"zh": "关键证据：验证损失掉头向上（本机实测）", "en": "The Decisive Evidence: Validation Loss Turns Upward (measured)"},
         "subtitle": CURVE_PROTO,
         "right": MOD, "markers": False, "smooth": True,
         "x": 2.22, "y": 3.7, "w": 19.0, "h": 11.6, "y_max": 1.6,
         "categories": EPOCHS_X,
         "series": [
             {"name": {"zh": "无正则（基线）", "en": "No regularization (baseline)"},
              "values": VAL_LOSS_BASE, "color": "#B91C1C", "emphasis": True},
             {"name": {"zh": "权重衰减 1e-2", "en": "Weight decay 1e-2"},
              "values": VAL_LOSS_WD, "color": "#059669"},
         ],
         "x_label": {"zh": "训练轮次（每 20 轮取一点）", "en": "Epoch (one point every 20)"},
         "y_label": {"zh": "验证集损失", "en": "Validation loss"},
         "notes": [
             {"zh": "基线：第 5 个点（第 81 轮）触底 0.6357，此后单调上升到第 400 轮的 0.8672。",
              "en": "Baseline: bottoms out at 0.6357 at point 5 (epoch 81), then climbs monotonically to 0.8672 at epoch 400."},
             {"zh": "同样的 400 轮，加了权重衰减的那条线在 0.58–0.61 之间横住，没有掉头。",
              "en": "Over the same 400 epochs, the weight-decay line stays flat in 0.58-0.61 and never turns up."},
             {"zh": "跨 5 个种子平均：基线验证损失上升 +0.155±0.089；权重衰减只上升 +0.027±0.014。",
              "en": "Averaged over 5 seeds: baseline validation loss rises by +0.155±0.089; weight decay only +0.027±0.014."},
             {"zh": "这条曲线的分岔，就是过拟合与不过拟合的分界线。",
              "en": "This fork in the curve is the line between overfitting and not."},
         ]},

        {"type": "table",
         "title": {"zh": "症状 → 诊断 → 对策", "en": "Symptom to Diagnosis to Remedy"},
         "subtitle": {"zh": "先读证据，再动手；开错药会越治越差",
                      "en": "Read the evidence first; the wrong prescription makes it worse"},
         "right": MOD,
         "cols": [{"zh": "你看到的现象", "en": "What you see"},
                  {"zh": "诊断", "en": "Diagnosis"},
                  {"zh": "该做什么 / 不该做什么", "en": "Do / do not"}],
         "widths": [9.6, 6.8, 13.0],
         "head_size": 12.0, "body_size": 11.0,
         "rows": [
             [{"zh": "训练损失高，验证损失也高，两条线贴近",
               "en": "Train loss high, validation loss high, lines close"},
              {"zh": "欠拟合", "en": "Underfitting"},
              {"zh": "加宽/加深网络、补特征、减弱或撤掉正则、训练更久。此时加 Dropout 只会更糟。",
               "en": "Widen/deepen, add features, weaken or remove regularisation, train longer. Adding dropout here makes it worse."}],
             [{"zh": "训练损失持续下降，验证损失掉头上升",
               "en": "Train loss keeps falling, validation loss turns upward"},
              {"zh": "过拟合", "en": "Overfitting"},
              {"zh": "早停、权重衰减、Dropout、数据增强、增加数据量。注意：验证「准确率」可能看不出变化。",
               "en": "Early stop, weight decay, dropout, augmentation, more data. Note: validation accuracy may show nothing."}],
             [{"zh": "训练与验证都很好，换新数据崩掉",
               "en": "Both look great, then a fresh batch collapses"},
              {"zh": "数据泄漏或分布漂移", "en": "Leakage or distribution shift"},
              {"zh": "回查划分顺序与预处理位置；检查新数据的采集条件是否与训练集一致。",
               "en": "Re-audit the split order and where preprocessing was fitted; check whether the new data was collected the same way."}],
             [{"zh": "多次运行结果在 ±3 个百分点内跳",
               "en": "Repeated runs swing within ±3 points"},
              {"zh": "噪声，不是结论", "en": "Noise, not a conclusion"},
              {"zh": "换 3–5 个种子重跑，报告均值 ± 标准差；差异小于一个标准差时不要宣布「更优」。",
               "en": "Re-run over 3-5 seeds, report mean ± sd; do not declare a win when the difference is under one sd."}],
             [{"zh": "验证损失在最低点附近来回小幅波动",
               "en": "Validation loss wobbles slightly near its minimum"},
              {"zh": "正常收敛", "en": "Normal convergence"},
              {"zh": "保留该状态即可。不要去追第 400 轮那个更低的训练损失。",
               "en": "Keep this state. Do not chase the lower training loss at epoch 400."}],
         ],
         "note": {"zh": "本课程要求：把「诊断依据」写进实验报告，而不是只写结论。依据 = 训练/验证损失曲线的具体轮次与数值。",
                  "en": "Course rule: put the evidence in the report, not just the verdict. Evidence = concrete epochs and values from the train/validation loss curves."}},

        # ------------------------------------------------- Part 04 (p18-23) -
        {"type": "section", "num": "04",
         "title": {"zh": "正则化：四个刹车及其代价", "en": "Regularization: Four Brakes and Their Cost"},
         "title_en": {"zh": "Regularization", "en": "Regularization"},
         "lead": {"zh": "正则化不是「免费的提分技巧」，它是用一点训练集拟合度，换一点泛化可靠性。\n刹车踩多了，车会停住——那叫欠拟合。",
                  "en": "Regularisation is not a free score boost. It trades a little training fit for a little generalisation.\nBrake too hard and the car stops — that is called underfitting."},
         "pillars": [
             {"title": {"zh": "早停", "en": "Early Stop"},
              "sub": {"zh": "在验证损失最低处停下", "en": "Stop at the validation-loss minimum"}},
             {"title": {"zh": "权重衰减", "en": "Weight Decay"},
              "sub": {"zh": "惩罚大权重", "en": "Penalise large weights"}},
             {"title": {"zh": "Dropout / 增强", "en": "Dropout / Augmentation"},
              "sub": {"zh": "给数据与表示加扰动", "en": "Perturb data and representation"}},
         ]},

        {"type": "cards", "cols": 4, "h": 12.0, "top": 3.6,
         "title": {"zh": "四种手段，各自在刹车什么", "en": "Four Brakes, Four Things Being Slowed Down"},
         "subtitle": {"zh": "它们都在限制模型的「自由度」，但限制的方式完全不同",
                      "en": "All four limit the model's freedom, but in completely different ways"},
         "right": MOD,
         "cards": [
             {"title": {"zh": "早停", "en": "Early Stop"},
              "title_en": {"zh": "Early stopping", "en": "Early stopping"},
              "accent": "#1E4FA8", "bg": "#F0F5FC",
              "body": [
                  {"zh": "监视验证损失，连续 N 轮不改善就停，并恢复到最佳权重。",
                   "en": "Watch validation loss; stop after N epochs without improvement, then restore the best weights."},
                  {"zh": "刹车对象：训练时长。不改模型、不改数据。",
                   "en": "Slows: training time. Changes neither the model nor the data."},
                  {"zh": "最大副作用：验证集被用于决策，反复使用会渐渐失效。",
                   "en": "Main side effect: validation is now used for decisions; repeated reuse wears it out."},
                  {"zh": "本轮实测：把 400 轮砍到 105 轮，测试准确率 0.874 vs 基线 0.878。",
                   "en": "Measured this week: 400 epochs cut to 105, test accuracy 0.874 vs baseline 0.878."},
              ]},
             {"title": {"zh": "权重衰减（L2）", "en": "Weight Decay (L2)"},
              "title_en": {"zh": "Weight decay", "en": "Weight decay"},
              "accent": "#059669", "bg": "#ECFDF5",
              "body": [
                  {"zh": "在损失里加 λ‖w‖²，让权重被持续拉向 0，模型更「平缓」。",
                   "en": "Add λ‖w‖² to the loss, pulling weights toward zero and making the function smoother."},
                  {"zh": "刹车对象：参数幅度。一行参数即可启用。",
                   "en": "Slows: parameter magnitude. One argument to enable."},
                  {"zh": "关键经验：它压住的是验证损失的上升，而不是提高准确率。",
                   "en": "Key lesson: it suppresses the rise in validation loss rather than raising accuracy."},
                  {"zh": "本轮实测：验证损失上升 +0.027±0.014，基线为 +0.155±0.089。",
                   "en": "Measured this week: validation loss rise +0.027±0.014 versus +0.155±0.089 for the baseline."},
              ]},
             {"title": {"zh": "Dropout", "en": "Dropout"},
              "title_en": {"zh": "Dropout", "en": "Dropout"},
              "accent": "#D97706", "bg": "#FFFBEB", "title_color": "#B45309",
              "body": [
                  {"zh": "训练时随机把一部分神经元置零，迫使网络不依赖某个单点特征。",
                   "en": "Randomly zero a fraction of neurons during training, so the net cannot rely on one unit."},
                  {"zh": "刹车对象：神经元之间的共适应。评估时必须关闭。",
                   "en": "Slows: co-adaptation between neurons. Must be off at evaluation time."},
                  {"zh": "易踩的坑：model.train() / model.eval() 忘记切换，结果每次评估都不一样。",
                   "en": "Classic bug: forgetting model.train() / model.eval(), so every evaluation differs."},
                  {"zh": "本轮实测：测试准确率 0.884±0.011 vs 基线 0.878±0.012 —— 差 0.006，小于一个标准差。",
                   "en": "Measured this week: test 0.884±0.011 vs baseline 0.878±0.012 — a 0.006 gap, under one sd."},
              ]},
             {"title": {"zh": "数据增强", "en": "Data Augmentation"},
              "title_en": {"zh": "Augmentation", "en": "Augmentation"},
              "accent": "#B91C1C", "bg": "#FEF2F2", "title_color": "#B91C1C",
              "body": [
                  {"zh": "对训练样本施加保持标签不变的变换，等价于扩充数据多样性。",
                   "en": "Apply label-preserving transforms to training samples — diversity instead of more data."},
                  {"zh": "刹车对象：训练集规模。增强算子必须符合数据语义。",
                   "en": "Slows: effective dataset size. The transform must respect the data's semantics."},
                  {"zh": "本任务上的实测反例：像素级位移 + 噪声把测试准确率拉到 0.824，反而更差。",
                   "en": "Measured counter-example here: pixel shifts + noise drop test accuracy to 0.824 — worse."},
                  {"zh": "原因：8×8 的手写数字只有 64 个像素，位移会抹掉笔画结构，等于制造了错标签。",
                   "en": "Why: at 8x8 there are only 64 pixels; shifting erases stroke structure and creates mislabelled data."},
              ]},
         ]},

        {"type": "code",
         "title": {"zh": "四种手段在 PyTorch 里怎么写", "en": "The Four Brakes in PyTorch"},
         "subtitle": {"zh": "全部改动加起来不到 15 行——难点不在写代码，在于知道什么时候不该写",
                      "en": "Under 15 lines in total — the hard part is knowing when not to write them"},
         "right": MOD,
         "blocks": [
             {"title": {"zh": "① 早停 + ② 权重衰减", "en": "1. Early stop + 2. Weight decay"},
              "size": 10.0,
              "code": {
                  "zh": [
                      "# ② 权重衰减：只是一行参数",
                      "opt = torch.optim.Adam(model.parameters(),",
                      "                       lr=1e-3, weight_decay=1e-2)",
                      "",
                      "# ① 早停：自己维护最佳状态",
                      "best, best_state, bad = float('inf'), None, 0",
                      "for ep in range(1, 401):",
                      "    train_one_epoch(model, opt, loader)",
                      "    va_loss, va_acc = evaluate(model, Xva, yva)",
                      "    if va_loss < best - 1e-4:",
                      "        best, bad = va_loss, 0",
                      "        best_state = {k: v.clone() for k, v in",
                      "                      model.state_dict().items()}",
                      "    else:",
                      "        bad += 1",
                      "        if bad >= 20:",
                      "            break",
                      "model.load_state_dict(best_state)   # 恢复最佳",
                  ],
                  "en": [
                      "# 2. Weight decay: just one argument",
                      "opt = torch.optim.Adam(model.parameters(),",
                      "                       lr=1e-3, weight_decay=1e-2)",
                      "",
                      "# 1. Early stop: keep the best state yourself",
                      "best, best_state, bad = float('inf'), None, 0",
                      "for ep in range(1, 401):",
                      "    train_one_epoch(model, opt, loader)",
                      "    va_loss, va_acc = evaluate(model, Xva, yva)",
                      "    if va_loss < best - 1e-4:",
                      "        best, bad = va_loss, 0",
                      "        best_state = {k: v.clone() for k, v in",
                      "                      model.state_dict().items()}",
                      "    else:",
                      "        bad += 1",
                      "        if bad >= 20:",
                      "            break",
                      "model.load_state_dict(best_state)   # restore best",
                  ]}},
             {"title": {"zh": "③ Dropout + ④ 增强", "en": "3. Dropout + 4. Augmentation"},
              "size": 10.0,
              "code": {
                  "zh": [
                      "# ③ Dropout：插在隐藏层之间",
                      "net = nn.Sequential(",
                      "    nn.Linear(64, 128), nn.ReLU(), nn.Dropout(0.3),",
                      "    nn.Linear(128, 64), nn.ReLU(), nn.Dropout(0.3),",
                      "    nn.Linear(64, 10))",
                      "",
                      "net.train()   # 训练：Dropout 生效",
                      "net.eval()    # 评估：Dropout 自动关闭！",
                      "",
                      "# ④ 增强：只作用在训练 batch 上",
                      "def augment(xb):",
                      "    xb = shift_pixels(xb, max_shift=1)",
                      "    noise = torch.randn_like(xb) * 0.15",
                      "    return (xb + noise).clamp(0, 1)",
                      "",
                      "for xb, yb in train_loader:",
                      "    xb = augment(xb)          # 验证集绝不增强",
                      "    loss = F.cross_entropy(net(xb), yb)",
                  ],
                  "en": [
                      "# 3. Dropout: insert between hidden layers",
                      "net = nn.Sequential(",
                      "    nn.Linear(64, 128), nn.ReLU(), nn.Dropout(0.3),",
                      "    nn.Linear(128, 64), nn.ReLU(), nn.Dropout(0.3),",
                      "    nn.Linear(64, 10))",
                      "",
                      "net.train()   # training: Dropout is active",
                      "net.eval()    # eval: Dropout switches off!",
                      "",
                      "# 4. Augmentation: training batch only",
                      "def augment(xb):",
                      "    xb = shift_pixels(xb, max_shift=1)",
                      "    noise = torch.randn_like(xb) * 0.15",
                      "    return (xb + noise).clamp(0, 1)",
                      "",
                      "for xb, yb in train_loader:",
                      "    xb = augment(xb)          # never augment val",
                      "    loss = F.cross_entropy(net(xb), yb)",
                  ]}},
         ],
         "note": {"zh": "记住 train/eval 切换是 Dropout 的第一号 bug 来源：评估时忘记 net.eval()，验证准确率会随机抖动，你甚至可能因此得出错误的「正则化有效」。",
                  "en": "The train/eval switch is bug number one for dropout: forget net.eval() and validation accuracy jitters randomly — enough to make you believe a regulariser works when it does not."}},

        {"type": "table",
         "title": {"zh": "本机实测：六种方案横向对照", "en": "Measured on This Machine: Six Arms Side by Side"},
         "subtitle": PROTO,
         "right": MOD,
         "cols": [{"zh": "方案", "en": "Arm"},
                  {"zh": "训练准确率", "en": "Train acc"},
                  {"zh": "验证准确率", "en": "Val acc"},
                  {"zh": "验证损失 最低→第400轮", "en": "Val loss best to 400"},
                  {"zh": "损失上升", "en": "Rise"},
                  {"zh": "测试准确率", "en": "Test acc"}],
         "widths": [4.9, 4.3, 4.6, 5.7, 4.4, 4.5],
         "head_size": 11.0, "body_size": 10.5,
         "rows": [
             [{"zh": "无正则（基线）", "en": "Baseline"},
              {"zh": "1.000", "en": "1.000"}, {"zh": "0.856", "en": "0.856"},
              {"zh": "0.516 → 0.671", "en": "0.516 to 0.671"},
              {"zh": "+0.155", "en": "+0.155"}, {"zh": "0.878", "en": "0.878"}],
             [{"zh": "早停（patience 20）", "en": "Early stop (patience 20)"},
              {"zh": "1.000", "en": "1.000"}, {"zh": "0.858", "en": "0.858"},
              {"zh": "0.516 → 0.534", "en": "0.516 to 0.534"},
              {"zh": "+0.018", "en": "+0.018"}, {"zh": "0.874", "en": "0.874"}],
             [{"zh": "权重衰减 1e-2", "en": "Weight decay 1e-2"},
              {"zh": "1.000", "en": "1.000"}, {"zh": "0.844", "en": "0.844"},
              {"zh": "0.497 → 0.524", "en": "0.497 to 0.524"},
              {"zh": "+0.027", "en": "+0.027"}, {"zh": "0.867", "en": "0.867"}],
             [{"zh": "Dropout 0.3", "en": "Dropout 0.3"},
              {"zh": "1.000", "en": "1.000"}, {"zh": "0.857", "en": "0.857"},
              {"zh": "0.474 → 0.645", "en": "0.474 to 0.645"},
              {"zh": "+0.171", "en": "+0.171"}, {"zh": "0.884", "en": "0.884"}],
             [{"zh": "数据增强", "en": "Augmentation"},
              {"zh": "0.960", "en": "0.960"}, {"zh": "0.814", "en": "0.814"},
              {"zh": "0.529 → 0.606", "en": "0.529 to 0.606"},
              {"zh": "+0.077", "en": "+0.077"}, {"zh": "0.824", "en": "0.824"}],
             [{"zh": "组合（衰减+Dropout+增强）", "en": "Combined (wd + dropout + aug)"},
              {"zh": "0.875", "en": "0.875"}, {"zh": "0.716", "en": "0.716"},
              {"zh": "0.849 → 0.884", "en": "0.849 to 0.884"},
              {"zh": "+0.035", "en": "+0.035"}, {"zh": "0.740", "en": "0.740"}],
         ],
         "note": {"zh": "表内为 5 个种子（42–46）的均值；测试准确率的标准差在 0.010–0.024 之间。读取方式见下一页。",
                  "en": "Means over 5 seeds (42-46); test-accuracy standard deviations run 0.010-0.024. How to read this table is on the next slide."}},

        {"type": "checklist",
         "title": {"zh": "怎么读这张表：三条诚实的结论", "en": "How to Read That Table: Three Honest Conclusions"},
         "subtitle": {"zh": "这次实验没有给出「正则化提高准确率」这个漂亮答案 —— 我们照实报告",
                      "en": "This experiment did not produce the tidy answer \"regularisation raises accuracy\" — so we report what happened"},
         "right": MOD,
         "items": [
             {"badge": {"zh": "结论 1", "en": "Finding 1"}, "accent": "#B91C1C",
              "title": {"zh": "正则化压住的是验证损失，不是提高准确率",
                        "en": "Regularisation suppresses validation loss — it does not raise accuracy"},
              "desc": {"zh": "基线验证损失上升 +0.155，早停只 +0.018，权重衰减只 +0.027。但六种方案的验证准确率全落在 0.716–0.858，测试准确率差异也都在一个标准差内。用准确率根本分辨不出谁更好；用验证损失一眼就能看出谁在退化。",
                       "en": "Baseline validation loss rises +0.155; early stop only +0.018, weight decay only +0.027. Yet validation accuracy across all six arms sits in 0.716-0.858 and every test-accuracy difference is within one sd. Accuracy cannot tell them apart; validation loss tells you instantly who is degrading."}},
             {"badge": {"zh": "结论 2", "en": "Finding 2"}, "accent": "#D97706",
              "title": {"zh": "数据增强与组合正则在本任务上有害，是欠拟合不是过拟合",
                        "en": "Augmentation and the combined arm hurt here — that is underfitting, not overfitting"},
              "desc": {"zh": "增强把测试准确率从 0.878 拉到 0.824，训练准确率也从 1.000 掉到 0.960；组合方案更是崩到 0.740。原因不是「正则太弱」，而是刹车踩过头：8×8 只有 64 个像素，位移会抹掉笔画结构，等于给训练数据制造了错标签。",
                       "en": "Augmentation pulls test accuracy from 0.878 down to 0.824 and train accuracy from 1.000 to 0.960; the combined arm collapses to 0.740. The cause is not weak regularisation but an over-applied brake: at 8x8 there are only 64 pixels, and shifting erases stroke structure, effectively mislabelling the training data."}},
             {"badge": {"zh": "结论 3", "en": "Finding 3"}, "accent": "#1E4FA8",
              "title": {"zh": "一次实验的差异可能是噪声，必须跨种子重复",
                        "en": "A single run's difference may be noise — always repeat across seeds"},
              "desc": {"zh": "同一个改动在不同种子下，测试准确率波动可达 ±3 个百分点。Dropout 的 0.884 对基线 0.878 只差 0.006，小于一个标准差（0.012）——按本课程的判定规则，这不足以宣布「Dropout 更优」，只能说「未观察到显著差异」。",
                       "en": "The same change moves test accuracy by up to ±3 points across seeds. Dropout's 0.884 versus the baseline's 0.878 is a 0.006 gap, under one sd (0.012) — by this course's rule that is not enough to claim a win, only to say no significant difference was observed."}},
         ],
         "note": {"zh": "这正是官方教案里那条思政要求的落点：实事求是——如实报告不成功的实验，是科研诚信的基本要求。",
                  "en": "This is exactly where the official lesson plan's value requirement lands: report unsuccessful experiments honestly — it is a basic requirement of research integrity."}},

        # ------------------------------------------------- Part 05 (p24-27) -
        {"type": "section", "num": "05",
         "title": {"zh": "Lab · 实验 5 过拟合复现与正则化对比", "en": "Lab · Overfitting Reproduction and Regularization"},
         "title_en": {"zh": "Hands-On Lab", "en": "Hands-On Lab"},
         "lead": {"zh": "先故意制造一次过拟合，再逐一施加四种手段。\n要求不是「让分数变高」，而是「用曲线说清楚每个手段到底改了什么」。",
                  "en": "Manufacture overfitting on purpose, then apply the four remedies one at a time.\nThe goal is not a higher score but curves that explain what each remedy actually changed."},
         "pillars": [
             {"title": {"zh": "制造过拟合", "en": "Manufacture It"},
              "sub": {"zh": "小训练集 + 大网络", "en": "Small train set, large net"}},
             {"title": {"zh": "逐个施加", "en": "One at a Time"},
              "sub": {"zh": "一次只改一个变量", "en": "Change one variable per run"}},
             {"title": {"zh": "量化改善", "en": "Quantify"},
              "sub": {"zh": "用验证损失与最佳轮次", "en": "Validation loss and best epoch"}},
         ]},

        {"type": "cards", "cols": 3, "h": 12.0, "top": 3.6,
         "title": {"zh": "实验任务：五个部分，逐步推进", "en": "Lab Tasks: Five Parts, One Step at a Time"},
         "subtitle": {"zh": "每一部分都有可检验的产出，做不出来就停下来查",
                      "en": "Every part ends in something checkable — if you cannot produce it, stop and debug"},
         "right": MOD,
         "cards": [
             {"title": {"zh": "A · 先制造过拟合", "en": "A. Manufacture Overfitting"},
              "title_en": {"zh": "before any fix", "en": "before any fix"},
              "accent": "#B91C1C", "bg": "#FEF2F2", "title_color": "#B91C1C",
              "body": [
                  {"zh": "数据：sklearn digits（8×8，1797 张，离线），先标准化到 0–1。",
                   "en": "Data: sklearn digits (8x8, 1797 images, offline), normalised to 0-1 first."},
                  {"zh": "划分：70/15/15 分层，随机种子固定；训练集只取 80 张。",
                   "en": "Split 70/15/15, stratified, fixed seed; keep only 80 training images."},
                  {"zh": "模型：64-128-64-10 的 MLP（17,226 个参数）。参数是样本数的 215 倍。",
                   "en": "Model: 64-128-64-10 MLP (17,226 parameters) — 215 parameters per training sample."},
                  {"zh": "产出：训练/验证准确率与损失四条曲线，指出验证损失的最低轮次。",
                   "en": "Deliverable: four curves (train/val accuracy and loss) plus the epoch of minimum validation loss."},
              ]},
             {"title": {"zh": "B · 逐个施加四种手段", "en": "B. Apply the Four Remedies"},
              "title_en": {"zh": "one at a time", "en": "one at a time"},
              "accent": "#1E4FA8", "bg": "#F0F5FC",
              "body": [
                  {"zh": "早停（patience=20，恢复最佳权重）；权重衰减（weight_decay=1e-2）。",
                   "en": "Early stop (patience 20, restore best); weight decay (weight_decay=1e-2)."},
                  {"zh": "Dropout（p=0.3）；数据增强（高斯噪声 σ=0.15 + ±1 像素位移）。",
                   "en": "Dropout (p=0.3); augmentation (Gaussian noise sigma=0.15 + ±1 px shift)."},
                  {"zh": "每次只改一个变量，其余与 A 完全一致；再加一个「全部组合」的对照臂。",
                   "en": "Change one variable at a time, everything else identical to A; add one combined arm."},
                  {"zh": "必须记录：验证损失最低值与第 400 轮的值、最佳轮次、实跑轮次。",
                   "en": "Record: validation loss at its minimum and at epoch 400, best epoch, epochs actually run."},
              ]},
             {"title": {"zh": "C · 量化 + D 诚实结论 + E 复现", "en": "C. Quantify, D. Conclude Honestly, E. Reproduce"},
              "title_en": {"zh": "the report", "en": "the report"},
              "accent": "#059669", "bg": "#ECFDF5",
              "body": [
                  {"zh": "量化：每臂给出「验证损失上升幅度」Δ = 第400轮 − 最低点，做成对照表。",
                   "en": "Quantify: for every arm compute Δ = loss at epoch 400 minus loss at its minimum, as a table."},
                  {"zh": "诚实结论：写出哪个手段对本任务有效、哪个无效、哪个反而有害，并给原因。",
                   "en": "Honest verdict: which remedy helped, which did nothing, which hurt — and why."},
                  {"zh": "跨种子：至少 3 个种子重跑主结论，报告均值 ± 标准差。",
                   "en": "Across seeds: re-run the key claim over at least 3 seeds; report mean ± sd."},
                  {"zh": "复现：固定随机种子，脚本一条命令可重跑；附上环境信息与库版本。",
                   "en": "Reproduce: fixed seed, one command to re-run; attach environment and library versions."},
              ]},
         ]},

        {"type": "table",
         "title": {"zh": "交付物与评分（实验 5）", "en": "Deliverables and Rubric (Lab 5)"},
         "subtitle": {"zh": "100 分制，事前公布；核心是「证据链是否完整」",
                      "en": "100 points, announced in advance; the core question is whether the evidence chain is complete"},
         "right": MOD,
         "cols": [{"zh": "交付物", "en": "Deliverable"},
                  {"zh": "具体要求", "en": "Requirement"},
                  {"zh": "分值", "en": "Points"}],
         "widths": [6.6, 18.3, 4.5],
         "head_size": 12.0, "body_size": 11.0,
         "rows": [
             [{"zh": "过拟合复现证据", "en": "Overfitting evidence"},
              {"zh": "训练/验证四条曲线 + 验证损失最低轮次的具体数值；能指出「训练准确率已饱和到 1.000」",
               "en": "Four curves plus the exact epoch of minimum validation loss; must show train accuracy saturating at 1.000"},
              {"zh": "20", "en": "20"}],
             [{"zh": "正则化对照表", "en": "Regularization comparison"},
              {"zh": "六臂（基线/早停/权重衰减/Dropout/增强/组合）的训练、验证、测试准确率与验证损失上升幅度 Δ",
               "en": "All six arms (baseline / early stop / weight decay / dropout / augmentation / combined) with train, val, test accuracy and Δ"},
              {"zh": "30", "en": "30"}],
             [{"zh": "量化结论", "en": "Quantified verdict"},
              {"zh": "明确说明哪个手段有效、哪个无效、哪个有害，并给出机理解释（而不是「效果不好」四个字）",
               "en": "State which remedy helped, which did not, which hurt, with a mechanism — not just \"it did not work\""},
              {"zh": "25", "en": "25"}],
             [{"zh": "跨种子稳定性", "en": "Cross-seed stability"},
              {"zh": "至少 3 个种子的重跑结果，报告均值 ± 标准差；说明结论是否稳定",
               "en": "At least 3 seeds re-run, mean ± sd reported, and a statement of whether the conclusion holds"},
              {"zh": "15", "en": "15"}],
             [{"zh": "可复现性", "en": "Reproducibility"},
              {"zh": "一条命令可重跑全部结果；固定种子；附环境与库版本（Python / torch / sklearn）",
               "en": "One command re-runs everything; fixed seeds; environment and library versions attached"},
              {"zh": "10", "en": "10"}],
         ],
         "note": {"zh": "扣分重点：只贴曲线不给轮次数值；把「准确率没变」写成「正则化无效」；只跑一个种子就下结论。",
                  "en": "Common deductions: curves without epoch numbers; reading \"accuracy did not move\" as \"regularisation is useless\"; concluding from a single seed."}},

        # ------------------------------------------------------ wrap-up -----
        {"type": "quiz",
         "title": {"zh": "随堂小测 · 模块二综合", "en": "Quick Check · Module 2 Review"},
         "subtitle": {"zh": "先自己选，再对照下一页的答案与理由",
                      "en": "Answer first, then compare with the next page"},
         "right": MOD, "cols": 2,
         "questions": [
             {"tag": {"zh": "指标", "en": "Metrics"},
              "q": {"zh": "某二分类器在 1000 个样本（50 个正例）上准确率 0.95。最需要补看哪个指标？为什么？",
                    "en": "A binary classifier scores 0.95 accuracy on 1,000 samples with 50 positives. Which metric must you look at next, and why?"},
              "options": [
                  {"zh": "A. 不用看，0.95 已经足够好", "en": "A. None — 0.95 is already good enough"},
                  {"zh": "B. 召回率：正例只占 5%，全部判负就能拿到 0.95，先确认正例有没有被漏掉",
                   "en": "B. Recall: positives are only 5%, so predicting all-negative already gives 0.95 — first confirm the positives are not being missed"},
                  {"zh": "C. 训练损失：它最能反映模型状态", "en": "C. Training loss: it reflects the model state best"},
                  {"zh": "D. 参数量：模型太大才需要担心", "en": "D. Parameter count: only large models are a worry"},
              ]},
             {"tag": {"zh": "诊断", "en": "Diagnosis"},
              "q": {"zh": "训练准确率 1.000、验证准确率 0.856、验证损失从第 85 轮起持续上升。诊断是什么？",
                    "en": "Train accuracy 1.000, validation accuracy 0.856, validation loss rising since epoch 85. What is the diagnosis?"},
              "options": [
                  {"zh": "A. 欠拟合，应该加大模型", "en": "A. Underfitting — enlarge the model"},
                  {"zh": "B. 过拟合，证据是验证损失已掉头上升（准确率被天花板掩盖了）",
                   "en": "B. Overfitting — the evidence is validation loss turning upward (accuracy hides it behind a ceiling)"},
                  {"zh": "C. 数据有问题，应该重新采集", "en": "C. The data is broken — collect again"},
                  {"zh": "D. 看不出来，必须看测试集才能判断", "en": "D. Cannot tell — you need the test set"},
              ]},
             {"tag": {"zh": "协议", "en": "Protocol"},
              "q": {"zh": "以下哪个做法会让验证分数虚高？",
                    "en": "Which of these inflates the validation score?"},
              "options": [
                  {"zh": "A. 先划分数据集，再只用训练集拟合标准化参数",
                   "en": "A. Split first, then fit the scaler on the training set only"},
                  {"zh": "B. 对全量数据先做过采样与标准化，再划分训练/验证集",
                   "en": "B. Oversample and normalise the whole dataset first, then split"},
                  {"zh": "C. 用 StratifiedKFold 做分层交叉验证",
                   "en": "C. Use StratifiedKFold for cross-validation"},
                  {"zh": "D. 用 5 个随机种子重跑并报告均值 ± 标准差",
                   "en": "D. Re-run over 5 seeds and report mean ± sd"},
              ]},
             {"tag": {"zh": "正则化", "en": "Regularization"},
              "q": {"zh": "本机实测中，权重衰减 1e-2 最干净的收益是什么？",
                    "en": "In this week's measurements, what was weight decay 1e-2's cleanest benefit?"},
              "options": [
                  {"zh": "A. 把测试准确率从 0.878 提到 0.95", "en": "A. Raising test accuracy from 0.878 to 0.95"},
                  {"zh": "B. 把训练准确率降到 0.90，避免过拟合", "en": "B. Lowering train accuracy to 0.90 to avoid overfitting"},
                  {"zh": "C. 把验证损失的上升幅度从 +0.155 压到 +0.027",
                   "en": "C. Suppressing the rise in validation loss from +0.155 to +0.027"},
                  {"zh": "D. 减少参数量", "en": "D. Reducing the parameter count"},
              ]},
         ]},

        {"type": "summary",
         "title": {"zh": "本周要点与课后任务", "en": "This Week's Takeaways and Homework"},
         "subtitle": {"zh": "把「训练集分数」和「可信的分数」彻底区分开来",
                      "en": "Separate the training-set score from a trustworthy score"},
         "right": MOD,
         "points": [
             {"zh": "指标选择的本质是把业务代价写进公式：漏报贵看召回率，误报贵看精确率，两者都要看 F1，排序能力看 AUC。",
              "en": "Choosing a metric is writing business cost into a formula: recall when a miss is costly, precision when a false alarm is, F1 when both matter, AUC for ranking."},
             {"zh": "评估协议决定数字是否可信：先划分后处理、测试集只碰一次、小数据用分层 K 折、结论必须跨种子重复。",
              "en": "The protocol decides whether the number is believable: split before processing, touch test once, stratify and K-fold on small data, and repeat across seeds."},
             {"zh": "过拟合的唯一可靠证据是验证损失掉头上升；验证准确率会因为天花板效应看不出退化。",
              "en": "The only reliable evidence of overfitting is validation loss turning upward; validation accuracy hides the degradation behind a ceiling."},
             {"zh": "四种正则化手段动作不同：早停限时长、权重衰减限幅度、Dropout 限共适应、增强限数据多样性——都不是免费的。",
              "en": "The four remedies act differently: early stop limits time, weight decay limits magnitude, dropout limits co-adaptation, augmentation limits data diversity — none is free."},
             {"zh": "本周实测结论：正则化压住了验证损失，但没有提高准确率；数据增强与组合正则在 8×8 图像上反而有害。照实报告。",
              "en": "What we measured: regularisation suppressed validation loss but did not raise accuracy; augmentation and combined regularisation actually hurt on 8x8 images. Report it as it is."},
         ],
         "todo_title": {"zh": "课后任务", "en": "After Class"},
         "todos": [
             {"title": {"zh": "提交正则化对比实验报告", "en": "Submit the regularization report"},
              "desc": {"zh": "含六臂对照表、验证损失上升幅度 Δ、跨种子均值 ± 标准差，以及「哪种手段对本任务最有效及原因」的明确结论。",
                       "en": "Six-arm table, the validation-loss rise Δ, cross-seed mean ± sd, and an explicit verdict on which remedy works best here and why."}},
             {"title": {"zh": "完成模块二综合小测", "en": "Finish the Module 2 quiz"},
              "desc": {"zh": "覆盖 W5–W8 知识点（KT9–KT14），下次课复习导入环节对答案。",
                       "en": "Covers W5-W8 knowledge points (KT9-KT14); answers reviewed at the start of next class."}},
         ]},

        {"type": "closing",
         "quote": {"zh": "先证明你的数字可信，\n再谈你的模型多好。",
                   "en": "Prove your number is trustworthy first;\nargue about how good your model is second."},
         "quote_sub": {"zh": "下周：卷积神经网络与计算机视觉应用 —— 实验 6 会用到本周的评估协议与增强策略，请把曲线读法带过去。",
                       "en": "Next week: CNNs for Computer Vision — Lab 6 reuses this week's evaluation protocol and augmentation, so bring your curve-reading."},
         "next": {"zh": "W7 · 卷积、池化与感受野 · 用增强与 GPU 训练 CNN · 混淆矩阵与错分案例分析（实验 6）",
                  "en": "W7 · Convolution, pooling and receptive fields · training a CNN with augmentation on GPU · confusion matrix and error-case analysis (Lab 6)"}},
    ],
}
