"""Week 3 — Machine Learning Foundations  ·  slide spec (bilingual)."""

SPEC = {
    "week": 3,
    "slides": [
        # ---------------------------------------------------------- cover ----
        {"type": "cover",
         "kicker": {"zh": "SE 4XXX · 本科课程", "en": "SE 4XXX · UNDERGRADUATE COURSE"},
         "title": {"zh": "机器学习基础", "en": "Machine Learning Foundations"},
         "title_sub": {"zh": "Machine Learning Foundations",
                       "en": "Learning from data · loss and optimisation · generalisation"},
         "subtitle": {"zh": "Week 3 · 三类范式 · 参数与超参数 · 梯度下降 · 交叉验证",
                      "en": "Week 3 · Paradigms · Parameters vs Hyperparameters · Gradient Descent · Cross-Validation"},
         "chips": [
             ({"zh": "Module 1 · W2–4", "en": "Module 1 · W2–4"}, 1.0),
             ({"zh": "180 min · 授课 + 实验 + 小测", "en": "180 min · Lecture + Lab + Quiz"}, 1.5),
             ({"zh": "scikit-learn · Pipeline · GridSearchCV", "en": "scikit-learn · Pipeline · GridSearchCV"}, 1.6),
             ({"zh": "留学生班 · 英文授课", "en": "International Students"}, 1.0),
         ]},

        # ------------------------------------------------------- contents ----
        {"type": "contents",
         "right": {"zh": "Module 1 · Week 3", "en": "Module 1 · Week 3"},
         "count": {"zh": "5 部分", "en": "5 Parts"},
         "count_label": {"zh": "本周结构", "en": "Part"},
         "tagline": {"zh": "先理解「学习」到底在学什么，\n再动手把工作流工程化。\nUnderstand learning before you automate it.",
                     "en": "Understand what \"learning\" actually means, then engineer the workflow."},
         "timing": {"zh": "理论约 90 min · Lab 约 75 min · 小测与小结 15 min",
                    "en": "Theory ~90 min · Lab ~75 min · Quiz & Summary 15 min"},
         "parts": [
             {"title": {"zh": "学习是什么", "en": "What Is Learning"},
              "title_en": "What Is Learning",
              "desc": {"zh": "定义 · 三类范式 · 统一术语表",
                       "en": "Definition · three paradigms · shared vocabulary"}},
             {"title": {"zh": "模型与参数", "en": "Model & Parameters"},
              "title_en": "Model & Parameters",
              "desc": {"zh": "假设空间 · 线性模型 · 参数 vs 超参数",
                       "en": "Hypothesis space · linear model · parameters vs hyperparameters"}},
             {"title": {"zh": "损失与优化", "en": "Loss & Optimization"},
              "title_en": "Loss & Optimization",
              "desc": {"zh": "MSE · 交叉熵 · 梯度下降 · 学习率",
                       "en": "MSE · cross-entropy · gradient descent · learning rate"}},
             {"title": {"zh": "泛化与评估", "en": "Generalization"},
              "title_en": "Generalization & Evaluation",
              "desc": {"zh": "训练/验证/测试 · k 折交叉验证 · 过拟合与欠拟合",
                       "en": "Train/val/test · k-fold CV · overfitting vs underfitting"}},
             {"title": {"zh": "Lab · sklearn 工作流", "en": "Lab · sklearn Workflow"},
              "title_en": "Hands-On Lab",
              "desc": {"zh": "Pipeline 防泄漏 · GridSearchCV 调参 · 分类与回归",
                       "en": "Leakage-free Pipeline · GridSearchCV · classification & regression"}},
         ]},

        # -------------------------------------------------- Part 01 (p3-7) ---
        {"type": "section", "num": "01",
         "title": {"zh": "学习是什么", "en": "What Is Learning"},
         "title_en": {"zh": "What Is Learning", "en": "What Is Learning"},
         "lead": {"zh": "机器学习不是「写规则」，而是「从样例中反推出规则」。\n这一页之后，你应该能说清：它在学什么、拿什么学、学到了什么。",
                  "en": "Machine learning is not writing rules — it is inferring rules from examples.\nAfter this part you can state what is learned, from what, and into what."},
         "pillars": [
             {"title": {"zh": "经验驱动", "en": "From Experience"},
              "sub": {"zh": "数据替代手写规则", "en": "Data replaces hand-written rules"}},
             {"title": {"zh": "三类范式", "en": "Three Paradigms"},
              "sub": {"zh": "监督 / 无监督 / 强化", "en": "Supervised / unsupervised / RL"}},
             {"title": {"zh": "统一术语", "en": "Shared Vocabulary"},
              "sub": {"zh": "样本 · 特征 · 标签 · 推理", "en": "Sample · feature · label · inference"}},
         ]},

        {"type": "compare",
         "title": {"zh": "传统编程 vs 机器学习", "en": "Traditional Programming vs Machine Learning"},
         "right": {"zh": "Module 1 · Week 3", "en": "Module 1 · Week 3"},
         "columns": [
             {"title": {"zh": "传统编程", "en": "Traditional Programming"}, "accent": "6B7280",
              "bg": "F5F7FA",
              "items": [
                  {"zh": "人写规则：if 面积 > 100 且 地铁 < 500m → 贵",
                   "en": "Humans write rules: if area > 100 and metro < 500m -> expensive"},
                  {"zh": "输入：规则 + 数据", "en": "Input: rules + data"},
                  {"zh": "输出：答案", "en": "Output: answers"},
                  {"zh": "规则复杂到写不出来时就失效", "en": "Breaks when rules get too complex to write"}]},
             {"title": {"zh": "机器学习", "en": "Machine Learning"}, "accent": "1E4FA8",
              "bg": "F0F5FC",
              "items": [
                  {"zh": "人给样例：1 万套房子的 (特征, 成交价)",
                   "en": "Humans supply examples: 10k houses as (features, price)"},
                  {"zh": "输入：数据 + 答案", "en": "Input: data + answers"},
                  {"zh": "输出：规则（模型）", "en": "Output: rules (the model)"},
                  {"zh": "规则由算法从样例中反推出来", "en": "The algorithm infers the rules from examples"}]},
         ],
         "note": {"zh": "Tom Mitchell 定义：一个程序在任务 T 上的表现 P 随经验 E 提升，就说它从 E 中学习了。",
                  "en": "Tom Mitchell: a program learns from experience E w.r.t. task T and performance measure P if P improves with E."}},

        {"type": "table",
         "title": {"zh": "三类学习范式", "en": "Three Learning Paradigms"},
         "right": {"zh": "Module 1 · Week 3", "en": "Module 1 · Week 3"},
         "cols": [{"zh": "范式", "en": "Paradigm"},
                  {"zh": "数据长什么样", "en": "Data Shape"},
                  {"zh": "典型任务", "en": "Typical Tasks"},
                  {"zh": "代表算法", "en": "Representative Algorithms"}],
         "widths": [5.2, 8.6, 7.0, 8.6],
         "h": 6.6,
         "bold_first": True,
         "rows": [
             [{"zh": "监督学习", "en": "Supervised"},
              {"zh": "(x, y) 成对，有标准答案", "en": "(x, y) pairs with ground truth"},
              {"zh": "分类、回归", "en": "Classification, regression"},
              {"zh": "逻辑回归、随机森林、SVM", "en": "Logistic regression, random forest, SVM"}],
             [{"zh": "无监督学习", "en": "Unsupervised"},
              {"zh": "只有 x，没有标签", "en": "Only x, no labels"},
              {"zh": "聚类、降维、异常检测", "en": "Clustering, dimensionality reduction, anomaly detection"},
              {"zh": "KMeans、PCA、DBSCAN", "en": "KMeans, PCA, DBSCAN"}],
             [{"zh": "强化学习", "en": "Reinforcement"},
              {"zh": "(状态, 动作, 奖励) 序列", "en": "(state, action, reward) sequences"},
              {"zh": "决策、控制、博弈", "en": "Decision making, control, games"},
              {"zh": "Q-learning、PPO、DQN", "en": "Q-learning, PPO, DQN"}],
         ],
         "note": {"zh": "本课程第 1–6 周聚焦监督学习；无监督与强化在后续模块出现。",
                  "en": "Weeks 1-6 focus on supervised learning; unsupervised and RL appear later."}},

        {"type": "cards", "cols": 3, "h": 4.9, "top": 3.5,
         "title": {"zh": "术语表：一张表读懂论文和文档", "en": "Vocabulary: Read Any Paper After This"},
         "right": {"zh": "Module 1 · Week 3", "en": "Module 1 · Week 3"},
         "cards": [
             {"title": {"zh": "样本 Sample", "en": "Sample"},
              "title_en": "sample",
              "body": [{"zh": "数据集中的一条记录", "en": "One row of the dataset"}]},
             {"title": {"zh": "特征 Feature", "en": "Feature"},
              "title_en": "feature · x",
              "body": [{"zh": "描述样本的属性列（面积、像素）", "en": "Attribute columns (area, pixels)"}]},
             {"title": {"zh": "标签 Label", "en": "Label"},
              "title_en": "label · y",
              "body": [{"zh": "要预测的目标值（价格、类别）", "en": "The target to predict (price, class)"}]},
             {"title": {"zh": "训练集 Training Set", "en": "Training Set"},
              "title_en": "training set",
              "body": [{"zh": "用来拟合参数的那部分数据", "en": "The portion used to fit parameters"}]},
             {"title": {"zh": "推理 Inference", "en": "Inference"},
              "title_en": "inference · predict",
              "body": [{"zh": "模型训练完后对新样本做预测", "en": "Predicting on new samples after training"}]},
             {"title": {"zh": "泛化 Generalization", "en": "Generalization"},
              "title_en": "generalization",
              "body": [{"zh": "在没见过的数据上仍然表现好", "en": "Performing well on unseen data"}]},
         ]},

        {"type": "flow", "y": 6.2, "h": 4.9,
         "title": {"zh": "一个直觉例子：房价预测", "en": "An Intuition: Predicting House Prices"},
         "right": {"zh": "Module 1 · Week 3", "en": "Module 1 · Week 3"},
         "steps": [
             {"title": {"zh": "收集样例", "en": "Collect"},
              "title_en": "Collect",
              "desc": {"zh": "1 万套已成交房子\n(面积, 房龄, 地铁距离; 成交价)",
                       "en": "10k sold houses\n(area, age, metro; price)"}},
             {"title": {"zh": "假设一条规则", "en": "Hypothesise"},
              "title_en": "Hypothesise",
              "desc": {"zh": "先猜 价格 ≈ w × 面积 + b",
                       "en": "Guess price ≈ w × area + b"}},
             {"title": {"zh": "定义误差", "en": "Measure"},
              "title_en": "Measure error",
              "desc": {"zh": "用损失函数量化\n猜得有多离谱", "en": "A loss function quantifies\nhow wrong the guess is"}},
             {"title": {"zh": "自动调整", "en": "Adjust"},
              "title_en": "Adjust",
              "desc": {"zh": "沿着误差下降的方向\n反复微调 w、b", "en": "Repeatedly nudge w, b\ndownhill on the loss"}},
             {"title": {"zh": "预测新房", "en": "Predict"},
              "title_en": "Predict",
              "desc": {"zh": "给一套没见过的房子\n输出价格", "en": "Output a price for\na house never seen"}},
         ],
         "note": {"zh": "这五步就是后面所有模型的骨架：假设 → 度量误差 → 优化 → 预测。深度学习也只不过把「假设」换成了神经网络。",
                  "en": "These five steps are the skeleton of every model that follows; deep learning only swaps the hypothesis for a neural network."}},

        # -------------------------------------------------- Part 02 (p8-12) --
        {"type": "section", "num": "02",
         "title": {"zh": "模型与参数", "en": "Model & Parameters"},
         "title_en": {"zh": "Model & Parameters", "en": "Model & Parameters"},
         "lead": {"zh": "模型是一族函数的集合（假设空间），训练就是在这个空间里挑最好的那一个。",
                  "en": "A model is a family of functions (the hypothesis space); training picks the best member of that family."},
         "pillars": [
             {"title": {"zh": "假设空间", "en": "Hypothesis Space"},
              "sub": {"zh": "模型能表示的所有函数", "en": "Every function the model can express"}},
             {"title": {"zh": "参数即知识", "en": "Parameters Are Knowledge"},
              "sub": {"zh": "w、b 就是学到的东西", "en": "w and b are what gets learned"}},
             {"title": {"zh": "容量要匹配", "en": "Capacity Must Match"},
              "sub": {"zh": "太小欠拟合，太大过拟合", "en": "Too small underfits, too large overfits"}},
         ]},

        {"type": "cards", "cols": 3, "h": 6.2, "top": 3.6,
         "title": {"zh": "模型、参数与线性模型", "en": "Models, Parameters and the Linear Model"},
         "right": {"zh": "Module 1 · Week 3", "en": "Module 1 · Week 3"},
         "cards": [
             {"title": {"zh": "模型 = 假设空间 + 一个点", "en": "Model = Space + One Point"},
              "title_en": "model",
              "body": [
                  {"zh": "所有 y = wx + b 构成一个函数族",
                   "en": "All y = wx + b form a function family"},
                  {"zh": "训练 = 在这个族里挑出误差最小的那个点",
                   "en": "Training picks the member with the lowest error"}]},
             {"title": {"zh": "线性模型展开", "en": "The Linear Model"},
              "title_en": "ŷ = w·x + b",
              "body": [
                  {"zh": "w 权重：每个特征的重要程度",
                   "en": "w, the weight: how much each feature matters"},
                  {"zh": "b 偏置：整体平移量",
                   "en": "b, the bias: a global offset"},
                  {"zh": "多个特征时：ŷ = w₁x₁ + … + wₙxₙ + b",
                   "en": "With n features: ŷ = w₁x₁ + … + wₙxₙ + b"}]},
             {"title": {"zh": "参数从数据里学出来", "en": "Parameters Come From Data"},
              "title_en": "parameters",
              "body": [
                  {"zh": "训练前 w、b 是随机初始化的",
                   "en": "w and b start from random initialisation"},
                  {"zh": "训练过程不断修正它们",
                   "en": "Training keeps correcting them"},
                  {"zh": "训练结束后它们就是「学到的知识」",
                   "en": "After training they are the learned knowledge"}]},
         ]},

        {"type": "chart", "w": 19.0, "h": 12.0,
         "title": {"zh": "拟合直线：机器学到的那条线", "en": "Fitting a Line: What the Machine Learned"},
         "right": {"zh": "Module 1 · Week 3", "en": "Module 1 · Week 3"},
         "categories": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
         "x_label": {"zh": "特征 x（如面积）", "en": "Feature x (e.g. area)"},
         "y_label": {"zh": "目标 y（如价格）", "en": "Target y (e.g. price)"},
         "series": [
             {"name": {"zh": "真实数据点", "en": "Observed data"}, "color": "9CA3AF", "smooth": False,
              "values": [3.2, 4.6, 6.1, 9.4, 11.2, 12.8, 15.6, 16.9, 19.4, 21.1]},
             {"name": {"zh": "拟合直线 ŷ = wx + b", "en": "Fitted line ŷ = wx + b"}, "color": "1E4FA8",
              "smooth": False, "no_markers": True, "emphasis": True,
              "values": [3, 5, 7, 9, 11, 13, 15, 17, 19, 21]},
         ],
         "notes": [
             {"zh": "每个竖着的差距就是一个残差（residual）",
              "en": "Each vertical gap is one residual"},
             {"zh": "训练的目标：让所有残差的平方和最小（最小二乘）",
              "en": "Training minimises the sum of squared residuals (least squares)"},
             {"zh": "这条线就是模型，w 和 b 是它学到的参数",
              "en": "This line is the model; w and b are its learned parameters"},
             {"zh": "换新数据不用重新写代码，重新 fit 即可",
              "en": "New data means refit — not rewrite"},
         ]},

        {"type": "cards", "cols": 3, "h": 6.4, "top": 3.6,
         "title": {"zh": "模型容量：太小、刚好、太大", "en": "Capacity: Too Small, Just Right, Too Large"},
         "right": {"zh": "Module 1 · Week 3", "en": "Module 1 · Week 3"},
         "cards": [
             {"title": {"zh": "容量太小 → 欠拟合", "en": "Too Small → Underfitting"},
              "title_en": "underfitting", "accent": "D97706", "bg": "FFFBEB",
              "body": [
                  {"zh": "连训练集上的规律都没抓住",
                   "en": "Misses patterns even in the training set"},
                  {"zh": "表现：训练集和测试集都差",
                   "en": "Symptom: bad on train AND test"},
                  {"zh": "对策：加特征、换更灵活的模型",
                   "en": "Fix: more features, a more flexible model"}]},
             {"title": {"zh": "容量刚好 → 可用", "en": "Just Right → Deployable"},
              "title_en": "the sweet spot", "accent": "059669", "bg": "ECFDF5",
              "body": [
                  {"zh": "抓住了规律，没被噪声带跑",
                   "en": "Captures the pattern without chasing noise"},
                  {"zh": "表现：训练集和验证集都好且接近",
                   "en": "Symptom: train and validation both good and close"},
                  {"zh": "这是本周 Lab 要做到的事",
                   "en": "This is what this week's lab aims for"}]},
             {"title": {"zh": "容量太大 → 过拟合", "en": "Too Large → Overfitting"},
              "title_en": "overfitting", "accent": "B91C1C", "bg": "FEF2F2",
              "body": [
                  {"zh": "把噪声当成了规律背下来",
                   "en": "Memorises noise as if it were signal"},
                  {"zh": "表现：训练集极好，验证集明显下滑",
                   "en": "Symptom: great on train, clearly worse on validation"},
                  {"zh": "对策：正则化、早停、更多数据、降容量",
                   "en": "Fix: regularisation, early stopping, more data, less capacity"}]},
         ]},

        {"type": "table",
         "title": {"zh": "参数 vs 超参数（本周最容易搞混的一对）",
                   "en": "Parameters vs Hyperparameters (This Week's Classic Mix-up)"},
         "right": {"zh": "Module 1 · Week 3", "en": "Module 1 · Week 3"},
         "cols": [{"zh": "对比项", "en": "Aspect"},
                  {"zh": "参数 Parameter", "en": "Parameter"},
                  {"zh": "超参数 Hyperparameter", "en": "Hyperparameter"}],
         "widths": [6.4, 11.4, 11.6],
         "h": 8.4, "bold_first": True,
         "rows": [
             [{"zh": "谁决定", "en": "Who sets it"},
              {"zh": "训练过程从数据里学出来", "en": "Learned from data during training"},
              {"zh": "人在训练前手动设定", "en": "Set by you before training"}],
             [{"zh": "例子", "en": "Examples"},
              {"zh": "线性回归的 w、b；决策树的划分阈值",
               "en": "w and b in linear regression; split thresholds in a tree"},
              {"zh": "学习率、正则强度 C、max_depth、k 折的 k",
               "en": "Learning rate, C, max_depth, k in k-fold"}],
             [{"zh": "怎么定", "en": "How to choose"},
              {"zh": "由优化算法自动更新", "en": "Updated automatically by the optimiser"},
              {"zh": "用验证集 + 网格搜索 / 随机搜索来挑",
               "en": "Chosen on the validation set via grid / random search"}],
             [{"zh": "写在哪", "en": "Where it appears"},
              {"zh": "model.coef_ 、 model.intercept_",
               "en": "model.coef_ , model.intercept_"},
              {"zh": "Pipeline 里能搜的参数（如 clf__C）",
               "en": "Searchable keys in a Pipeline (e.g. clf__C)"}],
         ],
         "note": {"zh": "一句话：参数是「学」出来的，超参数是「选」出来的。Lab 的 GridSearchCV 就是在帮你选。",
                  "en": "Parameters are learned; hyperparameters are chosen. GridSearchCV in the lab does the choosing."}},

        # -------------------------------------------------- Part 03 (p13-17) -
        {"type": "section", "num": "03",
         "title": {"zh": "损失与优化", "en": "Loss & Optimization"},
         "title_en": {"zh": "Loss & Optimization", "en": "Loss & Optimization"},
         "lead": {"zh": "损失函数告诉模型「错得多离谱」，优化算法告诉它「往哪改」。",
                  "en": "The loss tells the model how wrong it is; the optimiser tells it which way to move."},
         "pillars": [
             {"title": {"zh": "损失函数", "en": "Loss Function"},
              "sub": {"zh": "把「错」变成一个数字", "en": "Turning error into one number"}},
             {"title": {"zh": "梯度下降", "en": "Gradient Descent"},
              "sub": {"zh": "蒙眼下山那一步", "en": "Walking downhill blindfolded"}},
             {"title": {"zh": "学习率", "en": "Learning Rate"},
              "sub": {"zh": "每一步迈多大", "en": "How big each step is"}},
         ]},

        {"type": "table",
         "title": {"zh": "常见损失函数", "en": "Common Loss Functions"},
         "subtitle": {"zh": "选错损失，模型就会优化错目标",
                      "en": "Pick the wrong one and the model optimises the wrong thing"},
         "right": {"zh": "Module 1 · Week 3", "en": "Module 1 · Week 3"},
         "cols": [{"zh": "损失", "en": "Loss"},
                  {"zh": "公式", "en": "Formula"},
                  {"zh": "用在哪", "en": "Used for"},
                  {"zh": "特点", "en": "Property"}],
         "widths": [5.4, 8.2, 7.2, 8.6],
         "h": 8.4, "bold_first": True,
         "rows": [
             [{"zh": "MSE 均方误差", "en": "MSE"},
              "mean((y − ŷ)²)",
              {"zh": "回归默认选择", "en": "Regression default"},
              {"zh": "对大误差惩罚重，对异常值敏感",
               "en": "Punishes large errors heavily; outlier-sensitive"}],
             [{"zh": "MAE 平均绝对误差", "en": "MAE"},
              "mean(|y − ŷ|)",
              {"zh": "回归，且数据有异常值", "en": "Regression with outliers"},
              {"zh": "量纲和目标一致，稳健但不可导点",
               "en": "Same unit as the target; robust, kink at zero"}],
             [{"zh": "交叉熵", "en": "Cross-Entropy"},
              "−Σ y·log(ŷ)",
              {"zh": "分类（本周 digits 用这个）",
               "en": "Classification (this week's digits)"},
              {"zh": "惩罚「错且自信」，概率校准好",
               "en": "Punishes confident mistakes; well-calibrated"}],
             [{"zh": "R² 决定系数", "en": "R²"},
              "1 − SS_res / SS_tot",
              {"zh": "回归的评估指标（不是损失）",
               "en": "Regression metric (not a loss)"},
              {"zh": "1 完美，0 等于猜均值，可负",
               "en": "1 perfect, 0 = guessing the mean, can be negative"}],
         ],
         "note": {"zh": "本周 Lab：分类看 accuracy，回归看 MAE 和 R² —— 别把回归的 score() 当准确率。",
                  "en": "In the lab: accuracy for classification, MAE and R² for regression — score() is not accuracy for regressors."}},

        {"type": "flow", "y": 6.2, "h": 5.0,
         "title": {"zh": "梯度下降：蒙眼下山", "en": "Gradient Descent: Walking Downhill Blindfolded"},
         "right": {"zh": "Module 1 · Week 3", "en": "Module 1 · Week 3"},
         "steps": [
             {"title": {"zh": "站在当前点", "en": "Stand"},
              "title_en": "Start somewhere",
              "desc": {"zh": "参数随机初始化\n(w, b 随便取一组)",
                       "en": "Parameters start at random\n(w, b are arbitrary)"}},
             {"title": {"zh": "摸最陡的方向", "en": "Feel the Slope"},
              "title_en": "Compute the gradient",
              "desc": {"zh": "算梯度：哪边是下坡\n以及有多陡",
                       "en": "The gradient says which way is\ndownhill and how steep"}},
             {"title": {"zh": "迈一小步", "en": "Take a Step"},
              "title_en": "Step downhill",
              "desc": {"zh": "w ← w − η · 梯度\nη 就是学习率",
                       "en": "w ← w − η · gradient\nη is the learning rate"}},
             {"title": {"zh": "重复到平稳", "en": "Repeat"},
              "title_en": "Until it flattens",
              "desc": {"zh": "走到谷底附近\n损失不再明显下降",
                       "en": "Stop near the bottom when\nthe loss stops improving"}},
         ],
         "note": {"zh": "梯度下降只保证找到「附近的最低点」；凸问题（线性回归、逻辑回归）里附近就是全局，神经网络里不是。",
                  "en": "Gradient descent only guarantees a nearby minimum — global for convex problems (linear/logistic regression), not for neural networks."}},

        {"type": "cards", "cols": 3, "h": 6.6, "top": 3.6,
         "title": {"zh": "学习率 η：最重要的那个超参数",
                   "en": "Learning Rate η: The One Hyperparameter That Matters Most"},
         "right": {"zh": "Module 1 · Week 3", "en": "Module 1 · Week 3"},
         "cards": [
             {"title": {"zh": "太小", "en": "Too Small"},
              "title_en": "η = 1e-6", "accent": "6B7280", "bg": "F5F7FA",
              "body": [
                  {"zh": "每一步挪一点点，训练极慢",
                   "en": "Tiny steps — training crawls"},
                  {"zh": "可能还没走到就到了时间上限",
                   "en": "May never arrive before the time budget runs out"},
                  {"zh": "表现：损失下降极其平缓",
                   "en": "Symptom: the loss curve is almost flat"}]},
             {"title": {"zh": "合适", "en": "Just Right"},
              "title_en": "η = 1e-3 ~ 1e-1", "accent": "059669", "bg": "ECFDF5",
              "body": [
                  {"zh": "先快后慢地稳定下降",
                   "en": "Fast at first, then smoothly flattening"},
                  {"zh": "几百步内收敛到较低损失",
                   "en": "Converges within a few hundred steps"},
                  {"zh": "表现：曲线像滑梯，末端走平",
                   "en": "Symptom: a slide-shaped curve that flattens"}]},
             {"title": {"zh": "太大", "en": "Too Large"},
              "title_en": "η = 1.0", "accent": "B91C1C", "bg": "FEF2F2",
              "body": [
                  {"zh": "一步跨过谷底，来回震荡",
                   "en": "Overshoots the valley and oscillates"},
                  {"zh": "严重时损失发散成 NaN",
                   "en": "In the worst case the loss diverges to NaN"},
                  {"zh": "表现：损失上下跳动甚至变大",
                   "en": "Symptom: the loss jumps around or grows"}]},
         ]},

        {"type": "code", "h": 11.6,
         "title": {"zh": "训练循环长什么样", "en": "What the Training Loop Looks Like"},
         "right": {"zh": "Module 1 · Week 3", "en": "Module 1 · Week 3"},
         "blocks": [
             {"title": {"zh": "手写梯度下降（原理版）", "en": "Gradient descent, from scratch"},
              "code": {"zh": [
                  "for epoch in range(n_epochs):",
                  "    y_hat = w * X + b          # 前向",
                  "    loss = mse(y, y_hat)       # 算损失",
                  "    gw, gb = grad(loss, w, b)  # 求梯度",
                  "    w -= lr * gw               # 更新参数",
                  "    b -= lr * gb",
                  "    if epoch % 50 == 0:",
                  "        print(epoch, loss)",
              ], "en": [
                  "for epoch in range(n_epochs):",
                  "    y_hat = w * X + b          # forward",
                  "    loss = mse(y, y_hat)       # the loss",
                  "    gw, gb = grad(loss, w, b)  # gradient",
                  "    w -= lr * gw               # update",
                  "    b -= lr * gb",
                  "    if epoch % 50 == 0:",
                  "        print(epoch, loss)",
              ]}},
             {"title": {"zh": "scikit-learn（工程版）", "en": "The scikit-learn way"},
              "code": [
                  "from sklearn.pipeline import Pipeline",
                  "from sklearn.preprocessing import StandardScaler",
                  "from sklearn.linear_model import LogisticRegression",
                  "",
                  "pipe = Pipeline([",
                  "    ('scale', StandardScaler()),",
                  "    ('clf', LogisticRegression(max_iter=1000)),",
                  "])",
                  "pipe.fit(X_train, y_train)   # learn params",
                  "pipe.score(X_test, y_test)   # evaluate",
              ]},
         ],
         "note": {"zh": "三个术语：batch 一次送进去的样本数；epoch 把训练集完整过一遍；step 一次参数更新。工程上你只会写右边这种。",
                  "en": "Three terms: batch = samples per update; epoch = one full pass over the training set; step = one parameter update. In practice you write the version on the right."}},

        # -------------------------------------------------- Part 04 (p18-22) -
        {"type": "section", "num": "04",
         "title": {"zh": "泛化与评估", "en": "Generalization & Evaluation"},
         "title_en": {"zh": "Generalization & Evaluation", "en": "Generalization & Evaluation"},
         "lead": {"zh": "训练集上再好看也不算数。真正的问题是：没见过的数据上还行不行？",
                  "en": "A great training score proves nothing. The real question is: does it hold on unseen data?"},
         "pillars": [
             {"title": {"zh": "三分数据", "en": "Three Splits"},
              "sub": {"zh": "训练 / 验证 / 测试", "en": "Train / validation / test"}},
             {"title": {"zh": "交叉验证", "en": "Cross-Validation"},
              "sub": {"zh": "数据少时的可靠估计", "en": "Reliable estimates on small data"}},
             {"title": {"zh": "诊断过拟合", "en": "Diagnose Overfitting"},
              "sub": {"zh": "看两条曲线的差距", "en": "Watch the gap between two curves"}},
         ]},

        {"type": "splitbar", "y": 5.4, "h": 3.3,
         "title": {"zh": "数据三分：各司其职", "en": "Three Splits, Three Jobs"},
         "right": {"zh": "Module 1 · Week 3", "en": "Module 1 · Week 3"},
         "segments": [
             {"title": {"zh": "训练集", "en": "Training Set"}, "value": 60, "pct": "60–80%",
              "color": "1E4FA8",
              "desc": {"zh": "用来拟合参数。模型只看这部分数据来学习。",
                       "en": "Used to fit parameters. The model only learns from this part."}},
             {"title": {"zh": "验证集", "en": "Validation Set"}, "value": 20, "pct": "10–20%",
              "color": "3D7BD9",
              "desc": {"zh": "用来挑超参数和做早停。会被反复使用，所以不能当最终成绩。",
                       "en": "Used to choose hyperparameters and early-stop. Reused often, so it is not the final grade."}},
             {"title": {"zh": "测试集", "en": "Test Set"}, "value": 20, "pct": "10–20%",
              "color": "0E3F8C",
              "desc": {"zh": "只在最后用一次，模拟「上线后遇到的新数据」。",
                       "en": "Touched once, at the very end — it simulates data seen after deployment."}},
         ],
         "note": {"zh": "铁律：测试集只能碰一次。用它反复调参，它就已经变成验证集了，你的分数也就不可信了。",
                  "en": "Iron rule: touch the test set once. Tune on it repeatedly and it silently becomes a validation set — your score stops meaning anything."}},

        {"type": "kfold", "k": 5, "y": 4.3, "w": 17.5,
         "title": {"zh": "k 折交叉验证：数据不够时的标准做法",
                   "en": "k-Fold Cross-Validation: The Standard When Data Is Scarce"},
         "right": {"zh": "Module 1 · Week 3", "en": "Module 1 · Week 3"},
         "notes": [
             {"zh": "把训练集切成 k 份（常用 k = 5 或 10）",
              "en": "Split the training set into k parts (k = 5 or 10 is typical)"},
             {"zh": "每一轮拿其中 1 份当验证、其余当训练，共训 k 次",
              "en": "Each round holds out one part, training on the rest — k trainings total"},
             {"zh": "取 k 次分数的平均值作为估计，更稳",
              "en": "Average the k scores — a far more stable estimate"},
             {"zh": "代价是 k 倍训练时间，所以深度模型少用",
              "en": "Costs k× training time, so deep models use it sparingly"},
             {"zh": "GridSearchCV 内部就是这么做的（cv=5）",
              "en": "GridSearchCV(cv=5) does exactly this under the hood"},
         ],
         "note": {"zh": "分类任务用 StratifiedKFold，保证每折里各类比例一致。",
                  "en": "For classification use StratifiedKFold so each fold keeps the class proportions."}},

        {"type": "table",
         "title": {"zh": "诊断表：看到这两个分数，你就知道该干什么",
                   "en": "Diagnostics: Two Scores Tell You Exactly What To Do"},
         "right": {"zh": "Module 1 · Week 3", "en": "Module 1 · Week 3"},
         "cols": [{"zh": "训练集表现", "en": "Train Score"},
                  {"zh": "验证集表现", "en": "Validation Score"},
                  {"zh": "结论", "en": "Diagnosis"},
                  {"zh": "对策", "en": "What To Do"}],
         "widths": [4.6, 4.6, 5.4, 14.8],
         "h": 8.4, "bold_first": True,
         "rows": [
             [{"zh": "低", "en": "Low"}, {"zh": "低", "en": "Low"},
              {"zh": "欠拟合", "en": "Underfitting"},
              {"zh": "加特征、换更强模型、减弱正则化、训练更久",
               "en": "Add features, use a stronger model, weaken regularisation, train longer"}],
             [{"zh": "高", "en": "High"}, {"zh": "明显更低", "en": "Clearly lower"},
              {"zh": "过拟合", "en": "Overfitting"},
              {"zh": "加正则化、早停、扩充数据、降模型容量、做特征选择",
               "en": "Regularise, early-stop, collect more data, reduce capacity, select features"}],
             [{"zh": "高", "en": "High"}, {"zh": "高且接近", "en": "High and close"},
              {"zh": "拟合良好", "en": "Healthy fit"},
              {"zh": "可以进入测试集做最终评估，一次",
               "en": "Move on to the test set for one final evaluation"}],
             [{"zh": "低", "en": "Low"}, {"zh": "高（反常）", "en": "High (suspicious)"},
              {"zh": "数据泄漏或划分错误", "en": "Leakage or a bad split"},
              {"zh": "检查是否在划分前做了填充/标准化、时间序列是否随机切分",
               "en": "Check for pre-split imputation/scaling, or a random split on time series"}],
         ],
         "note": {"zh": "第四行最危险：分数好看但流程错了。本周 Lab 的 Pipeline 正是为了避免它。",
                  "en": "Row four is the dangerous one — a pretty score from a broken protocol. This week's Pipeline exists to prevent it."}},

        {"type": "chart", "w": 19.0, "h": 12.0, "y_max": 14,
         "title": {"zh": "一张图看懂欠拟合、刚好、过拟合",
                   "en": "Underfit, Healthy, Overfit — In One Picture"},
         "right": {"zh": "Module 1 · Week 3", "en": "Module 1 · Week 3"},
         "categories": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
         "x_label": {"zh": "模型容量（复杂度）→", "en": "Model capacity (complexity) →"},
         "y_label": {"zh": "误差 Error", "en": "Error"},
         "series": [
             {"name": {"zh": "训练误差", "en": "Training error"}, "color": "1E4FA8",
              "values": [9.6, 7.4, 5.6, 4.1, 2.9, 2.0, 1.3, 0.8, 0.5, 0.3]},
             {"name": {"zh": "验证误差", "en": "Validation error"}, "color": "D97706",
              "values": [10.2, 7.9, 6.1, 4.8, 4.2, 4.6, 5.9, 7.6, 9.8, 12.4]},
         ],
         "notes": [
             {"zh": "左侧：两条都高 → 欠拟合（容量不足）",
              "en": "Left: both high → underfitting (not enough capacity)"},
             {"zh": "中间：验证误差最低 → 这就是要找的点",
              "en": "Middle: validation error bottoms out → the sweet spot"},
             {"zh": "右侧：训练继续降、验证反升 → 过拟合",
              "en": "Right: train keeps falling, validation rises → overfitting"},
             {"zh": "本周 Lab 用 C 控制容量，看验证曲线选点",
              "en": "In the lab, C controls capacity — pick the point by the validation curve"},
             {"zh": "这就是偏差-方差权衡：拟合能力与稳定性不可兼得",
              "en": "This is the bias-variance trade-off: flexibility versus stability"},
         ]},

        # -------------------------------------------------- Part 05 (p23-29) -
        {"type": "section", "num": "05",
         "title": {"zh": "Lab · sklearn 工作流", "en": "Lab · The sklearn Workflow"},
         "title_en": {"zh": "Hands-On: The sklearn Workflow", "en": "Hands-On: The sklearn Workflow"},
         "lead": {"zh": "75 分钟，把「fit → predict → evaluate」升级成工程可用版。",
                  "en": "75 minutes to upgrade \"fit → predict → evaluate\" into something production-ready."},
         "pillars": [
             {"title": {"zh": "四段任务", "en": "Four Missions"},
              "sub": {"zh": "A 基线 → D 回归", "en": "A baseline → D regression"}},
             {"title": {"zh": "防泄漏", "en": "No Leakage"},
              "sub": {"zh": "预处理必须进 Pipeline", "en": "Preprocessing belongs in the Pipeline"}},
             {"title": {"zh": "留下痕迹", "en": "Paper Trail"},
              "sub": {"zh": "每个 Checkpoint 都要写", "en": "Answer every checkpoint"}},
         ]},

        {"type": "cards", "cols": 3, "h": 6.6, "top": 3.6,
         "title": {"zh": "今天要用的数据与交付物", "en": "Today's Datasets and Deliverable"},
         "right": {"zh": "Lab · 75 min", "en": "Lab · 75 min"},
         "cards": [
             {"title": {"zh": "分类：load_digits", "en": "Classification: load_digits"},
              "title_en": "1797 × 64 → 10 classes",
              "body": [
                  {"zh": "8×8 手写数字灰度图，展平成 64 个特征",
                   "en": "8×8 handwritten digits flattened to 64 features"},
                  {"zh": "用 LogisticRegression 做多分类",
                   "en": "Multi-class with LogisticRegression"},
                  {"zh": "指标：accuracy", "en": "Metric: accuracy"}]},
             {"title": {"zh": "回归：load_diabetes", "en": "Regression: load_diabetes"},
              "title_en": "442 × 10 → continuous",
              "body": [
                  {"zh": "10 个生理指标预测病情进展",
                   "en": "10 physiological features predict disease progression"},
                  {"zh": "用 RandomForestRegressor",
                   "en": "Uses RandomForestRegressor"},
                  {"zh": "指标：MAE 与 R²（不是 accuracy）",
                   "en": "Metrics: MAE and R² (never accuracy)"}]},
             {"title": {"zh": "交付：lab-03.ipynb", "en": "Deliverable: lab-03.ipynb"},
              "title_en": "≥ 2 commits, pushed",
              "body": [
                  {"zh": "Restart & Run All 必须无报错",
                   "en": "Restart & Run All must pass cleanly"},
                  {"zh": "每个 Checkpoint 用自己的话写",
                   "en": "Every checkpoint answered in your own words"},
                  {"zh": "至少 2 次有意义的 commit 并推送",
                   "en": "At least 2 meaningful commits, pushed"}]},
         ]},

        {"type": "code", "h": 12.0,
         "title": {"zh": "Part A–B：先跑基线，再装进 Pipeline",
                   "en": "Parts A–B: Baseline First, Then the Pipeline"},
         "right": {"zh": "Lab · Part A–B", "en": "Lab · Part A–B"},
         "blocks": [
             {"title": {"zh": "A · 无 Pipeline 的基线（10 min）", "en": "A · Baseline, no pipeline (10 min)"},
              "code": [
                  "from sklearn.datasets import load_digits",
                  "from sklearn.model_selection import train_test_split",
                  "from sklearn.linear_model import LogisticRegression",
                  "",
                  "X, y = load_digits(return_X_y=True)",
                  "X_tr, X_te, y_tr, y_te = train_test_split(",
                  "    X, y, test_size=0.2, random_state=42)",
                  "",
                  "LogisticRegression(max_iter=1000).fit(X_tr, y_tr) \\",
                  "    .score(X_te, y_te)",
                  "",
                  "# Checkpoint A: record the accuracy.",
                  "# If a ConvergenceWarning appears, what is it telling you?",
              ]},
             {"title": {"zh": "B · 装进 Pipeline（15 min）", "en": "B · The same model, in a Pipeline (15 min)"},
              "code": [
                  "from sklearn.pipeline import Pipeline",
                  "from sklearn.preprocessing import StandardScaler",
                  "",
                  "pipe = Pipeline([",
                  "    ('scale', StandardScaler()),",
                  "    ('clf', LogisticRegression(max_iter=1000)),",
                  "])",
                  "pipe.fit(X_tr, y_tr)",
                  "pipe.score(X_te, y_te)",
                  "",
                  "# Checkpoint B: did scaling change accuracy?",
                  "# Why does it matter here but not for a tree model?",
                  "# Pitfall: fitting the scaler on all data leaks.",
              ]},
         ],
         "note": {"zh": "Pipeline 的价值不在省代码，而在于「缩放器只在每个训练折内拟合」——交叉验证才可信。",
                  "en": "A Pipeline is not about saving keystrokes — it guarantees the scaler fits only on each training fold, so cross-validation stays honest."}},

        {"type": "code", "h": 10.6,
         "title": {"zh": "Part C：用 GridSearchCV 系统调参",
                   "en": "Part C: Systematic Tuning with GridSearchCV"},
         "right": {"zh": "Lab · Part C", "en": "Lab · Part C"},
         "blocks": [
             {"title": {"zh": "网格搜索（20 min）", "en": "The sweep (20 min)"},
              "code": [
                  "from sklearn.model_selection import GridSearchCV",
                  "",
                  "grid = {'clf__C': [0.01, 0.1, 1, 10]}",
                  "search = GridSearchCV(pipe, grid, cv=5, n_jobs=-1)",
                  "search.fit(X_tr, y_tr)",
                  "",
                  "print(search.best_params_)",
                  "print(search.best_score_)      # CV score",
                  "print(search.score(X_te, y_te)) # test score",
                  "",
                  "# Checkpoint C: why is the CV score usually lower",
                  "# than the test score? Smaller C = stronger",
                  "# regularisation, i.e. less capacity.",
              ]},
             {"title": {"zh": "读结果的三个要点", "en": "Reading the result"},
              "code": [
                  "# 1. best_params_ is the CHOSEN hyperparameter;",
                  "#    coef_ / intercept_ are the LEARNED parameters",
                  "",
                  "# 2. cv_results_ holds every candidate's score",
                  "import pandas as pd",
                  "pd.DataFrame(search.cv_results_)[",
                  "    ['param_clf__C', 'mean_test_score',",
                  "     'std_test_score']]",
                  "",
                  "# 3. Watch the std: when means are close,",
                  "#    prefer the more stable option.",
                  "#    A gap < 1 std is not worth agonising over.",
              ]},
         ],
         "note": {"zh": "注意命名规则：clf__C 表示「Pipeline 里叫 clf 那一步的参数 C」。两个下划线。",
                  "en": "Mind the naming rule: clf__C means parameter C of the step named clf inside the Pipeline — two underscores."}},

        {"type": "table",
         "title": {"zh": "Part D：换任务不换骨架，只换指标",
                   "en": "Part D: Same Skeleton, Different Metrics"},
         "right": {"zh": "Lab · Part D", "en": "Lab · Part D"},
         "cols": [{"zh": "任务", "en": "Task"},
                  {"zh": "该看的指标", "en": "Metric To Use"},
                  {"zh": "含义", "en": "What It Means"},
                  {"zh": "常见误解", "en": "Common Mistake"}],
         "widths": [5.0, 7.6, 9.0, 7.8],
         "h": 7.2, "bold_first": True,
         "rows": [
             [{"zh": "分类 digits", "en": "Classification (digits)"},
              "accuracy / F1",
              {"zh": "预测对的占比（F1 兼顾精确率与召回率）",
               "en": "Share of correct predictions (F1 balances precision and recall)"},
              {"zh": "类别不均衡时 accuracy 会骗人",
               "en": "Accuracy lies when classes are imbalanced"}],
             [{"zh": "回归 diabetes", "en": "Regression (diabetes)"},
              "MAE / R²",
              {"zh": "MAE：平均差多少（与目标同量纲）；R²：比猜均值好多少",
               "en": "MAE: average error in target units; R²: how much better than guessing the mean"},
              {"zh": "回归里 score() 返回 R²，不是准确率",
               "en": "For regressors, score() returns R² — not accuracy"}],
             [{"zh": "两者通用", "en": "Both"},
              {"zh": "fit → predict → evaluate", "en": "fit → predict → evaluate"},
              {"zh": "骨架完全一样，只是换模型与换指标",
               "en": "Identical skeleton; only the model and the metric change"},
              {"zh": "不要把测试集拿来反复调",
               "en": "Never tune repeatedly on the test set"}],
         ],
         "note": {"zh": "Checkpoint D：用一句人话向外行解释 R² = 0.45 是什么意思（提示：比直接猜平均值好多少）。",
                  "en": "Checkpoint D: explain in plain language what R² = 0.45 means to a stakeholder."}},

        {"type": "checklist",
         "title": {"zh": "常见坑与排查清单", "en": "Pitfalls and a Debugging Checklist"},
         "right": {"zh": "Lab · 75 min", "en": "Lab · 75 min"},
         "items": [
             {"badge": {"zh": "坑 1", "en": "Pitfall 1"},
              "title": {"zh": "先划分，再拟合任何预处理器", "en": "Split first, fit preprocessing after"},
              "desc": {"zh": "在全体数据上 fit StandardScaler 或填充器，就等于把测试集信息泄漏进训练；放进 Pipeline 就自动避免了。",
                       "en": "Fitting a scaler or imputer on all data leaks test information into training; a Pipeline prevents it by construction."}},
             {"badge": {"zh": "坑 2", "en": "Pitfall 2"},
              "title": {"zh": "参数 ≠ 超参数", "en": "Parameters are not hyperparameters"},
              "desc": {"zh": "coef_ 是学出来的，C、max_depth、cv 是你选的。Lab 里被搜索的是后者。",
                       "en": "coef_ is learned; C, max_depth and cv are chosen. GridSearchCV searches the latter."}},
             {"badge": {"zh": "坑 3", "en": "Pitfall 3"},
              "title": {"zh": "CV 分与测试分不一致是常态", "en": "CV and test scores naturally differ"},
              "desc": {"zh": "CV 每折只用 4/5 数据训练，通常略低于测试分；差太多（>5 个点）才需要怀疑流程。",
                       "en": "Each fold trains on 4/5 of the data, so CV is usually a little lower; only a large gap (>5 pts) signals a broken protocol."}},
             {"badge": {"zh": "坑 4", "en": "Pitfall 4"},
              "title": {"zh": "忘了固定随机种子", "en": "Forgetting the random seed"},
              "desc": {"zh": "train_test_split 与模型都设 random_state，否则结果无法复现，也无法与同学对答案。",
                       "en": "Set random_state on both the split and the model, or results are unreproducible and impossible to compare."}},
             {"badge": {"zh": "坑 5", "en": "Pitfall 5"},
              "title": {"zh": "ConvergenceWarning 不是错误，但要看", "en": "ConvergenceWarning is not an error — but read it"},
              "desc": {"zh": "它说迭代次数不够：提高 max_iter，或先把特征标准化。这正是 Part B 存在的理由。",
                       "en": "It says the solver ran out of iterations: raise max_iter, or scale the features first — exactly why Part B exists."}},
         ]},

        {"type": "cards", "cols": 2, "h": 6.6, "top": 3.6,
         "title": {"zh": "Part F：把本周技能推到大作业里", "en": "Part F: Push This Week's Skill Into Your Capstone"},
         "right": {"zh": "Capstone · M3", "en": "Capstone · M3"},
         "cards": [
             {"title": {"zh": "M3 · 仓库与数据管线", "en": "M3 · Repository & Data Pipeline"},
              "title_en": "Milestone 3", "accent": "0E3F8C",
              "body": [
                  {"zh": "建 src/data/（加载、清洗、划分）与 src/train.py，能端到端跑通并打印结果",
                   "en": "Create src/data/ (load, clean, split) and an src/train.py that runs end-to-end and prints something"},
                  {"zh": "划分策略要说明理由：分层 / 分组 / 按时间；时间序列不能随机切",
                   "en": "Justify your split: stratified / grouped / time-based — never random on time series"},
                  {"zh": "清洗写进管线，绝不手工改 CSV；requirements.txt 固定版本",
                   "en": "Cleaning lives in the pipeline, never in hand-edited CSVs; pin requirements.txt"},
                  {"zh": "不用绝对路径", "en": "No absolute paths"}]},
             {"title": {"zh": "交付与规则", "en": "Deliverables & Rules"},
              "title_en": "Before you leave", "accent": "B91C1C", "bg": "FEF2F2",
              "body": [
                  {"zh": "下课前 push：python src/train.py 在队友机器上不改代码就能跑",
                   "en": "Push before the lab ends: python src/train.py must run on a teammate's machine unedited"},
                  {"zh": "Part F 不计入本次 Lab 分，但计入 Capstone（35%）",
                   "en": "Part F is graded under the Capstone (35%), not under this lab"},
                  {"zh": "迟交：每次 −2 团队分，上限 −20",
                   "en": "Late: −2 team points each time, up to −20"},
                  {"zh": "Lab 本身迟交：每天 −10%，最多 3 天",
                   "en": "Lab late policy: −10% per day, max 3 days"}]},
         ]},

        # -------------------------------------------------- wrap-up (p30-32) -
        {"type": "quiz", "cols": 2, "h": 4.15, "top": 3.1,
         "title": {"zh": "小测 · 举手作答", "en": "Quick Quiz (Show of Hands)"},
         "right": {"zh": "Module 1 · Week 3", "en": "Module 1 · Week 3"},
         "questions": [
             {"tag": {"zh": "Q1 单选", "en": "Q1 Single"},
              "q": {"zh": "标准化缩放器应该在哪里 fit？", "en": "Where should a scaler be fitted?"},
              "options": [
                  {"zh": "A. 在全体数据上，划分之前", "en": "A. On all data, before splitting"},
                  {"zh": "B. 只在该折的训练部分上", "en": "B. Only on the training portion of each fold"},
                  {"zh": "C. 只在测试集上", "en": "C. Only on the test set"}]},
             {"tag": {"zh": "Q2 单选", "en": "Q2 Single"},
              "q": {"zh": "下面哪个是超参数？", "en": "Which of these is a hyperparameter?"},
              "options": [
                  {"zh": "A. 线性回归的 w", "en": "A. w of a linear regression"},
                  {"zh": "B. 决策树的划分阈值", "en": "B. A tree's split threshold"},
                  {"zh": "C. 正则化强度 C", "en": "C. Regularisation strength C"}]},
             {"tag": {"zh": "Q3 单选", "en": "Q3 Single"},
              "q": {"zh": "训练集 98%、验证集 72%，这是？", "en": "Train 98%, validation 72% — what is this?"},
              "options": [
                  {"zh": "A. 欠拟合", "en": "A. Underfitting"},
                  {"zh": "B. 过拟合", "en": "B. Overfitting"},
                  {"zh": "C. 数据泄漏", "en": "C. Data leakage"}]},
             {"tag": {"zh": "Q4 判断", "en": "Q4 True/False"},
              "q": {"zh": "「回归模型上调用 score() 得到的是准确率。」",
                   "en": "\"Calling score() on a regressor gives accuracy.\""},
              "options": [{"zh": "□ 对   □ 错（它返回 R²）", "en": "□ True   □ False (it returns R²)"}]},
             {"tag": {"zh": "Q5 单选", "en": "Q5 Single"},
              "q": {"zh": "学习率设置过大会发生什么？", "en": "What happens if the learning rate is too large?"},
              "options": [
                  {"zh": "A. 训练变慢但一定收敛", "en": "A. Slower but it still converges"},
                  {"zh": "B. 损失震荡甚至发散", "en": "B. The loss oscillates or diverges"},
                  {"zh": "C. 模型容量变小", "en": "C. Model capacity shrinks"}]},
             {"tag": {"zh": "Q6 简答", "en": "Q6 Short"},
              "q": {"zh": "用自己的话说：Pipeline 到底防住了什么？",
                   "en": "In your own words: what exactly does a Pipeline prevent?"},
              "options": [{"zh": "（口头回答，30 秒内）", "en": "(Answer out loud, 30 seconds)"}]},
         ]},

        {"type": "summary",
         "title": {"zh": "小结", "en": "Summary"},
         "right": {"zh": "Module 1 · Week 3", "en": "Module 1 · Week 3"},
         "points": [
             {"zh": "机器学习 = 从样例中反推规则；监督、无监督、强化是三类范式",
              "en": "ML infers rules from examples; supervised, unsupervised and RL are the three paradigms"},
             {"zh": "参数是学出来的，超参数是选出来的——GridSearchCV 负责后者",
              "en": "Parameters are learned, hyperparameters are chosen — GridSearchCV handles the latter"},
             {"zh": "损失函数定义「什么算错」，梯度下降负责「往哪改」，学习率控制步长",
              "en": "The loss defines what counts as wrong; gradient descent decides where to move; the learning rate sets the step"},
             {"zh": "训练/验证/测试三分，测试集只碰一次；数据少时用 k 折交叉验证",
              "en": "Train/validation/test, and touch the test set once; use k-fold CV when data is scarce"},
             {"zh": "Pipeline 的价值是防泄漏：预处理只拟合训练折",
              "en": "A Pipeline's real value is preventing leakage: preprocessing fits only on training folds"},
         ],
         "todo_title": {"zh": "课后待办", "en": "After Class"},
         "todos": [
             {"title": {"zh": "完成 Lab 03", "en": "Finish Lab 03"},
              "desc": {"zh": "lab-03.ipynb + 各 Checkpoint 说明 · 周一 23:59 截止",
                       "en": "lab-03.ipynb with checkpoint write-ups · due Monday 23:59"}},
             {"title": {"zh": "推送到 Git", "en": "Push to Git"},
              "desc": {"zh": "至少 2 次 commit：feat: complete lab 03",
                       "en": "At least 2 commits, e.g. feat: complete lab 03"}},
             {"title": {"zh": "预习第 4 周", "en": "Preview Week 4"},
              "desc": {"zh": "教材第 4 章：指标、阈值、过拟合与 Ridge",
                       "en": "Chapter 4: metrics, thresholds, overfitting and Ridge"}},
         ]},

        {"type": "closing",
         "quote": {"zh": "「模型的可信度，取决于评估它的流程，而不是它在训练集上的分数。」",
                   "en": "\"A model is only as trustworthy as the protocol that evaluates it.\""},
         "quote_sub": {"zh": "—— 这也是为什么本周要先讲 Pipeline，再讲调参",
                       "en": "— which is why Pipeline comes before tuning this week"},
         "thanks": {"zh": "谢谢大家", "en": "Thank you"},
         "next_label": {"zh": "下周预告", "en": "Next week"},
         "next": {"zh": "Week 4 · 机器学习应用与模型评估：指标与阈值选择、过拟合诊断、Ridge 正则化",
                  "en": "Week 4 · ML Applications & Model Evaluation: metrics and thresholds, diagnosing overfitting, Ridge regularisation"},
         "sign": {"zh": "AI Application Development · Week 3 Lecture · 32 / 32",
                  "en": "AI Application Development · Week 3 Lecture · 32 / 32"}},
    ],
}
