"""Week 4 — Neural Networks and Modelling with nn.Module  ·  slide spec (bilingual).

Aligned with the official course documents (52015CC3BV):
CU(4) · Module 1 (Week 1-4, closing week) · Lab 3 (MLP classification + ablations)
· Module 1 milestone: problem definition sheet + data pipeline + model.
"""

SPEC = {
    "week": 4,
    "slides": [
        # ---------------------------------------------------------- cover ----
        {"type": "cover",
         "kicker": {"zh": "52015CC3BV · 本科 · 来华项目", "en": "52015CC3BV · UNDERGRADUATE · INTERNATIONAL"},
         "title": {"zh": "神经网络与 nn.Module 建模", "en": "Neural Networks and Modelling with nn.Module"},
         "title_sub": {"zh": "Neural Networks and Modelling with nn.Module",
                       "en": "From a perceptron to a well-built MLP: non-linearity, nn.Module, and controlled comparisons"},
         "subtitle": {"zh": "Week 4 · CU(4) · 感知机与多层网络 · 激活函数 · nn.Module 与层 · 参数初始化 · 宽度与深度对照 · 模块一收官",
                      "en": "Week 4 · CU(4) · Perceptron & MLP · activations · nn.Module & layers · initialisation · width/depth ablations · Module 1 wrap-up"},
         "chips": [
             ({"zh": "模块一 · W1–4", "en": "Module 1 · W1-4"}, 1.0),
             ({"zh": "180 min · 授课 + 实验 + 小测", "en": "180 min · Lecture + Lab + Quiz"}, 1.5),
             ({"zh": "PyTorch · nn.Module · ReLU · Dropout", "en": "PyTorch · nn.Module · ReLU · Dropout"}, 1.7),
             ({"zh": "留学生班 · 英文授课", "en": "International Students"}, 1.0),
         ]},

        # ------------------------------------------------------- contents ----
        {"type": "contents",
         "right": {"zh": "模块一 · Week 4", "en": "Module 1 · Week 4"},
         "count": {"zh": "5 部分", "en": "5 Parts"},
         "count_label": {"zh": "本周结构", "en": "Part"},
         "tagline": {"zh": "先弄清「非线性从哪里来」，\n再学会把网络写规范，\n最后用对照实验决定它该有多大、多深。\nAsk why it bends, then how to build it, then how big it must be.",
                     "en": "First: where does non-linearity come from? Then: how do we build a network properly? Finally: how big and how deep should it be - decided by controlled experiments."},
         "timing": {"zh": "理论约 90 min · Lab 80 min · 小测与小结 10 min",
                    "en": "Theory ~90 min · Lab 80 min · Quiz & Summary 10 min"},
         "parts": [
             {"title": {"zh": "从感知机到多层感知机", "en": "From a Perceptron to an MLP"},
              "title_en": "Perceptron to MLP",
              "desc": {"zh": "一个神经元能做什么 · 隐藏层做什么 · 前向传播",
                       "en": "What one neuron does · the job of a hidden layer · the forward pass"}},
             {"title": {"zh": "激活函数与非线性", "en": "Activations and Non-linearity"},
              "title_en": "Activations",
              "desc": {"zh": "sigmoid / tanh / ReLU / LeakyReLU · 去掉激活会怎样",
                       "en": "sigmoid / tanh / ReLU / LeakyReLU · what happens without them"}},
             {"title": {"zh": "nn.Module 规范建模", "en": "Modelling with nn.Module"},
              "title_en": "nn.Module",
              "desc": {"zh": "__init__ 建层 · forward 写数据流 · 常用层与初始化",
                       "en": "Layers in __init__ · data flow in forward · layers and init"}},
             {"title": {"zh": "宽度、深度与模型容量", "en": "Width, Depth and Capacity"},
              "title_en": "Width & Depth",
              "desc": {"zh": "消融对照表 · 参数量与准确率 · 适用才是最好",
                       "en": "Ablation table · parameters vs accuracy · fitness beats size"}},
             {"title": {"zh": "Lab · 实验 3 与模块一里程碑", "en": "Lab · Experiment 3 and the Milestone"},
              "title_en": "Hands-On Lab",
              "desc": {"zh": "搭 MLP · 有/无激活对照 · 宽度深度对照 · 里程碑交付",
                       "en": "Build an MLP · with/without activation · width & depth · milestone delivery"}},
         ]},

        # ------------------------------------------------- Part 01 (p3-7) ---
        {"type": "section", "num": "01",
         "title": {"zh": "从感知机到多层感知机", "en": "From a Perceptron to an MLP"},
         "title_en": {"zh": "Perceptron to MLP", "en": "Perceptron to MLP"},
         "lead": {"zh": "一个神经元只能画一条直线；把神经元叠成层、层间加上非线性，网络才第一次具备了「弯曲」的能力。\n这一部分之后，你要能亲手画出数据在一个 MLP 里是怎么一步步走过去的。",
                  "en": "One neuron can only draw a straight line. Stack neurons into layers and add non-linearity between them, and the network finally gains the ability to bend.\nAfter this part you can trace by hand how data moves through an MLP."},
         "pillars": [
             {"title": {"zh": "一个神经元", "en": "One Neuron"},
              "sub": {"zh": "线性 + 阈值 = 一条直线", "en": "Linear + threshold = one line"}},
             {"title": {"zh": "隐藏层", "en": "Hidden Layer"},
              "sub": {"zh": "先做特征变换再判断", "en": "Transform features, then decide"}},
             {"title": {"zh": "前向传播", "en": "Forward Pass"},
              "sub": {"zh": "矩阵乘法 + 非线性", "en": "Matrix multiply + activation"}},
         ]},

        {"type": "cards", "cols": 3, "h": 6.2, "top": 3.6,
         "title": {"zh": "三代结构：从一根线到一张网", "en": "Three Generations: From One Line to a Network"},
         "right": {"zh": "模块一 · Week 4", "en": "Module 1 · Week 4"},
         "cards": [
             {"title": {"zh": "① 感知机（1958）", "en": "1 · The Perceptron"},
              "title_en": "one neuron, one line", "accent": "6B7280", "bg": "F5F7FA",
              "body": [{"zh": "一个神经元 = 线性模型 + 阈值判断", "en": "One neuron = a linear model plus a threshold"},
                       {"zh": "能画一条直线：AND / OR 可解", "en": "It draws one straight line: AND / OR are solvable"},
                       {"zh": "线性不可分的问题（如 XOR）解不了", "en": "Linearly inseparable problems (e.g. XOR) are not"}]},
             {"title": {"zh": "② 多层感知机", "en": "2 · The MLP"},
              "title_en": "hidden layers transform", "accent": "1E4FA8", "bg": "F0F5FC",
              "body": [{"zh": "隐藏层先做特征变换，输出层再做判断", "en": "Hidden layers transform features; the output layer decides"},
                       {"zh": "同一批数据，在新空间里变得可分", "en": "The same data becomes separable in a new space"},
                       {"zh": "层与层全连接：nn.Linear 堆叠", "en": "Fully connected layers: stacked nn.Linear"}]},
             {"title": {"zh": "③ 现代深度网络", "en": "3 · Modern Deep Nets"},
              "title_en": "depth, not extreme width", "accent": "0E3F8C", "bg": "F0F5FC",
              "body": [{"zh": "几十到上百层，靠「深」而不是「极宽」", "en": "Dozens to hundreds of layers: depth, not extreme width"},
                       {"zh": "本质仍是 MLP 的堆叠，加上结构与技巧", "en": "Still stacked MLPs, plus architecture and tricks"},
                       {"zh": "本周先把最小的 MLP 写规范", "en": "This week: get the smallest MLP written correctly"}]},
         ]},

        {"type": "compare",
         "title": {"zh": "单层感知机 vs 多层感知机", "en": "Single-Layer Perceptron vs MLP"},
         "right": {"zh": "模块一 · Week 4", "en": "Module 1 · Week 4"},
         "columns": [
             {"title": {"zh": "单层（线性模型）", "en": "Single Layer (Linear)"}, "accent": "B91C1C",
              "bg": "FEF2F2",
              "items": [
                  {"zh": "只有一个线性层：y = σ(w·x + b)", "en": "One linear layer only: y = σ(w·x + b)"},
                  {"zh": "决策边界是一条直线（高维是超平面）", "en": "The decision boundary is one line (a hyperplane in high dimensions)"},
                  {"zh": "只能处理线性可分的数据", "en": "Handles linearly separable data only"},
                  {"zh": "参数最少、训练最快、最不容易过拟合", "en": "Fewest parameters, fastest to train, least prone to overfitting"},
                  {"zh": "案例：AND / OR 可解；make_circles 只能到 0.47（随机水平）", "en": "Example: AND / OR solvable; make_circles stalls at 0.47 (chance level)"}]},
             {"title": {"zh": "多层（含非线性）", "en": "Multi-Layer (Non-linear)"}, "accent": "059669",
              "bg": "ECFDF5",
              "items": [
                  {"zh": "隐藏层 + 激活：h = ReLU(W1 x + b1)", "en": "Hidden layer + activation: h = ReLU(W1 x + b1)"},
                  {"zh": "决策边界可以弯曲（分段线性拼接）", "en": "The decision boundary can bend (piecewise-linear)"},
                  {"zh": "非线性激活让表达力发生质变", "en": "A non-linear activation changes expressive power qualitatively"},
                  {"zh": "参数更多，需要更多数据与正则化", "en": "More parameters: needs more data and regularisation"},
                  {"zh": "案例：make_circles 从 0.47 提到 0.98", "en": "Example: make_circles rises from 0.47 to 0.98"}]},
         ],
         "note": {"zh": "关键不是「层多」，而是「层与层之间有非线性」。少了激活函数，叠多少层都还是右边这一栏左边的那个线性模型。",
                  "en": "The point is not \"more layers\" but \"non-linearity between layers\". Without an activation, any number of layers is still the linear model in the other column."}},

        {"type": "flow", "y": 6.4, "h": 4.7,
         "title": {"zh": "前向传播：数据在网络里怎么走", "en": "The Forward Pass: How Data Moves Through the Net"},
         "right": {"zh": "模块一 · Week 4", "en": "Module 1 · Week 4"},
         "steps": [
             {"title": {"zh": "输入", "en": "Input"},
              "title_en": "x : (N, 2)",
              "desc": {"zh": "一批 N 个样本，\n每个 2 维特征", "en": "A batch of N samples,\neach with 2 features"}},
             {"title": {"zh": "线性层 1", "en": "Linear 1"},
              "title_en": "z1 = x @ W1.T + b1",
              "desc": {"zh": "2 维 → 8 维，\n把特征升到新空间", "en": "2-d -> 8-d: lift features\ninto a new space"}},
             {"title": {"zh": "激活", "en": "Activate"},
              "title_en": "h = ReLU(z1)",
              "desc": {"zh": "逐元素非线性，\n形状不变", "en": "Element-wise non-linearity;\nshape unchanged"}},
             {"title": {"zh": "线性层 2", "en": "Linear 2"},
              "title_en": "z2 = h @ W2.T + b2",
              "desc": {"zh": "8 维 → 2 类 logits，\n这就是输出", "en": "8-d -> 2 logits:\nthat is the output"}},
             {"title": {"zh": "损失", "en": "Loss"},
              "title_en": "CrossEntropyLoss(z2, y)",
              "desc": {"zh": "softmax 已含在损失里，\n不要再加一次", "en": "Softmax is inside the loss -\ndo not add it again"}},
         ],
         "note": {"zh": "前向传播没有魔法：矩阵乘法 + 逐元素非线性，重复两三次。把第 3 步（激活）去掉，整张网络会塌缩成一次大的矩阵乘法——这就是本周对照实验的核心。",
                  "en": "The forward pass is no magic: matrix multiplies plus element-wise activation, repeated. Remove step 3 and the whole network collapses into one big matrix multiply - the core of this week's experiment."}},

        {"type": "table",
         "title": {"zh": "读出一个网络的「尺寸」：形状与参数量", "en": "Reading a Network's Size: Shapes and Parameters"},
         "right": {"zh": "模块一 · Week 4", "en": "Module 1 · Week 4"},
         "subtitle": {"zh": "示例：输入 2 维 → 隐藏 4 → 输出 2 类，一批 4 个样本",
                      "en": "Example: 2-d input -> 4 hidden units -> 2 classes, batch of 4"},
         "cols": [{"zh": "部件", "en": "Component"},
                  {"zh": "权重形状", "en": "Weight shape"},
                  {"zh": "参数量", "en": "Params"},
                  {"zh": "说明", "en": "Note"}],
         "widths": [7.0, 7.8, 4.6, 10.02],
         "h": 8.4, "bold_first": True,
         "rows": [
             [{"zh": "输入 x", "en": "Input x"},
              "(4, 2)", "0",
              {"zh": "4 个样本，每个 2 维特征", "en": "4 samples, 2 features each"}],
             [{"zh": "nn.Linear(2, 4)", "en": "nn.Linear(2, 4)"},
              "W (4, 2), b (4,)", "12",
              {"zh": "2 维 → 4 维：参数 = 2x4 + 4", "en": "2-d -> 4-d: params = 2x4 + 4"}],
             [{"zh": "nn.ReLU()", "en": "nn.ReLU()"},
              "(4, 4)", "0",
              {"zh": "逐元素，形状不变、零参数", "en": "Element-wise: same shape, zero parameters"}],
             [{"zh": "nn.Linear(4, 2)", "en": "nn.Linear(4, 2)"},
              "W (2, 4), b (2,)", "10",
              {"zh": "4 维 → 2 类 logits：4x2 + 2", "en": "4-d -> 2 logits: 4x2 + 2"}],
             [{"zh": "合计", "en": "Total"},
              "-", "22",
              {"zh": "前向 = 两次矩阵乘法 + 一次非线性", "en": "Forward = two matrix multiplies + one activation"}],
         ],
         "note": {"zh": "记住这个读法：nn.Linear(in, out) 的参数量永远是 in x out + out。W4 之后你评估任何一个网络，第一件事就是算它有多少参数。",
                  "en": "Remember the reading rule: nn.Linear(in, out) always costs in x out + out parameters. From Week 4 on, the first thing you do with any network is count its parameters."}},

        # ------------------------------------------------- Part 02 (p8-12) --
        {"type": "section", "num": "02",
         "title": {"zh": "激活函数与非线性", "en": "Activations and Non-linearity"},
         "title_en": {"zh": "Activation Functions", "en": "Activation Functions"},
         "lead": {"zh": "激活函数是整个网络「非线性能力」的唯一来源。去掉它，无论叠多少层，网络都退化为一个线性模型。\n这一部分我们要现场做一次「去掉激活函数」的对照实验，让你自己发现这个结论。",
                  "en": "Activations are the only source of non-linearity in a network. Remove them and, no matter how many layers you stack, the network degenerates into a linear model.\nIn this part we run a live \"remove the activation\" experiment so you discover that conclusion yourself."},
         "pillars": [
             {"title": {"zh": "为什么需要", "en": "Why Needed"},
              "sub": {"zh": "没有它就退化为线性", "en": "Without it, linear again"}},
             {"title": {"zh": "四大家族", "en": "The Family"},
              "sub": {"zh": "sigmoid / tanh / ReLU / LeakyReLU", "en": "sigmoid / tanh / ReLU / LeakyReLU"}},
             {"title": {"zh": "对照实验", "en": "Controlled Test"},
              "sub": {"zh": "只改一个变量", "en": "Change one variable only"}},
         ]},

        {"type": "cards", "cols": 2, "h": 5.4, "top": 3.6,
         "title": {"zh": "激活函数家族：四个成员，四种取舍", "en": "The Activation Family: Four Members, Four Trade-offs"},
         "right": {"zh": "模块一 · Week 4", "en": "Module 1 · Week 4"},
         "cards": [
             {"title": {"zh": "Sigmoid", "en": "Sigmoid"},
              "title_en": {"zh": "squash to (0, 1)", "en": "squash to (0, 1)"},
              "accent": "6B7280", "bg": "F5F7FA",
              "body": [{"zh": "σ(z) = 1 / (1 + e^(-z))", "en": "σ(z) = 1 / (1 + e^(-z))"},
                       {"zh": "输出 (0,1)，可以当概率来读", "en": "Range (0,1): readable as a probability"},
                       {"zh": "导数最大只有 0.25，深层里梯度迅速衰减", "en": "Derivative peaks at 0.25; gradients decay quickly when deep"},
                       {"zh": "现在只在输出层做二分类概率时用", "en": "Now used mainly at the output for a binary probability"}]},
             {"title": {"zh": "Tanh", "en": "Tanh"},
              "title_en": {"zh": "zero-centred", "en": "zero-centred"},
              "accent": "1E4FA8", "bg": "F0F5FC",
              "body": [{"zh": "tanh(z) = (e^z - e^(-z)) / (e^z + e^(-z))", "en": "tanh(z) = (e^z - e^(-z)) / (e^z + e^(-z))"},
                       {"zh": "输出 (-1,1)，以 0 为中心，比 sigmoid 好训", "en": "Range (-1,1), zero-centred, trains better than sigmoid"},
                       {"zh": "仍然会饱和，梯度消失并没有被解决", "en": "Still saturates: vanishing gradients are not solved"},
                       {"zh": "常见于早期 RNN 与部分 Transformer 变体", "en": "Seen in early RNNs and some Transformer variants"}]},
             {"title": {"zh": "ReLU", "en": "ReLU"},
              "title_en": {"zh": "the modern default", "en": "the modern default"},
              "accent": "059669", "bg": "ECFDF5",
              "body": [{"zh": "ReLU(z) = max(0, z)", "en": "ReLU(z) = max(0, z)"},
                       {"zh": "正区间梯度恒为 1，计算最便宜", "en": "Gradient is 1 on the positive side and it is the cheapest to compute"},
                       {"zh": "负区间输出 0：可能出现「神经元死亡」", "en": "Zero on the negative side: some units can die out"},
                       {"zh": "隐藏层默认选项——除非有理由换", "en": "The default hidden-layer choice unless you have a reason"}]},
             {"title": {"zh": "LeakyReLU", "en": "LeakyReLU"},
              "title_en": {"zh": "fix the dead unit", "en": "fix the dead unit"},
              "accent": "D97706", "bg": "FFFBEB",
              "body": [{"zh": "LeakyReLU(z) = max(0.01z, z)", "en": "LeakyReLU(z) = max(0.01z, z)"},
                       {"zh": "负区间留一点斜率，神经元不会彻底死掉", "en": "A small negative slope keeps units from dying completely"},
                       {"zh": "代价是多一个超参数，收益并不总是明显", "en": "The cost is one more hyper-parameter, with not always a clear gain"},
                       {"zh": "当 ReLU 明显不收敛时的第一备选", "en": "The first fallback when ReLU clearly fails to converge"}]},
         ]},

        {"type": "table",
         "title": {"zh": "四种激活对比：范围、梯度、用法", "en": "Four Activations Compared: Range, Gradient, Usage"},
         "right": {"zh": "模块一 · Week 4", "en": "Module 1 · Week 4"},
         "cols": [{"zh": "函数", "en": "Function"},
                  {"zh": "输出范围", "en": "Range"},
                  {"zh": "梯度特性", "en": "Gradient"},
                  {"zh": "推荐用法", "en": "Where to Use It"}],
         "widths": [5.4, 5.6, 9.4, 9.02],
         "h": 8.6, "bold_first": True,
         "rows": [
             [{"zh": "Sigmoid", "en": "Sigmoid"},
              "(0, 1)",
              {"zh": "最大 0.25，深层衰减极快", "en": "Max 0.25, decays extremely fast when deep"},
              {"zh": "输出层二分类概率；隐藏层避免使用", "en": "Output layer for a binary probability; avoid in hidden layers"}],
             [{"zh": "Tanh", "en": "Tanh"},
              "(-1, 1)",
              {"zh": "最大 1.0，仍然会饱和", "en": "Max 1.0, still saturates"},
              {"zh": "需要零中心输出时用；深层仍不推荐", "en": "When you need a zero-centred output; still not for deep nets"}],
             [{"zh": "ReLU", "en": "ReLU"},
              "[0, +inf)",
              {"zh": "正区间恒为 1，不衰减", "en": "Exactly 1 on the positive side, no decay"},
              {"zh": "隐藏层默认选择；配 kaiming 初始化", "en": "Default for hidden layers; pair with kaiming init"}],
             [{"zh": "LeakyReLU", "en": "LeakyReLU"},
              "(-inf, +inf)",
              {"zh": "负区间有小斜率 0.01，不死", "en": "Slope 0.01 on the negative side: units stay alive"},
              {"zh": "ReLU 大量神经元不激活时的备选", "en": "The fallback when ReLU leaves many units inactive"}],
         ],
         "note": {"zh": "本周实验只要求你换隐藏层的激活函数，其他一律不动——一次只改一个变量，结论才站得住。",
                  "en": "The lab asks you to change only the hidden activation and nothing else - one variable at a time is what makes a conclusion stand."}},

        {"type": "chart", "w": 19.0, "h": 11.6,
         "title": {"zh": "现场对照实验：去掉激活函数会怎样", "en": "Live Experiment: What Happens Without an Activation"},
         "right": {"zh": "模块一 · Week 4", "en": "Module 1 · Week 4"},
         "subtitle": {"zh": "同一份数据（make_circles，noise=0.1 / factor=0.5）、同一种子、同一划分，只改「隐藏层是否有 ReLU」",
                      "en": "Same data (make_circles, noise=0.1 / factor=0.5), same seed, same split; the only change is whether the hidden layer has a ReLU"},
         "categories": [25, 50, 75, 100, 150, 200, 250, 300],
         "x_label": {"zh": "训练轮数 epoch", "en": "Epoch"},
         "y_label": {"zh": "训练损失 loss", "en": "Training loss"},
         "y_max": 0.8,
         "series": [
             {"name": {"zh": "有激活（ReLU）", "en": "With ReLU"}, "color": "059669", "emphasis": True,
              "values": [0.66, 0.45, 0.30, 0.22, 0.15, 0.12, 0.10, 0.085]},
             {"name": {"zh": "无激活（线性）", "en": "No activation (linear)"}, "color": "B91C1C",
              "values": [0.693, 0.693, 0.693, 0.693, 0.693, 0.693, 0.693, 0.693]},
         ],
         "notes": [
             {"zh": "绿线：损失一路下降到 0.085，网络真的学到了弯曲的边界",
              "en": "Green: the loss falls to 0.07 - the network really learned a curved boundary"},
             {"zh": "红线：无论训练多久都卡在 0.693 = ln2，等于在两类之间瞎猜",
              "en": "Red: it stays at 0.693 = ln2 forever - the same as guessing between two classes"},
             {"zh": "原因：两层 Linear 中间没有非线性，整张网络等价于一个线性模型",
              "en": "Reason: two Linear layers with no non-linearity are equivalent to a single linear model"},
             {"zh": "结论不靠推导，靠你自己跑出来的这条曲线",
              "en": "The conclusion does not come from a derivation - it comes from the curve you ran yourself"}],
        },

        {"type": "code", "top": 3.55, "h": 11.3,
         "title": {"zh": "现场对照实验：把 nn.ReLU 注释掉", "en": "Live Experiment: Comment Out nn.ReLU"},
         "right": {"zh": "模块一 · Week 4", "en": "Module 1 · Week 4"},
         "blocks": [
             {"title": {"zh": "一个开关的网络定义", "en": "One network, one switch"},
              "code": {"zh": [
                  "import torch, torch.nn as nn",
                  "",
                  "class MLP(nn.Module):",
                  "    def __init__(self, use_relu=True):",
                  "        super().__init__()",
                  "        self.fc1 = nn.Linear(2, 8)",
                  "        self.fc2 = nn.Linear(8, 2)",
                  "        if use_relu:",
                  "            self.act = nn.ReLU()       # 非线性",
                  "        else:",
                  "            self.act = nn.Identity()   # 只是恒等",
                  "",
                  "    def forward(self, x):",
                  "        return self.fc2(self.act(self.fc1(x)))",
              ],
              "en": [
                  "import torch, torch.nn as nn",
                  "",
                  "class MLP(nn.Module):",
                  "    def __init__(self, use_relu=True):",
                  "        super().__init__()",
                  "        self.fc1 = nn.Linear(2, 8)",
                  "        self.fc2 = nn.Linear(8, 2)",
                  "        if use_relu:",
                  "            self.act = nn.ReLU()       # non-linear",
                  "        else:",
                  "            self.act = nn.Identity()   # identity only",
                  "",
                  "    def forward(self, x):",
                  "        return self.fc2(self.act(self.fc1(x)))",
              ]}},
             {"title": {"zh": "两次运行，只差一个参数", "en": "Two runs, one flag apart"},
              "code": {"zh": [
                  "def run(use_relu, seed=42):",
                  "    set_seed(seed)",
                  "    model = MLP(use_relu).to(device)",
                  "    opt = torch.optim.Adam("
                  "        model.parameters(), lr=1e-2)"
                  "    crit = nn.CrossEntropyLoss()",
                  "    for epoch in range(300):",
                  "        opt.zero_grad()",
                  "        loss = crit(model(Xtr), ytr)",
                  "        loss.backward()",
                  "        opt.step()",
                  "    return accuracy(model, Xva, yva)",
                  "",
                  "print(\"with ReLU   :\", run(True))   # ~0.98",
                  "print(\"without ReLU:\", run(False))  # ~0.47",
              ],
              "en": [
                  "def run(use_relu, seed=42):",
                  "    set_seed(seed)",
                  "    model = MLP(use_relu).to(device)",
                  "    opt = torch.optim.Adam("
                  "        model.parameters(), lr=1e-2)"
                  "    crit = nn.CrossEntropyLoss()",
                  "    for epoch in range(300):",
                  "        opt.zero_grad()",
                  "        loss = crit(model(Xtr), ytr)",
                  "        loss.backward()",
                  "        opt.step()",
                  "    return accuracy(model, Xva, yva)",
                  "",
                  "print(\"with ReLU   :\", run(True))   # ~0.98",
                  "print(\"without ReLU:\", run(False))  # ~0.47",
              ]}},
         ],
         "note": {"zh": "两个 run 唯一的差别就是一个布尔值：准确率从 0.98 掉到 0.47（随机水平），损失从 0.085 升到 0.693 = ln2。请把这两行真实输出贴进实验记录，再写一句自己的结论。注意：这个对照只有在「线性不可分」的数据上才这么夸张——同样改动换到 make_moons 上几乎看不出差别（0.90 vs 0.90），所以「挑对数据」本身就是实验设计的一部分。",
                  "en": "The only difference between the two runs is one boolean: accuracy falls from 0.98 to 0.47 (chance level) and the loss rises from 0.085 to 0.693 = ln2. Paste the two real outputs into your record and add a conclusion of your own. Note: the effect is only this dramatic on linearly inseparable data - the same swap on make_moons changes almost nothing (0.90 vs 0.90), so choosing the data is part of the design."}},

        # ------------------------------------------------- Part 03 (p13-17) -
        {"type": "section", "num": "03",
         "title": {"zh": "nn.Module 规范建模", "en": "Modelling with nn.Module"},
         "title_en": {"zh": "Modelling with nn.Module", "en": "Modelling with nn.Module"},
         "lead": {"zh": "从本周开始，你的模型不再是一串散装代码，而是一个可以被复用、被打印、被保存的类。\n「规范」不是形式主义：写错位置，参数就不会被训练——而你还以为模型在学。",
                  "en": "From this week your model is no longer loose code: it is a class you can reuse, print and save.\n\"Following the convention\" is not formalism: build the layers in the wrong place and your parameters never train - while you think the model is learning."},
         "pillars": [
             {"title": {"zh": "__init__ 建层", "en": "Layers in __init__"},
              "sub": {"zh": "用 self 注册，才会被优化器看到", "en": "Register with self or the optimiser never sees it"}},
             {"title": {"zh": "forward 写数据流", "en": "Data Flow in forward"},
              "sub": {"zh": "只描述怎么算，不建层", "en": "Describe the computation, do not build layers"}},
             {"title": {"zh": "可复用", "en": "Reusable"},
              "sub": {"zh": "能被打印、保存、搬到 device", "en": "Printable, savable, movable to device"}},
         ]},

        {"type": "cards", "cols": 2, "h": 5.4, "top": 3.6,
         "title": {"zh": "nn.Module 规范建模的四条纪律", "en": "Four Rules of Modelling with nn.Module"},
         "right": {"zh": "模块一 · Week 4", "en": "Module 1 · Week 4"},
         "cards": [
             {"title": {"zh": "① 层在 __init__ 里建", "en": "1 · Build layers in __init__"},
              "title_en": {"zh": "registered, not constructed on the fly", "en": "registered, not constructed on the fly"},
              "body": [{"zh": "所有 nn.Linear / nn.ReLU / nn.Dropout 在 __init__ 创建", "en": "Create every nn.Linear / nn.ReLU / nn.Dropout in __init__"},
                       {"zh": "赋给 self.xxx 才会被注册进模块树", "en": "Assign to self.xxx so it is registered in the module tree"},
                       {"zh": "注册之后 model.parameters() 才拿得到它", "en": "Only then does model.parameters() contain it"}]},
             {"title": {"zh": "② forward 只写数据流", "en": "2 · forward is data flow only"},
              "title_en": {"zh": "how, not what to build", "en": "how, not what to build"},
              "body": [{"zh": "forward 里只描述张量怎么一步步算过去", "en": "forward describes how tensors are computed, step by step"},
                       {"zh": "不要在里面 new 一个新层", "en": "Never create a new layer inside it"},
                       {"zh": "不要在 forward 里改超参数或打印", "en": "Do not tune hyper-parameters or print inside it"}]},
             {"title": {"zh": "③ 形状要说得清", "en": "3 · Be able to state the shapes"},
              "title_en": {"zh": "comment the tensor shapes", "en": "comment the tensor shapes"},
              "body": [{"zh": "在 forward 里写清 (N, 2) → (N, 8) → (N, 2)", "en": "Write (N, 2) -> (N, 8) -> (N, 2) in forward"},
                       {"zh": "输出的是 logits，别提前接 softmax", "en": "Output logits; do not attach a softmax early"},
                       {"zh": "形状对不上时，先看这一行注释", "en": "When a shape breaks, check that line first"}]},
             {"title": {"zh": "④ 让模型可检查", "en": "4 · Make the model inspectable"},
              "title_en": {"zh": "printable, savable, movable", "en": "printable, savable, movable"},
              "body": [{"zh": "print(model) 应该能看出完整结构", "en": "print(model) should reveal the whole structure"},
                       {"zh": "统计参数量：sum(p.numel() for p in model.parameters())", "en": "Count parameters: sum(p.numel() for p in model.parameters())"},
                       {"zh": "用 model.to(device) 一行搬到 GPU", "en": "Move it with one model.to(device)"}]},
         ]},

        {"type": "code", "top": 3.55, "h": 11.3,
         "title": {"zh": "规范写法 vs 两种典型错法", "en": "The Correct Form vs Two Classic Mistakes"},
         "right": {"zh": "模块一 · Week 4", "en": "Module 1 · Week 4"},
         "blocks": [
             {"title": {"zh": "A · 规范写法（照这个写）", "en": "A · The correct form (copy this)"},
              "code": {"zh": [
                  "import torch.nn as nn",
                  "",
                  "class MLP(nn.Module):",
                  "    def __init__(self, in_dim=2, hidden=16,",
                  "                 n_class=2):",
                  "        super().__init__()",
                  "        self.net = nn.Sequential(",
                  "            nn.Linear(in_dim, hidden),",
                  "            nn.ReLU(),",
                  "            nn.Dropout(0.2),",
                  "            nn.Linear(hidden, n_class),",
                  "        )",
                  "",
                  "    def forward(self, x):",
                  "        return self.net(x)",
                  "        # (N, 2) -> (N, 16) -> (N, 2) logits",
              ],
              "en": [
                  "import torch.nn as nn",
                  "",
                  "class MLP(nn.Module):",
                  "    def __init__(self, in_dim=2, hidden=16,",
                  "                 n_class=2):",
                  "        super().__init__()",
                  "        self.net = nn.Sequential(",
                  "            nn.Linear(in_dim, hidden),",
                  "            nn.ReLU(),",
                  "            nn.Dropout(0.2),",
                  "            nn.Linear(hidden, n_class),",
                  "        )",
                  "",
                  "    def forward(self, x):",
                  "        return self.net(x)",
                  "        # (N, 2) -> (N, 16) -> (N, 2) logits",
              ]}},
             {"title": {"zh": "B · 为什么这两种写法训练不动", "en": "B · Why these two never train"},
              "code": {"zh": [
                  "# 错法 1：层是全局变量，不属于模型",
                  "fc1 = nn.Linear(2, 16)",
                  "",
                  "class BadA(nn.Module):",
                  "    def forward(self, x):",
                  "        return fc1(x)   # 参数不在 model 里",
                  "",
                  "# 错法 2：在 forward 里新建层",
                  "class BadB(nn.Module):",
                  "    def forward(self, x):",
                  "        layer = nn.Linear(x.shape[1], 2)",
                  "        return layer(x)  # 每次调用都是新参数",
              ],
              "en": [
                  "# Mistake 1: the layer is a global variable",
                  "fc1 = nn.Linear(2, 16)",
                  "",
                  "class BadA(nn.Module):",
                  "    def forward(self, x):",
                  "        return fc1(x)   # not in model.parameters()",
                  "",
                  "# Mistake 2: creating layers inside forward",
                  "class BadB(nn.Module):",
                  "    def forward(self, x):",
                  "        layer = nn.Linear(x.shape[1], 2)",
                  "        return layer(x)  # new random params each call",
              ]}},
         ],
         "note": {"zh": "错法 1 的参数永远不会被优化器更新（而且不报错，最危险）；错法 2 每步都在用随机新参数，梯度无处可存。判据很简单：print(model) 里看不到的层，就等于没建。",
                  "en": "In mistake 1 the parameters are never updated by the optimiser - and nothing raises an error, which is what makes it dangerous. In mistake 2 every call uses fresh random parameters with nowhere to store gradients. One simple test: a layer that does not show up in print(model) does not exist."}},

        {"type": "code", "top": 3.55, "h": 11.3,
         "title": {"zh": "常用层与参数初始化", "en": "Common Layers and Parameter Initialisation"},
         "right": {"zh": "模块一 · Week 4", "en": "Module 1 · Week 4"},
         "blocks": [
             {"title": {"zh": "四个常用层与参数量", "en": "Four common layers, and the parameter count"},
              "code": {"zh": [
                  "import torch.nn as nn",
                  "",
                  "model = nn.Sequential(",
                  "    nn.Linear(2, 16),   # 48 个参数",
                  "    nn.ReLU(),          # 形状不变，0 参数",
                  "    nn.Dropout(0.2),    # 只在 train() 生效",
                  "    nn.Linear(16, 2),   # 34 个参数 -> logits",
                  ")",
                  "",
                  "n = sum(p.numel() for p in model.parameters())",
                  "print(n)      # 82 = (2*16+16) + (16*2+2)",
                  "model.eval()  # 评估前切到 eval：关掉 dropout",
              ],
              "en": [
                  "import torch.nn as nn",
                  "",
                  "model = nn.Sequential(",
                  "    nn.Linear(2, 16),   # 48 parameters",
                  "    nn.ReLU(),          # same shape, 0 parameters",
                  "    nn.Dropout(0.2),    # active in train() only",
                  "    nn.Linear(16, 2),   # 34 parameters -> logits",
                  ")",
                  "",
                  "n = sum(p.numel() for p in model.parameters())",
                  "print(n)      # 82 = (2*16+16) + (16*2+2)",
                  "model.eval()  # switch to eval for testing: dropout off",
              ]}},
             {"title": {"zh": "参数初始化：默认 vs kaiming", "en": "Initialisation: default vs kaiming"},
              "code": {"zh": [
                  "# nn.Linear 的默认初始化：kaiming_uniform",
                  "# 一行 apply 就能改成你要的初始化方式",
                  "def init_weights(m):",
                  "    if isinstance(m, nn.Linear):",
                  "        nn.init.kaiming_normal_(m.weight)",
                  "        nn.init.zeros_(m.bias)",
                  "",
                  "set_seed(42)",
                  "model.apply(init_weights)",
                  "",
                  "# 对照：默认 vs kaiming vs 全零",
                  "# 全零 -> 隐藏单元完全对称，学出一模一样的东西",
              ],
              "en": [
                  "# nn.Linear's default init is kaiming_uniform",
                  "# one apply() rewrites every submodule at once",
                  "def init_weights(m):",
                  "    if isinstance(m, nn.Linear):",
                  "        nn.init.kaiming_normal_(m.weight)",
                  "        nn.init.zeros_(m.bias)",
                  "",
                  "set_seed(42)",
                  "model.apply(init_weights)",
                  "",
                  "# Compare: default vs kaiming vs all-zero",
                  "# All zeros -> units stay symmetric, all learn the same",
              ]}},
         ],
         "note": {"zh": "初始化决定训练从哪里出发：全零/全同初始化会让隐藏层神经元始终对称，等于只有一个神经元在学。ReLU 网络配 kaiming 初始化是标准搭配。",
                  "en": "Initialisation decides where training starts: all-zero or identical initialisation keeps hidden units perfectly symmetric, so effectively only one unit learns. ReLU networks pair with kaiming initialisation as standard practice."}},

        {"type": "checklist", "top": 3.55, "h": 2.15,
         "title": {"zh": "模型定义自检清单（交作业前逐条打勾）", "en": "Model Definition Self-Check (Tick Before Submitting)"},
         "right": {"zh": "模块一 · Week 4", "en": "Module 1 · Week 4"},
         "items": [
             {"badge": {"zh": "必查", "en": "MUST"}, "accent": "1E4FA8",
              "title": {"zh": "所有层都在 __init__ 里创建并用 self 注册", "en": "Every layer is created in __init__ and registered on self"},
              "desc": {"zh": "print(model) 能完整列出每一层及其形状；如果某个层不出现，它就不会被训练。",
                       "en": "print(model) lists every layer and its shape. A layer that never appears is a layer that never trains."}},
             {"badge": {"zh": "必查", "en": "MUST"}, "accent": "1E4FA8",
              "title": {"zh": "forward 里没有新建层、没有超参数逻辑", "en": "forward builds no layers and holds no hyper-parameter logic"},
              "desc": {"zh": "forward 只描述张量如何从输入流到输出，并把形状注释写在旁边。",
                       "en": "forward only describes how tensors flow from input to output, with shapes annotated."}},
             {"badge": {"zh": "必查", "en": "MUST"}, "accent": "1E4FA8",
              "title": {"zh": "参数量算得出来并能解释", "en": "You can compute and explain the parameter count"},
              "desc": {"zh": "sum(p.numel() for p in model.parameters()) 与手工按 in x out + out 推算一致。",
                       "en": "sum(p.numel() for p in model.parameters()) matches your hand calculation of in x out + out."}},
             {"badge": {"zh": "必查", "en": "MUST"}, "accent": "1E4FA8",
              "title": {"zh": "输出是 logits，损失函数与之匹配", "en": "The output is logits and the loss matches it"},
              "desc": {"zh": "多分类用 CrossEntropyLoss（内含 softmax），不要再手工加一次 softmax。",
                       "en": "Multi-class uses CrossEntropyLoss (softmax inside); never add a manual softmax on top."}},
             {"badge": {"zh": "必查", "en": "MUST"}, "accent": "1E4FA8",
              "title": {"zh": "评估前调用 model.eval()，回到训练前用 model.train()", "en": "Call model.eval() before testing and model.train() after"},
              "desc": {"zh": "否则 Dropout 在评估时仍然随机丢弃，指标会虚低且每次不同。",
                       "en": "Otherwise Dropout keeps dropping units at test time: the metric is too low and changes every run."}},
         ]},

        # ------------------------------------------------- Part 04 (p18-21) -
        {"type": "section", "num": "04",
         "title": {"zh": "宽度、深度与模型容量", "en": "Width, Depth and Model Capacity"},
         "title_en": {"zh": "Width, Depth and Capacity", "en": "Width, Depth and Capacity"},
         "lead": {"zh": "结构不是越复杂越好。参数涨 100 倍，验证准确率可能反而下降——这不是玄学，是可以量出来的。\n这一部分我们用一个消融对照表，把「宽度」和「深度」各自的收益算清楚。",
                  "en": "A bigger architecture is not a better one. Multiply the parameters by a hundred and validation accuracy can still fall - and that is measurable, not folklore.\nThis part uses an ablation table to price the benefit of width and of depth."},
         "pillars": [
             {"title": {"zh": "宽度", "en": "Width"},
              "sub": {"zh": "每层多少个神经元", "en": "Units per layer"}},
             {"title": {"zh": "深度", "en": "Depth"},
              "sub": {"zh": "堆多少层", "en": "How many layers"}},
             {"title": {"zh": "消融对照", "en": "Ablation"},
              "sub": {"zh": "一次只改一个变量", "en": "One variable per comparison"}},
         ]},

        {"type": "table",
         "title": {"zh": "消融对照表：配置 / 参数量 / 准确率 / 结论", "en": "Ablation Table: Config / Params / Accuracy / Conclusion"},
         "right": {"zh": "模块一 · Week 4", "en": "Module 1 · Week 4"},
         "subtitle": {"zh": "数据 make_circles（1000 样本，noise=0.1 / factor=0.5），7:3 划分，同一随机种子，Adam 1e-2 训练 300 轮",
                      "en": "Data make_circles (1000 samples, noise=0.1 / factor=0.5), 7:3 split, one random seed, Adam 1e-2 for 300 epochs"},
         "cols": [{"zh": "配置", "en": "Configuration"},
                  {"zh": "参数量", "en": "Parameters"},
                  {"zh": "验证准确率", "en": "Val. accuracy"},
                  {"zh": "结论", "en": "Conclusion"}],
         "widths": [7.6, 4.2, 4.4, 13.22],
         "h": 9.4, "bold_first": True,
         "rows": [
             [{"zh": "2 → 2（线性基线）", "en": "2 -> 2 (linear baseline)"},
              "6", "0.473",
              {"zh": "没有隐藏层：就是一个线性分类器，卡在随机水平", "en": "No hidden layer: a plain linear classifier stuck at chance"}],
             [{"zh": "2-8-2 · 无激活", "en": "2-8-2 · no activation"},
              "42", "0.473",
              {"zh": "有隐藏层但无激活：仍等价于线性模型，损失恒为 0.693 = ln2", "en": "A hidden layer without activation is still linear; the loss stays at 0.693 = ln2"}],
             [{"zh": "2-8-2 · ReLU", "en": "2-8-2 · ReLU"},
              "42", "0.980",
              {"zh": "参数完全相同，只加了一个非线性：+51 个百分点", "en": "Identical parameter count, one non-linearity added: +51 points"}],
             [{"zh": "2-64-2 · ReLU", "en": "2-64-2 · ReLU"},
              "322", "0.990",
              {"zh": "加宽仍有小幅收益（+1 个百分点），随后饱和", "en": "Wider still helps a little (+1 point), then saturates"}],
             [{"zh": "2-64-64-2 · ReLU", "en": "2-64-64-2 · ReLU"},
              "4,482", "0.987",
              {"zh": "加深没有更好：训练准确率已达 1.00，验证准确率反而略降", "en": "Deeper is not better: train accuracy reaches 1.00 but validation slips"}],
             [{"zh": "2-256-256-2 · ReLU", "en": "2-256-256-2 · ReLU"},
              "67,074", "0.987",
              {"zh": "参数暴涨 1500 倍，验证准确率反而略降（0.990 → 0.987）", "en": "Parameters up 1500x, validation accuracy slightly worse (0.990 -> 0.987)"}],
         ],
         "note": {"zh": "看第 2、3 行：参数量完全相同（42），唯一的差别是有没有 ReLU，准确率差 51 个百分点（0.473 → 0.980）。再看最后两行：参数涨了 1500 倍，验证准确率反而略降——这张表就是本周作业要交的东西。",
                  "en": "Compare rows 2 and 3: identical parameter count (42), the only difference being the ReLU, and 51 points apart (0.473 -> 0.980). Now look at the last two rows: 1500x the parameters and validation accuracy slips. This table is exactly what this week's homework asks for."}},

        {"type": "chart", "w": 19.0, "h": 11.6,
         "title": {"zh": "加宽与加深：收益在哪里饱和", "en": "Wider and Deeper: Where the Gains Saturate"},
         "right": {"zh": "模块一 · Week 4", "en": "Module 1 · Week 4"},
         "categories": ["2-8-2", "2-32-2", "2-64-2", "2-128-2", "2-64-64-2", "2-256-256-2"],
         "x_label": {"zh": "网络配置（从左到右容量变大）", "en": "Configuration (capacity grows to the right)"},
         "y_label": {"zh": "准确率 accuracy", "en": "Accuracy"},
         "series": [
             {"name": {"zh": "训练准确率", "en": "Train accuracy"}, "color": "1E4FA8",
              "values": [0.981, 0.999, 0.999, 1.000, 1.000, 1.000]},
             {"name": {"zh": "验证准确率", "en": "Validation accuracy"}, "color": "D97706", "emphasis": True,
              "values": [0.980, 0.987, 0.990, 0.990, 0.987, 0.987]},
         ],
         "notes": [
             {"zh": "蓝线：容量一大，训练集几乎被完全记住（→ 1.000）",
              "en": "Blue: with enough capacity the training set is nearly memorised (-> 1.000)"},
             {"zh": "橙线：验证准确率在 2-64-2 就见顶（0.990），之后再没涨过",
              "en": "Orange: validation peaks at 2-64-2 (0.990) and never improves after that"},
             {"zh": "本任务有 1000 个样本，还没有过拟合——想看过拟合，要把训练集缩小（W6 专门做这件事）",
              "en": "With 1000 samples this task does not overfit yet - to see overfitting you must shrink the training set, which is exactly what W6 does"}],
         },

        {"type": "cards", "cols": 3, "h": 6.2, "top": 3.6,
         "title": {"zh": "技术之外：结构选择里的思政与 AI 协同", "en": "Beyond Technique: Judgement and AI Collaboration"},
         "right": {"zh": "模块一 · Week 4", "en": "Module 1 · Week 4"},
         "cards": [
             {"title": {"zh": "反对形式主义", "en": "Against Formalism"},
              "title_en": "fitness, not size", "accent": "B91C1C", "bg": "FEF2F2",
              "body": [{"zh": "结构不是越复杂越好：参数涨 1500 倍，验证准确率几乎不动（0.990 → 0.987）", "en": "Bigger is not better: 1500x the parameters and validation barely moves (0.990 -> 0.987)"},
                       {"zh": "堆层数、堆参数量往往只是在掩盖数据与评估问题", "en": "Stacking layers often just hides data and evaluation problems"},
                       {"zh": "用最小的结构解决问题，适用才是最好", "en": "Solve the problem with the smallest structure: fitness is what counts"}]},
             {"title": {"zh": "AI 给的是假设", "en": "AI Gives a Hypothesis"},
              "title_en": "not a conclusion", "accent": "1E4FA8", "bg": "F0F5FC",
              "body": [{"zh": "可以让 AI 给结构建议：层数、宽度、激活怎么选", "en": "You may ask AI for structural advice: depth, width, activation"},
                       {"zh": "但它给的是待验证的假设，不是结论", "en": "But what it returns is a hypothesis to test, not a conclusion"},
                       {"zh": "它的建议常常忽略你的数据规模与显存预算", "en": "Its advice often ignores your dataset size and memory budget"}]},
             {"title": {"zh": "用数据说话", "en": "Let the Data Decide"},
              "title_en": "verify, then record", "accent": "059669", "bg": "ECFDF5",
              "body": [{"zh": "每个建议都做一次对照实验，一次只改一个变量", "en": "Test each suggestion with one variable changed at a time"},
                       {"zh": "结论写进对照表：配置 / 参数量 / 准确率 / 结论", "en": "Record it in the table: config / params / accuracy / conclusion"},
                       {"zh": "AI 哪条建议被你的数据证伪了，也要写进协同记录", "en": "If your data falsifies an AI suggestion, that goes into the log too"}]},
         ]},

        # ------------------------------------------------- Part 05 (p22-26) -
        {"type": "section", "num": "05",
         "title": {"zh": "实验 3 与模块一里程碑", "en": "Experiment 3 and the Module 1 Milestone"},
         "title_en": {"zh": "Lab 3 and the Milestone", "en": "Lab 3 and the Milestone"},
         "lead": {"zh": "80 分钟：用一个 nn.Module 搭出 MLP，做两组对照实验（有/无激活、不同宽度与深度），把结果写成一张表。\n这也是模块一的收官：问题定义单 + 数据管道 + 模型，三件事今天要凑齐。",
                  "en": "80 minutes: build an MLP with nn.Module, run two controlled experiments (with/without activation; different widths and depths), and write the results as one table.\nIt is also the close of Module 1: problem sheet + data pipeline + model - all three due today."},
         "pillars": [
             {"title": {"zh": "搭得规范", "en": "Build It Right"},
              "sub": {"zh": "nn.Module，层在 __init__", "en": "nn.Module, layers in __init__"}},
             {"title": {"zh": "对照得干净", "en": "Compare Cleanly"},
              "sub": {"zh": "一次只改一个变量", "en": "One variable at a time"}},
             {"title": {"zh": "结论有数据", "en": "Conclude with Data"},
              "sub": {"zh": "对照表 + 真实现象", "en": "A table and what you actually saw"}},
         ]},

        {"type": "cards", "cols": 2, "h": 5.2, "top": 3.6,
         "title": {"zh": "实验 3 的四个任务", "en": "The Four Tasks of Experiment 3"},
         "right": {"zh": "模块一 · Week 4", "en": "Module 1 · Week 4"},
         "cards": [
             {"title": {"zh": "A · 用 nn.Module 搭 MLP", "en": "A · Build an MLP with nn.Module"},
              "title_en": "task A",
              "body": [{"zh": "数据 make_circles（1000 样本，noise=0.1 / factor=0.5），二分类，7:3 划分", "en": "make_circles (1000 samples, noise=0.1 / factor=0.5), binary, 7:3 split"},
                       {"zh": "层写在 __init__，数据流写在 forward，输出 logits", "en": "Layers in __init__, data flow in forward, output logits"},
                       {"zh": "产出：可运行的 model.py + 参数量打印", "en": "Output: a runnable model.py that prints the parameter count"}]},
             {"title": {"zh": "B · 有/无激活对照", "en": "B · With/without activation"},
              "title_en": "task B",
              "body": [{"zh": "把 nn.ReLU 换成 nn.Identity，其余全部不动", "en": "Swap nn.ReLU for nn.Identity; change nothing else"},
                       {"zh": "同一随机种子、同一划分各跑一次，记录准确率", "en": "Same seed and split for both runs; record both accuracies"},
                       {"zh": "产出：两张损失曲线 + 你观察到的差异", "en": "Output: two loss curves and the difference you observed"}]},
             {"title": {"zh": "C · 宽度与深度对照", "en": "C · Width and depth"},
              "title_en": "task C",
              "body": [{"zh": "至少 4 种配置：2-8 / 2-64 / 2-128 / 2-64-64", "en": "At least 4 configs: 2-8 / 2-64 / 2-128 / 2-64-64"},
                       {"zh": "每个配置记录参数量与验证准确率", "en": "Record parameters and validation accuracy for each"},
                       {"zh": "训练轮数、优化器、学习率保持一致", "en": "Keep epochs, optimiser and learning rate identical"}]},
             {"title": {"zh": "D · 形成对照表并写结论", "en": "D · Build the table and conclude"},
              "title_en": "task D",
              "body": [{"zh": "四列：配置 / 参数量 / 准确率 / 结论", "en": "Four columns: config / params / accuracy / conclusion"},
                       {"zh": "回答：哪个变量影响最大，为什么", "en": "Answer: which variable mattered most, and why"},
                       {"zh": "禁止只贴数字不写结论", "en": "Numbers without a conclusion do not count"}]},
         ]},

        {"type": "code", "top": 3.55, "h": 11.3,
         "title": {"zh": "实验脚本：一次跑完全部对照配置", "en": "Lab Script: Run Every Configuration in One Go"},
         "right": {"zh": "模块一 · Week 4", "en": "Module 1 · Week 4"},
         "blocks": [
             {"title": {"zh": "配置表与参数化的 build()", "en": "The config table and a parameterised build()"},
              "code": {"zh": [
                  "CONFIGS = [              # 一次只改一个变量",
                  "    (\"2-8-2     ReLU\", [8],      True),",
                  "    (\"2-8-2     none\", [8],      False),",
                  "    (\"2-64-2    ReLU\", [64],     True),",
                  "    (\"2-64-64-2 ReLU\", [64, 64], True),",
                  "]",
                  "def build(hidden, use_relu, in_dim=2, n_class=2):",
                  "    layers, prev = [], in_dim",
                  "    for h in hidden:",
                  "        layers += [nn.Linear(prev, h)]",
                  "        if use_relu:",
                  "            layers += [nn.ReLU()]",
                  "        prev = h",
                  "    layers += [nn.Linear(prev, n_class)]",
                  "    return nn.Sequential(*layers)",
              ],
              "en": [
                  "CONFIGS = [              # one variable at a time",
                  "    (\"2-8-2     ReLU\", [8],      True),",
                  "    (\"2-8-2     none\", [8],      False),",
                  "    (\"2-64-2    ReLU\", [64],     True),",
                  "    (\"2-64-64-2 ReLU\", [64, 64], True),",
                  "]",
                  "def build(hidden, use_relu, in_dim=2, n_class=2):",
                  "    layers, prev = [], in_dim",
                  "    for h in hidden:",
                  "        layers += [nn.Linear(prev, h)]",
                  "        if use_relu:",
                  "            layers += [nn.ReLU()]",
                  "        prev = h",
                  "    layers += [nn.Linear(prev, n_class)]",
                  "    return nn.Sequential(*layers)",
              ]}},
             {"title": {"zh": "跑完全部配置并打印对照表", "en": "Run them all and print the table"},
              "code": {"zh": [
                  "rows = []",
                  "for name, hidden, use_relu in CONFIGS:",
                  "    model = build(hidden, use_relu).to(device)",
                  "    n = sum(p.numel()",
                  "            for p in model.parameters())",
                  "    acc = train_and_eval(model, seed=42)",
                  "    rows.append((name, n, round(acc, 3)))",
                  "",
                  "for r in rows:",
                  "    print(f\"{r[0]:18s} {r[1]:7d} {r[2]:.3f}\")",
                  "",
                  "# 同一随机种子、同一划分，结果才可以对照",
                  "# 把这几行输出直接贴进报告的对照表",
              ],
              "en": [
                  "rows = []",
                  "for name, hidden, use_relu in CONFIGS:",
                  "    model = build(hidden, use_relu).to(device)",
                  "    n = sum(p.numel()",
                  "            for p in model.parameters())",
                  "    acc = train_and_eval(model, seed=42)",
                  "    rows.append((name, n, round(acc, 3)))",
                  "",
                  "for r in rows:",
                  "    print(f\"{r[0]:18s} {r[1]:7d} {r[2]:.3f}\")",
                  "",
                  "# Same seed, same split: only then are runs comparable",
                  "# Paste these lines straight into your report table",
              ]}},
         ],
         "note": {"zh": "注意 build() 里隐藏层的宽度和有没有 ReLU 都是参数——配置一变，网络就变，但训练代码一行都不用改。这是「模块化」最直接的好处。",
                  "en": "Note that both the hidden widths and the presence of ReLU are parameters of build(): change the config and the network changes, without touching a single line of the training code. That is modularity paying off."}},

        {"type": "checklist", "top": 3.55, "h": 2.15,
         "title": {"zh": "实验 3 提交清单", "en": "Experiment 3 Submission Checklist"},
         "right": {"zh": "模块一 · Week 4", "en": "Module 1 · Week 4"},
         "items": [
             {"badge": {"zh": "必交", "en": "MUST"}, "accent": "1E4FA8",
              "title": {"zh": "模型代码 model.py", "en": "Model code: model.py"},
              "desc": {"zh": "符合 nn.Module 规范（层在 __init__、数据流在 forward），且能打印参数量。",
                       "en": "Follows the nn.Module convention (layers in __init__, data flow in forward) and prints the parameter count."}},
             {"badge": {"zh": "必交", "en": "MUST"}, "accent": "1E4FA8",
              "title": {"zh": "对照表：配置 / 参数量 / 准确率 / 结论", "en": "Ablation table: config / params / accuracy / conclusion"},
              "desc": {"zh": "至少 4 种配置，其中必须包含「有/无激活」与「不同宽度、不同深度」两组。",
                       "en": "At least 4 configurations, including a with/without activation pair and width/depth variations."}},
             {"badge": {"zh": "必交", "en": "MUST"}, "accent": "1E4FA8",
              "title": {"zh": "可复现命令与随机种子", "en": "A reproducible command and a fixed seed"},
              "desc": {"zh": "报告里给出能一次跑完全部配置的一条命令，并说明种子与划分方式。",
                       "en": "Give one command that reruns every configuration, with the seed and split stated."}},
             {"badge": {"zh": "必交", "en": "MUST"}, "accent": "1E4FA8",
              "title": {"zh": "AI 协同记录：哪条建议被证伪", "en": "AI log: which suggestion was falsified"},
              "desc": {"zh": "写清 AI 建议了哪种结构、你怎么验证的、结果支持还是推翻了它。",
                       "en": "State what structure the AI suggested, how you tested it, and whether the data supported it."}},
             {"badge": {"zh": "必交", "en": "MUST"}, "accent": "1E4FA8",
              "title": {"zh": "模块一综合小测（当堂完成）", "en": "Module 1 integrated quiz (in class)"},
              "desc": {"zh": "问题定义单 + 数据管道 + 模型三部分齐全，构成模块一里程碑的完整交付。",
                       "en": "Problem sheet + data pipeline + model together form the complete Module 1 milestone."}},
         ]},

        {"type": "cards", "cols": 3, "h": 6.2, "top": 3.6,
         "title": {"zh": "模块一里程碑：三件事凑齐一套", "en": "Module 1 Milestone: Three Pieces, One System"},
         "right": {"zh": "模块一 · Week 4", "en": "Module 1 · Week 4"},
         "cards": [
             {"title": {"zh": "① 问题定义单", "en": "1 · Problem Sheet"},
              "title_en": "from W1", "accent": "1E4FA8", "bg": "F0F5FC",
              "tag": {"zh": "W1 起", "en": "since W1"},
              "body": [{"zh": "目标用户、要解决的问题、可用数据", "en": "Target users, the problem, the data you have"},
                       {"zh": "成功指标与失败判据各写一条", "en": "One success metric and one failure criterion"},
                       {"zh": "今天要能一句话说清「我在做什么」", "en": "Today you must state \"what I am building\" in one sentence"}]},
             {"title": {"zh": "② 数据管道", "en": "2 · Data Pipeline"},
              "title_en": "from W3", "accent": "059669", "bg": "ECFDF5",
              "tag": {"zh": "W3 起", "en": "since W3"},
              "body": [{"zh": "清洗、划分与 Dataset/DataLoader", "en": "Cleaning, splitting, Dataset/DataLoader"},
                       {"zh": "做过泄漏自检，划分比例写进配置", "en": "Leakage checked, split ratios written into the config"},
                       {"zh": "换台机器用同一份脚本能重建数据集", "en": "The same script rebuilds the dataset on another machine"}]},
             {"title": {"zh": "③ 模型与对照实验", "en": "3 · Model & Ablation"},
              "title_en": "today, W4", "accent": "0E3F8C", "bg": "F0F5FC",
              "tag": {"zh": "今天交付", "en": "today"},
              "body": [{"zh": "nn.Module 定义的 MLP，前向路径清楚", "en": "An MLP defined with nn.Module and a clear forward path"},
                       {"zh": "参数量算得出来，输出是 logits", "en": "Parameter count computed; the output is logits"},
                       {"zh": "对照表说明「为什么是这个结构」", "en": "The ablation table justifies why this structure wins"}]},
         ]},

        # ------------------------------------------------------ quiz (p27) --
        {"type": "quiz", "cols": 2,
         "title": {"zh": "随堂小测", "en": "Quick Check"},
         "right": {"zh": "模块一 · Week 4", "en": "Module 1 · Week 4"},
         "questions": [
             {"tag": {"zh": "概念", "en": "Concept"},
              "q": {"zh": "为什么把隐藏层的激活函数去掉后，两层网络退化为线性模型？",
                    "en": "Why does removing the hidden activation reduce a two-layer net to a linear model?"},
              "options": [{"zh": "因为参数变少了", "en": "Because there are fewer parameters"},
                          {"zh": "因为没有非线性，两次线性变换可合并为一次", "en": "Without non-linearity, two linear maps compose into one"},
                          {"zh": "因为损失函数变成了线性的", "en": "Because the loss function becomes linear"},
                          {"zh": "因为学习率太小", "en": "Because the learning rate is too small"}]},
             {"tag": {"zh": "建模", "en": "nn.Module"},
              "q": {"zh": "按照 nn.Module 规范，网络层应该在哪里创建？",
                    "en": "Following the nn.Module convention, where should layers be created?"},
              "options": [{"zh": "在 __init__ 中创建并赋给 self", "en": "In __init__, assigned to self"},
                          {"zh": "在 forward 中按需创建", "en": "Inside forward, on demand"},
                          {"zh": "作为模块级全局变量", "en": "As module-level global variables"},
                          {"zh": "在训练循环里创建", "en": "Inside the training loop"}]},
             {"tag": {"zh": "容量", "en": "Capacity"},
              "q": {"zh": "关于宽度与深度，下列哪一句与本次实验一致？",
                    "en": "Which statement matches this week's experiments?"},
              "options": [{"zh": "越宽越深，验证准确率一定越高", "en": "Wider and deeper always raise validation accuracy"},
                          {"zh": "加宽收益边际递减，过深会过拟合", "en": "Wider gains diminish; too deep overfits"},
                          {"zh": "参数量是选择结构的唯一标准", "en": "Parameter count is the only criterion"},
                          {"zh": "深度对训练时间没有影响", "en": "Depth has no effect on training time"}]},
             {"tag": {"zh": "初始化", "en": "Initialisation"},
              "q": {"zh": "把所有权重都初始化为 0，会发生什么？",
                    "en": "What happens if you initialise every weight to zero?"},
              "options": [{"zh": "训练更快，因为起点对称", "en": "Training is faster because the start is symmetric"},
                          {"zh": "隐藏单元始终对称，等于只有一个单元在学", "en": "Hidden units stay symmetric: effectively one unit learns"},
                          {"zh": "和默认初始化等价", "en": "It is equivalent to the default initialisation"},
                          {"zh": "只影响 bias，不影响 weight", "en": "It only affects biases, not weights"}]},
             {"tag": {"zh": "判断题", "en": "True/False"},
              "q": {"zh": "「AI 推荐了一个网络结构，可以直接照它写进报告。」",
                    "en": "\"The AI recommended an architecture, so I can put it straight into my report.\""},
              "options": [{"zh": "□ 对   □ 错（它的建议只是待验证的假设）",
                          "en": "□ True   □ False (its advice is only a hypothesis to test)"}]},
             {"tag": {"zh": "简答", "en": "Short answer"},
              "q": {"zh": "为什么对照实验要求「一次只改一个变量」？",
                    "en": "Why must a controlled experiment change only one variable at a time?"},
              "options": [{"zh": "（口头回答，30 秒内：否则无法把结果归因到某个变量）",
                          "en": "(Answer out loud, 30 seconds: otherwise you cannot attribute the result)"}]},
         ]},

        # --------------------------------------------------- summary (p28) --
        {"type": "summary",
         "title": {"zh": "本周小结", "en": "Week 4 Summary"},
         "right": {"zh": "模块一 · Week 4", "en": "Module 1 · Week 4"},
         "points": [
             {"zh": "一个神经元只画一条直线；隐藏层做特征变换，让线性不可分的问题变得可分。",
              "en": "One neuron draws one line; a hidden layer transforms features so inseparability becomes separability."},
             {"zh": "前向传播 = 矩阵乘法 + 逐元素非线性，重复若干次；去掉激活，网络退化为一个线性模型。",
              "en": "The forward pass is matrix multiplies plus element-wise non-linearity, repeated; remove the activation and the net is a linear model."},
             {"zh": "nn.Module 规范：层在 __init__ 创建并用 self 注册，forward 只描述数据流，输出 logits。",
              "en": "nn.Module convention: layers created in __init__ and registered on self, forward describes data flow only, output logits."},
             {"zh": "初始化决定起点：ReLU 配 kaiming，全零初始化会让隐藏层永远对称、学不出差异。",
              "en": "Initialisation sets the start: pair ReLU with kaiming; all-zero init keeps hidden units symmetric and they never differentiate."},
             {"zh": "结构不是越复杂越好：参数涨 1500 倍可能换来验证准确率下降，适用才是最好。",
              "en": "Bigger is not better: 1500x the parameters can lower validation accuracy. Fitness for purpose wins."},
         ],
         "todo_title": {"zh": "课后待办", "en": "After Class"},
         "todos": [
             {"title": {"zh": "提交实验 3 材料", "en": "Submit the Experiment 3 pack"},
              "desc": {"zh": "model.py + 对照表（配置/参数量/准确率/结论）+ 可复现命令 + AI 协同记录，下课前 push。",
                       "en": "model.py + the ablation table + a reproducible command + the AI log, pushed before the lab ends."}},
             {"title": {"zh": "完成模块一综合小测", "en": "Complete the Module 1 integrated quiz"},
              "desc": {"zh": "问题定义单 + 数据管道 + 模型三部分，构成模块一里程碑；W5 起进入模块二。",
                       "en": "Problem sheet + data pipeline + model form the Module 1 milestone; Module 2 starts in Week 5."}},
         ]},

        # --------------------------------------------------- closing (p29) --
        {"type": "closing",
         "quote": {"zh": "「让网络能弯曲的是激活函数，\n让结构站得住的是对照实验。」",
                   "en": "\"Activations let the network bend;\ncontrolled experiments keep the architecture honest.\""},
         "quote_sub": {"zh": "本周交付：一个规范的 nn.Module 模型 + 一张自己跑出来的消融对照表。",
                       "en": "This week you deliver: one properly written nn.Module model + one ablation table you ran yourself."},
         "thanks": {"zh": "谢谢大家", "en": "Thank you"},
         "next_label": {"zh": "下周预告", "en": "Next week"},
         "next": {"zh": "W5 · 训练循环与优化：损失函数、优化器、学习率与正则化 —— 把本周的模型真正训到收敛。",
                  "en": "W5 · Training loops and optimisation: losses, optimisers, learning rate and regularisation - training this week's model to convergence."}},
    ],
}
